import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const HAPPY_PATH=['PENDING','RESPONDED','ACCEPTED','INSPECTION_SCHEDULED','IN_PROGRESS','COMPLETED'];
const transitionActor=new Map([['PENDING->RESPONDED','PROVIDER'],['RESPONDED->ACCEPTED','CUSTOMER'],['ACCEPTED->INSPECTION_SCHEDULED','PROVIDER'],['INSPECTION_SCHEDULED->IN_PROGRESS','CUSTOMER'],['IN_PROGRESS->COMPLETED','PROVIDER']]);
const DISPATCH_WINDOWS={URGENT:30,STANDARD:60,SCHEDULED:120};
const DISPATCH_EXTENSION_MINUTES=60;
const CUSTOMER_RESPONSE_MINUTES=15;
const MAX_CUSTOMER_RETRIES=3;
const MAX_AVAILABLE_PROVIDERS=5;
const FINAL_DISPATCH_MESSAGE="We're sorry, but there are no available providers at this time.";
function canTransition(from,to,actor){return transitionActor.get(`${from}->${to}`)===actor;}
function canProviderRespond(status){return status==='PENDING'||status==='RESPONDED';}
function canCustomerSelect({status,providerResponse}){return status==='RESPONDED'&&providerResponse==='INTERESTED';}
function canScheduleInspection({status,providerSelected,providerConfirmed}){return status==='ACCEPTED'&&providerSelected&&providerConfirmed;}
function canStartWork({status,estimateStatus}){return status==='INSPECTION_SCHEDULED'&&estimateStatus==='APPROVED';}
function canComplete({status,assignedProvider}){return status==='IN_PROGRESS'&&assignedProvider;}
function canCancel({status,assignedProvider}){return (status==='PENDING'||status==='RESPONDED')&&!assignedProvider;}

test('happy path has the frozen six request statuses in order',()=>{assert.deepEqual(HAPPY_PATH,['PENDING','RESPONDED','ACCEPTED','INSPECTION_SCHEDULED','IN_PROGRESS','COMPLETED']);});
test('only the agreed actor can drive each happy-path transition',()=>{assert.equal(canTransition('PENDING','RESPONDED','PROVIDER'),true);assert.equal(canTransition('PENDING','ACCEPTED','PROVIDER'),false);assert.equal(canTransition('RESPONDED','ACCEPTED','CUSTOMER'),true);assert.equal(canTransition('ACCEPTED','INSPECTION_SCHEDULED','PROVIDER'),true);assert.equal(canTransition('INSPECTION_SCHEDULED','IN_PROGRESS','CUSTOMER'),true);assert.equal(canTransition('IN_PROGRESS','COMPLETED','PROVIDER'),true);assert.equal(canTransition('IN_PROGRESS','COMPLETED','CUSTOMER'),false);});
test('provider response never assigns the job',()=>{assert.equal(canProviderRespond('PENDING'),true);assert.equal(canProviderRespond('RESPONDED'),true);assert.equal(canProviderRespond('ACCEPTED'),false);assert.equal(canCustomerSelect({status:'RESPONDED',providerResponse:'INTERESTED'}),true);assert.equal(canCustomerSelect({status:'PENDING',providerResponse:'INTERESTED'}),false);});
test('inspection scheduling requires customer selection and provider confirmation',()=>{assert.equal(canScheduleInspection({status:'ACCEPTED',providerSelected:true,providerConfirmed:true}),true);assert.equal(canScheduleInspection({status:'ACCEPTED',providerSelected:true,providerConfirmed:false}),false);});
test('work starts only after estimate approval and completion only from in-progress',()=>{assert.equal(canStartWork({status:'INSPECTION_SCHEDULED',estimateStatus:'APPROVED'}),true);assert.equal(canStartWork({status:'INSPECTION_SCHEDULED',estimateStatus:'SENT'}),false);assert.equal(canComplete({status:'IN_PROGRESS',assignedProvider:true}),true);assert.equal(canComplete({status:'ACCEPTED',assignedProvider:true}),false);});
test('customer cancellation is a side path only before provider selection',()=>{assert.equal(canCancel({status:'PENDING',assignedProvider:false}),true);assert.equal(canCancel({status:'RESPONDED',assignedProvider:false}),true);assert.equal(canCancel({status:'ACCEPTED',assignedProvider:true}),false);assert.equal(canCancel({status:'IN_PROGRESS',assignedProvider:true}),false);});
test('payment is outside the lifecycle contract',()=>{assert.equal([...transitionActor.keys()].some(x=>/PAY|PAID|PAYMENT/.test(x)),false);});

test('dispatch priority windows are exactly 30, 60 and 120 minutes',()=>{assert.deepEqual(DISPATCH_WINDOWS,{URGENT:30,STANDARD:60,SCHEDULED:120});assert.equal(DISPATCH_EXTENSION_MINUTES,60);});
test('base dispatch migration contains tier windows and exactly one one-hour extension',async()=>{const source=await readFile(new URL('../migrations/0038_automated_dispatch_timeouts.sql',import.meta.url),'utf8');assert.match(source,/URGENT[^\n]*30 minutes|WHEN 'URGENT' THEN interval '30 minutes'/i);assert.match(source,/SCHEDULED[^\n]*2 hours|WHEN 'SCHEDULED' THEN interval '2 hours'/i);assert.match(source,/ELSE interval '1 hour'/i);assert.match(source,/dispatch_initial_deadline_at\+interval '1 hour'/i);});
test('provider availability cap is exactly five and first response starts customer timer without assigning',async()=>{const source=await readFile(new URL('../migrations/0041_dispatch_provider_cap_customer_response.sql',import.meta.url),'utf8');assert.equal(MAX_AVAILABLE_PROVIDERS,5);assert.match(source,/v_count\s*>?=\s*5/i);assert.match(source,/Provider availability limit reached/i);assert.match(source,/dispatch_customer_response_deadline_at=now\(\)\+interval '15 minutes'/i);assert.doesNotMatch(source,/assigned_provider_user_id\s*=\s*new\.provider_user_id/i);});
test('customer response window is 15 minutes with a maximum of three retries',async()=>{const source=await readFile(new URL('../migrations/0041_dispatch_provider_cap_customer_response.sql',import.meta.url),'utf8');assert.equal(CUSTOMER_RESPONSE_MINUTES,15);assert.equal(MAX_CUSTOMER_RETRIES,3);assert.match(source,/v_retry<3/i);assert.match(source,/dispatch_customer_retry_count=v_retry/i);assert.match(source,/CUSTOMER_RESPONSE_RETRY_/i);assert.match(source,/dispatch_state='CUSTOMER_TIMEOUT'/i);assert.match(source,/after 3 retries/i);});
test('search with one or more providers ends in customer selection rather than one-hour extension',async()=>{const source=await readFile(new URL('../migrations/0041_dispatch_provider_cap_customer_response.sql',import.meta.url),'utf8');assert.match(source,/IF v_count>0 THEN UPDATE public\.request_intake SET dispatch_state='AWAITING_CUSTOMER'/i);assert.match(source,/ELSE UPDATE public\.request_intake SET dispatch_state='EXTENDED'/i);});
test('dispatch final no-provider notification uses the exact customer message',async()=>{const source=await readFile(new URL('../migrations/0041_dispatch_provider_cap_customer_response.sql',import.meta.url),'utf8');assert.match(source,/We''re sorry, but there are no available providers at this time\./);assert.equal(FINAL_DISPATCH_MESSAGE,"We're sorry, but there are no available providers at this time.");});
test('dispatch retry restarts Step 1 after either provider exhaustion or customer timeout',async()=>{const source=await readFile(new URL('../migrations/0041_dispatch_provider_cap_customer_response.sql',import.meta.url),'utf8');assert.match(source,/dispatch_state NOT IN \('EXHAUSTED','CUSTOMER_TIMEOUT'\)/i);assert.match(source,/dispatch_state='SEARCHING'/i);assert.match(source,/dispatch_attempt=dispatch_attempt\+1/i);assert.match(source,/status='WITHDRAWN'/i);assert.match(source,/status='PENDING'/i);assert.match(source,/dispatch_customer_retry_count=0/i);});
test('cancelled dispatch is terminal and retry rejects cancelled requests',async()=>{const base=await readFile(new URL('../migrations/0038_automated_dispatch_timeouts.sql',import.meta.url),'utf8');const latest=await readFile(new URL('../migrations/0041_dispatch_provider_cap_customer_response.sql',import.meta.url),'utf8');assert.match(base,/new\.status='CANCELLED'/i);assert.match(latest,/Cancelled requests cannot be retried/i);assert.match(latest,/dispatch_state='CANCELLED'/i);});
test('customer selection is blocked after search or customer response termination',async()=>{const source=await readFile(new URL('../migrations/0041_dispatch_provider_cap_customer_response.sql',import.meta.url),'utf8');assert.match(source,/dispatch_state NOT IN \('SEARCHING','EXTENDED','AWAITING_CUSTOMER'\)/i);assert.match(source,/Provider selection window is no longer active/i);});
test('customer request UI supports five-provider shortlist and both retry termination states',async()=>{const source=await readFile(new URL('../app/requests/page.tsx',import.meta.url),'utf8');assert.match(source,/up to 5 providers/i);assert.match(source,/CUSTOMER_TIMEOUT/);assert.match(source,/EXHAUSTED/);assert.match(source,/Reminder retries:/);assert.match(source,/Try Again/);assert.match(source,/action:'retry'/);});
test('scheduled legacy urgency maps to SCHEDULED dispatch tier',async()=>{const source=await readFile(new URL('../migrations/0038_automated_dispatch_timeouts.sql',import.meta.url),'utf8');assert.match(source,/WHEN 'SCHEDULE' THEN 'SCHEDULED'/);assert.match(source,/WHEN 'SCHEDULED' THEN 'SCHEDULED'/);});

test('provider and customer request-list UI contain no legacy request status checks',async()=>{for(const file of ['app/provider/page.tsx','app/requests/page.tsx']){const source=await readFile(new URL(`../${file}`,import.meta.url),'utf8');assert.equal(/status\s*===\s*['\"]NEW['\"]/.test(source),false,`${file} still checks NEW`);assert.equal(/status\s*===\s*['\"]PROCESSING['\"]/.test(source),false,`${file} still checks PROCESSING`);}});
test('provider UI uses response language instead of treating response as assignment',async()=>{const source=await readFile(new URL('../app/provider/page.tsx',import.meta.url),'utf8');assert.match(source,/Respond to customer/i);assert.match(source,/(not assigned yet|no assignment has been made yet)/i);assert.doesNotMatch(source,/Accept & Send Response/);});
test('registration is WhatsApp OTP-gated and no longer uses direct client signUp',async()=>{const source=await readFile(new URL('../app/login/page.tsx',import.meta.url),'utf8');assert.match(source,/\/api\/auth\/send-otp/);assert.match(source,/\/api\/auth\/register/);assert.match(source,/Send WhatsApp OTP/i);assert.match(source,/6-digit WhatsApp code/i);assert.doesNotMatch(source,/auth\.signUp\s*\(/);});
test('forgot/reset password routes and views exist',async()=>{for(const file of ['app/api/auth/forgot-password/route.ts','app/api/auth/reset-password/route.ts','app/forgot-password/page.tsx','app/reset-password/page.tsx']){const source=await readFile(new URL(`../${file}`,import.meta.url),'utf8');assert.ok(source.length>80,`${file} should not be empty`);}});
test('profile supports optional photo phone and address architecture',async()=>{const source=await readFile(new URL('../app/profile/page.tsx',import.meta.url),'utf8');assert.match(source,/profile photo/i);assert.match(source,/phone verification/i);assert.match(source,/Primary address/i);assert.match(source,/Provider business \/ physical address/i);assert.match(source,/Saved service addresses/i);assert.match(source,/Make Default/i);assert.match(source,/\/api\/user\/profile/);});
test('admin user table exposes phone verification and core address data',async()=>{const source=await readFile(new URL('../app/admin/users/page.tsx',import.meta.url),'utf8');assert.match(source,/Core Address/);assert.match(source,/Default Service Address/);assert.match(source,/Verification/);});
test('address migration keeps profile addresses optional and saved addresses normalized',async()=>{const source=await readFile(new URL('../migrations/0033_auth_profile_addresses.sql',import.meta.url),'utf8');assert.match(source,/user_service_addresses/);assert.match(source,/is_default BOOLEAN NOT NULL DEFAULT FALSE/i);assert.match(source,/default_service_address_id/i);assert.match(source,/ADD COLUMN IF NOT EXISTS address_line1 TEXT,/i);assert.doesNotMatch(source,/ADD COLUMN IF NOT EXISTS address_line1 TEXT NOT NULL/i);});
test('request list exposes cancellation only through the guarded cancel path',async()=>{const source=await readFile(new URL('../app/requests/page.tsx',import.meta.url),'utf8');assert.match(source,/status==='PENDING'\|\|r\.status==='RESPONDED'/);assert.match(source,/Cancel Request/);assert.match(source,/\/api\/service-requests\//);});
