'use client';

import { useEffect, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import AppModeSwitch from '../../AppModeSwitch';
import { useProviderMode } from '../useProviderMode';

const SETUP_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-setup-data';
type Listing={categoryId:string;pricingModel:'FIXED'|'STARTING_FROM'|'HOURLY'|'QUOTE_REQUIRED';priceAmount:string;description:string;isActive:boolean};
export default function ProviderListingsPage(){
 const state=useProviderMode(true);const[listings,setListings]=useState<Listing[]>([]);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
 useEffect(()=>{if(!state.ready)return;void load();},[state.ready,state.categories.length]);
 async function session(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return null;}return data.session;}
 async function load(){try{const s=await session();if(!s)return;const r=await fetch(SETUP_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`},body:JSON.stringify({action:'get'})});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to load listings');setListings(state.categories.map(c=>{const x=(p.listings||[]).find((l:any)=>l.category_id===c.id);return{categoryId:c.id,pricingModel:x?.pricing_model||'QUOTE_REQUIRED',priceAmount:x?.price_amount==null?'':String(x.price_amount),description:x?.description||'',isActive:x?.is_active!==false&&state.selectedCategoryIds.includes(c.id)};}));}catch(e){setMessage(e instanceof Error?e.message:'Unable to load listings.');}}
 function update(id:string,patch:Partial<Listing>){setListings(v=>v.map(x=>x.categoryId===id?{...x,...patch}:x));}
 async function save(){setBusy(true);try{const s=await session();if(!s)return;const r=await fetch(SETUP_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`},body:JSON.stringify({action:'save_listings',listings:listings.filter(x=>state.selectedCategoryIds.includes(x.categoryId)).map(x=>({categoryId:x.categoryId,pricingModel:x.pricingModel,priceAmount:x.pricingModel==='QUOTE_REQUIRED'?null:x.priceAmount,description:x.description,isActive:x.isActive}))})});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to save listings');setMessage('Listings saved.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save listings.');}finally{setBusy(false);}}
 if(state.loading)return <main className="providerModePage"><div className="providerModeShell"><div className="providerModeCard">Loading service listings…</div></div></main>;
 const selected=state.categories.filter(c=>state.selectedCategoryIds.includes(c.id));
 return <main className="providerModePage"><div className="providerModeShell">
  <header className="providerModeTop"><div><span className="modeBadge provider"><span className="modeDot provider"/>Provider</span><h1>Listings</h1><p>Manage services, pricing and descriptions.</p></div><AppModeSwitch mode="provider" compact/></header>
  <section className="providerModeCard"><div className="providerSectionHead"><div><h2>Your services</h2><p>Turn listings on/off and set how customers see your pricing.</p></div><a className="secondary" href="/provider/services">Add or remove services</a></div>{selected.length?<div className="providerListingEditor">{selected.map(c=>{const l=listings.find(x=>x.categoryId===c.id)||{categoryId:c.id,pricingModel:'QUOTE_REQUIRED' as const,priceAmount:'',description:'',isActive:true};return <details className="providerListingRow providerListingManage" key={c.id} open={selected.length<=4}><summary><span>{c.name}</span><small>{l.isActive?'Active':'Paused'}</small></summary><label className="listingToggle"><input type="checkbox" checked={l.isActive} onChange={e=>update(c.id,{isActive:e.target.checked})}/><strong>Accept matches for this service</strong></label><select value={l.pricingModel} onChange={e=>update(c.id,{pricingModel:e.target.value as Listing['pricingModel']})}><option value="QUOTE_REQUIRED">Quote required</option><option value="FIXED">Fixed</option><option value="STARTING_FROM">Starting from</option><option value="HOURLY">Hourly</option></select>{l.pricingModel!=='QUOTE_REQUIRED'?<input type="number" min="0" step="0.01" value={l.priceAmount} onChange={e=>update(c.id,{priceAmount:e.target.value})} placeholder="MVR"/>:<div className="listingPriceMuted">Inspection / estimate</div>}<textarea rows={2} value={l.description} onChange={e=>update(c.id,{description:e.target.value})} placeholder="Describe this service"/></details>})}</div>:<div className="providerEmptyState"><h3>No active listings</h3><p>Add your first service so FixIt can match you with relevant customers.</p><a className="primary" href="/provider/services">Add your first service</a></div>}<div className="providerSetupActions"><span className="muted">{message}</span><button className="primary" disabled={busy||!selected.length} onClick={()=>void save()}>{busy?'Saving…':'Save listings'}</button></div></section>
  <section className="providerModeCard"><div className="providerSectionHead"><div><h2>Provider status</h2><p>{state.providerApproved?'Your listings are eligible for ranked matching when active and available.':'Your listings stay private until provider approval is complete.'}</p></div><span className={`modeBadge ${state.providerApproved?'customer':'provider'}`}>{state.providerApproved?'Approved':'Pending'}</span></div></section>
 </div></main>;
}
