'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../lib/supabaseClient';
import CustomerHeader from '../components/customer/CustomerHeader';
import ServiceIcon from '../components/customer/ServiceIcon';
import '../customer-v3.css';
import './requests-redesign.css';

const API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/customer-requests';
const DISPATCH_API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/dispatch-control';
const NO_PROVIDER_MESSAGE="We're sorry, but there are no available providers at this time.";

type RequestRow={id:string;ticket_number:string;service_name:string;service_category_code:string;service_location_text:string;preferred_date:string;problem_description:string;status:string;assigned_provider_label?:string|null;cancelled_at?:string|null;cancellation_reason?:string|null;created_at:string;updated_at:string};
type DispatchState='SEARCHING'|'EXTENDED'|'AWAITING_CUSTOMER'|'SECURED'|'EXHAUSTED'|'CUSTOMER_TIMEOUT'|'CANCELLED'|'NOT_REQUIRED';
type DispatchRow={id:string;ticket_number:string;status:string;urgency?:string|null;assigned_provider_user_id?:string|null;dispatch_tier?:'URGENT'|'STANDARD'|'SCHEDULED'|null;dispatch_state?:DispatchState|null;dispatch_attempt:number;dispatch_started_at?:string|null;dispatch_initial_deadline_at?:string|null;dispatch_extended_at?:string|null;dispatch_extension_deadline_at?:string|null;dispatch_secured_at?:string|null;dispatch_exhausted_at?:string|null;dispatch_customer_contact_started_at?:string|null;dispatch_customer_response_deadline_at?:string|null;dispatch_customer_retry_count:number;dispatch_customer_last_contact_at?:string|null;dispatch_customer_failed_at?:string|null;dispatch_customer_mode?:'WAITING_MORE'|null;dispatch_wait_provider_count?:number|null;dispatch_waiting_since?:string|null;available_provider_count:number};
type NotificationRow={id:string;request_id?:string|null;notification_type:string;title:string;message:string;dispatch_attempt?:number|null;created_at:string;read_at?:string|null};
type Filter='ACTIVE'|'COMPLETED'|'ALL';

function pretty(v:string){return v.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());}
function when(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'});}
function preferred(v:string){const d=new Date(`${v}T00:00:00`);return Number.isNaN(d.getTime())?v:d.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});}
function countdown(v:string|undefined|null,now:number){if(!v)return'—';const end=new Date(v).getTime();if(!Number.isFinite(end))return'—';const total=Math.max(0,Math.floor((end-now)/1000));const h=Math.floor(total/3600);const m=Math.floor((total%3600)/60);const s=total%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
function actionFor(r:RequestRow){if(r.status==='PENDING')return'Waiting for provider responses';if(r.status==='RESPONDED')return'Compare provider responses';if(r.status==='ACCEPTED')return'Continue with selected provider';if(r.status==='INSPECTION_SCHEDULED')return'View inspection schedule';if(r.status==='IN_PROGRESS')return'Track work in progress';if(r.status==='COMPLETED')return'View completion';if(r.status==='CANCELLED')return'Request cancelled';return'Open request';}
function canCancel(r:RequestRow){return (r.status==='PENDING'||r.status==='RESPONDED')&&!r.assigned_provider_label;}
function searchDeadline(d?:DispatchRow){if(!d)return null;return d.dispatch_state==='EXTENDED'?d.dispatch_extension_deadline_at:d.dispatch_initial_deadline_at;}
function dispatchText(d:DispatchRow|undefined,now:number){
 if(!d)return null;
 const count=Math.min(5,d.available_provider_count||0);
 const searchTimer=countdown(searchDeadline(d),now);
 const responseTimer=countdown(d.dispatch_customer_response_deadline_at,now);
 if(d.dispatch_state==='SEARCHING'){
  if(d.dispatch_customer_mode==='WAITING_MORE')return{title:`Waiting for more providers · ${count}/5`,body:'We are keeping your request open to find more available providers.',timer:searchTimer,tone:'search'};
  if(count>0)return{title:`${count} provider${count===1?'':'s'} available`,body:'You can choose now or keep searching for more options.',timer:responseTimer,tone:'secured'};
  return{title:'Searching for available providers',body:'This request is scheduled and will be sent to matching providers.',timer:searchTimer,tone:'search'};
 }
 if(d.dispatch_state==='EXTENDED'){
  if(d.dispatch_customer_mode==='WAITING_MORE')return{title:`Waiting for more providers · ${count}/5`,body:'The provider search has been extended.',timer:searchTimer,tone:'extended'};
  if(count>0)return{title:`${count} provider${count===1?'':'s'} available`,body:'Choose now or wait while the extended search continues.',timer:responseTimer,tone:'secured'};
  return{title:'Search extended by 1 hour',body:'We are continuing to look for an available provider.',timer:searchTimer,tone:'extended'};
 }
 if(d.dispatch_state==='AWAITING_CUSTOMER')return{title:`Choose from ${count} available provider${count===1?'':'s'}`,body:'Provider search is complete. Select a provider before the timer expires.',timer:responseTimer,tone:'secured'};
 if(d.dispatch_state==='CUSTOMER_TIMEOUT')return{title:'Provider selection timed out',body:"We couldn't complete provider assignment because we didn't receive your response after 3 retries.",timer:null,tone:'exhausted'};
 if(d.dispatch_state==='EXHAUSTED')return{title:'No providers available',body:NO_PROVIDER_MESSAGE,timer:null,tone:'exhausted'};
 if(d.dispatch_state==='SECURED')return{title:'Provider assigned',body:'A service provider has accepted your request. Open the request to continue.',timer:null,tone:'secured'};
 return null;
}

export default function MyRequestsPage(){
 const[requests,setRequests]=useState<RequestRow[]>([]);const[dispatch,setDispatch]=useState<Record<string,DispatchRow>>({});const[notifications,setNotifications]=useState<NotificationRow[]>([]);const[filter,setFilter]=useState<Filter>('ACTIVE');const[busy,setBusy]=useState(false);const[cancelling,setCancelling]=useState('');const[retrying,setRetrying]=useState('');const[waiting,setWaiting]=useState('');const[message,setMessage]=useState('Loading…');const[now,setNow]=useState(()=>Date.now());
 useEffect(()=>{void load();const poll=window.setInterval(()=>void load(true),3000);return()=>window.clearInterval(poll);},[]);
 useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id);},[]);
 async function token(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return '';}return data.session.access_token;}
 async function call(body:Record<string,unknown>){const t=await token();if(!t)throw new Error('Sign in required');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to load requests');return p;}
 async function dispatchCall(body:Record<string,unknown>){const t=await token();if(!t)throw new Error('Sign in required');const r=await fetch(DISPATCH_API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to update provider search');return p;}
 async function load(silent=false){if(!silent)setBusy(true);try{const[p,d]=await Promise.all([call({action:'list'}),dispatchCall({action:'status'})]);setRequests(p.requests||[]);const map:Record<string,DispatchRow>={};for(const row of d.requests||[])map[row.ticket_number]=row;setDispatch(map);setNotifications(d.notifications||[]);if(!silent)setMessage((p.requests||[]).length?'Up to date':'No requests yet');}catch(e){if(!silent)setMessage(e instanceof Error?e.message:'Unable to load requests');}finally{if(!silent)setBusy(false);}}
 async function retrySearch(r:RequestRow){const d=dispatch[r.ticket_number];if(!['EXHAUSTED','CUSTOMER_TIMEOUT'].includes(String(d?.dispatch_state)))return;setRetrying(r.ticket_number);setMessage('Restarting provider search…');try{await dispatchCall({action:'retry',ticketNumber:r.ticket_number});setMessage(`Provider search restarted for ${r.ticket_number}.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to restart provider search.');}finally{setRetrying('');}}
 async function waitForMore(r:RequestRow){const d=dispatch[r.ticket_number];if(!d||!['SEARCHING','EXTENDED'].includes(String(d.dispatch_state))||d.available_provider_count<1||d.available_provider_count>=5)return;setWaiting(r.ticket_number);setMessage('Continuing the provider search…');try{await dispatchCall({action:'wait_more',ticketNumber:r.ticket_number});setMessage(`Continuing search for more providers for ${r.ticket_number}.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to continue the provider search.');}finally{setWaiting('');}}
 async function cancelRequest(r:RequestRow){if(!canCancel(r))return;if(!window.confirm(`Cancel request ${r.ticket_number}? This ends the provider search and cannot be retried.`))return;setCancelling(r.ticket_number);setMessage('Cancelling request…');try{const t=await token();const response=await fetch(`/api/service-requests/${encodeURIComponent(r.ticket_number)}`,{method:'DELETE',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({reason:'Cancelled by customer before provider selection'})});const p=await response.json();if(!response.ok)throw new Error(p?.error||'Unable to cancel request.');setMessage(`${r.ticket_number} cancelled.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to cancel request.');}finally{setCancelling('');}}
 async function markNotificationRead(id:string){try{await dispatchCall({action:'mark_read',notificationId:id});setNotifications(v=>v.map(n=>n.id===id?{...n,read_at:new Date().toISOString()}:n));}catch{}}
 const visible=useMemo(()=>requests.filter(r=>filter==='ALL'||(filter==='COMPLETED'?r.status==='COMPLETED':!['COMPLETED','CANCELLED'].includes(r.status))),[requests,filter]);
 const counts=useMemo(()=>({all:requests.length,active:requests.filter(r=>!['COMPLETED','CANCELLED'].includes(r.status)).length,completed:requests.filter(r=>r.status==='COMPLETED').length}),[requests]);
 const unreadNotifications=notifications.filter(n=>!n.read_at);
 return <main className="c3Page"><CustomerHeader title="Requests" backHref="/" right={<a className="c3IconButton" href="/?new=1" aria-label="New request"><svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg></a>}/><div className="c3Shell c3Requests">
  <div className="c3RequestsTop"><div><h1>My requests</h1><p>{counts.active?`${counts.active} active request${counts.active===1?'':'s'}`:'Nothing needs your attention right now.'}</p></div><button className="c3Secondary c3Refresh" onClick={()=>void load()} disabled={busy}>{busy?'Refreshing…':'Refresh'}</button></div>
  {unreadNotifications.length?<section className="c3Notice c3DispatchNotice" aria-label="Dispatch notifications"><strong>Provider search update</strong>{unreadNotifications.slice(0,3).map(n=><div key={n.id}><span>{n.message}</span><button className="c3Secondary" type="button" onClick={()=>void markNotificationRead(n.id)}>Dismiss</button></div>)}</section>:null}
  <div className="c3Filters"><button className={filter==='ACTIVE'?'active':''} onClick={()=>setFilter('ACTIVE')}><span className="c3FilterIcon">▣</span>Active {counts.active}</button><button className={filter==='COMPLETED'?'active':''} onClick={()=>setFilter('COMPLETED')}><span className="c3FilterIcon">✓</span>Completed {counts.completed}</button><button className={filter==='ALL'?'active':''} onClick={()=>setFilter('ALL')}><span className="c3FilterIcon">⊞</span>All {counts.all}</button></div>
  {message&&message!=='Up to date'?<div className="c3Notice">{message}</div>:null}
  <section className="c3RequestList">{visible.map(r=>{const d=dispatch[r.ticket_number];const secured=Boolean(r.assigned_provider_label||d?.assigned_provider_user_id||d?.dispatch_state==='SECURED');const info=dispatchText(d,now);const retryable=['EXHAUSTED','CUSTOMER_TIMEOUT'].includes(String(d?.dispatch_state));const canWait=Boolean(!secured&&d&&['SEARCHING','EXTENDED'].includes(String(d.dispatch_state))&&d.available_provider_count>0&&d.available_provider_count<5&&d.dispatch_customer_mode!=='WAITING_MORE');return <article key={r.id} className={`c3RequestCard ${r.status==='COMPLETED'?'completed':''}`}>
   <div className="c3RequestMain"><div className="c3RequestIcon"><ServiceIcon name={r.service_name}/></div><div className="c3RequestIdentity"><span className={`c3Status ${r.status==='COMPLETED'?'completed':''}`}>{pretty(secured&&r.status==='PENDING'?'ACCEPTED':r.status)}</span><h2>{r.service_name}</h2><p className="c3ProviderLine"><span aria-hidden="true">♙</span>{r.status==='CANCELLED'?'Cancelled before provider selection':r.assigned_provider_label||(secured?'Provider assigned':'Provider not selected yet')}</p><p className="c3Ticket">Request ID: <strong>{r.ticket_number}</strong></p></div></div>
   {info?<div className={`c3SearchPanel ${info.tone}`}><div className="c3SearchPulse" aria-hidden="true"><span></span></div><div className="c3SearchCopy"><strong>{info.title}</strong><p>{info.body}</p>{d?.dispatch_attempt>1?<small>Search attempt {d.dispatch_attempt}</small>:null}</div>{info.timer?<div className="c3Countdown"><span>Live countdown</span><strong>{info.timer}</strong><small>HRS&nbsp;&nbsp;&nbsp;&nbsp; MIN&nbsp;&nbsp;&nbsp;&nbsp; SEC</small></div>:null}</div>:null}
   <div className="c3RequestMeta"><div><span className="c3MetaIcon">●</span><div><small>Location</small><strong>{r.service_location_text}</strong></div></div><div><span className="c3MetaIcon">□</span><div><small>Preferred date</small><strong>{preferred(r.preferred_date)}</strong></div></div><div><span className="c3MetaIcon">＋</span><div><small>Created on</small><strong>{when(r.created_at)}</strong></div></div></div>
   <div className="c3NextPanel"><div className="c3NextIcon" aria-hidden="true">⌛</div><div><small>Next step</small><strong>{secured?'Continue with assigned provider':retryable?'Retry provider search or cancel the request':d?.dispatch_customer_mode==='WAITING_MORE'?'Waiting for another provider':d?.available_provider_count>0?'Provider responses received':actionFor(r)}</strong><p>{secured?'A provider has accepted your request. Open the request for the latest details.':r.status==='PENDING'?'We’ll notify you as soon as a provider responds.':'Open the request for the latest status and available actions.'}</p></div></div>
   <div className="c3RequestAction"><div className="c3ActionButtons">{retryable?<button className="c3Primary" type="button" disabled={retrying===r.ticket_number} onClick={()=>void retrySearch(r)}>{retrying===r.ticket_number?'Restarting…':'Try Again'}</button>:null}{canWait?<button className="c3Secondary" type="button" disabled={waiting===r.ticket_number} onClick={()=>void waitForMore(r)}>{waiting===r.ticket_number?'Waiting…':'Wait for More Providers'}</button>:null}{!secured&&d?.dispatch_customer_mode==='WAITING_MORE'?<button className="c3Secondary" type="button" disabled>Waiting for More</button>:null}{!secured&&canCancel(r)?<button className="c3Danger" type="button" disabled={cancelling===r.ticket_number} onClick={()=>void cancelRequest(r)}><span aria-hidden="true">♲</span>{cancelling===r.ticket_number?'Cancelling…':'Cancel Request'}</button>:null}<a className="c3Primary c3OpenDetails" href={`/requests/${encodeURIComponent(r.ticket_number)}`}>{secured?'Open Provider':'Open Details'}<span aria-hidden="true">›</span></a></div></div>
   {!secured&&r.status==='PENDING'?<div className="c3NotifyStrip"><span className="c3Shield">✓</span><div><strong>We’re finding the best provider for you.</strong><p>You’ll be notified as soon as the status changes.</p></div><span className="c3Bell" aria-hidden="true">●</span></div>:null}
  </article>})}{!visible.length?<div className="c3Empty"><h2>No requests here</h2><p>{filter==='COMPLETED'?'Completed requests will appear here.':'Create a request when you need a local service provider.'}</p><a className="c3Primary" href="/">Create request</a></div>:null}</section>
 </div></main>;
}
