'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../lib/supabaseClient';

const API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/customer-requests';
type RequestRow={id:string;ticket_number:string;service_name:string;service_category_code:string;service_location_text:string;preferred_date:string;problem_description:string;status:string;assigned_provider_label?:string|null;created_at:string;updated_at:string};
type Filter='ACTIVE'|'COMPLETED'|'ALL';
function pretty(v:string){return v.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());}
function when(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'});}
function currentLabel(r:RequestRow){if(r.status==='NEW')return'Waiting for provider responses';if(r.status==='ACCEPTED')return r.assigned_provider_label?'Provider selected':'Choose a provider';if(r.status==='PROCESSING')return'Work in progress';if(r.status==='COMPLETED')return'Completed';return pretty(r.status);}
function actionLabel(r:RequestRow){if(r.status==='NEW')return'View responses';if(r.status==='ACCEPTED')return'Continue request';if(r.status==='PROCESSING')return'Track work';if(r.status==='COMPLETED')return'View completion';return'Open request';}
function ServiceIcon({name}:{name:string}){const n=name.toLowerCase();const common={width:25,height:25,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.9,strokeLinecap:'round' as const,strokeLinejoin:'round' as const};if(n.includes('electric'))return <svg {...common}><path d="M13 2 5 14h7l-1 8 8-12h-7l1-8Z"/></svg>;if(n.includes('plumb')||n.includes('water'))return <svg {...common}><path d="M12 2s6 7 6 12a6 6 0 0 1-12 0c0-5 6-12 6-12Z"/></svg>;if(n.includes('air')||n.includes('ac'))return <svg {...common}><path d="M12 2v20M4.2 6.5l15.6 9M4.2 17.5l15.6-9"/></svg>;return <svg {...common}><path d="m14.7 6.3 3-3a4 4 0 0 1-5.1 5.1L5.4 15.6a2 2 0 1 0 3 3l7.2-7.2a4 4 0 0 1 5.1-5.1l-3 3"/></svg>}

export default function MyRequestsPage(){
 const[requests,setRequests]=useState<RequestRow[]>([]);const[filter,setFilter]=useState<Filter>('ACTIVE');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('Loading requests…');
 useEffect(()=>{void load();},[]);
 async function token(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return '';}return data.session.access_token;}
 async function call(body:Record<string,unknown>){const t=await token();if(!t)throw new Error('Sign in required');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Request history failed');return p;}
 async function load(){setBusy(true);try{const p=await call({action:'list'});setRequests(p.requests||[]);setMessage((p.requests||[]).length?'Up to date':'No requests yet');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load requests.');}finally{setBusy(false);}}
 const visible=useMemo(()=>requests.filter(r=>filter==='ALL'||(filter==='COMPLETED'?r.status==='COMPLETED':r.status!=='COMPLETED')),[requests,filter]);
 const counts=useMemo(()=>({all:requests.length,active:requests.filter(r=>r.status!=='COMPLETED').length,completed:requests.filter(r=>r.status==='COMPLETED').length}),[requests]);
 return <main className="customerV2Requests">
  <header className="customerV2Header"><a className="customerV2Logo" href="/">iFix<span>It</span></a><div className="customerV2HeaderActions"><button className="customerV2IconButton" type="button" disabled={busy} onClick={()=>void load()} aria-label="Refresh"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.9"><path d="M20 12a8 8 0 1 1-2.3-5.7L20 8"/><path d="M20 3v5h-5"/></svg></button><a className="customerV2Avatar" href="/profile" aria-label="Profile">U</a></div></header>
  <div className="customerV2RequestsShell">
   <section className="customerV2RequestsHero"><div><span>MY REQUESTS</span><h1>What needs your attention?</h1><p>Active jobs stay focused. Completed jobs stay out of the way.</p></div><a href="/" className="customerV2NewRequest">+ New request</a></section>
   <div className="customerV2RequestTabs"><button className={filter==='ACTIVE'?'active':''} onClick={()=>setFilter('ACTIVE')}>Active <span>{counts.active}</span></button><button className={filter==='COMPLETED'?'active':''} onClick={()=>setFilter('COMPLETED')}>Completed <span>{counts.completed}</span></button><button className={filter==='ALL'?'active':''} onClick={()=>setFilter('ALL')}>All <span>{counts.all}</span></button></div>
   <div className="customerV2RequestList">{visible.map(r=><a className={`customerV2RequestCard ${r.status==='COMPLETED'?'completed':''}`} key={r.id} href={`/requests/${encodeURIComponent(r.ticket_number)}`}><div className="customerV2RequestIcon"><ServiceIcon name={r.service_name}/></div><div className="customerV2RequestMain"><div className="customerV2RequestTop"><span className={`customerV2Status status-${r.status.toLowerCase()}`}>{currentLabel(r)}</span><small>{r.ticket_number}</small></div><h2>{r.service_name}</h2><p>{r.problem_description}</p><div className="customerV2RequestMeta"><span><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>{r.service_location_text}</span><span><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M6 3v3M18 3v3M4 8h16M5 5h14v16H5z"/></svg>{when(r.preferred_date)}</span></div>{r.assigned_provider_label?<div className="customerV2ProviderLine"><span>{r.assigned_provider_label.slice(0,1).toUpperCase()}</span><strong>{r.assigned_provider_label}</strong></div>:null}<div className="customerV2RequestAction"><strong>{actionLabel(r)}</strong><span>›</span></div></div></a>)}{!visible.length?<div className="customerV2RequestEmpty"><div>✓</div><h2>{filter==='COMPLETED'?'No completed requests yet':'You’re all caught up'}</h2><p>{filter==='ACTIVE'?'Create a new request whenever you need help.':'Completed jobs will appear here.'}</p><a href="/">Create request</a></div>:null}</div>
   <p className="customerV2Sync">{message}</p>
  </div>
 </main>;
}
