'use client';

import type { ReactNode } from 'react';
type Props={title?:string;backHref?:string;right?:ReactNode};

const featherStyles=`
:root{--fx-blue:#6366f1;--fx-blue-dark:#4f46e5;--fx-surface:#ffffff;--fx-bg:#f8fafc;--fx-text:#0f172a;--fx-muted:#64748b;--fx-line:#e2e8f0;--fx-shadow:0 12px 30px rgba(15,23,42,.07)}
.c4App{min-height:100vh;background:var(--fx-bg);font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.c4App.dv{font-family:"Noto Sans Thaana","MV Boli",Tahoma,sans-serif}.c4Main{margin-left:260px;min-width:0}.c4App.dv .c4Main{margin-left:0;margin-right:260px}
.c4Sidebar{position:fixed;inset:0 auto 0 0;width:260px;padding:24px 16px;background:#fff;border-right:1px solid var(--fx-line);z-index:60;display:flex;flex-direction:column;overflow-y:auto}.c4App.dv .c4Sidebar{left:auto;right:0;border-right:0;border-left:1px solid var(--fx-line)}
.c4Brand{display:flex;align-items:center;gap:12px;padding:0 8px 26px;text-decoration:none;color:var(--fx-text)}.c4BrandMark{width:42px;height:42px;border-radius:13px;background:var(--fx-blue);color:#fff;display:grid;place-items:center;font-weight:900;font-size:20px;box-shadow:0 6px 16px rgba(99,102,241,.24)}.c4Brand strong{display:block;font-size:21px;letter-spacing:-.5px}.c4Brand small{display:block;color:var(--fx-muted);font-size:10px;margin-top:2px}
.c4Lang,.c4LangCompact{display:flex;padding:3px;border:1px solid var(--fx-line);background:#f8fafc;border-radius:10px;gap:2px}.c4Lang{margin:0 4px 18px}.c4Lang button,.c4LangCompact button{border:0;background:transparent;color:var(--fx-muted);font-weight:800;border-radius:7px;cursor:pointer}.c4Lang button{flex:1;min-height:34px}.c4LangCompact button{min-width:34px;min-height:32px;padding:0 8px}.c4Lang button.active,.c4LangCompact button.active{background:var(--fx-blue);color:#fff;box-shadow:0 2px 8px rgba(99,102,241,.25)}
.c4NavLabel{padding:12px 10px 7px;color:#94a3b8;font-size:10px;font-weight:900;letter-spacing:.09em;text-transform:uppercase}.c4Nav{display:grid;gap:3px}.c4Nav a,.c4Nav button{min-height:44px;border:0;background:transparent;border-radius:10px;color:var(--fx-muted);display:flex;align-items:center;gap:12px;padding:0 12px;text-decoration:none;font-size:14px;font-weight:750;cursor:pointer;text-align:left}.c4App.dv .c4Nav a,.c4App.dv .c4Nav button{text-align:right}.c4Nav a span,.c4Nav button span{width:22px;text-align:center;font-size:18px}.c4Nav a:hover,.c4Nav button:hover{background:#f1f5f9;color:var(--fx-text)}.c4Nav a.active{background:var(--fx-blue);color:#fff;box-shadow:0 5px 14px rgba(99,102,241,.2)}
.c4SidebarFoot{margin-top:auto;border-top:1px solid var(--fx-line);padding:16px 8px 0;display:grid;gap:12px}.c4Identity{display:flex;align-items:center;gap:10px;min-width:0}.c4Identity>span{width:36px;height:36px;border-radius:50%;background:#eef2ff;color:var(--fx-blue-dark);display:grid;place-items:center;font-size:12px;font-weight:900}.c4Identity strong{font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.c4Logout{border:0;background:transparent;color:#dc2626;text-align:left;font-weight:750;padding:7px 0;cursor:pointer}.c4App.dv .c4Logout{text-align:right}.c4HeaderActions{display:flex;align-items:center;gap:8px}
.c3Page{background:var(--fx-bg)!important;color:var(--fx-text)!important}.c3Shell{width:min(1060px,calc(100% - 48px))!important}.c3Header{height:72px!important;background:rgba(255,255,255,.95)!important;backdrop-filter:blur(16px)!important;border-bottom:1px solid var(--fx-line)!important;box-shadow:0 1px 3px rgba(15,23,42,.04)!important}.c4App.dv .c3Header{direction:rtl}
.c3Logo{font-size:25px!important;letter-spacing:-1.1px!important}.c3Logo span{color:var(--fx-text)!important}.c3Logo b{color:var(--fx-blue)!important}.c3Logo small{color:var(--fx-muted)!important;font-size:8px!important}.c3IconButton,.c3Avatar{border:1px solid var(--fx-line)!important;background:#fff!important;color:var(--fx-text)!important;box-shadow:0 1px 2px rgba(15,23,42,.03)!important}.c3Avatar{background:var(--fx-blue)!important;color:#fff!important;border-color:var(--fx-blue)!important}
.c3Home{padding-top:28px!important;gap:24px!important}.c3Welcome{position:relative;overflow:hidden;background:linear-gradient(135deg,rgba(99,102,241,.12),rgba(165,180,252,.08) 58%,rgba(255,255,255,.94))!important;color:var(--fx-text)!important;border:1px solid rgba(226,232,240,.9)!important;border-radius:24px!important;padding:32px!important;box-shadow:none!important}.c3Welcome:after{content:'';position:absolute;width:240px;height:240px;border-radius:50%;right:-80px;top:-110px;background:rgba(99,102,241,.08);pointer-events:none}.c4App.dv .c3Welcome:after{right:auto;left:-80px}.c3Welcome small{color:var(--fx-blue)!important;opacity:1!important;font-weight:900!important}.c3Welcome h1{font-size:clamp(31px,4.5vw,46px)!important;letter-spacing:-1.6px!important;max-width:680px!important}.c4App.dv .c3Welcome h1{letter-spacing:0!important;line-height:1.45}.c3Welcome p{color:var(--fx-muted)!important;opacity:1!important;font-size:16px!important;line-height:1.65!important}
.c3Primary{background:var(--fx-blue)!important;border-radius:12px!important;min-height:48px!important;box-shadow:0 6px 16px rgba(99,102,241,.16)!important}.c3Primary:hover{background:var(--fx-blue-dark)!important}.c3Welcome .c3Primary{background:var(--fx-blue)!important;color:#fff!important;box-shadow:0 8px 18px rgba(99,102,241,.18)!important;z-index:1}.c3Secondary{border-color:var(--fx-line)!important;border-radius:12px!important;background:#fff!important;color:var(--fx-text)!important;min-height:46px!important}
.c3Section{border:1px solid var(--fx-line)!important;border-radius:18px!important;box-shadow:0 4px 24px rgba(15,23,42,.045)!important;padding:24px!important}.c3SectionHead small,.c3Question small{color:var(--fx-blue)!important}.c3SectionHead h2{font-size:23px!important}.c3SectionHead p,.c3Question p{color:var(--fx-muted)!important}.c3ServiceGrid{gap:14px!important}.c3ServiceTile{background:#fff!important;border:1px solid var(--fx-line)!important;border-radius:16px!important;min-height:128px!important;box-shadow:0 1px 2px rgba(15,23,42,.025)!important;transition:transform .16s ease,box-shadow .2s ease,border-color .2s ease!important}.c3ServiceTile:hover{transform:translateY(-2px)!important;box-shadow:0 8px 26px rgba(15,23,42,.07)!important;border-color:#c7d2fe!important}.c3ServiceTile.selected{background:#eef2ff!important;border-color:#a5b4fc!important;color:var(--fx-blue-dark)!important}.c3ServiceIcon{color:var(--fx-blue)!important}.c3ServiceTile span{color:var(--fx-muted)!important}
.c3ActiveCard{border-color:var(--fx-line)!important;border-radius:16px!important;background:#fff!important}.c3Status{background:#eef2ff!important;color:var(--fx-blue-dark)!important}.c3Status.completed{background:#ecfdf5!important;color:#047857!important}.c3Wizard{padding-top:24px!important}.c3WizardCard{border:1px solid var(--fx-line)!important;border-radius:20px!important;box-shadow:0 4px 20px rgba(15,23,42,.045)!important;padding:30px!important}.c3StepDot{background:#e2e8f0!important}.c3StepDot.active,.c3StepDot.done{background:var(--fx-blue)!important}.c3Question h1{font-size:clamp(29px,4.5vw,40px)!important;color:var(--fx-text)!important}.c4App.dv .c3Question h1{letter-spacing:0!important;line-height:1.5}
.c3Field input,.c3Field select,.c3Field textarea{border-color:#cbd5e1!important;border-radius:12px!important;background:#fff!important}.c4App.dv .c3Field input,.c4App.dv .c3Field select,.c4App.dv .c3Field textarea{text-align:right}.c3Field input:focus,.c3Field select:focus,.c3Field textarea:focus{border-color:var(--fx-blue)!important;box-shadow:0 0 0 3px rgba(99,102,241,.11)!important}.c3Chip{border-color:var(--fx-line)!important}.c3Chip.selected{background:var(--fx-blue)!important;border-color:var(--fx-blue)!important}.c3Urgency button{border-color:var(--fx-line)!important;background:#fff!important}.c3Urgency button.selected{background:#eef2ff!important;border-color:#a5b4fc!important;color:var(--fx-blue-dark)!important}.c3PhotoDrop{border-color:#cbd5e1!important;background:#f8fafc!important}.c3Notice{background:#f1f5f9!important;color:#475569!important}.c3Warning{background:#fffbeb!important;color:#92400e!important}.c3ActionDock{background:rgba(248,250,252,.92)!important}
button,a,input,select,textarea{transition:border-color .15s ease,background-color .15s ease,color .15s ease,box-shadow .15s ease,transform .15s ease}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid rgba(99,102,241,.28)!important;outline-offset:2px!important}
@media(max-width:960px){.c4Sidebar{display:none}.c4Main,.c4App.dv .c4Main{margin:0}.c3Shell{width:min(100% - 28px,760px)!important}}
@media(max-width:760px){.c3Shell{width:min(100% - 20px,660px)!important}.c3Home{padding-top:14px!important;gap:14px!important}.c3Welcome{padding:22px!important;border-radius:18px!important}.c3Welcome h1{font-size:30px!important}.c3Section{padding:17px!important;border-radius:16px!important}.c3ServiceGrid{gap:10px!important}.c3ServiceTile{min-height:110px!important;border-radius:14px!important;padding:14px!important}.c3WizardCard{padding:18px!important;border-radius:16px!important;box-shadow:none!important}.c3Header{height:64px!important}.c3Logo{font-size:23px!important}.c4LangCompact{display:flex}}
`;

export default function CustomerHeader({title,backHref,right}:Props){return <><style>{featherStyles}</style><header className="c3Header"><div className="c3HeaderSide">{backHref?<a className="c3IconButton" href={backHref} aria-label="Back"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 18l-6-6 6-6"/></svg></a>:<span/>}</div><a className="c3Logo" href="/" aria-label="FixIt home"><span>Fix</span><b>It</b>{title?<small>{title}</small>:null}</a><div className="c3HeaderSide c3HeaderRight">{right}</div></header></>}
