'use client';

import type { ReactNode } from 'react';
type Props={title?:string;backHref?:string;right?:ReactNode};

const featherStyles=`
:root{--fx-blue:#2563eb;--fx-blue-dark:#1d4ed8;--fx-surface:#ffffff;--fx-bg:#f8fafc;--fx-text:#0f172a;--fx-muted:#64748b;--fx-line:#e2e8f0;--fx-shadow:0 12px 30px rgba(15,23,42,.07)}
.c3Page{background:var(--fx-bg)!important;color:var(--fx-text)!important}
.c3Shell{width:min(1180px,calc(100% - 32px))!important}
.c3Header{height:72px!important;background:rgba(255,255,255,.94)!important;backdrop-filter:blur(16px)!important;border-bottom:1px solid var(--fx-line)!important;box-shadow:0 1px 3px rgba(15,23,42,.04)!important}
.c3Logo{font-size:25px!important;letter-spacing:-1.1px!important}.c3Logo span{color:var(--fx-text)!important}.c3Logo b{color:var(--fx-blue)!important}.c3Logo small{color:var(--fx-muted)!important;font-size:8px!important}
.c3IconButton,.c3Avatar{border:1px solid var(--fx-line)!important;background:#fff!important;color:var(--fx-text)!important;box-shadow:0 1px 2px rgba(15,23,42,.03)!important}
.c3Home{padding-top:28px!important;gap:24px!important}
.c3Welcome{position:relative;overflow:hidden;background:linear-gradient(135deg,rgba(37,99,235,.11),rgba(59,130,246,.05) 58%,rgba(255,255,255,.92))!important;color:var(--fx-text)!important;border:1px solid rgba(226,232,240,.9)!important;border-radius:28px!important;padding:34px!important;box-shadow:none!important}
.c3Welcome:after{content:'';position:absolute;width:240px;height:240px;border-radius:50%;right:-80px;top:-110px;background:rgba(37,99,235,.08);pointer-events:none}
.c3Welcome small{color:var(--fx-blue)!important;opacity:1!important;font-weight:900!important}.c3Welcome h1{font-size:clamp(32px,5vw,48px)!important;letter-spacing:-1.8px!important;max-width:680px!important}.c3Welcome p{color:var(--fx-muted)!important;opacity:1!important;font-size:16px!important}
.c3Primary{background:var(--fx-blue)!important;border-radius:13px!important;min-height:48px!important;box-shadow:0 6px 16px rgba(37,99,235,.16)!important}.c3Primary:hover{background:var(--fx-blue-dark)!important}.c3Welcome .c3Primary{background:var(--fx-blue)!important;color:#fff!important;box-shadow:0 8px 18px rgba(37,99,235,.18)!important;z-index:1}
.c3Secondary{border-color:var(--fx-line)!important;border-radius:13px!important;background:#fff!important;color:var(--fx-text)!important;min-height:46px!important}
.c3Section{border:1px solid var(--fx-line)!important;border-radius:22px!important;box-shadow:0 1px 3px rgba(15,23,42,.035)!important;padding:24px!important}.c3SectionHead small,.c3Question small{color:var(--fx-blue)!important}.c3SectionHead h2{font-size:24px!important}.c3SectionHead p,.c3Question p{color:var(--fx-muted)!important}
.c3ServiceGrid{gap:14px!important}.c3ServiceTile{background:#fff!important;border:1px solid var(--fx-line)!important;border-radius:18px!important;min-height:132px!important;box-shadow:0 1px 2px rgba(15,23,42,.025)!important;transition:transform .16s ease,box-shadow .2s ease,border-color .2s ease!important}.c3ServiceTile:hover{transform:translateY(-3px)!important;box-shadow:var(--fx-shadow)!important;border-color:#bfdbfe!important}.c3ServiceTile.selected{background:#eff6ff!important;border-color:#93c5fd!important;color:var(--fx-blue)!important}.c3ServiceIcon{color:var(--fx-blue)!important}.c3ServiceTile span{color:var(--fx-muted)!important}
.c3ActiveCard{border-color:var(--fx-line)!important;border-radius:18px!important;background:#fff!important}.c3Status{background:#eff6ff!important;color:var(--fx-blue)!important}.c3Status.completed{background:#ecfdf5!important;color:#047857!important}
.c3Wizard{padding-top:24px!important}.c3WizardCard{border:1px solid var(--fx-line)!important;border-radius:24px!important;box-shadow:0 4px 20px rgba(15,23,42,.045)!important;padding:30px!important}.c3StepDot{background:#e2e8f0!important}.c3StepDot.active,.c3StepDot.done{background:var(--fx-blue)!important}.c3Question h1{font-size:clamp(30px,5vw,42px)!important;color:var(--fx-text)!important}
.c3Field input,.c3Field select,.c3Field textarea{border-color:#cbd5e1!important;border-radius:14px!important;background:#fff!important}.c3Field input:focus,.c3Field select:focus,.c3Field textarea:focus{border-color:var(--fx-blue)!important;box-shadow:0 0 0 3px rgba(37,99,235,.11)!important}.c3Chip{border-color:var(--fx-line)!important}.c3Chip.selected{background:var(--fx-blue)!important;border-color:var(--fx-blue)!important}.c3Urgency button{border-color:var(--fx-line)!important;background:#fff!important}.c3Urgency button.selected{background:#eff6ff!important;border-color:#93c5fd!important;color:var(--fx-blue)!important}
.c3PhotoDrop{border-color:#cbd5e1!important;background:#f8fafc!important}.c3Notice{background:#f1f5f9!important;color:#475569!important}.c3Warning{background:#fffbeb!important;color:#92400e!important}
.c3ActionDock{background:rgba(248,250,252,.92)!important}.c3RequestCard{border:1px solid var(--fx-line)!important;box-shadow:0 1px 3px rgba(15,23,42,.04)!important}.c3RequestIcon{background:#eff6ff!important;color:var(--fx-blue)!important}.c3Filters button{background:#e2e8f0!important;color:#475569!important}.c3Filters button.active{background:var(--fx-text)!important;color:#fff!important}
.c3Detail .activeHero,.c3Detail .successBanner,.c3Detail .screenCard,.c3Detail .providerSummaryCard,.c3Detail .progressCard,.c3Detail .workDoneCard,.c3Detail .satisfactionCard,.c3Detail .feedbackCard{border:1px solid var(--fx-line)!important;box-shadow:0 2px 12px rgba(15,23,42,.045)!important}
button,a,input,select,textarea{transition:border-color .15s ease,background-color .15s ease,color .15s ease,box-shadow .15s ease,transform .15s ease}
button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid rgba(37,99,235,.3)!important;outline-offset:2px!important}
@media(max-width:760px){.c3Shell{width:min(100% - 20px,660px)!important}.c3Home{padding-top:14px!important;gap:14px!important}.c3Welcome{padding:22px!important;border-radius:22px!important}.c3Welcome h1{font-size:31px!important}.c3Section{padding:17px!important;border-radius:18px!important}.c3ServiceGrid{gap:10px!important}.c3ServiceTile{min-height:110px!important;border-radius:16px!important;padding:14px!important}.c3WizardCard{padding:18px!important;border-radius:20px!important;box-shadow:none!important}.c3Header{height:64px!important}.c3Logo{font-size:23px!important}}
`;

export default function CustomerHeader({title,backHref,right}:Props){return <><style>{featherStyles}</style><header className="c3Header"><div className="c3HeaderSide">{backHref?<a className="c3IconButton" href={backHref} aria-label="Back"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 18l-6-6 6-6"/></svg></a>:<span/>}</div><a className="c3Logo" href="/" aria-label="FixIt home"><span>Fix</span><b>It</b>{title?<small>{title}</small>:null}</a><div className="c3HeaderSide c3HeaderRight">{right}</div></header></>}
