'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';

type Atoll={id:string;code?:string|null;display_name:string;sort_order?:number};
type Island={id:string;atoll_id:string;display_name:string;sort_order?:number};
type LocationUnit={id:string;atoll_id:string;island_id:string;unit_type:string;display_name:string;sort_order?:number};
type ProfilePayload={profile?:{full_name?:string|null}|null;error?:string};
type CataloguePayload={atolls?:Atoll[];islands?:Island[];wards?:LocationUnit[];error?:string};
type ServiceAddress={id:string;user_id:string;label:string;address_line1:string;address_line2?:string|null;city?:string|null;state_region?:string|null;postal_code?:string|null;country?:string|null;service_atoll_id?:string|null;service_island_id?:string|null;service_location_unit_id?:string|null;access_instructions?:string|null;is_default:boolean;is_active:boolean;updated_at?:string|null};
type AddressPayload={addresses?:ServiceAddress[];address?:ServiceAddress;error?:string};
type Props={onSaved:()=>Promise<void>|void;onSaveAndSend:()=>void};

function localPhone(value:unknown){const digits=String(value??'').replace(/\D/g,'');if(digits.length===10&&digits.startsWith('960'))return digits.slice(3);if(digits.length>=7)return digits.slice(-7);return digits;}
function addressText(address:ServiceAddress){return [address.address_line1,address.address_line2,address.city,address.state_region].filter(Boolean).join(', ');}
function missingAddressFields(address:ServiceAddress,wards:LocationUnit[]=[]){const missing:string[]=[];if(!String(address.address_line1||'').trim())missing.push('House / Apartment');if(!String(address.address_line2||'').trim())missing.push('Road');if(!address.service_atoll_id)missing.push('Atoll / Region');if(!address.service_island_id)missing.push('Island / City');const islandHasWards=Boolean(address.service_island_id&&wards.some(w=>w.island_id===address.service_island_id));if(islandHasWards&&!address.service_location_unit_id)missing.push('Ward');return missing;}
async function addressApi(method:'GET'|'POST'|'PATCH'|'DELETE',body?:Record<string,unknown>){const response=await fetch('/api/user/service-addresses',{method,credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const payload=await response.json().catch(()=>({})) as AddressPayload;if(!response.ok)throw new Error(payload.error||'Unable to update Service Address.');return payload;}

export default function RequestProfileCompletion({onSaved,onSaveAndSend}:Props){
 const[name,setName]=useState('');const[phone,setPhone]=useState('');const[addresses,setAddresses]=useState<ServiceAddress[]>([]);const[selectedId,setSelectedId]=useState('');
 const[atolls,setAtolls]=useState<Atoll[]>([]);const[islands,setIslands]=useState<Island[]>([]);const[wards,setWards]=useState<LocationUnit[]>([]);const[editingId,setEditingId]=useState<string|null>(null);const[showForm,setShowForm]=useState(false);const[formStep,setFormStep]=useState<1|2>(1);
 const[house,setHouse]=useState('');const[road,setRoad]=useState('');const[atollId,setAtollId]=useState('');const[islandId,setIslandId]=useState('');const[wardId,setWardId]=useState('');const[accessInstructions,setAccessInstructions]=useState('');
 const[loading,setLoading]=useState(true);const[locationLoading,setLocationLoading]=useState(true);const[locationError,setLocationError]=useState('');const[saving,setSaving]=useState(false);const[message,setMessage]=useState('');
 const filteredIslands=useMemo(()=>islands.filter(i=>i.atoll_id===atollId),[islands,atollId]);const filteredWards=useMemo(()=>wards.filter(w=>w.island_id===islandId),[wards,islandId]);const selectedAtoll=useMemo(()=>atolls.find(a=>a.id===atollId)||null,[atolls,atollId]);const selectedIsland=useMemo(()=>islands.find(i=>i.id===islandId&&i.atoll_id===atollId)||null,[islands,islandId,atollId]);const selectedWard=useMemo(()=>wards.find(w=>w.id===wardId&&w.island_id===islandId)||null,[wards,wardId,islandId]);const selectedAddress=useMemo(()=>addresses.find(a=>a.id===selectedId)||null,[addresses,selectedId]);const selectedAddressWard=useMemo(()=>wards.find(w=>w.id===selectedAddress?.service_location_unit_id)||null,[wards,selectedAddress]);
 const validContact=name.trim().length>=2&&localPhone(phone).length===7;const wardRequired=filteredWards.length>0;const validCore=Boolean(house.trim()&&road.trim()&&selectedAtoll&&selectedIsland);const validForm=Boolean(validCore&&(!wardRequired||selectedWard));
 useEffect(()=>{void loadLocations();void load();},[]);

 async function loadLocations(){setLocationLoading(true);setLocationError('');try{const response=await fetch('/api/locations/catalogue',{credentials:'same-origin',cache:'no-store'});const payload=await response.json().catch(()=>({})) as CataloguePayload;if(!response.ok)throw new Error(payload.error||'Unable to load Atoll / Region, Island / City and Ward selections.');if(!payload.atolls?.length)throw new Error('Atoll / Region list is empty. Please try again.');if(!payload.islands?.length)throw new Error('Island / City list is empty. Please try again.');setAtolls(payload.atolls);setIslands(payload.islands);setWards(payload.wards||[]);}catch(error){setAtolls([]);setIslands([]);setWards([]);setLocationError(error instanceof Error?error.message:'Unable to load Atoll / Region, Island / City and Ward selections.');}finally{setLocationLoading(false);}}
 async function load(preferredId?:string){setLoading(true);try{const {data}=await supabase.auth.getSession();const session=data.session;if(!session)throw new Error('Your login session has expired. Please sign in again.');if(!session.user.phone||!session.user.phone_confirmed_at)throw new Error('OTP verification is required before you can create a service request. Please sign in again and verify your phone.');setPhone(localPhone(session.user.phone));const [profileResponse,addressPayload]=await Promise.all([fetch('/api/user/profile',{credentials:'same-origin',cache:'no-store'}),addressApi('GET')]);const profilePayload=await profileResponse.json().catch(()=>({})) as ProfilePayload;if(!profileResponse.ok||!profilePayload.profile)throw new Error(profilePayload.error||'Unable to load profile.');const nextAddresses=addressPayload.addresses||[];const nextSelected=(preferredId&&nextAddresses.some(a=>a.id===preferredId)?preferredId:'')||nextAddresses.find(a=>a.is_default)?.id||nextAddresses[0]?.id||'';setName(profilePayload.profile.full_name||'');setAddresses(nextAddresses);setSelectedId(nextSelected);setShowForm(!nextAddresses.length);if(!nextAddresses.length)setFormStep(1);const incomplete=nextAddresses.find(a=>missingAddressFields(a,wards).length);if(incomplete)setMessage(`Complete this saved Service Address: ${missingAddressFields(incomplete,wards).join(', ')}.`);else if(!(profilePayload.profile.full_name||'').trim())setMessage('Add your full name in Profile before sending the request.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to load Service Addresses.');}finally{setLoading(false);}}
 function resetForm(){setEditingId(null);setHouse('');setRoad('');setAtollId('');setIslandId('');setWardId('');setAccessInstructions('');setFormStep(1);}
 function addNew(){resetForm();setShowForm(true);setMessage('');window.requestAnimationFrame(()=>document.querySelector<HTMLElement>('[data-service-address-form]')?.scrollIntoView({behavior:'smooth',block:'start'}));}
 function editAddress(address:ServiceAddress){setEditingId(address.id);setHouse(address.address_line1||address.label||'');setRoad(address.address_line2||'');setAtollId(address.service_atoll_id||'');setIslandId(address.service_island_id||'');setWardId(address.service_location_unit_id||'');setAccessInstructions(address.access_instructions||'');setFormStep(1);setShowForm(true);setMessage('');window.requestAnimationFrame(()=>document.querySelector<HTMLElement>('[data-service-address-form]')?.scrollIntoView({behavior:'smooth',block:'start'}));}
 function cancelForm(){resetForm();setShowForm(false);setMessage('');}
 function goNext(){const missing:string[]=[];if(!house.trim())missing.push('House / Apartment');if(!road.trim())missing.push('Road');if(!selectedAtoll)missing.push('Atoll / Region');if(!selectedIsland)missing.push('Island / City');if(wardRequired&&!selectedWard)missing.push('Ward');if(missing.length){setMessage(`Enter the missing Service Address records: ${missing.join(', ')}.`);return;}setMessage('');setFormStep(2);window.requestAnimationFrame(()=>document.querySelector<HTMLElement>('[data-service-address-form]')?.scrollIntoView({behavior:'smooth',block:'start'}));}
 async function makeDefault(address:ServiceAddress){const missing=missingAddressFields(address,wards);if(missing.length)throw new Error(`Enter the missing Service Address records: ${missing.join(', ')}.`);const payload=await addressApi('PATCH',{action:'set_default',id:address.id});window.dispatchEvent(new Event('fixit:profile-updated'));await onSaved();return payload.address;}
 function selectAddress(address:ServiceAddress){const missing=missingAddressFields(address,wards);if(missing.length){setSelectedId('');editAddress(address);setMessage(`Enter the missing Service Address records: ${missing.join(', ')}.`);return;}setSelectedId(address.id);setMessage(address.is_default?'Default Service Address selected for this request.':'Service Address selected for this request. Your profile default has not changed.');}

 async function saveAddress(event:FormEvent){event.preventDefault();if(saving)return;if(formStep===1){goNext();return;}const missing:string[]=[];if(!house.trim())missing.push('House / Apartment');if(!road.trim())missing.push('Road');if(!selectedAtoll)missing.push('Atoll / Region');if(!selectedIsland)missing.push('Island / City');if(wardRequired&&!selectedWard)missing.push('Ward');if(missing.length){setMessage(`Enter the missing Service Address records: ${missing.join(', ')}.`);setFormStep(1);return;}setSaving(true);setMessage(editingId?'Updating Service Address…':'Saving Service Address…');try{const existingAddress=editingId?addresses.find(a=>a.id===editingId):null;const body={label:house.trim(),address_line1:house.trim(),address_line2:road.trim(),city:selectedIsland!.display_name,state_region:selectedAtoll!.display_name,postal_code:existingAddress?.postal_code||null,service_atoll_id:selectedAtoll!.id,service_island_id:selectedIsland!.id,service_location_unit_id:selectedWard?.id||null,access_instructions:accessInstructions.trim()||null};const payload=await addressApi(editingId?'PATCH':'POST',editingId?{...body,id:editingId}:body);if(!payload.address)throw new Error('Service Address was not returned after saving.');const shouldBeDefault=addresses.length===0||Boolean(existingAddress?.is_default);if(shouldBeDefault&&!payload.address.is_default)await makeDefault(payload.address);resetForm();setShowForm(false);await load(payload.address.id);setMessage(shouldBeDefault?'Service Address saved as your default and selected for this request.':'New Service Address saved and selected for this request. Your profile default has not changed.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to save Service Address.');}finally{setSaving(false);}}
 async function removeAddress(address:ServiceAddress){if(saving)return;setSaving(true);setMessage('Removing Service Address…');try{await addressApi('DELETE',{id:address.id});const remaining=addresses.filter(a=>a.id!==address.id);await load(remaining[0]?.id);window.dispatchEvent(new Event('fixit:profile-updated'));await onSaved();setMessage(remaining.length?'Service Address removed. Default address is synchronized.':'Service Address removed. Profile address cleared; add a Service Address to continue.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to remove Service Address.');}finally{setSaving(false);}}
 async function continueRequest(){if(saving)return;if(!validContact){setMessage('Your account needs a name and OTP-verified Maldives phone number.');return;}if(!selectedAddress){setMessage('Choose a Service Address before continuing.');return;}const missing=missingAddressFields(selectedAddress,wards);if(missing.length){editAddress(selectedAddress);setMessage(`Enter the missing Service Address records: ${missing.join(', ')}.`);return;}setSaving(true);setMessage('Service Address confirmed. Sending your request…');try{onSaveAndSend();}catch(error){setMessage(error instanceof Error?error.message:'Unable to confirm Service Address.');setSaving(false);}}

 if(loading)return <section className="c3WizardCard c3ProfileCompletion" aria-label="Service Address"><div className="c3Notice">Loading saved Service Addresses…</div></section>;
 return <section className="c3WizardCard c3ProfileCompletion" aria-label="Service Address">
  <div className="c3SectionHead"><div><small>{showForm?`Step ${formStep} of 2`:'Service request'}</small><h2>{showForm?(formStep===1?(editingId?'Edit Service Address':'Add Service Address'):'Specifics & Access'):'Select Service Address'}</h2><p>{showForm?(formStep===1?'Enter the full service location, including Ward when available.':'Add optional entry instructions for the provider.'):'Choose from your saved locations or add a new one.'}</p></div></div>
  {!showForm?<><div className="c3Review" style={{marginBottom:16}}><div className="c3ReviewRow"><span>Verified phone</span><strong>{phone?`+960 ${phone}`:'Not verified'}</strong></div><div className="c3ReviewRow"><span>Name</span><strong>{name||'Missing'}</strong></div></div>{addresses.length?<div className="c3Urgency" style={{marginBottom:16}}>{addresses.map(address=><div key={address.id} style={{display:'grid',gap:8}}><button type="button" className={selectedId===address.id?'selected':''} onClick={()=>selectAddress(address)} disabled={saving}><strong>{address.address_line1||address.label||'Unnamed address'}{address.is_default?' · Default':''}</strong><span>{addressText(address)||'Address details missing'}</span>{address.service_location_unit_id&&wards.find(w=>w.id===address.service_location_unit_id)?<span>Ward: {wards.find(w=>w.id===address.service_location_unit_id)?.display_name}</span>:null}</button><div style={{display:'flex',gap:8}}><button type="button" className="c3Secondary" onClick={()=>editAddress(address)} disabled={saving}>Edit</button><button type="button" className="c3Secondary" onClick={()=>void removeAddress(address)} disabled={saving}>Remove</button></div></div>)}</div>:<div className="c3Notice">No saved Service Address yet.</div>}<button type="button" className="c3Secondary" onClick={addNew} disabled={saving}>+ Add a New Service Address</button>{selectedAddress?<div className="c3Review" style={{marginTop:16}}><div className="c3ReviewRow"><span>Selected for this service</span><strong>{selectedAddress.address_line1||selectedAddress.label}</strong></div><div className="c3ReviewRow"><span>Location</span><strong>{addressText(selectedAddress)}</strong></div>{selectedAddressWard?<div className="c3ReviewRow"><span>Ward</span><strong>{selectedAddressWard.display_name}</strong></div>:null}{selectedAddress.access_instructions?<div className="c3ReviewRow"><span>Access notes</span><strong>{selectedAddress.access_instructions}</strong></div>:null}</div>:null}<button className="c3Primary" type="button" onClick={()=>void continueRequest()} disabled={saving||!validContact||!selectedAddress} style={{marginTop:16}}>{saving?'Confirming…':'Proceed'}</button></>:null}
  {showForm?<form className="c3Form" data-service-address-form onSubmit={saveAddress} noValidate>
   {formStep===1?<><label>House / Apartment Name<input value={house} onChange={e=>setHouse(e.target.value)} autoComplete="address-line1" placeholder="House or apartment name" disabled={saving}/></label><label>Road / Street<input value={road} onChange={e=>setRoad(e.target.value)} autoComplete="address-line2" placeholder="Road or street" disabled={saving}/></label><label>Atoll / Region<select value={atollId} onChange={e=>{setAtollId(e.target.value);setIslandId('');setWardId('');}} disabled={saving||locationLoading}><option value="">{locationLoading?'Loading Atoll / Region…':'Select Atoll / Region'}</option>{atolls.map(a=><option key={a.id} value={a.id}>{a.display_name}</option>)}</select></label><label>Island / City<select value={islandId} onChange={e=>{setIslandId(e.target.value);setWardId('');}} disabled={saving||locationLoading||!atollId}><option value="">Select Island / City</option>{filteredIslands.map(i=><option key={i.id} value={i.id}>{i.display_name}</option>)}</select></label><label>Ward {wardRequired?null:<span style={{fontWeight:500}}>optional</span>}<select value={wardId} onChange={e=>setWardId(e.target.value)} disabled={saving||locationLoading||!islandId||!filteredWards.length}><option value="">{!islandId?'Select Island / City first':filteredWards.length?'Select Ward':'No ward required for this island'}</option>{filteredWards.map(w=><option key={w.id} value={w.id}>{w.display_name}</option>)}</select></label><div style={{display:'flex',gap:8}}><button className="c3Secondary" type="button" onClick={cancelForm} disabled={saving}>Back</button><button className="c3Primary" type="button" onClick={goNext} disabled={saving||locationLoading||Boolean(locationError)||!validForm}>Next Step →</button></div></>:<><label className="full">Access Instructions <span style={{fontWeight:500}}>optional</span><textarea value={accessInstructions} onChange={e=>setAccessInstructions(e.target.value)} placeholder="Floor, unit, gate or directions for the provider" disabled={saving}/></label><div style={{display:'flex',gap:8}}><button className="c3Secondary" type="button" onClick={()=>setFormStep(1)} disabled={saving}>Back</button><button className="c3Primary" type="submit" disabled={saving||locationLoading||Boolean(locationError)||!validForm}>{saving?'Saving…':editingId?'Update & Proceed':'Save and Proceed'}</button></div></>}
  </form>:null}
  {locationError?<p className="c3Notice" role="alert">{locationError}</p>:null}
  {message?<p className="c3Notice" role="status" aria-live="polite">{message}</p>:null}
 </section>;
}
