'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { apiLogout } from '../lib/apiClient';
import CustomerHeader from './components/customer/CustomerHeader';
import CustomerSidebar from './components/customer/CustomerSidebar';
import ServiceIcon from './components/customer/ServiceIcon';
import { useFixitLocale } from './components/customer/useFixitLocale';
import './customer-v3.css';

const SUBMIT_REQUEST_URL='/api/legacy-edge?service=submit-request';
const MEDIA_URL='/api/legacy-edge?service=request-media';
const LOCATION_URL='/api/locations/catalog';
const SERVICES_URL='/api/services/catalog';

type Profile={role:'CUSTOMER'|'PROVIDER'|'ADMIN';full_name?:string|null;phone_number?:string|null;provider_approved?:boolean};
type Atoll={id:string;code?:string;display_name:string;sort_order?:number};
type Island={id:string;atoll_id:string;display_name:string;location_kind?:string;sort_order?:number};
type LocationUnit={id:string;atoll_id:string;island_id:string;unit_type:string;display_name:string;sort_order?:number};
type ServiceCategory={id:string;code:string;name:string;sort_order:number};
type ServiceAddress={id:string;label:string;address_line1:string;address_line2?:string|null;city?:string|null;state_region?:string|null;service_atoll_id?:string|null;service_island_id?:string|null;service_location_unit_id?:string|null;access_instructions?:string|null;is_default:boolean;is_active:boolean};
type LastRequest={id:string;service:string;location:string;status:string;createdAt:string};
type Step=1|2|3|4|5;
type NewAddressDraft={label:string;atollId:string;islandId:string;wardId:string;road:string;house:string;access:string};
const EMPTY_ADDRESS:NewAddressDraft={label:'Home',atollId:'',islandId:'',wardId:'',road:'',house:'',access:''};

function displayStatus(status:unknown){const value=String(status||'NEW').toUpperCase();if(value==='PENDING'||value==='RESPONDED')return'NEW';if(value==='IN_PROGRESS'||value==='INSPECTION_SCHEDULED')return'PROCESSING';return value;}
async function jsonFetch(input:RequestInfo|URL,init:RequestInit={},timeoutMs=15000){const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(input,{...init,credentials:'same-origin',cache:'no-store',signal:controller.signal});const payload=await response.json().catch(()=>({}));if(response.status===401){window.location.replace('/login?next=%2Fhome');throw new Error('Authentication required.');}if(!response.ok)throw new Error(payload?.error||'Request failed.');return payload;}finally{window.clearTimeout(timer);}}
function isSupportedPhoto(file:File){const type=String(file.type||'').toLowerCase();if(type.startsWith('image/'))return true;return /\.(jpe?g|png|webp|heic|heif)$/i.test(String(file.name||''));}

export default function CustomerPortal(){
 const{language,setLanguage,t,isDhivehi}=useFixitLocale();
 const[profile,setProfile]=useState<Profile|null>(null);const[authReady,setAuthReady]=useState(false);const[mode,setMode]=useState<'home'|'request'>('home');const[step,setStep]=useState<Step>(1);
 const[services,setServices]=useState<ServiceCategory[]>([]);const[serviceCode,setServiceCode]=useState('');const[description,setDescription]=useState('');const[photos,setPhotos]=useState<File[]>([]);const[notes,setNotes]=useState('');
 const[addresses,setAddresses]=useState<ServiceAddress[]>([]);const[selectedAddressId,setSelectedAddressId]=useState('');const[atolls,setAtolls]=useState<Atoll[]>([]);const[islands,setIslands]=useState<Island[]>([]);const[wards,setWards]=useState<LocationUnit[]>([]);
 const[addingAddress,setAddingAddress]=useState(false);const[newAddress,setNewAddress]=useState<NewAddressDraft>(EMPTY_ADDRESS);const[addressBusy,setAddressBusy]=useState(false);
 const[isOnSiteSameAsCustomer,setIsOnSiteSameAsCustomer]=useState(true);const[onSiteContactName,setOnSiteContactName]=useState('');const[onSiteContactPhone,setOnSiteContactPhone]=useState('');
 const[message,setMessage]=useState('');const[submitting,setSubmitting]=useState(false);const[uploading,setUploading]=useState(false);const[lastRequest,setLastRequest]=useState<LastRequest|null>(null);

 const selectedService=useMemo(()=>services.find(s=>s.code===serviceCode)||null,[services,serviceCode]);
 const selectedAddress=useMemo(()=>addresses.find(a=>a.id===selectedAddressId)||null,[addresses,selectedAddressId]);
 const selectedAtoll=useMemo(()=>atolls.find(a=>a.id===newAddress.atollId)||null,[atolls,newAddress.atollId]);
 const selectedIsland=useMemo(()=>islands.find(i=>i.id===newAddress.islandId&&i.atoll_id===newAddress.atollId)||null,[islands,newAddress.islandId,newAddress.atollId]);
 const selectedWard=useMemo(()=>wards.find(w=>w.id===newAddress.wardId&&w.island_id===newAddress.islandId)||null,[wards,newAddress.wardId,newAddress.islandId]);
 const filteredIslands=useMemo(()=>islands.filter(i=>i.atoll_id===newAddress.atollId),[islands,newAddress.atollId]);
 const filteredWards=useMemo(()=>wards.filter(w=>w.atoll_id===newAddress.atollId&&w.island_id===newAddress.islandId),[wards,newAddress.atollId,newAddress.islandId]);
 const photoUrls=useMemo(()=>photos.map(file=>URL.createObjectURL(file)),[photos]);
 useEffect(()=>()=>photoUrls.forEach(url=>URL.revokeObjectURL(url)),[photoUrls]);

 useEffect(()=>{let live=true;void(async()=>{try{const session=await jsonFetch('/api/auth/session');if(session?.authenticated!==true)throw new Error('Unable to confirm your secure login session.');const[profilePayload,locationPayload,servicePayload,addressPayload]=await Promise.all([jsonFetch('/api/user/profile'),jsonFetch(LOCATION_URL),jsonFetch(SERVICES_URL),jsonFetch('/api/user/service-addresses')]);if(!live)return;setProfile(profilePayload?.profile||session?.profile||null);setAtolls(locationPayload?.atolls||[]);setIslands(locationPayload?.islands||[]);setWards(locationPayload?.wards||[]);setServices(servicePayload?.services||[]);const rows=(addressPayload?.addresses||[]) as ServiceAddress[];setAddresses(rows);setSelectedAddressId(rows.find(a=>a.is_default)?.id||rows[0]?.id||'');try{const raw=localStorage.getItem('fixit:last-request');if(raw){const r=JSON.parse(raw);setLastRequest({id:r.id||r.ticket_number,service:r.service||r.service_name,location:r.location||r.service_location_text,status:displayStatus(r.status),createdAt:r.createdAt||r.created_at});}}catch{}if(new URLSearchParams(window.location.search).get('new')==='1')setMode('request');}catch(error){if(live&&!(error instanceof Error&&error.message==='Authentication required.'))setMessage(error instanceof Error?error.message:'Unable to load request setup.');}finally{if(live)setAuthReady(true);}})();return()=>{live=false;};},[]);

 async function reloadAddresses(preferId=''){const payload=await jsonFetch('/api/user/service-addresses');const rows=(payload?.addresses||[]) as ServiceAddress[];setAddresses(rows);setSelectedAddressId(preferId&&rows.some(a=>a.id===preferId)?preferId:(rows.find(a=>a.is_default)?.id||rows[0]?.id||''));}
 async function signOut(){await apiLogout();window.location.replace('/login');}
 function resetContact(){setIsOnSiteSameAsCustomer(true);setOnSiteContactName('');setOnSiteContactPhone('');}
 function startRequest(category?:ServiceCategory){resetContact();setDescription('');setNotes('');setPhotos([]);setMessage('');setAddingAddress(false);setNewAddress(EMPTY_ADDRESS);if(category){setServiceCode(category.code);setStep(2);}else{setServiceCode('');setStep(1);}setMode('request');window.scrollTo({top:0});}
 function closeRequest(){setMode('home');setStep(1);setAddingAddress(false);setMessage('');window.scrollTo({top:0});}
 function next(){if(step===1&&!selectedService){setMessage('Choose a service.');return;}if(step===2&&description.trim().length<10){setMessage('Tell us a little more about the problem.');return;}if(step===3&&!selectedAddress){setMessage('Choose or add a Service Address.');return;}if(step===4&&!isOnSiteSameAsCustomer&&(onSiteContactName.trim().length<2||onSiteContactPhone.trim().length<5)){setMessage('Enter the on-site contact name and phone number.');return;}setMessage('');setStep(Math.min(5,step+1) as Step);window.scrollTo({top:0,behavior:'smooth'});}
 function back(){if(addingAddress){setAddingAddress(false);setNewAddress(EMPTY_ADDRESS);setMessage('');return;}if(step===1){closeRequest();return;}setMessage('');setStep((step-1) as Step);window.scrollTo({top:0,behavior:'smooth'});}
 function choosePhotos(list:FileList|null){if(!list)return;const picked=Array.from(list);const accepted=picked.filter(isSupportedPhoto);if(picked.length&&accepted.length===0){setMessage('Unsupported photo format. Use JPEG, PNG, WebP, HEIC or HEIF.');return;}const next=[...photos,...accepted].slice(0,3);if(next.some(f=>f.size>5*1024*1024)){setMessage('Each photo must be 5 MB or smaller.');return;}setPhotos(next);setMessage(accepted.length<picked.length?'Some unsupported files were skipped.':picked.length+photos.length>3?'Maximum 3 photos.':'');}
 async function uploadPhotos(ticket:string){if(!photos.length)return;setUploading(true);try{for(const file of photos){let uploaded=false;let lastError='';for(let attempt=1;attempt<=3&&!uploaded;attempt++){try{const form=new FormData();form.append('ticketNumber',ticket);form.append('file',file,file.name||'photo.jpg');const r=await fetch(MEDIA_URL,{method:'POST',credentials:'same-origin',cache:'no-store',body:form,signal:AbortSignal.timeout(25000)});const p=await r.json().catch(()=>({}));if(r.status===401){window.location.replace('/login?next=%2Fhome');throw new Error('Authentication required.');}if(r.ok){uploaded=true;break;}lastError=p?.error||`Unable to upload ${file.name||'photo'}`;}catch(error){if(error instanceof Error&&error.message==='Authentication required.')throw error;lastError=error instanceof Error?error.message:`Unable to upload ${file.name||'photo'}`;}if(!uploaded&&attempt<3)await new Promise(resolve=>window.setTimeout(resolve,500*attempt));}if(!uploaded)throw new Error(lastError||'Photo upload failed.');}}finally{setUploading(false);}}

 function validateNewAddress(){if(newAddress.label.trim().length<2)return'Enter a name for the address.';if(!selectedAtoll)return'Select an Atoll / Region.';if(!selectedIsland)return'Select an Island / City.';if(filteredWards.length&&!selectedWard)return'Select a Ward.';if(newAddress.road.trim().length<2)return'Enter Road / Street.';if(newAddress.house.trim().length<2)return'Enter House / Apartment.';return'';}
 async function saveNewAddress(event:FormEvent){event.preventDefault();if(addressBusy)return;const error=validateNewAddress();if(error){setMessage(error);return;}setAddressBusy(true);setMessage('Saving Service Address…');try{const payload=await jsonFetch('/api/user/service-addresses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:newAddress.label.trim(),address_line1:newAddress.house.trim(),address_line2:newAddress.road.trim(),city:selectedIsland?.display_name||'',state_region:selectedAtoll?.display_name||'',service_atoll_id:selectedAtoll?.id||null,service_island_id:selectedIsland?.id||null,service_location_unit_id:selectedWard?.id||null,access_instructions:newAddress.access.trim()||null})});await reloadAddresses(payload?.address?.id||'');setAddingAddress(false);setNewAddress(EMPTY_ADDRESS);setMessage('Service Address saved and selected.');}catch(error){if(!(error instanceof Error&&error.message==='Authentication required.'))setMessage(error instanceof Error?error.message:'Unable to save Service Address.');}finally{setAddressBusy(false);}}

 async function submitRequest(){if(!selectedService||!selectedAddress){setMessage('Review the service and Service Address before sending.');return;}if(submitting)return;setSubmitting(true);setMessage('Sending request…');const originalDefault=addresses.find(a=>a.is_default)||null;let switchedDefault=false;try{if(!selectedAddress.is_default){await jsonFetch('/api/user/service-addresses',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selectedAddress.id,action:'set_default'})});switchedDefault=true;}const payload=await jsonFetch(SUBMIT_REQUEST_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({serviceCategoryCode:serviceCode,islandId:selectedAddress.service_island_id,locationUnitId:selectedAddress.service_location_unit_id||null,preferredDate:null,description:description.trim(),customerNotes:notes.trim()||selectedAddress.access_instructions||null,urgency:'STANDARD',isOnSiteSameAsCustomer,onSiteContactName:isOnSiteSameAsCustomer?null:onSiteContactName.trim(),onSiteContactPhone:isOnSiteSameAsCustomer?null:onSiteContactPhone.trim(),serviceAddressId:selectedAddress.id,clientRequestId:crypto.randomUUID()})},20000);if(!payload?.request?.ticket_number)throw new Error('Unable to submit request.');let photoWarning='';try{await uploadPhotos(payload.request.ticket_number);}catch(error){if(error instanceof Error&&error.message==='Authentication required.')throw error;photoWarning=error instanceof Error?` Photos need retry: ${error.message}`:' Photos need retry.';}const request:LastRequest={id:payload.request.ticket_number,service:payload.request.service_name||selectedService.name,location:payload.request.service_location_text||addressSummary(selectedAddress),status:displayStatus(payload.request.status),createdAt:payload.request.created_at||new Date().toISOString()};localStorage.setItem('fixit:last-request',JSON.stringify(request));setLastRequest(request);setMessage(`Request sent.${photoWarning}`);window.location.assign(`/requests/${encodeURIComponent(request.id)}`);}catch(error){if(!(error instanceof Error&&error.message==='Authentication required.'))setMessage(error instanceof Error?error.message:'Unable to submit request.');}finally{if(switchedDefault&&originalDefault){try{await jsonFetch('/api/user/service-addresses',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:originalDefault.id,action:'set_default'})});}catch{}}setSubmitting(false);}}

 function addressSummary(a:ServiceAddress){const ward=wards.find(w=>w.id===a.service_location_unit_id)?.display_name;return[a.state_region,a.city,ward,a.address_line2,a.address_line1].filter(Boolean).join(' · ');}
 function phoneLabel(){const value=String(profile?.phone_number||'').trim();if(!value)return'Verified account phone';return value.startsWith('+960')?value:`+960 ${value}`;}
 if(!authReady)return <div className="c4App" aria-busy="true" aria-label="Loading account"/>;
 const firstName=(profile?.full_name||'there').split(' ')[0];
 const right=<div className="c4HeaderActions"><div className="c4LangCompact"><button className={language==='en'?'active':''} onClick={()=>setLanguage('en')}>EN</button><button className={language==='dv'?'active':''} onClick={()=>setLanguage('dv')}>ދި</button></div>{profile?<button className="c3Avatar" onClick={()=>window.location.href='/profile'} aria-label={t('profile')}>{(profile.full_name||profile.role).slice(0,2).toUpperCase()}</button>:null}</div>;

 return <div className={`c4App ${isDhivehi?'dv':''}`} dir={isDhivehi?'rtl':'ltr'}><CustomerSidebar language={language} setLanguage={setLanguage} profileName={profile?.full_name} onNewRequest={()=>startRequest()} onSignOut={profile?signOut:undefined}/><main className="c4Main c3Page frozenCustomerFlow"><CustomerHeader title={mode==='request'?'Request for Service':t('home')} backHref={mode==='request'?'/home':undefined} right={right}/><div className="c3Shell">
 {mode==='home'?<div className="c3Home"><section className="c3Welcome"><div><small>{t('fixitMaldives')}</small><h1>{t('hi')} {firstName}, {t('whatNeedsFixing')}</h1><p>Select a service to start a simple five-step request.</p></div><button className="c3Primary" onClick={()=>startRequest()}>Create Request</button></section><section className="c3Section" id="all-services"><div className="c3SectionHead"><div><small>Services</small><h2>What service do you need?</h2></div></div><div className="c3ServiceGrid">{services.map(item=><button className="c3ServiceTile" key={item.id} onClick={()=>startRequest(item)}><ServiceIcon name={item.name}/><strong>{item.name}</strong><span>Start request</span></button>)}</div></section>{lastRequest?<section className="c3Section"><div className="c3SectionHead"><div><small>Latest request</small><h2>{lastRequest.service}</h2></div><a className="c3Secondary" href="/requests">All Requests</a></div><div className="c3ActiveCard"><div><span className={`c3Status ${lastRequest.status==='COMPLETED'?'completed':''}`}>{lastRequest.status}</span><p>{lastRequest.location} · {lastRequest.id}</p></div><a className="c3Primary" href={`/requests/${encodeURIComponent(lastRequest.id)}`}>Open</a></div></section>:null}</div>:<div className="c3Wizard">
  <div className="c3WizardTop"><div className="c3StepDots">{([1,2,3,4,5] as const).map(n=><span key={n} className={`c3StepDot ${n===step?'active':n<step?'done':''}`}/>)}</div><span className="c3Status">Step {step} of 5</span></div>
  <section className={`c3WizardCard ${addingAddress?'frozenAddressSubscreen':''}`}>
   {step===1?<><div className="c3Question"><small>REQUEST FOR SERVICE</small><h1>What can we help you fix?</h1><p>Choose the service that best matches your problem.</p></div><div className="c3ServiceGrid frozenServiceGrid">{services.map(item=><button className={`c3ServiceTile ${serviceCode===item.code?'selected':''}`} key={item.id} onClick={()=>setServiceCode(item.code)}><ServiceIcon name={item.name}/><strong>{item.name}</strong><span>{serviceCode===item.code?'Selected ✓':'Choose service'}</span></button>)}</div></>:null}
   {step===2?<><div className="c3Question"><small>PHOTOS & DETAILS</small><h1>Tell us what’s wrong</h1><p>A short description and up to 3 photos help the provider prepare.</p></div>{selectedService?<div className="frozenSelectedService"><ServiceIcon name={selectedService.name}/><div><small>Selected service</small><strong>{selectedService.name}</strong></div></div>:null}<div className="c3Form"><label className="c3Field full">What is the problem?<textarea maxLength={5000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the issue…"/><span className="frozenFieldHelp">{description.length} characters · add at least 10</span></label></div><div className="c3PhotoDrop"><label className="c3Secondary">+ Add photos ({photos.length}/3)<input type="file" accept="image/*,.heic,.heif" multiple disabled={photos.length>=3} onChange={e=>{choosePhotos(e.target.files);e.currentTarget.value='';}}/></label><p>Optional · maximum 3 photos · 5 MB each.</p><div className="c3PhotoGrid">{photos.map((file,index)=><div className="c3Photo" key={`${file.name}:${file.lastModified}`}><img src={photoUrls[index]} alt={`Request photo ${index+1}`}/><button type="button" onClick={()=>setPhotos(current=>current.filter((_,i)=>i!==index))}>×</button></div>)}</div></div></>:null}
   {step===3?<>{!addingAddress?<><div className="c3Question"><small>SERVICE ADDRESS</small><h1>Where do you need the service?</h1><p>Choose a saved address or add a new one.</p></div><div className="frozenAddressList">{addresses.map(a=><button type="button" key={a.id} className={`frozenAddressCard ${selectedAddressId===a.id?'selected':''}`} onClick={()=>setSelectedAddressId(a.id)}><div className="frozenAddressHead"><div><strong>{a.label}</strong>{a.is_default?<span>DEFAULT</span>:null}</div><b>{selectedAddressId===a.id?'✓':'○'}</b></div><p>{addressSummary(a)}</p>{a.access_instructions?<small>{a.access_instructions}</small>:null}</button>)}{!addresses.length?<div className="c3Notice">No Service Address saved yet.</div>:null}</div><button type="button" className="c3Secondary frozenAddAddress" onClick={()=>{setAddingAddress(true);setMessage('');}}>+ Add Service Address</button></>:<form onSubmit={saveNewAddress}><div className="c3Question"><small>NEW SERVICE ADDRESS</small><h1>Where should the provider go?</h1></div><div className="c3Form"><label className="c3Field full">Name<input value={newAddress.label} onChange={e=>setNewAddress(v=>({...v,label:e.target.value}))}/></label><label className="c3Field full">Atoll / Region<select value={newAddress.atollId} onChange={e=>setNewAddress(v=>({...v,atollId:e.target.value,islandId:'',wardId:''}))}><option value="">Select Atoll / Region</option>{atolls.map(a=><option key={a.id} value={a.id}>{a.display_name}</option>)}</select></label><label className="c3Field full">Island / City<select value={newAddress.islandId} disabled={!newAddress.atollId} onChange={e=>setNewAddress(v=>({...v,islandId:e.target.value,wardId:''}))}><option value="">Select Island / City</option>{filteredIslands.map(i=><option key={i.id} value={i.id}>{i.display_name}</option>)}</select></label>{filteredWards.length?<label className="c3Field full">Ward<select value={newAddress.wardId} onChange={e=>setNewAddress(v=>({...v,wardId:e.target.value}))}><option value="">Select Ward</option>{filteredWards.map(w=><option key={w.id} value={w.id}>{w.display_name}</option>)}</select></label>:null}<label className="c3Field full">Road / Street<input value={newAddress.road} onChange={e=>setNewAddress(v=>({...v,road:e.target.value}))}/></label><label className="c3Field full">House / Apartment<input value={newAddress.house} onChange={e=>setNewAddress(v=>({...v,house:e.target.value}))}/></label><label className="c3Field full">Access Instructions <span>Optional</span><textarea value={newAddress.access} onChange={e=>setNewAddress(v=>({...v,access:e.target.value}))}/></label></div><div className="frozenSubActions"><button type="button" className="c3Secondary" onClick={()=>{setAddingAddress(false);setNewAddress(EMPTY_ADDRESS);}}>Back</button><button type="submit" className="c3Primary" disabled={addressBusy}>{addressBusy?'Saving…':'Save Address'}</button></div></form>}</>:null}
   {step===4?<><div className="c3Question"><small>CONTACT & ACCESS</small><h1>Who will be there?</h1><p>Your OTP-verified account contact is reused automatically.</p></div><div className="c3Urgency frozenContactChoices"><button type="button" className={isOnSiteSameAsCustomer?'selected':''} onClick={resetContact}><strong>I will be there</strong><span>{profile?.full_name||'Account holder'} · {phoneLabel()}</span><b>VERIFIED ✓</b></button><button type="button" className={!isOnSiteSameAsCustomer?'selected':''} onClick={()=>setIsOnSiteSameAsCustomer(false)}><strong>Someone else</strong><span>Add the on-site contact</span></button></div>{!isOnSiteSameAsCustomer?<div className="c3Form"><label className="c3Field">Contact Name<input value={onSiteContactName} onChange={e=>setOnSiteContactName(e.target.value)}/></label><label className="c3Field">Contact Phone<input type="tel" value={onSiteContactPhone} onChange={e=>setOnSiteContactPhone(e.target.value)}/></label></div>:null}<div className="c3Form"><label className="c3Field full">Additional Instructions <span>Optional</span><textarea maxLength={240} value={notes} onChange={e=>setNotes(e.target.value)}/><span className="frozenFieldHelp">{notes.length} / 240</span></label></div></>:null}
   {step===5?<><div className="c3Question"><small>REVIEW & SEND</small><h1>Check everything before sending</h1></div><div className="c3Review frozenReview"><div className="c3ReviewRow"><div><span>SERVICE</span><strong>{selectedService?.name}</strong></div><button type="button" onClick={()=>setStep(1)}>Edit</button></div><div className="c3ReviewRow"><div><span>PROBLEM</span><strong>{description}</strong></div><button type="button" onClick={()=>setStep(2)}>Edit</button></div><div className="c3ReviewRow"><div><span>PHOTOS</span><strong>{photos.length} attached</strong></div><button type="button" onClick={()=>setStep(2)}>Edit</button></div><div className="c3ReviewRow"><div><span>SERVICE ADDRESS</span><strong>{selectedAddress?`${selectedAddress.label} · ${addressSummary(selectedAddress)}`:'Not selected'}</strong></div><button type="button" onClick={()=>setStep(3)}>Edit</button></div><div className="c3ReviewRow"><div><span>CONTACT</span><strong>{isOnSiteSameAsCustomer?`${profile?.full_name||'Account holder'} · ${phoneLabel()} · Verified`:`${onSiteContactName} · ${onSiteContactPhone}`}</strong></div><button type="button" onClick={()=>setStep(4)}>Edit</button></div></div><div className="c3Notice frozenReadyNotice"><strong>Ready to send</strong><span>The first eligible provider who accepts will be assigned automatically.</span></div>{uploading?<div className="c3Notice">Uploading photos…</div>:null}</>:null}
   {message?<div className="c3Notice" role="status">{message}</div>:null}
  </section>
  {!addingAddress?<div className="c3ActionDock"><div className="c3ActionInner"><button type="button" className="c3Secondary" onClick={back}>{step===1?'Cancel':'Back'}</button>{step<5?<button type="button" className="c3Primary" onClick={next} disabled={step===2&&description.trim().length<10||step===3&&!selectedAddress||step===4&&!isOnSiteSameAsCustomer&&(onSiteContactName.trim().length<2||onSiteContactPhone.trim().length<5)}>Next →</button>:<button type="button" className="c3Primary" onClick={()=>void submitRequest()} disabled={submitting||uploading}>{submitting?'Sending…':'Send Request'}</button>}</div></div>:null}
 </div>}
 </div></main></div>;
}
