'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabaseClient';
import CustomerHeader from './components/customer/CustomerHeader';
import CustomerSidebar from './components/customer/CustomerSidebar';
import ServiceIcon from './components/customer/ServiceIcon';
import { useFixitLocale } from './components/customer/useFixitLocale';
import './customer-v3.css';

const SUBMIT_REQUEST_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/submit-request';
const MEDIA_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/request-media';
const LOCATION_URL='/api/locations/catalog';

type Profile={role:'CUSTOMER'|'PROVIDER'|'ADMIN';full_name?:string|null;phone_number?:string|null;provider_approved?:boolean};
type Atoll={id:string;code?:string;display_name:string;sort_order?:number};
type Island={id:string;atoll_id:string;display_name:string;location_kind?:string;sort_order?:number};
type LocationUnit={id:string;atoll_id:string;island_id:string;unit_type:string;display_name:string;sort_order?:number};
type ServiceCategory={id:string;code:string;name:string;sort_order:number};
type ServiceAddress={id:string;label:string;address_line1:string;address_line2?:string|null;city?:string|null;state_region?:string|null;service_atoll_id?:string|null;service_island_id?:string|null;service_location_unit_id?:string|null;access_instructions?:string|null;is_default:boolean;is_active:boolean};
type LastRequest={id:string;service:string;location:string;status:string;createdAt:string};
type Step=1|2|3|4|5;
type NewAddressDraft={label:string;atollId:string;islandId:string;wardId:string;road:string;house:string;access:string};
const EMPTY_ADDRESS:NewAddressDraft={label:'Home',atollId:'',islandId:'',wardId:'',road:'',house:'',access:''};

async function loadAccountProfile(){const response=await fetch('/api/user/profile',{credentials:'same-origin',cache:'no-store'});if(!response.ok)return null;const payload=await response.json().catch(()=>({}));return payload?.profile as Profile|null;}
function displayStatus(status:unknown){const value=String(status||'NEW').toUpperCase();if(value==='PENDING'||value==='RESPONDED')return'NEW';if(value==='IN_PROGRESS'||value==='INSPECTION_SCHEDULED')return'PROCESSING';return value;}
async function fetchWithTimeout(input:RequestInfo|URL,init:RequestInit={},timeoutMs=15000){const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(input,{...init,signal:controller.signal});}finally{window.clearTimeout(timer);}}

export default function CustomerPortal(){
 const{language,setLanguage,t,isDhivehi}=useFixitLocale();
 const[profile,setProfile]=useState<Profile|null>(null);const[authReady,setAuthReady]=useState(false);const[mode,setMode]=useState<'home'|'request'>('home');const[step,setStep]=useState<Step>(1);
 const[services,setServices]=useState<ServiceCategory[]>([]);const[serviceCode,setServiceCode]=useState('');const[description,setDescription]=useState('');const[photos,setPhotos]=useState<File[]>([]);const[notes,setNotes]=useState('');
 const[addresses,setAddresses]=useState<ServiceAddress[]>([]);const[selectedAddressId,setSelectedAddressId]=useState('');const[atolls,setAtolls]=useState<Atoll[]>([]);const[islands,setIslands]=useState<Island[]>([]);const[wards,setWards]=useState<LocationUnit[]>([]);
 const[addingAddress,setAddingAddress]=useState(false);const[newAddress,setNewAddress]=useState<NewAddressDraft>(EMPTY_ADDRESS);const[addressBusy,setAddressBusy]=useState(false);
 const[isOnSiteSameAsCustomer,setIsOnSiteSameAsCustomer]=useState(true);const[onSiteContactName,setOnSiteContactName]=useState('');const[onSiteContactPhone,setOnSiteContactPhone]=useState('');
 const[message,setMessage]=useState('');const[submitting,setSubmitting]=useState(false);const[uploading,setUploading]=useState(false);const[lastRequest,setLastRequest]=useState<LastRequest|null>(null);

 const selectedService=useMemo(()=>services.find(s=>s.code===serviceCode)||null,[services,serviceCode]);
 const selectedAddress=useMemo(()=>addresses.find(a=>a.id===selectedAddressId)||null,[addresses,selectedAddressId]);
 const selectedAtoll=useMemo(()=>atolls.find(a=>a.id===newAddress.atollId)||null,[atolls,newAddress.atollId]);
 const selectedIsland=useMemo(()=>islands.find(i=>i.id===newAddress.islandId&&i.atoll_id===newAddress.atollId)||null,[islands,newAddress.islandId,newAddress.atollId]);
 const selectedWard=useMemo(()=>wards.find(w=>w.id===newAddress.wardId&&w.island_id===newAddress.islandId)||null,[wards,newAddress.wardId,newAddress.islandId]);
 const filteredIslands=useMemo(()=>islands.filter(i=>i.atoll_id===newAddress.atollId),[islands,newAddress.atollId]);
 const filteredWards=useMemo(()=>wards.filter(w=>w.atoll_id===newAddress.atollId&&w.island_id===newAddress.islandId),[wards,newAddress.atollId,newAddress.islandId]);
 const photoUrls=useMemo(()=>photos.map(file=>URL.createObjectURL(file)),[photos]);
 useEffect(()=>()=>photoUrls.forEach(url=>URL.revokeObjectURL(url)),[photoUrls]);

 useEffect(()=>{let live=true;void(async()=>{const{data}=await supabase.auth.getSession();if(!data.session){if(live)setAuthReady(true);return;}try{const[p]=await Promise.all([loadAccountProfile(),loadCatalogue(),loadAddresses()]);if(live)setProfile(p);}catch(error){if(live)setMessage(error instanceof Error?error.message:'Unable to load request setup.');}try{const raw=localStorage.getItem('fixit:last-request');if(raw&&live){const r=JSON.parse(raw);setLastRequest({id:r.id||r.ticket_number,service:r.service||r.service_name,location:r.location||r.service_location_text,status:displayStatus(r.status),createdAt:r.createdAt||r.created_at});}}catch{}if(live)setAuthReady(true);})();return()=>{live=false;};},[]);

 async function token(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.replace('/login?next=%2Fhome');throw new Error('Sign in required.');}return data.session.access_token;}
 async function loadCatalogue(){const[locationResponse,serviceResult]=await Promise.all([fetch(LOCATION_URL,{credentials:'same-origin',cache:'no-store'}),supabase.from('service_categories').select('id,code,name,sort_order').eq('is_active',true).is('parent_id',null).order('sort_order').order('name')]);const location=await locationResponse.json().catch(()=>({}));if(!locationResponse.ok)throw new Error(location?.error||'Unable to load Maldives locations.');if(serviceResult.error)throw serviceResult.error;setAtolls((location.atolls||[]) as Atoll[]);setIslands((location.islands||[]) as Island[]);setWards((location.wards||[]) as LocationUnit[]);setServices((serviceResult.data||[]) as ServiceCategory[]);}
 async function loadAddresses(){const response=await fetch('/api/user/service-addresses',{credentials:'same-origin',cache:'no-store'});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error||'Unable to load Service Addresses.');const rows=(payload.addresses||[]) as ServiceAddress[];setAddresses(rows);setSelectedAddressId(current=>current&&rows.some(a=>a.id===current)?current:(rows.find(a=>a.is_default)?.id||rows[0]?.id||''));}
 async function signOut(){await supabase.auth.signOut();window.location.href='/login';}
 function resetContact(){setIsOnSiteSameAsCustomer(true);setOnSiteContactName('');setOnSiteContactPhone('');}
 function startRequest(category?:ServiceCategory){resetContact();setDescription('');setNotes('');setPhotos([]);setMessage('');setAddingAddress(false);setNewAddress(EMPTY_ADDRESS);if(category){setServiceCode(category.code);setStep(2);}else{setServiceCode('');setStep(1);}setMode('request');window.scrollTo({top:0});}
 function closeRequest(){setMode('home');setStep(1);setAddingAddress(false);setMessage('');window.scrollTo({top:0});}
 function next(){if(step===1&&!selectedService){setMessage('Choose a service.');return;}if(step===2&&description.trim().length<10){setMessage('Tell us a little more about the problem.');return;}if(step===3&&!selectedAddress){setMessage('Choose or add a Service Address.');return;}if(step===4&&!isOnSiteSameAsCustomer&&(onSiteContactName.trim().length<2||onSiteContactPhone.trim().length<5)){setMessage('Enter the on-site contact name and phone number.');return;}setMessage('');setStep(Math.min(5,step+1) as Step);window.scrollTo({top:0,behavior:'smooth'});}
 function back(){if(addingAddress){setAddingAddress(false);setNewAddress(EMPTY_ADDRESS);setMessage('');return;}if(step===1){closeRequest();return;}setMessage('');setStep((step-1) as Step);window.scrollTo({top:0,behavior:'smooth'});}
 function choosePhotos(list:FileList|null){if(!list)return;const next=[...photos,...Array.from(list)].filter(f=>f.type.startsWith('image/')).slice(0,5);if(next.some(f=>f.size>5*1024*1024)){setMessage('Each photo must be 5 MB or smaller.');return;}setPhotos(next);}
 async function uploadPhotos(ticket:string,jwt:string){if(!photos.length)return;setUploading(true);try{for(const file of photos){let lastError='';for(let attempt=1;attempt<=3;attempt++){try{const form=new FormData();form.append('ticketNumber',ticket);form.append('file',file,file.name||'photo.jpg');const r=await fetchWithTimeout(MEDIA_URL,{method:'POST',headers:{Authorization:`Bearer ${jwt}`},body:form},25000);const p=await r.json().catch(()=>({}));if(r.ok){lastError='';break;}lastError=p?.error||`Unable to upload ${file.name||'photo'}`;}catch(error){lastError=error instanceof Error?error.message:`Unable to upload ${file.name||'photo'}`;}if(attempt<3)await new Promise(resolve=>window.setTimeout(resolve,500*attempt));}if(lastError)throw new Error(lastError);}}finally{setUploading(false);}}

 function validateNewAddress(){if(newAddress.label.trim().length<2)return'Enter a Name for the address.';if(!selectedAtoll)return'Select an Atoll / Region.';if(!selectedIsland)return'Select an Island / City.';if(filteredWards.length&&!selectedWard)return'Select a Ward.';if(newAddress.road.trim().length<2)return'Enter Road / Street.';if(newAddress.house.trim().length<2)return'Enter House / Apartment.';return'';}
 async function saveNewAddress(event:FormEvent){event.preventDefault();if(addressBusy)return;const error=validateNewAddress();if(error){setMessage(error);return;}setAddressBusy(true);setMessage('Saving Service Address…');try{const response=await fetch('/api/user/service-addresses',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:newAddress.label.trim(),address_line1:newAddress.house.trim(),address_line2:newAddress.road.trim(),city:selectedIsland?.display_name||'',state_region:selectedAtoll?.display_name||'',service_atoll_id:selectedAtoll?.id||null,service_island_id:selectedIsland?.id||null,service_location_unit_id:selectedWard?.id||null,access_instructions:newAddress.access.trim()||null})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error||'Unable to save Service Address.');await loadAddresses();setSelectedAddressId(payload.address?.id||'');setAddingAddress(false);setNewAddress(EMPTY_ADDRESS);setMessage('Service Address saved and selected.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to save Service Address.');}finally{setAddressBusy(false);}}

 async function submitRequest(){if(!selectedService||!selectedAddress){setMessage('Review the service and Service Address before sending.');return;}if(submitting)return;setSubmitting(true);setMessage('Sending request…');const originalDefault=addresses.find(a=>a.is_default)||null;let switchedDefault=false;try{const jwt=await token();if(!selectedAddress.is_default){const setDefault=await fetch('/api/user/service-addresses',{method:'PATCH',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selectedAddress.id,action:'set_default'})});const p=await setDefault.json().catch(()=>({}));if(!setDefault.ok)throw new Error(p?.error||'Unable to select Service Address.');switchedDefault=true;}const response=await fetchWithTimeout(SUBMIT_REQUEST_URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${jwt}`},body:JSON.stringify({serviceCategoryCode:serviceCode,islandId:selectedAddress.service_island_id,locationUnitId:selectedAddress.service_location_unit_id||null,preferredDate:null,description:description.trim(),customerNotes:notes.trim()||selectedAddress.access_instructions||null,urgency:'STANDARD',isOnSiteSameAsCustomer,onSiteContactName:isOnSiteSameAsCustomer?null:onSiteContactName.trim(),onSiteContactPhone:isOnSiteSameAsCustomer?null:onSiteContactPhone.trim(),serviceAddressId:selectedAddress.id,clientRequestId:crypto.randomUUID()})},20000);const payload=await response.json().catch(()=>({}));if(!response.ok||!payload?.request?.ticket_number)throw new Error(payload?.error||'Unable to submit request');let photoWarning='';try{await uploadPhotos(payload.request.ticket_number,jwt);}catch(error){photoWarning=error instanceof Error?` Photos need retry: ${error.message}`:' Photos need retry.';}const request:LastRequest={id:payload.request.ticket_number,service:payload.request.service_name||selectedService.name,location:payload.request.service_location_text||addressSummary(selectedAddress),status:displayStatus(payload.request.status),createdAt:payload.request.created_at||new Date().toISOString()};localStorage.setItem('fixit:last-request',JSON.stringify(request));setLastRequest(request);setMessage(`Request sent.${photoWarning}`);window.location.assign(`/requests/${encodeURIComponent(request.id)}`);}catch(error){setMessage(error instanceof Error?error.message:'Unable to submit request.');}finally{if(switchedDefault&&originalDefault){try{await fetch('/api/user/service-addresses',{method:'PATCH',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:originalDefault.id,action:'set_default'})});}catch{}}setSubmitting(false);}}

 function addressSummary(a:ServiceAddress){const ward=wards.find(w=>w.id===a.service_location_unit_id)?.display_name;return[a.state_region,a.city,ward,a.address_line2,a.address_line1].filter(Boolean).join(' · ');}
 function phoneLabel(){const value=String(profile?.phone_number||'').trim();if(!value)return'Verified account phone';return value.startsWith('+960')?value:`+960 ${value}`;}
 if(!authReady)return <div className="c4App" aria-busy="true" aria-label="Loading account"/>;
 const firstName=(profile?.full_name||'there').split(' ')[0];
 const right=<div className="c4HeaderActions"><div className="c4LangCompact"><button className={language==='en'?'active':''} onClick={()=>setLanguage('en')}>EN</button><button className={language==='dv'?'active':''} onClick={()=>setLanguage('dv')}>ދި</button></div>{profile?<button className="c3Avatar" onClick={()=>window.location.href='/profile'} aria-label={t('profile')}>{(profile.full_name||profile.role).slice(0,2).toUpperCase()}</button>:null}</div>;

 return <div className={`c4App ${isDhivehi?'dv':''}`} dir={isDhivehi?'rtl':'ltr'}><CustomerSidebar language={language} setLanguage={setLanguage} profileName={profile?.full_name} onNewRequest={()=>startRequest()} onSignOut={profile?signOut:undefined}/><main className="c4Main c3Page frozenCustomerFlow"><CustomerHeader title={mode==='request'?'Request for Service':t('home')} backHref={mode==='request'?'/home':undefined} right={right}/><div className="c3Shell">
 {mode==='home'?<div className="c3Home"><section className="c3Welcome"><div><small>{t('fixitMaldives')}</small><h1>{t('hi')} {firstName}, {t('whatNeedsFixing')}</h1><p>Select a service to start a simple five-step request.</p></div><button className="c3Primary" onClick={()=>startRequest()}>Create Request</button></section><section className="c3Section" id="all-services"><div className="c3SectionHead"><div><small>Services</small><h2>What service do you need?</h2></div></div><div className="c3ServiceGrid">{services.map(item=><button className="c3ServiceTile" key={item.id} onClick={()=>startRequest(item)}><ServiceIcon name={item.name}/><strong>{item.name}</strong><span>Start request</span></button>)}</div></section>{lastRequest?<section className="c3Section"><div className="c3SectionHead"><div><small>Latest request</small><h2>{lastRequest.service}</h2></div><a className="c3Secondary" href="/requests">All Requests</a></div><div className="c3ActiveCard"><div><span className={`c3Status ${lastRequest.status==='COMPLETED'?'completed':''}`}>{lastRequest.status}</span><p>{lastRequest.location} · {lastRequest.id}</p></div><a className="c3Primary" href={`/requests/${encodeURIComponent(lastRequest.id)}`}>Open</a></div></section>:null}</div>:<div className="c3Wizard">
  <div className="c3WizardTop"><div className="c3StepDots">{([1,2,3,4,5] as const).map(n=><span key={n} className={`c3StepDot ${n===step?'active':n<step?'done':''}`}/>)}</div><span className="c3Status">Step {step} of 5</span></div>
  <section className={`c3WizardCard ${addingAddress?'frozenAddressSubscreen':''}`}>
   {step===1?<><div className="c3Question"><small>REQUEST FOR SERVICE</small><h1>What can we help you fix?</h1><p>Choose the service that best matches your problem. You can describe the details on the next screen.</p></div><div className="c3ServiceGrid frozenServiceGrid">{services.map(item=><button className={`c3ServiceTile ${serviceCode===item.code?'selected':''}`} key={item.id} onClick={()=>setServiceCode(item.code)}><div className="frozenServiceIcon"><ServiceIcon name={item.name}/></div><strong>{item.name}</strong><span>{serviceCode===item.code?'Selected ✓':'Choose service'}</span></button>)}</div>{selectedService?<div className="c3Notice frozenSelectedSummary"><span>Selected service</span><strong>{selectedService.name}</strong></div>:null}</>:null}

   {step===2?<><div className="c3Question"><small>DESCRIBE THE PROBLEM</small><h1>Tell us what’s wrong</h1><p>A short, clear description helps the provider understand the job before arriving.</p></div>{selectedService?<div className="frozenSelectedService"><ServiceIcon name={selectedService.name}/><div><small>Selected service</small><strong>{selectedService.name}</strong></div></div>:null}<div className="c3Form"><label className="c3Field full">What is the problem?<textarea maxLength={5000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="For example: The AC is running but the room is not getting cold."/><span className="frozenFieldHelp">{description.length} characters · add at least 10</span></label></div><div className="c3PhotoDrop"><label className="c3Secondary">+ Add photos ({photos.length}/5)<input type="file" accept="image/*" multiple onChange={e=>{choosePhotos(e.target.files);e.currentTarget.value='';}}/></label><p>Optional · show the problem area if helpful.</p><div className="c3PhotoGrid">{photos.map((file,index)=><div className="c3Photo" key={`${file.name}:${file.lastModified}`}><img src={photoUrls[index]} alt={`Request photo ${index+1}`}/><button type="button" onClick={()=>setPhotos(current=>current.filter((_,i)=>i!==index))}>×</button></div>)}</div></div></>:null}

   {step===3?<>{!addingAddress?<><div className="c3Question"><small>SERVICE ADDRESS</small><h1>Where do you need the service?</h1><p>Choose a saved address or add a new one. Your default address is selected automatically.</p></div><div className="frozenAddressList">{addresses.map(a=><button type="button" key={a.id} className={`frozenAddressCard ${selectedAddressId===a.id?'selected':''}`} onClick={()=>setSelectedAddressId(a.id)}><div className="frozenAddressHead"><div><strong>{a.label}</strong>{a.is_default?<span>DEFAULT</span>:null}</div><b>{selectedAddressId===a.id?'✓':'○'}</b></div><p>{addressSummary(a)}</p>{a.access_instructions?<small>{a.access_instructions}</small>:null}</button>)}{!addresses.length?<div className="c3Notice">No Service Address saved yet.</div>:null}</div><button type="button" className="c3Secondary frozenAddAddress" onClick={()=>{setAddingAddress(true);setMessage('');}}>+ Add Service Address</button></>:<form onSubmit={saveNewAddress}><div className="c3Question"><small>NEW SERVICE ADDRESS · 3A</small><h1>Where should the provider go?</h1><p>Add the address once. It will be saved and selected for this request.</p></div><div className="c3Form">
    <label className="c3Field full">Name<input value={newAddress.label} onChange={e=>setNewAddress(v=>({...v,label:e.target.value}))} placeholder="Home, Office, Apartment…"/><span className="frozenFieldHelp">A simple label to recognize this address later.</span></label>
    <label className="c3Field full">Atoll / Region<select value={newAddress.atollId} onChange={e=>setNewAddress(v=>({...v,atollId:e.target.value,islandId:'',wardId:''}))}><option value="">Select Atoll / Region</option>{atolls.map(a=><option key={a.id} value={a.id}>{a.display_name}</option>)}</select></label>
    <label className="c3Field full">Island / City<select value={newAddress.islandId} disabled={!newAddress.atollId} onChange={e=>setNewAddress(v=>({...v,islandId:e.target.value,wardId:''}))}><option value="">{newAddress.atollId?'Select Island / City':'Select Atoll / Region first'}</option>{filteredIslands.map(i=><option key={i.id} value={i.id}>{i.display_name}</option>)}</select></label>
    {filteredWards.length?<label className="c3Field full">Ward<select value={newAddress.wardId} onChange={e=>setNewAddress(v=>({...v,wardId:e.target.value}))}><option value="">Select Ward</option>{filteredWards.map(w=><option key={w.id} value={w.id}>{w.display_name}</option>)}</select><span className="frozenFieldHelp">Shown only where a ward applies.</span></label>:null}
    <label className="c3Field full">Road / Street<input value={newAddress.road} onChange={e=>setNewAddress(v=>({...v,road:e.target.value}))} placeholder="Road or street name"/></label>
    <label className="c3Field full">House / Apartment<input value={newAddress.house} onChange={e=>setNewAddress(v=>({...v,house:e.target.value}))} placeholder="House, building or apartment"/></label>
    <label className="c3Field full">Access Instructions <span>Optional</span><textarea value={newAddress.access} onChange={e=>setNewAddress(v=>({...v,access:e.target.value}))} placeholder="Floor, entrance, landmark…"/></label>
    </div><div className="frozenSubActions"><button type="button" className="c3Secondary" onClick={()=>{setAddingAddress(false);setNewAddress(EMPTY_ADDRESS);setMessage('');}}>Back</button><button type="submit" className="c3Primary" disabled={addressBusy}>{addressBusy?'Saving…':'Save Address'}</button></div></form>}</>:null}

   {step===4?<><div className="c3Question"><small>CONTACT & ACCESS</small><h1>Who will be there?</h1><p>Your OTP-verified account contact is reused automatically.</p></div><div className="c3Urgency frozenContactChoices"><button type="button" className={isOnSiteSameAsCustomer?'selected':''} onClick={resetContact}><strong>I will be there</strong><span>{profile?.full_name||'Account holder'} · {phoneLabel()}</span><b>VERIFIED ✓</b></button><button type="button" className={!isOnSiteSameAsCustomer?'selected':''} onClick={()=>setIsOnSiteSameAsCustomer(false)}><strong>Someone else</strong><span>Add the person the provider should contact</span></button></div>{!isOnSiteSameAsCustomer?<div className="c3Form"><label className="c3Field">Contact Name<input value={onSiteContactName} onChange={e=>setOnSiteContactName(e.target.value)} placeholder="Full name"/></label><label className="c3Field">Contact Phone<input type="tel" value={onSiteContactPhone} onChange={e=>setOnSiteContactPhone(e.target.value)} placeholder="+960 7XXXXXX"/></label></div>:null}<div className="c3Form"><label className="c3Field full">Additional Instructions <span>Optional</span><textarea maxLength={240} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Floor, gate, landmark, access instructions…"/><span className="frozenFieldHelp">{notes.length} / 240</span></label></div></>:null}

   {step===5?<><div className="c3Question"><small>REVIEW & SEND</small><h1>Check everything before sending</h1><p>You can edit any section before the request is submitted.</p></div><div className="c3Review frozenReview">
    <div className="c3ReviewRow"><div><span>SERVICE</span><strong>{selectedService?.name}</strong></div><button type="button" onClick={()=>setStep(1)}>Edit</button></div>
    <div className="c3ReviewRow"><div><span>PROBLEM</span><strong>{description}</strong></div><button type="button" onClick={()=>setStep(2)}>Edit</button></div>
    <div className="c3ReviewRow"><div><span>PHOTOS</span><strong>{photos.length} attached</strong></div><button type="button" onClick={()=>setStep(2)}>Edit</button></div>
    <div className="c3ReviewRow"><div><span>SERVICE ADDRESS</span><strong>{selectedAddress?`${selectedAddress.label} · ${addressSummary(selectedAddress)}`:'Not selected'}</strong></div><button type="button" onClick={()=>setStep(3)}>Edit</button></div>
    <div className="c3ReviewRow"><div><span>CONTACT</span><strong>{isOnSiteSameAsCustomer?`${profile?.full_name||'Account holder'} · ${phoneLabel()} · Verified`:`${onSiteContactName} · ${onSiteContactPhone}`}</strong></div><button type="button" onClick={()=>setStep(4)}>Edit</button></div>
    {(notes||selectedAddress?.access_instructions)?<div className="c3ReviewRow"><div><span>ACCESS NOTES</span><strong>{notes||selectedAddress?.access_instructions}</strong></div><button type="button" onClick={()=>setStep(4)}>Edit</button></div>:null}
   </div><div className="c3Notice frozenReadyNotice"><strong>Ready to send</strong><span>After sending, you’ll go directly to the full Request Details screen.</span></div>{uploading?<div className="c3Notice">Uploading photos…</div>:null}</>:null}

   {message?<div className="c3Notice" role="status">{message}</div>:null}
  </section>
  {!addingAddress?<div className="c3ActionDock"><div className="c3ActionInner"><button type="button" className="c3Secondary" onClick={back}>{step===1?'Cancel':'Back'}</button>{step<5?<button type="button" className="c3Primary" onClick={next} disabled={step===2&&description.trim().length<10||step===3&&!selectedAddress||step===4&&!isOnSiteSameAsCustomer&&(onSiteContactName.trim().length<2||onSiteContactPhone.trim().length<5)}>Next →</button>:<button type="button" className="c3Primary" onClick={()=>void submitRequest()} disabled={submitting||uploading}>{submitting?'Sending…':'Send Request'}</button>}</div><p className="frozenDockHint">{step===1?'Next: describe the problem and add photos':step===2?'Next: choose your service address':step===3?'Next: contact & access':step===4?'Next: review and send':'No payment is required at this stage'}</p></div>:null}
 </div>}
 </div></main></div>;
}
