'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabaseClient';
import { useAutoLocation } from '../lib/useAutoLocation';
import CustomerHeader from './components/customer/CustomerHeader';
import CustomerSidebar from './components/customer/CustomerSidebar';
import ServiceIcon from './components/customer/ServiceIcon';
import { useFixitLocale } from './components/customer/useFixitLocale';
import './customer-v3.css';

const SUBMIT_REQUEST_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/submit-request';
const MEDIA_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/request-media';
const LOCATION_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/location-catalogue';
const PROFILE_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/profile-requirements';
const REQUEST_TYPES=['URGENT','STANDARD','SCHEDULE'] as const;
type RequestType=typeof REQUEST_TYPES[number];
type Profile={role:'CUSTOMER'|'PROVIDER'|'ADMIN';full_name?:string|null;provider_approved?:boolean};
type Atoll={id:string;code:string;display_name:string;sort_order:number};
type Island={id:string;atoll_id:string;display_name:string;location_kind:string;sort_order:number};
type LocationUnit={id:string;atoll_id:string;island_id:string;parent_id?:string|null;unit_type:string;display_name:string;reference_code?:string|null;sort_order:number};
type ServiceCategory={id:string;code:string;name:string;sort_order:number};
type ServiceSubcategory={id:string;category_id:string;code:string;name:string;description?:string|null;sort_order:number};
type ProfileStatus={profile_completeness:number;missing_required_field_keys:string[];required_fields:{field_key:string;display_name:string;is_completed:boolean}[];can_request:boolean;completion_required:boolean};
type LastRequest={id:string;service:string;location:string;status:string;createdAt:string};
type Draft={serviceCode:string;subcategoryCode:string;atollId:string;islandId:string;unitId:string;preferredDate:string;description:string;notes:string;urgency:string;isOnSiteSameAsCustomer:boolean;onSiteContactName:string;onSiteContactPhone:string};
type Step=1|2|3|4|5;

async function loadAccountProfile(){
 const response=await fetch('/api/user/profile',{credentials:'same-origin',cache:'no-store'});
 if(!response.ok)return null;
 const payload=await response.json().catch(()=>({}));
 return payload?.profile as Profile|null;
}
function normalizeRequestStatus(status:unknown){return String(status||'').toUpperCase()==='NEW'?'PENDING':String(status||'PENDING').toUpperCase();}

export default function HomePage(){
 const{language,setLanguage,t,isDhivehi}=useFixitLocale();
 const[profile,setProfile]=useState<Profile|null>(null);const[authReady,setAuthReady]=useState(false);const[profileStatus,setProfileStatus]=useState<ProfileStatus|null>(null);const[mode,setMode]=useState<'home'|'request'>('home');const[step,setStep]=useState<Step>(1);
 const[serviceCategories,setServiceCategories]=useState<ServiceCategory[]>([]);const[subcategories,setSubcategories]=useState<ServiceSubcategory[]>([]);const[serviceCode,setServiceCode]=useState('');const[subcategoryCode,setSubcategoryCode]=useState('');
 const[atolls,setAtolls]=useState<Atoll[]>([]);const[islands,setIslands]=useState<Island[]>([]);const[units,setUnits]=useState<LocationUnit[]>([]);const[atollId,setAtollId]=useState('');const[islandId,setIslandId]=useState('');const[unitId,setUnitId]=useState('');
 const[preferredDate,setPreferredDate]=useState('');const[description,setDescription]=useState('');const[notes,setNotes]=useState('');const[urgency,setUrgency]=useState<RequestType>('STANDARD');const[enabledRequestTypes,setEnabledRequestTypes]=useState<RequestType[]>([...REQUEST_TYPES]);const[isOnSiteSameAsCustomer,setIsOnSiteSameAsCustomer]=useState(true);const[onSiteContactName,setOnSiteContactName]=useState('');const[onSiteContactPhone,setOnSiteContactPhone]=useState('');const[photos,setPhotos]=useState<File[]>([]);const[message,setMessage]=useState('');const[submitting,setSubmitting]=useState(false);const[uploading,setUploading]=useState(false);const[draftSaved,setDraftSaved]=useState(false);const[lastRequest,setLastRequest]=useState<LastRequest|null>(null);
 const{resolving,resolved,error:locationError,resolveCurrentLocation}=useAutoLocation();
 const islandOptions=useMemo(()=>islands.filter(i=>i.atoll_id===atollId),[islands,atollId]);const unitOptions=useMemo(()=>units.filter(u=>u.island_id===islandId),[units,islandId]);const selectedCategory=useMemo(()=>serviceCategories.find(s=>s.code===serviceCode)||null,[serviceCategories,serviceCode]);const categorySubs=useMemo(()=>{const cat=serviceCategories.find(c=>c.code===serviceCode);return cat?subcategories.filter(s=>s.category_id===cat.id):[];},[serviceCategories,subcategories,serviceCode]);const selectedSub=useMemo(()=>subcategories.find(s=>s.code===subcategoryCode)||null,[subcategories,subcategoryCode]);const selectedIsland=useMemo(()=>islands.find(i=>i.id===islandId)||null,[islands,islandId]);const selectedUnit=useMemo(()=>units.find(u=>u.id===unitId)||null,[units,unitId]);const photoUrls=useMemo(()=>photos.map(file=>URL.createObjectURL(file)),[photos]);
 useEffect(()=>()=>{photoUrls.forEach(url=>URL.revokeObjectURL(url));},[photoUrls]);
 useEffect(()=>{try{const raw=localStorage.getItem('fixit:create-draft');if(raw){const d=JSON.parse(raw) as Draft;setServiceCode(d.serviceCode||'');setSubcategoryCode(d.subcategoryCode||'');setAtollId(d.atollId||'');setIslandId(d.islandId||'');setUnitId(d.unitId||'');setPreferredDate(d.preferredDate||'');setDescription(d.description||'');setNotes(d.notes||'');setUrgency((REQUEST_TYPES.includes(d.urgency as RequestType)?d.urgency:'STANDARD') as RequestType);setIsOnSiteSameAsCustomer(d.isOnSiteSameAsCustomer!==false);setOnSiteContactName(d.onSiteContactName||'');setOnSiteContactPhone(d.onSiteContactPhone||'');setDraftSaved(true);}const lr=localStorage.getItem('fixit:last-request');if(lr){const r=JSON.parse(lr);setLastRequest({id:r.id||r.ticket_number,service:r.service||r.service_name,location:r.location||r.service_location_text,status:normalizeRequestStatus(r.status),createdAt:r.createdAt||r.created_at});}}catch{}
  supabase.auth.getSession().then(async({data})=>{if(data.session){const p=await loadAccountProfile();setProfile(p);await Promise.all([loadCatalogue(data.session.access_token),loadRequestTypeSettings()]);if(p?.role==='CUSTOMER')await loadProfileStatus(data.session.access_token);}setAuthReady(true);});
  const{data:sub}=supabase.auth.onAuthStateChange(async(_event,session)=>{if(session){const p=await loadAccountProfile();setProfile(p);await Promise.all([loadCatalogue(session.access_token),loadRequestTypeSettings()]);if(p?.role==='CUSTOMER')await loadProfileStatus(session.access_token);}else{setProfile(null);setProfileStatus(null);}});return()=>sub.subscription.unsubscribe();},[]);
 async function token(){const{data}=await supabase.auth.getSession();return data.session?.access_token||'';}
 async function loadRequestTypeSettings(){const{data,error}=await supabase.from('request_form_fields').select('is_enabled,options').eq('field_key','urgency').maybeSingle();if(error)return;const configured=Array.isArray(data?.options)?data.options.map(value=>String(value).toUpperCase()).filter((value):value is RequestType=>REQUEST_TYPES.includes(value as RequestType)):[];const enabled=data?.is_enabled===false?[]:(configured.length?configured:[...REQUEST_TYPES]);setEnabledRequestTypes(enabled);setUrgency(current=>enabled.includes(current)?current:(enabled.includes('STANDARD')?'STANDARD':enabled[0]||'STANDARD'));}
 async function loadCatalogue(jwt:string){try{const r=await fetch(LOCATION_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${jwt}`},body:'{}'});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to load catalogue');setAtolls(p.atolls||[]);setIslands(p.islands||[]);setUnits(p.locationUnits||[]);setServiceCategories(p.serviceCategories||[]);setSubcategories(p.serviceSubcategories||[]);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load services.');}}
 async function loadProfileStatus(jwt:string){try{const r=await fetch(PROFILE_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${jwt}`},body:JSON.stringify({action:'status'})});const p=await r.json();if(r.ok)setProfileStatus(p);}catch{}}
 async function detectLocation(){const hit=await resolveCurrentLocation();if(hit){setAtollId(hit.atoll.id);setIslandId(hit.island.id);setUnitId(hit.locationUnit?.id||'');setMessage(`Location set to ${hit.island.display_name}${hit.locationUnit?` · ${hit.locationUnit.display_name}`:''}.`);}}
 async function signOut(){await supabase.auth.signOut();window.location.href='/login';}
 function openRequest(category?:ServiceCategory){if(category){setServiceCode(category.code);setSubcategoryCode('');setStep(1);}setMode('request');window.scrollTo({top:0});}
 function validateStep(current:Step){if(!profile)return'Please sign in first.';if(profileStatus&&!profileStatus.can_request)return'Complete the required profile fields first.';if(current>=1&&!serviceCode)return'Choose a service.';if(current>=1&&categorySubs.length&&!subcategoryCode)return'Choose a service type.';if(current>=2&&!islandId)return'Choose the service island or city.';if(current>=3&&description.trim().length<10)return'Tell us a little more about the problem.';if(current>=4&&!enabledRequestTypes.length)return'Request types are currently unavailable.';if(current>=4&&!enabledRequestTypes.includes(urgency))return'Choose an available request type.';if(current>=4&&urgency==='SCHEDULE'&&!preferredDate)return'Choose a preferred date.';if(current>=4&&!isOnSiteSameAsCustomer&&onSiteContactName.trim().length<2)return'Enter the on-site contact name.';if(current>=4&&!isOnSiteSameAsCustomer&&onSiteContactPhone.trim().length<5)return'Enter the on-site contact phone number.';return'';}
 function next(){const error=validateStep(step);if(error){setMessage(error);return;}setMessage('');setStep(Math.min(5,step+1) as Step);window.scrollTo({top:0,behavior:'smooth'});}
 function back(){if(step===1){setMode('home');setMessage('');return;}setStep((step-1) as Step);setMessage('');window.scrollTo({top:0,behavior:'smooth'});}
 function saveDraft(){localStorage.setItem('fixit:create-draft',JSON.stringify({serviceCode,subcategoryCode,atollId,islandId,unitId,preferredDate:urgency==='SCHEDULE'?preferredDate:'',description,notes,urgency,isOnSiteSameAsCustomer,onSiteContactName,onSiteContactPhone} satisfies Draft));setDraftSaved(true);setMessage(language==='dv'?'ޑްރާފްޓް މި ޑިވައިސްގައި ސޭވްވެއްޖެ.':'Draft saved on this device.');}
 function clearDraft(){localStorage.removeItem('fixit:create-draft');setDraftSaved(false);}
 function choosePhotos(list:FileList|null){if(!list)return;const next=[...photos,...Array.from(list)].filter(f=>f.type.startsWith('image/')).slice(0,3);if(next.some(f=>f.size>5*1024*1024)){setMessage('Each photo must be 5 MB or smaller.');return;}setPhotos(next);}
 async function uploadPhotos(ticket:string,jwt:string){if(!photos.length)return;setUploading(true);try{for(const file of photos){const form=new FormData();form.append('ticketNumber',ticket);form.append('file',file);const r=await fetch(MEDIA_URL,{method:'POST',headers:{Authorization:`Bearer ${jwt}`},body:form});const p=await r.json();if(!r.ok)throw new Error(p?.error||`Unable to upload ${file.name}`);}}finally{setUploading(false);}}
 async function submitRequest(){const error=validateStep(5);if(error){setMessage(error);return;}setSubmitting(true);setMessage(t('sending'));try{const jwt=await token();const response=await fetch(SUBMIT_REQUEST_URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${jwt}`},body:JSON.stringify({serviceCategoryCode:serviceCode,serviceSubcategoryCode:subcategoryCode||null,islandId,locationUnitId:unitId||null,preferredDate:urgency==='SCHEDULE'?preferredDate:null,description:description.trim(),customerNotes:notes.trim()||null,urgency,isOnSiteSameAsCustomer,onSiteContactName:isOnSiteSameAsCustomer?null:onSiteContactName.trim(),onSiteContactPhone:isOnSiteSameAsCustomer?null:onSiteContactPhone.trim(),clientRequestId:crypto.randomUUID()})});const payload=await response.json();if(!response.ok||!payload?.request?.ticket_number)throw new Error(payload?.error||'Unable to submit request');let photoWarning='';try{await uploadPhotos(payload.request.ticket_number,jwt);}catch(e){photoWarning=e instanceof Error?` Photos need retry: ${e.message}`:' Photos need retry.';}const request:LastRequest={id:payload.request.ticket_number,service:payload.request.service_name||selectedCategory?.name||'Service',location:payload.request.service_location_text||selectedIsland?.display_name||'Selected location',status:normalizeRequestStatus(payload.request.status),createdAt:payload.request.created_at||new Date().toISOString()};localStorage.setItem('fixit:last-request',JSON.stringify(request));setLastRequest(request);clearDraft();setMessage(`Request sent.${photoWarning}`);window.location.href=`/requests/${encodeURIComponent(request.id)}`;}catch(e){setMessage(e instanceof Error?e.message:'Unable to submit request.');}finally{setSubmitting(false);}}
 if(!authReady)return <div className="c4App" aria-busy="true" aria-label="Loading account"/>;
 const missingNames=profileStatus?.required_fields.filter(f=>!f.is_completed).map(f=>f.display_name)||[];const firstName=(profile?.full_name||'there').split(' ')[0];
 const right=<div className="c4HeaderActions"><div className="c4LangCompact"><button className={language==='en'?'active':''} onClick={()=>setLanguage('en')}>EN</button><button className={language==='dv'?'active':''} onClick={()=>setLanguage('dv')}>ދި</button></div>{profile?<button className="c3Avatar" onClick={()=>window.location.href='/profile'} aria-label={t('profile')}>{(profile.full_name||profile.role).slice(0,2).toUpperCase()}</button>:authReady?<a className="c3IconButton" href="/login" aria-label={t('signIn')}><svg viewBox="0 0 24 24"><path d="M12 12a4 4 0 100-8 4 4 0 000 8zm7 9a7 7 0 00-14 0"/></svg></a>:null}</div>;
 return <div className={`c4App ${isDhivehi?'dv':''}`} dir={isDhivehi?'rtl':'ltr'}><CustomerSidebar language={language} setLanguage={setLanguage} profileName={profile?.full_name} onNewRequest={()=>openRequest()} onSignOut={profile?signOut:undefined}/><main className="c4Main c3Page"><CustomerHeader title={mode==='request'?t('newRequest'):t('home')} backHref={mode==='request'?'/':undefined} right={right}/><div className="c3Shell">
 {mode==='home'?<div className="c3Home">
  <section className="c3Welcome"><div><small>{t('fixitMaldives')}</small><h1>{t('hi')} {firstName}, {t('whatNeedsFixing')}</h1><p>{t('intro')}</p></div><button className="c3Primary" onClick={()=>openRequest()}>{t('createRequest')}</button></section>
  {profileStatus&&missingNames.length?<div className="c3Notice c3Warning"><strong>{profileStatus.completion_required?'Complete your profile to continue':'Profile incomplete'}.</strong> {missingNames.join(', ')}. <a href="/profile">Update profile</a></div>:null}
  <section className="c3Section"><div className="c3SectionHead"><div><small>{t('services')}</small><h2>{t('chooseNeed')}</h2><p>{t('startWithService')}</p></div></div><div className="c3ServiceGrid">{serviceCategories.map(item=><button className="c3ServiceTile" key={item.id} onClick={()=>openRequest(item)}><ServiceIcon name={item.name}/><strong>{item.name}</strong><span>{t('startRequest')}</span></button>)}</div></section>
  {lastRequest?<section className="c3Section"><div className="c3SectionHead"><div><small>{t('latestRequest')}</small><h2>{t('pickUp')}</h2></div><a className="c3Secondary" href="/requests">{t('allRequests')}</a></div><div className="c3ActiveCard"><div><span className={`c3Status ${lastRequest.status==='COMPLETED'?'completed':''}`}>{lastRequest.status.replaceAll('_',' ')}</span><h3>{lastRequest.service}</h3><p>{lastRequest.location} · {lastRequest.id}</p></div><a className="c3Primary" href={`/requests/${encodeURIComponent(lastRequest.id)}`}>{t('open')}</a></div></section>:null}
 </div>:<div className="c3Wizard">
  <div className="c3WizardTop"><div className="c3StepDots">{[1,2,3,4,5].map(n=><span key={n} className={`c3StepDot ${n===step?'active':n<step?'done':''}`}/>)}</div><span className="c3Status">{t('step')} {step} {t('of')} 5</span></div>
  <section className="c3WizardCard">
   {step===1?<><div className="c3Question"><small>{t('service')}</small><h1>{t('whatHelp')}</h1><p>{t('chooseServiceType')}</p></div><div className="c3ServiceGrid" style={{marginTop:20}}>{serviceCategories.map(item=><button className={`c3ServiceTile ${serviceCode===item.code?'selected':''}`} key={item.id} onClick={()=>{setServiceCode(item.code);setSubcategoryCode('');}}><ServiceIcon name={item.name}/><strong>{item.name}</strong><span>{serviceCode===item.code?t('selected'):t('choose')}</span></button>)}</div>{serviceCode&&categorySubs.length?<div className="c3Subchips">{categorySubs.map(item=><button className={`c3Chip ${subcategoryCode===item.code?'selected':''}`} key={item.id} onClick={()=>setSubcategoryCode(item.code)}>{item.name}</button>)}</div>:null}</>:null}
   {step===2?<><div className="c3Question"><small>{t('location')}</small><h1>{t('whereJob')}</h1><p>{t('locationHelp')}</p></div><div className="c3Form"><label className="c3Field">{t('atoll')}<select value={atollId} onChange={e=>{setAtollId(e.target.value);setIslandId('');setUnitId('');}}><option value="">{t('selectAtoll')}</option>{atolls.map(a=><option key={a.id} value={a.id}>{a.code} — {a.display_name}</option>)}</select></label><label className="c3Field">{t('islandCity')}<select value={islandId} disabled={!atollId} onChange={e=>{setIslandId(e.target.value);setUnitId('');}}><option value="">{t('selectIsland')}</option>{islandOptions.map(i=><option key={i.id} value={i.id}>{i.display_name}</option>)}</select></label>{unitOptions.length?<label className="c3Field full">{t('wardArea')} <span style={{fontWeight:500,color:'var(--c3-muted)'}}>{t('optional')}</span><select value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">{t('wholeIsland')}</option>{unitOptions.map(u=><option key={u.id} value={u.id}>{u.display_name}</option>)}</select></label>:null}</div><button className="c3Secondary" style={{marginTop:14}} onClick={()=>void detectLocation()} disabled={!profile||resolving}>{resolving?t('findingLocation'):t('useLocation')}</button>{locationError&&!resolved?<div className="c3Notice">{locationError}</div>:null}</>:null}
   {step===3?<><div className="c3Question"><small>{t('problem')}</small><h1>{t('showWrong')}</h1><p>{t('problemHelp')}</p></div><div className="c3Form"><label className="c3Field full">{t('whatProblem')}<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder={language==='dv'?'މިސާލަކަށް: ކިޗަން ސިންކްއިން ފެން ލީކްވަނީ.':'For example: The kitchen sink is leaking under the cabinet.'}/></label><label className="c3Field full">{t('anythingElse')} <span style={{fontWeight:500,color:'var(--c3-muted)'}}>{t('optional')}</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder={language==='dv'?'ޕްރޮވައިޑަރަށް އެނގެން ޖެހޭ އިތުރު މަޢުލޫމާތު.':'Access notes or anything the provider should know.'}/></label></div><div className="c3PhotoDrop"><label className="c3Secondary">{t('addPhotos')} ({photos.length}/3)<input type="file" accept="image/*" multiple onChange={e=>{choosePhotos(e.target.files);e.currentTarget.value='';}}/></label><div className="c3PhotoGrid">{photos.map((file,index)=><div className="c3Photo" key={`${file.name}:${file.lastModified}`}><img src={photoUrls[index]} alt={`Request photo ${index+1}`}/><button onClick={()=>setPhotos(current=>current.filter((_,i)=>i!==index))}>×</button></div>)}</div></div></>:null}
   {step===4?<><div className="c3Question"><small>{t('schedule')}</small><h1>{t('whenHelp')}</h1><p>{t('scheduleHelp')}</p></div><div className="c3Urgency">{([{key:'URGENT',title:t('urgent'),text:t('asap')},{key:'STANDARD',title:t('standard'),text:t('normalSchedule')},{key:'SCHEDULE',title:t('scheduled'),text:t('usePreferred')}] as const).filter(x=>enabledRequestTypes.includes(x.key)).map(x=><button key={x.key} className={urgency===x.key?'selected':''} onClick={()=>{setUrgency(x.key);if(x.key!=='SCHEDULE')setPreferredDate('');}}><strong>{x.title}</strong><span>{x.text}</span></button>)}</div>{!enabledRequestTypes.length?<div className="c3Notice">No request types are currently enabled.</div>:null}{urgency==='SCHEDULE'?<div className="c3Form"><label className="c3Field full">{t('preferredDate')}<input type="date" value={preferredDate} onChange={e=>setPreferredDate(e.target.value)}/></label></div>:null}<div className="c3Question" style={{marginTop:24}}><small>On-site contact</small><h2>Who will be at the service location?</h2><p>The assigned provider receives these contact details only after you confirm them.</p></div><div className="c3Urgency"><button className={isOnSiteSameAsCustomer?'selected':''} onClick={()=>setIsOnSiteSameAsCustomer(true)}><strong>I will be there</strong><span>Use my profile name and phone</span></button><button className={!isOnSiteSameAsCustomer?'selected':''} onClick={()=>setIsOnSiteSameAsCustomer(false)}><strong>Someone else</strong><span>Add the person the provider should contact</span></button></div>{!isOnSiteSameAsCustomer?<div className="c3Form"><label className="c3Field">On-site contact name<input value={onSiteContactName} onChange={e=>setOnSiteContactName(e.target.value)} placeholder="Full name"/></label><label className="c3Field">On-site contact phone<input type="tel" value={onSiteContactPhone} onChange={e=>setOnSiteContactPhone(e.target.value)} placeholder="+960 7XXXXXX"/></label></div>:<div className="c3Notice">Your profile name and phone will be saved as the on-site contact for this request.</div>}</>:null}
   {step===5?<><div className="c3Question"><small>{t('review')}</small><h1>{t('readySend')}</h1><p>{t('reviewHelp')}</p></div><div className="c3Review"><div className="c3ReviewRow"><span>{t('service')}</span><strong>{selectedCategory?.name}{selectedSub?` · ${selectedSub.name}`:''}</strong></div><div className="c3ReviewRow"><span>{t('location')}</span><strong>{selectedIsland?.display_name}{selectedUnit?` · ${selectedUnit.display_name}`:''}</strong></div><div className="c3ReviewRow"><span>{t('problem')}</span><strong>{description}</strong></div><div className="c3ReviewRow"><span>{t('urgency')}</span><strong>{urgency.toLowerCase()}</strong></div>{urgency==='SCHEDULE'?<div className="c3ReviewRow"><span>{t('preferredDate')}</span><strong>{preferredDate}</strong></div>:null}<div className="c3ReviewRow"><span>On-site contact</span><strong>{isOnSiteSameAsCustomer?'You · profile contact':`${onSiteContactName} · ${onSiteContactPhone}`}</strong></div><div className="c3ReviewRow"><span>{t('photos')}</span><strong>{photos.length} {t('attached')}</strong></div></div>{uploading?<div className="c3Notice">{t('uploading')}</div>:null}</>:null}
   {message?<div className="c3Notice">{message}</div>:null}
  </section>
  <div className="c3ActionDock"><div className="c3ActionInner"><button className="c3Secondary" onClick={back}>{step===1?t('cancel'):t('back')}</button>{step<5?<button className="c3Primary" onClick={next}>{t('continue')}</button>:<button className="c3Primary" onClick={()=>void submitRequest()} disabled={submitting||uploading}>{submitting?t('sending'):t('sendRequest')}</button>}</div></div>
 </div>}
 </div></main></div>;
}