'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabaseClient';
import { useAutoLocation } from '../lib/useAutoLocation';
import './create-request.css';

const SUBMIT_REQUEST_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/submit-request';
const MEDIA_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/request-media';
const LOCATION_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/location-catalogue';
const PROFILE_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/profile-requirements';
type Profile={role:'CUSTOMER'|'PROVIDER'|'ADMIN';full_name?:string|null;provider_approved?:boolean};
type Atoll={id:string;code:string;display_name:string;sort_order:number};
type Island={id:string;atoll_id:string;display_name:string;location_kind:string;sort_order:number};
type LocationUnit={id:string;atoll_id:string;island_id:string;parent_id?:string|null;unit_type:string;display_name:string;reference_code?:string|null;sort_order:number};
type ServiceCategory={id:string;code:string;name:string;sort_order:number};
type ServiceSubcategory={id:string;category_id:string;code:string;name:string;description?:string|null;sort_order:number};
type ProfileStatus={profile_completeness:number;missing_required_field_keys:string[];required_fields:{field_key:string;display_name:string;is_completed:boolean}[];can_request:boolean;completion_required:boolean};
type LastRequest={id:string;service:string;location:string;status:string;createdAt:string};
type Draft={serviceCode:string;subcategoryCode:string;atollId:string;islandId:string;unitId:string;preferredDate:string;description:string;notes:string;urgency:string};

export default function HomePage(){
 const[profile,setProfile]=useState<Profile|null>(null);const[authReady,setAuthReady]=useState(false);const[profileStatus,setProfileStatus]=useState<ProfileStatus|null>(null);
 const[serviceCategories,setServiceCategories]=useState<ServiceCategory[]>([]);const[subcategories,setSubcategories]=useState<ServiceSubcategory[]>([]);const[serviceCode,setServiceCode]=useState('');const[subcategoryCode,setSubcategoryCode]=useState('');
 const[atolls,setAtolls]=useState<Atoll[]>([]);const[islands,setIslands]=useState<Island[]>([]);const[units,setUnits]=useState<LocationUnit[]>([]);const[atollId,setAtollId]=useState('');const[islandId,setIslandId]=useState('');const[unitId,setUnitId]=useState('');
 const[preferredDate,setPreferredDate]=useState('');const[description,setDescription]=useState('');const[notes,setNotes]=useState('');const[urgency,setUrgency]=useState<'URGENT'|'STANDARD'|'SCHEDULE'>('STANDARD');const[photos,setPhotos]=useState<File[]>([]);const[step,setStep]=useState<1|2>(1);const[message,setMessage]=useState('');const[submitting,setSubmitting]=useState(false);const[uploading,setUploading]=useState(false);const[draftSaved,setDraftSaved]=useState(false);const[lastRequest,setLastRequest]=useState<LastRequest|null>(null);const[autoTried,setAutoTried]=useState(false);
 const{resolving,resolved,error:locationError,resolveCurrentLocation}=useAutoLocation();
 const islandOptions=useMemo(()=>islands.filter(i=>i.atoll_id===atollId),[islands,atollId]);const unitOptions=useMemo(()=>units.filter(u=>u.island_id===islandId),[units,islandId]);const selectedCategory=useMemo(()=>serviceCategories.find(s=>s.code===serviceCode)||null,[serviceCategories,serviceCode]);const categorySubs=useMemo(()=>{const cat=serviceCategories.find(c=>c.code===serviceCode);return cat?subcategories.filter(s=>s.category_id===cat.id):[];},[serviceCategories,subcategories,serviceCode]);const selectedSub=useMemo(()=>subcategories.find(s=>s.code===subcategoryCode)||null,[subcategories,subcategoryCode]);const selectedIsland=useMemo(()=>islands.find(i=>i.id===islandId)||null,[islands,islandId]);const selectedUnit=useMemo(()=>units.find(u=>u.id===unitId)||null,[units,unitId]);const photoUrls=useMemo(()=>photos.map(file=>URL.createObjectURL(file)),[photos]);
 useEffect(()=>()=>{photoUrls.forEach(url=>URL.revokeObjectURL(url));},[photoUrls]);
 useEffect(()=>{try{const raw=localStorage.getItem('fixit:create-draft');if(raw){const d=JSON.parse(raw) as Draft;setServiceCode(d.serviceCode||'');setSubcategoryCode(d.subcategoryCode||'');setAtollId(d.atollId||'');setIslandId(d.islandId||'');setUnitId(d.unitId||'');setPreferredDate(d.preferredDate||'');setDescription(d.description||'');setNotes(d.notes||'');setUrgency((d.urgency as 'URGENT'|'STANDARD'|'SCHEDULE')||'STANDARD');setDraftSaved(true);}const lr=localStorage.getItem('fixit:last-request');if(lr){const r=JSON.parse(lr);setLastRequest({id:r.id||r.ticket_number,service:r.service||r.service_name,location:r.location||r.service_location_text,status:r.status||'NEW',createdAt:r.createdAt||r.created_at});}}catch{}
  supabase.auth.getSession().then(async({data})=>{if(data.session){const{data:p}=await supabase.from('auth_profiles').select('role,full_name,provider_approved').eq('user_id',data.session.user.id).maybeSingle();setProfile(p as Profile|null);await loadCatalogue(data.session.access_token);if(p?.role==='CUSTOMER')await loadProfileStatus(data.session.access_token);}setAuthReady(true);});
  const{data:sub}=supabase.auth.onAuthStateChange(async(_event,session)=>{if(session){const{data:p}=await supabase.from('auth_profiles').select('role,full_name,provider_approved').eq('user_id',session.user.id).maybeSingle();setProfile(p as Profile|null);await loadCatalogue(session.access_token);if(p?.role==='CUSTOMER')await loadProfileStatus(session.access_token);}else{setProfile(null);setProfileStatus(null);}});return()=>sub.subscription.unsubscribe();},[]);
 useEffect(()=>{if(!profile||!islands.length||autoTried||islandId)return;setAutoTried(true);void resolveCurrentLocation().then(hit=>{if(hit){setAtollId(hit.atoll.id);setIslandId(hit.island.id);setUnitId(hit.locationUnit?.id||'');setMessage(`Location detected: ${hit.island.display_name}${hit.locationUnit?` — ${hit.locationUnit.display_name}`:''}.`);}});},[profile,islands.length,autoTried,islandId,resolveCurrentLocation]);
 async function token(){const{data}=await supabase.auth.getSession();return data.session?.access_token||'';}
 async function loadCatalogue(jwt:string){try{const r=await fetch(LOCATION_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${jwt}`},body:'{}'});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to load catalogue');setAtolls(p.atolls||[]);setIslands(p.islands||[]);setUnits(p.locationUnits||[]);setServiceCategories(p.serviceCategories||[]);setSubcategories(p.serviceSubcategories||[]);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load service catalogue.');}}
 async function loadProfileStatus(jwt:string){try{const r=await fetch(PROFILE_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${jwt}`},body:JSON.stringify({action:'status'})});const p=await r.json();if(r.ok)setProfileStatus(p);}catch{}}
 async function detectLocation(){const hit=await resolveCurrentLocation();if(hit){setAtollId(hit.atoll.id);setIslandId(hit.island.id);setUnitId(hit.locationUnit?.id||'');setMessage(`Location detected: ${hit.island.display_name}${hit.locationUnit?` — ${hit.locationUnit.display_name}`:''}.`);}}
 async function signOut(){await supabase.auth.signOut();window.location.href='/login';}
 function validate(){if(!profile)return'Please sign in before submitting a request.';if(profile.role!=='CUSTOMER')return'Use a Customer account to create a service request.';if(profileStatus&&!profileStatus.can_request)return'Complete the required profile fields before creating a request.';if(!serviceCode)return'Select a service category.';if(categorySubs.length&&!subcategoryCode)return'Select a service type.';if(!islandId)return'Select the service island or city.';if(!preferredDate)return'Choose a preferred date.';if(description.trim().length<10)return'Describe the issue in at least 10 characters.';return'';}
 function continueToReview(event:FormEvent){event.preventDefault();const error=validate();if(error){setMessage(error);return;}setMessage('Review your request before submitting.');setStep(2);window.scrollTo({top:0,behavior:'smooth'});}
 function saveDraft(){const draft:Draft={serviceCode,subcategoryCode,atollId,islandId,unitId,preferredDate,description,notes,urgency};localStorage.setItem('fixit:create-draft',JSON.stringify(draft));setDraftSaved(true);setMessage('Draft saved on this device. Photos must be reselected if you leave this page.');}
 function clearDraft(){localStorage.removeItem('fixit:create-draft');setDraftSaved(false);}
 function choosePhotos(list:FileList|null){if(!list)return;const next=[...photos,...Array.from(list)].filter(f=>f.type.startsWith('image/')).slice(0,3);const tooLarge=next.find(f=>f.size>5*1024*1024);if(tooLarge){setMessage('Each photo must be 5 MB or smaller.');return;}setPhotos(next);}
 async function uploadPhotos(ticket:string,jwt:string){if(!photos.length)return;setUploading(true);try{for(const file of photos){const form=new FormData();form.append('ticketNumber',ticket);form.append('file',file);const r=await fetch(MEDIA_URL,{method:'POST',headers:{'Authorization':`Bearer ${jwt}`},body:form});const p=await r.json();if(!r.ok)throw new Error(p?.error||`Unable to upload ${file.name}`);}}finally{setUploading(false);}}
 async function submitRequest(){const error=validate();if(error){setMessage(error);setStep(1);return;}setSubmitting(true);setMessage('Creating your request…');try{const jwt=await token();const response=await fetch(SUBMIT_REQUEST_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${jwt}`},body:JSON.stringify({serviceCategoryCode:serviceCode,serviceSubcategoryCode:subcategoryCode||null,islandId,locationUnitId:unitId||null,preferredDate,description:description.trim(),customerNotes:notes.trim()||null,urgency,clientRequestId:crypto.randomUUID()})});const payload=await response.json();if(!response.ok||!payload?.request?.ticket_number)throw new Error(payload?.error||'Unable to submit request');let photoWarning='';try{await uploadPhotos(payload.request.ticket_number,jwt);}catch(e){photoWarning=e instanceof Error?` Request created, but photos need retry: ${e.message}`:' Request created, but photos need retry.';}const request:LastRequest={id:payload.request.ticket_number,service:payload.request.service_name||selectedCategory?.name||'Service',location:payload.request.service_location_text||selectedIsland?.display_name||'Selected location',status:payload.request.status||'NEW',createdAt:payload.request.created_at||new Date().toISOString()};localStorage.setItem('fixit:last-request',JSON.stringify({...request,preferredDate,description:description.trim(),trackingToken:payload.trackingToken}));setLastRequest(request);clearDraft();setPhotos([]);setServiceCode('');setSubcategoryCode('');setPreferredDate('');setDescription('');setNotes('');setUrgency('STANDARD');setStep(1);setMessage(`Request ${request.id} submitted successfully.${photoWarning}`);window.location.href=`/requests/${encodeURIComponent(request.id)}`;}catch(e){setMessage(e instanceof Error?e.message:'Unable to submit request.');}finally{setSubmitting(false);}}
 const missingNames=profileStatus?.required_fields.filter(f=>!f.is_completed).map(f=>f.display_name)||[];
 return <main className="shell createRequestApp">
  <header className="topbar"><div><a className="brand" href="/">iFixIt</a><p className="tagline">Service Marketplace</p></div><div className="actions">{profile?<><span className="pill">{profile.full_name||profile.role}</span><button className="secondary" onClick={signOut}>Sign Out</button></>:authReady?<a className="primary" href="/login">Sign In</a>:null}</div></header>
  <section className="createHero"><div className="createHeroCard"><p className="eyebrow">NEW SERVICE REQUEST</p><h1>What do you need fixed?</h1><p>Choose the service, location, urgency and preferred time. Add up to three photos so providers can understand the job before responding.</p><div className="actions"><a className="secondary" href="/requests">My Requests</a>{draftSaved?<span className="draftBadge">Draft saved on this device</span>:null}</div></div><aside className="createHeroCard createStepCard"><div className={`createStep ${step===1?'active':'done'}`}><span>1</span><div>Request details</div></div><div className={`createStep ${step===2?'active':''}`}><span>2</span><div>Review & submit</div></div><div className="createStep"><span>3</span><div>Providers respond</div></div></aside></section>
  {profileStatus&&missingNames.length?<div className="profileWarning"><div><strong>{profileStatus.completion_required?'Profile completion required':'Complete your profile when convenient'}</strong><p>Missing: {missingNames.join(', ')} · Profile {profileStatus.profile_completeness}% complete.</p></div><a className="secondary" href="/profile">Update Profile</a></div>:null}
  {step===1?<form onSubmit={continueToReview} className="createCard"><div className="createSectionHeader"><div><p className="eyebrow">1 · SERVICE</p><h2>Choose a service</h2></div><span className="pill">Live catalogue</span></div><div className="categoryGrid">{serviceCategories.map(item=><button key={item.id} type="button" className={serviceCode===item.code?'categoryButton selected':'categoryButton'} onClick={()=>{setServiceCode(item.code);setSubcategoryCode('');}}><strong>{item.name}</strong><small>Tap to select</small></button>)}{!serviceCategories.length?<div className="emptyQueue">No active services are currently available.</div>:null}</div>{serviceCode&&categorySubs.length?<><div className="createSectionHeader" style={{marginTop:18}}><div><p className="eyebrow">SERVICE TYPE</p><h2>What type of work?</h2></div></div><div className="subcategoryRow">{categorySubs.map(item=><button key={item.id} type="button" className={subcategoryCode===item.code?'subcategoryChip selected':'subcategoryChip'} onClick={()=>setSubcategoryCode(item.code)}>{item.name}</button>)}</div></>:null}
   <div className="createSectionHeader" style={{marginTop:22}}><div><p className="eyebrow">2 · LOCATION & TIME</p><h2>Where and when?</h2></div><button type="button" className="secondary" onClick={()=>void detectLocation()} disabled={!profile||resolving}>{resolving?'Detecting…':'Use Current Location'}</button></div><div className="requestFormGrid"><label className="requestField">Atoll<select value={atollId} onChange={e=>{setAtollId(e.target.value);setIslandId('');setUnitId('');}}><option value="">Select atoll</option>{atolls.map(a=><option key={a.id} value={a.id}>{a.code} — {a.display_name}</option>)}</select></label><label className="requestField">Island / City<select value={islandId} disabled={!atollId} onChange={e=>{setIslandId(e.target.value);setUnitId('');}}><option value="">Select island or city</option>{islandOptions.map(i=><option key={i.id} value={i.id}>{i.display_name}</option>)}</select></label>{unitOptions.length?<label className="requestField">Ward / Area <span className="muted">optional</span><select value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">Whole island / city</option>{unitOptions.map(u=><option key={u.id} value={u.id}>{u.display_name}</option>)}</select></label>:null}<label className="requestField">Preferred date<input type="date" value={preferredDate} onChange={e=>setPreferredDate(e.target.value)}/></label></div>
   <div className="createSectionHeader" style={{marginTop:22}}><div><p className="eyebrow">3 · URGENCY</p><h2>How soon do you need help?</h2></div></div><div className="urgencyGrid">{([{key:'URGENT',title:'Urgent',text:'As soon as possible'},{key:'STANDARD',title:'Standard',text:'Normal scheduling'},{key:'SCHEDULE',title:'Schedule',text:'Use my preferred date'}] as const).map(x=><button key={x.key} type="button" className={urgency===x.key?'urgencyButton selected':'urgencyButton'} onClick={()=>setUrgency(x.key)}><strong>{x.title}</strong><small>{x.text}</small></button>)}</div>
   <div className="createSectionHeader" style={{marginTop:22}}><div><p className="eyebrow">4 · DETAILS</p><h2>Describe the problem</h2></div></div><div className="requestFormGrid"><label className="requestField full">Problem description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What is broken, where is the problem, and what have you already tried?"/></label><label className="requestField full">Additional notes <span className="muted">optional</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Access instructions, preferred contact details, or anything else the provider should know."/></label></div>
   <div className="createSectionHeader" style={{marginTop:22}}><div><p className="eyebrow">5 · PHOTOS</p><h2>Add 2–3 helpful photos</h2><p className="muted">Photos are optional, private, and visible only within the request workflow.</p></div><span className="pill">{photos.length}/3</span></div><div className="photoPicker"><label className="photoAdd">＋ Add Photos<input type="file" accept="image/*" multiple onChange={e=>{choosePhotos(e.target.files);e.currentTarget.value='';}}/></label><p className="muted">JPG/PNG/HEIC supported by your browser · maximum 5 MB each.</p>{photos.length?<div className="photoPreviewGrid">{photos.map((file,index)=><div className="photoPreview" key={`${file.name}:${file.lastModified}`}><img src={photoUrls[index]} alt={`Request photo ${index+1}`}/><button type="button" className="photoRemove" aria-label="Remove photo" onClick={()=>setPhotos(current=>current.filter((_,i)=>i!==index))}>×</button></div>)}</div>:null}</div>
   <div className="createActions"><button type="button" className="secondary" onClick={saveDraft}>Save Draft</button><div><button type="submit" className="primary" disabled={!profile}>Continue</button></div></div>{message?<p className="formMessage" role="status">{message}</p>:null}{locationError&&!resolved?<p className="localNotice">{locationError}</p>:null}</form>:null}
  {step===2?<section className="reviewCard"><div className="createSectionHeader"><div><p className="eyebrow">REVIEW REQUEST</p><h2>Check everything before submitting</h2></div><button className="secondary" onClick={()=>setStep(1)}>Edit</button></div><div className="reviewGrid"><div className="reviewDatum"><span>Service</span><strong>{selectedCategory?.name||'Not selected'}{selectedSub?` · ${selectedSub.name}`:''}</strong></div><div className="reviewDatum"><span>Urgency</span><strong>{urgency==='SCHEDULE'?'Scheduled':urgency.charAt(0)+urgency.slice(1).toLowerCase()}</strong></div><div className="reviewDatum"><span>Location</span><strong>{selectedIsland?.display_name||'Not selected'}{selectedUnit?` — ${selectedUnit.display_name}`:''}</strong></div><div className="reviewDatum"><span>Preferred date</span><strong>{preferredDate}</strong></div><div className="reviewDatum full"><span>Problem</span><strong>{description}</strong></div>{notes?<div className="reviewDatum full"><span>Notes</span><strong>{notes}</strong></div>:null}<div className="reviewDatum"><span>Photos</span><strong>{photos.length} attached</strong></div><div className="reviewDatum"><span>Payment</span><strong>Paid directly to provider</strong></div></div>{uploading?<div className="uploadProgress" style={{marginTop:14}}>Uploading request photos…</div>:null}<div className="createActions"><button className="secondary" onClick={()=>setStep(1)}>Back</button><div><button className="secondary" onClick={saveDraft}>Save Draft</button><button className="primary" onClick={()=>void submitRequest()} disabled={submitting||uploading}>{submitting?'Submitting…':'Submit Request'}</button></div></div>{message?<p className="formMessage" role="status">{message}</p>:null}</section>:null}
  {lastRequest?<section className="createCard"><div className="latestRequestCard"><div><p className="eyebrow">LATEST REQUEST</p><h3>{lastRequest.id} · {lastRequest.service}</h3><p>{lastRequest.location} · {lastRequest.status}</p></div><a className="primary" href={`/requests/${encodeURIComponent(lastRequest.id)}`}>View Request</a></div></section>:null}
  <footer className="footer"><span>iFixIt Maldives</span><span>Customer service marketplace</span></footer>
 </main>;
}
