'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabaseClient';
import { useAutoLocation } from '../lib/useAutoLocation';
import './create-request.css';

const SUBMIT_REQUEST_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/submit-request';
const MEDIA_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/request-media';
const LOCATION_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/location-catalogue';
const PROFILE_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/profile-requirements';
type Profile={role:'CUSTOMER'|'PROVIDER'|'ADMIN';full_name?:string|null;provider_approved?:boolean};
type Atoll={id:string;code:string;display_name:string;sort_order:number};
type Island={id:string;atoll_id:string;display_name:string;location_kind:string;sort_order:number};
type LocationUnit={id:string;atoll_id:string;island_id:string;parent_id?:string|null;unit_type:string;display_name:string;reference_code?:string|null;sort_order:number};
type ServiceCategory={id:string;code:string;name:string;sort_order:number};
type ServiceSubcategory={id:string;category_id:string;code:string;name:string;description?:string|null;sort_order:number};
type ProfileStatus={profile_completeness:number;missing_required_field_keys:string[];required_fields:{field_key:string;display_name:string;is_completed:boolean}[];can_request:boolean;completion_required:boolean};
type LastRequest={id:string;service:string;location:string;status:string;createdAt:string};
type Draft={serviceCode:string;subcategoryCode:string;atollId:string;islandId:string;unitId:string;preferredDate:string;description:string;notes:string;urgency:string};
type Step=1|2|3|4;

type IconName='wrench'|'bolt'|'drop'|'snow'|'sparkle'|'paint'|'home'|'pin'|'camera'|'check'|'requests'|'user'|'clock';
function Icon({name,size=24}:{name:IconName;size?:number}){const common={width:size,height:size,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.9,strokeLinecap:'round' as const,strokeLinejoin:'round' as const};if(name==='bolt')return <svg {...common}><path d="M13 2 5 14h7l-1 8 8-12h-7l1-8Z"/></svg>;if(name==='drop')return <svg {...common}><path d="M12 2s6 7 6 12a6 6 0 0 1-12 0c0-5 6-12 6-12Z"/><path d="M9 15c.5 1.2 1.4 2 3 2"/></svg>;if(name==='snow')return <svg {...common}><path d="M12 2v20M4.2 6.5l15.6 9M4.2 17.5l15.6-9M8.5 4 12 7.5 15.5 4M8.5 20 12 16.5l3.5 3.5"/></svg>;if(name==='sparkle')return <svg {...common}><path d="m12 3 1.5 4.2L18 9l-4.5 1.8L12 15l-1.5-4.2L6 9l4.5-1.8L12 3Z"/><path d="m19 15 .7 2 2.3.8-2.3.8-.7 2.4-.8-2.4-2.2-.8 2.2-.8.8-2Z"/></svg>;if(name==='paint')return <svg {...common}><path d="M14 3 4 13l7 7L21 10l-7-7Z"/><path d="m5 12 7 7M15 7l2 2M3 20h7"/></svg>;if(name==='home')return <svg {...common}><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10M9 20v-6h6v6"/></svg>;if(name==='pin')return <svg {...common}><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>;if(name==='camera')return <svg {...common}><path d="M4 7h3l1.5-2h7L17 7h3v12H4V7Z"/><circle cx="12" cy="13" r="3.5"/></svg>;if(name==='check')return <svg {...common}><path d="m5 12 4 4L19 6"/></svg>;if(name==='requests')return <svg {...common}><path d="M6 3h12v18H6z"/><path d="M9 8h6M9 12h6M9 16h4"/></svg>;if(name==='user')return <svg {...common}><circle cx="12" cy="8" r="4"/><path d="M4 21c1-5 4-7 8-7s7 2 8 7"/></svg>;if(name==='clock')return <svg {...common}><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>;return <svg {...common}><path d="m14.7 6.3 3-3a4 4 0 0 1-5.1 5.1L5.4 15.6a2 2 0 1 0 3 3l7.2-7.2a4 4 0 0 1 5.1-5.1l-3 3"/></svg>}
function categoryIcon(name:string):IconName{const n=name.toLowerCase();if(n.includes('electric'))return'bolt';if(n.includes('plumb')||n.includes('water'))return'drop';if(n.includes('air')||n.includes('ac')||n.includes('cool'))return'snow';if(n.includes('clean'))return'sparkle';if(n.includes('paint'))return'paint';if(n.includes('home')||n.includes('carpent')||n.includes('handyman'))return'home';return'wrench';}

export default function HomePage(){
 const[profile,setProfile]=useState<Profile|null>(null);const[authReady,setAuthReady]=useState(false);const[profileStatus,setProfileStatus]=useState<ProfileStatus|null>(null);
 const[serviceCategories,setServiceCategories]=useState<ServiceCategory[]>([]);const[subcategories,setSubcategories]=useState<ServiceSubcategory[]>([]);const[serviceCode,setServiceCode]=useState('');const[subcategoryCode,setSubcategoryCode]=useState('');
 const[atolls,setAtolls]=useState<Atoll[]>([]);const[islands,setIslands]=useState<Island[]>([]);const[units,setUnits]=useState<LocationUnit[]>([]);const[atollId,setAtollId]=useState('');const[islandId,setIslandId]=useState('');const[unitId,setUnitId]=useState('');
 const[preferredDate,setPreferredDate]=useState('');const[description,setDescription]=useState('');const[notes,setNotes]=useState('');const[urgency,setUrgency]=useState<'URGENT'|'STANDARD'|'SCHEDULE'>('STANDARD');const[photos,setPhotos]=useState<File[]>([]);const[step,setStep]=useState<Step>(1);const[message,setMessage]=useState('');const[submitting,setSubmitting]=useState(false);const[uploading,setUploading]=useState(false);const[draftSaved,setDraftSaved]=useState(false);const[lastRequest,setLastRequest]=useState<LastRequest|null>(null);const[autoTried,setAutoTried]=useState(false);
 const{resolving,resolved,error:locationError,resolveCurrentLocation}=useAutoLocation();
 const islandOptions=useMemo(()=>islands.filter(i=>i.atoll_id===atollId),[islands,atollId]);const unitOptions=useMemo(()=>units.filter(u=>u.island_id===islandId),[units,islandId]);const selectedCategory=useMemo(()=>serviceCategories.find(s=>s.code===serviceCode)||null,[serviceCategories,serviceCode]);const categorySubs=useMemo(()=>{const cat=serviceCategories.find(c=>c.code===serviceCode);return cat?subcategories.filter(s=>s.category_id===cat.id):[];},[serviceCategories,subcategories,serviceCode]);const selectedSub=useMemo(()=>subcategories.find(s=>s.code===subcategoryCode)||null,[subcategories,subcategoryCode]);const selectedIsland=useMemo(()=>islands.find(i=>i.id===islandId)||null,[islands,islandId]);const selectedUnit=useMemo(()=>units.find(u=>u.id===unitId)||null,[units,unitId]);const photoUrls=useMemo(()=>photos.map(file=>URL.createObjectURL(file)),[photos]);
 useEffect(()=>()=>photoUrls.forEach(url=>URL.revokeObjectURL(url)),[photoUrls]);
 useEffect(()=>{try{const raw=localStorage.getItem('fixit:create-draft');if(raw){const d=JSON.parse(raw) as Draft;setServiceCode(d.serviceCode||'');setSubcategoryCode(d.subcategoryCode||'');setAtollId(d.atollId||'');setIslandId(d.islandId||'');setUnitId(d.unitId||'');setPreferredDate(d.preferredDate||'');setDescription(d.description||'');setNotes(d.notes||'');setUrgency((d.urgency as 'URGENT'|'STANDARD'|'SCHEDULE')||'STANDARD');setDraftSaved(true);}const lr=localStorage.getItem('fixit:last-request');if(lr){const r=JSON.parse(lr);setLastRequest({id:r.id||r.ticket_number,service:r.service||r.service_name,location:r.location||r.service_location_text,status:r.status||'NEW',createdAt:r.createdAt||r.created_at});}}catch{}
  supabase.auth.getSession().then(async({data})=>{if(data.session){const{data:p}=await supabase.from('auth_profiles').select('role,full_name,provider_approved').eq('user_id',data.session.user.id).maybeSingle();setProfile(p as Profile|null);await loadCatalogue(data.session.access_token);if(p?.role==='CUSTOMER')await loadProfileStatus(data.session.access_token);}setAuthReady(true);});
  const{data:sub}=supabase.auth.onAuthStateChange(async(_event,session)=>{if(session){const{data:p}=await supabase.from('auth_profiles').select('role,full_name,provider_approved').eq('user_id',session.user.id).maybeSingle();setProfile(p as Profile|null);await loadCatalogue(session.access_token);if(p?.role==='CUSTOMER')await loadProfileStatus(session.access_token);}else{setProfile(null);setProfileStatus(null);}});return()=>sub.subscription.unsubscribe();},[]);
 useEffect(()=>{if(!profile||!islands.length||autoTried||islandId)return;setAutoTried(true);void resolveCurrentLocation().then(hit=>{if(hit){setAtollId(hit.atoll.id);setIslandId(hit.island.id);setUnitId(hit.locationUnit?.id||'');setMessage(`Location detected: ${hit.island.display_name}${hit.locationUnit?` — ${hit.locationUnit.display_name}`:''}.`);}});},[profile,islands.length,autoTried,islandId,resolveCurrentLocation]);
 async function token(){const{data}=await supabase.auth.getSession();return data.session?.access_token||'';}
 async function loadCatalogue(jwt:string){try{const r=await fetch(LOCATION_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${jwt}`},body:'{}'});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to load catalogue');setAtolls(p.atolls||[]);setIslands(p.islands||[]);setUnits(p.locationUnits||[]);setServiceCategories(p.serviceCategories||[]);setSubcategories(p.serviceSubcategories||[]);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load service catalogue.');}}
 async function loadProfileStatus(jwt:string){try{const r=await fetch(PROFILE_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${jwt}`},body:JSON.stringify({action:'status'})});const p=await r.json();if(r.ok)setProfileStatus(p);}catch{}}
 async function detectLocation(){const hit=await resolveCurrentLocation();if(hit){setAtollId(hit.atoll.id);setIslandId(hit.island.id);setUnitId(hit.locationUnit?.id||'');setMessage(`Location detected: ${hit.island.display_name}${hit.locationUnit?` — ${hit.locationUnit.display_name}`:''}.`);}}
 async function signOut(){await supabase.auth.signOut();window.location.href='/login';}
 function saveDraft(){const draft:Draft={serviceCode,subcategoryCode,atollId,islandId,unitId,preferredDate,description,notes,urgency};localStorage.setItem('fixit:create-draft',JSON.stringify(draft));setDraftSaved(true);setMessage('Draft saved on this device.');}
 function clearDraft(){localStorage.removeItem('fixit:create-draft');setDraftSaved(false);}
 function choosePhotos(list:FileList|null){if(!list)return;const next=[...photos,...Array.from(list)].filter(f=>f.type.startsWith('image/')).slice(0,3);if(next.some(f=>f.size>5*1024*1024)){setMessage('Each photo must be 5 MB or smaller.');return;}setPhotos(next);}
 function stepError(target:Step){if(!profile)return'Please sign in before creating a request.';if(profile.role!=='CUSTOMER')return'Use a Customer account to create a service request.';if(profileStatus&&!profileStatus.can_request)return'Complete the required profile fields before creating a request.';if(target>=1&&(!serviceCode||(categorySubs.length&&!subcategoryCode)))return categorySubs.length?'Choose a service type.':'Choose a service.';if(target>=2&&(!islandId||!preferredDate))return!islandId?'Choose the service island or city.':'Choose a preferred date.';if(target>=3&&description.trim().length<10)return'Describe the problem in at least 10 characters.';return'';}
 function goNext(){const error=stepError(step);if(error){setMessage(error);return;}setMessage('');setStep(v=>Math.min(4,v+1) as Step);window.scrollTo({top:0,behavior:'smooth'});}
 function goBack(){setMessage('');setStep(v=>Math.max(1,v-1) as Step);window.scrollTo({top:0,behavior:'smooth'});}
 async function uploadPhotos(ticket:string,jwt:string){if(!photos.length)return;setUploading(true);try{for(const file of photos){const form=new FormData();form.append('ticketNumber',ticket);form.append('file',file);const r=await fetch(MEDIA_URL,{method:'POST',headers:{Authorization:`Bearer ${jwt}`},body:form});const p=await r.json();if(!r.ok)throw new Error(p?.error||`Unable to upload ${file.name}`);}}finally{setUploading(false);}}
 async function submitRequest(){const error=stepError(3);if(error){setMessage(error);return;}setSubmitting(true);setMessage('Creating your request…');try{const jwt=await token();const response=await fetch(SUBMIT_REQUEST_URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${jwt}`},body:JSON.stringify({serviceCategoryCode:serviceCode,serviceSubcategoryCode:subcategoryCode||null,islandId,locationUnitId:unitId||null,preferredDate,description:description.trim(),customerNotes:notes.trim()||null,urgency,clientRequestId:crypto.randomUUID()})});const payload=await response.json();if(!response.ok||!payload?.request?.ticket_number)throw new Error(payload?.error||'Unable to submit request');let photoWarning='';try{await uploadPhotos(payload.request.ticket_number,jwt);}catch(e){photoWarning=e instanceof Error?` Photos need retry: ${e.message}`:' Photos need retry.';}const request:LastRequest={id:payload.request.ticket_number,service:payload.request.service_name||selectedCategory?.name||'Service',location:payload.request.service_location_text||selectedIsland?.display_name||'Selected location',status:payload.request.status||'NEW',createdAt:payload.request.created_at||new Date().toISOString()};localStorage.setItem('fixit:last-request',JSON.stringify({...request,preferredDate,description:description.trim(),trackingToken:payload.trackingToken}));setLastRequest(request);clearDraft();setMessage(`Request ${request.id} submitted.${photoWarning}`);window.location.href=`/requests/${encodeURIComponent(request.id)}`;}catch(e){setMessage(e instanceof Error?e.message:'Unable to submit request.');}finally{setSubmitting(false);}}
 const missingNames=profileStatus?.required_fields.filter(f=>!f.is_completed).map(f=>f.display_name)||[];
 const stepMeta=[{n:1,label:'Service'},{n:2,label:'Location'},{n:3,label:'Problem'},{n:4,label:'Review'}] as const;
 return <main className="customerV2App">
  <header className="customerV2Header"><a className="customerV2Logo" href="/">iFix<span>It</span></a><div className="customerV2HeaderActions"><a href="/requests" className="customerV2IconButton" aria-label="My requests"><Icon name="requests" size={21}/></a>{profile?<a href="/profile" className="customerV2Avatar" aria-label="Profile">{(profile.full_name||'U').slice(0,1).toUpperCase()}</a>:authReady?<a className="customerV2SignIn" href="/login">Sign in</a>:null}</div></header>
  <div className="customerV2Shell">
   <section className="customerV2Intro"><div><span className="customerV2Kicker">NEW REQUEST</span><h1>{step===1?'What can we help with?':step===2?'Where do you need help?':step===3?'Show us the problem':'Ready to send?'}</h1><p>{step===1?'Pick the service that best matches the job.':step===2?'Choose the service location and when you prefer the visit.':step===3?'A short description and photos help providers respond faster.':'Review the details before providers receive your request.'}</p></div>{draftSaved?<span className="customerV2Saved">Draft saved</span>:null}</section>
   <nav className="customerV2Steps" aria-label="Request steps">{stepMeta.map(s=><button key={s.n} type="button" disabled={s.n>step} className={`${step===s.n?'active':''} ${step>s.n?'done':''}`} onClick={()=>s.n<step&&setStep(s.n as Step)}><span>{step>s.n?<Icon name="check" size={14}/>:s.n}</span><small>{s.label}</small></button>)}</nav>
   {profileStatus&&missingNames.length?<div className="customerV2ProfileNotice"><div><strong>{profileStatus.completion_required?'Complete your profile first':'Profile reminder'}</strong><span>{missingNames.join(', ')}</span></div><a href="/profile">Update</a></div>:null}
   {message?<div className="customerV2Message" role="status">{message}</div>:null}

   {step===1?<section className="customerV2Panel"><div className="customerV2SectionTitle"><h2>Choose a service</h2><span>{serviceCategories.length} available</span></div><div className="customerV2ServiceGrid">{serviceCategories.map(item=><button key={item.id} type="button" className={serviceCode===item.code?'selected':''} onClick={()=>{setServiceCode(item.code);setSubcategoryCode('');}}><span className="customerV2ServiceIcon"><Icon name={categoryIcon(item.name)} size={27}/></span><strong>{item.name}</strong><small>{serviceCode===item.code?'Selected':'Choose'}</small></button>)}</div>{serviceCode&&categorySubs.length?<div className="customerV2Subsection"><h3>What type of work?</h3><div className="customerV2Chips">{categorySubs.map(item=><button key={item.id} type="button" className={subcategoryCode===item.code?'selected':''} onClick={()=>setSubcategoryCode(item.code)}>{item.name}</button>)}</div></div>:null}</section>:null}

   {step===2?<section className="customerV2Panel"><div className="customerV2SectionTitle"><div><h2>Service location</h2><p>Where should the provider come?</p></div><button className="customerV2Locate" type="button" onClick={()=>void detectLocation()} disabled={!profile||resolving}><Icon name="pin" size={18}/>{resolving?'Locating…':'Use my location'}</button></div><div className="customerV2Fields"><label>Atoll<select value={atollId} onChange={e=>{setAtollId(e.target.value);setIslandId('');setUnitId('');}}><option value="">Select atoll</option>{atolls.map(a=><option key={a.id} value={a.id}>{a.code} — {a.display_name}</option>)}</select></label><label>Island / City<select value={islandId} disabled={!atollId} onChange={e=>{setIslandId(e.target.value);setUnitId('');}}><option value="">Select island or city</option>{islandOptions.map(i=><option key={i.id} value={i.id}>{i.display_name}</option>)}</select></label>{unitOptions.length?<label>Ward / Area <small>Optional</small><select value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">Whole island / city</option>{unitOptions.map(u=><option key={u.id} value={u.id}>{u.display_name}</option>)}</select></label>:null}<label>Preferred date<input type="date" value={preferredDate} onChange={e=>setPreferredDate(e.target.value)}/></label></div><div className="customerV2Subsection"><h3>How soon?</h3><div className="customerV2Urgency">{([{key:'URGENT',title:'Urgent',text:'As soon as possible'},{key:'STANDARD',title:'Standard',text:'Normal scheduling'},{key:'SCHEDULE',title:'Schedule',text:'Use my date'}] as const).map(x=><button key={x.key} type="button" className={urgency===x.key?'selected':''} onClick={()=>setUrgency(x.key)}><Icon name="clock" size={20}/><span><strong>{x.title}</strong><small>{x.text}</small></span></button>)}</div></div>{locationError&&!resolved?<p className="customerV2Hint">{locationError}</p>:null}</section>:null}

   {step===3?<section className="customerV2Panel"><div className="customerV2SectionTitle"><div><h2>What’s happening?</h2><p>Keep it short and clear.</p></div></div><div className="customerV2Fields single"><label>Problem description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Example: The kitchen tap is leaking continuously from the base."/><small>{description.length}/5000</small></label><label>Extra notes <small>Optional</small><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Access instructions or anything else the provider should know."/></label></div><div className="customerV2PhotoBox"><div className="customerV2PhotoHeading"><span className="customerV2PhotoIcon"><Icon name="camera" size={24}/></span><div><h3>Add photos</h3><p>Up to 3 photos · 5 MB each</p></div><span>{photos.length}/3</span></div><label className="customerV2PhotoAdd"><Icon name="camera" size={20}/>Choose photos<input type="file" accept="image/*" multiple onChange={e=>{choosePhotos(e.target.files);e.currentTarget.value='';}}/></label>{photos.length?<div className="customerV2PhotoGrid">{photos.map((file,index)=><div key={`${file.name}:${file.lastModified}`}><img src={photoUrls[index]} alt={`Request photo ${index+1}`}/><button type="button" onClick={()=>setPhotos(current=>current.filter((_,i)=>i!==index))} aria-label="Remove photo">×</button></div>)}</div>:null}</div></section>:null}

   {step===4?<section className="customerV2Panel"><div className="customerV2SectionTitle"><div><h2>Review request</h2><p>Providers will see these details.</p></div></div><div className="customerV2Review"><div><span>Service</span><strong>{selectedCategory?.name}{selectedSub?` · ${selectedSub.name}`:''}</strong></div><div><span>Location</span><strong>{selectedIsland?.display_name}{selectedUnit?` · ${selectedUnit.display_name}`:''}</strong></div><div><span>Preferred date</span><strong>{preferredDate}</strong></div><div><span>Urgency</span><strong>{urgency==='SCHEDULE'?'Scheduled':urgency.charAt(0)+urgency.slice(1).toLowerCase()}</strong></div><div className="wide"><span>Problem</span><strong>{description}</strong></div>{notes?<div className="wide"><span>Notes</span><strong>{notes}</strong></div>:null}<div><span>Photos</span><strong>{photos.length} attached</strong></div><div><span>Payment</span><strong>Direct to provider</strong></div></div>{uploading?<div className="customerV2Message">Uploading photos…</div>:null}</section>:null}

   {lastRequest&&step===1?<a className="customerV2Latest" href={`/requests/${encodeURIComponent(lastRequest.id)}`}><span className="customerV2LatestIcon"><Icon name="requests" size={20}/></span><span><small>Latest request</small><strong>{lastRequest.service}</strong><em>{lastRequest.location}</em></span><b>›</b></a>:null}
  </div>
  <div className="customerV2ActionDock"><div className="customerV2DockInner">{step>1?<button type="button" className="customerV2Back" onClick={goBack}>Back</button>:<button type="button" className="customerV2Back" onClick={saveDraft}>Save draft</button>}<div className="customerV2DockText"><small>Step {step} of 4</small><strong>{stepMeta[step-1].label}</strong></div>{step<4?<button type="button" className="customerV2Continue" onClick={goNext} disabled={!profile}>Continue <span>›</span></button>:<button type="button" className="customerV2Continue" onClick={()=>void submitRequest()} disabled={submitting||uploading}>{submitting?'Submitting…':'Send request'} <span>›</span></button>}</div></div>
 </main>;
}
