'use client';

import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '../../lib/supabaseClient';
import ProfileRequirementsCard from '../ProfileRequirementsCard';

const REQUIREMENTS_API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/profile-requirements';
type Profile={user_id:string;role:'CUSTOMER'|'PROVIDER'|'ADMIN';full_name?:string|null;email?:string|null;provider_approved?:boolean;phone_number?:string|null;is_phone_verified:boolean;profile_photo_url?:string|null;photoUrl?:string|null;created_at?:string};
type RequirementStatus={profile_completeness:number;missing_required_field_keys:string[];can_request:boolean;completion_required:boolean;counts?:{required:number;required_completed:number;optional:number;optional_completed:number}};

export default function ProfilePage(){
 const[profile,setProfile]=useState<Profile|null>(null);const[status,setStatus]=useState<RequirementStatus|null>(null);const[message,setMessage]=useState('Loading profile…');const[busy,setBusy]=useState(false);const[editing,setEditing]=useState(false);const[name,setName]=useState('');const[phone,setPhone]=useState('');const[photo,setPhoto]=useState<File|null>(null);const[clearPhoto,setClearPhoto]=useState(false);
 useEffect(()=>{void load();},[]);
 async function session(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return null;}return data.session;}
 async function load(){setBusy(true);try{const s=await session();if(!s)return;const r=await fetch('/api/user/profile',{headers:{Authorization:`Bearer ${s.access_token}`}});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to load your profile.');setProfile(p.profile);setName(p.profile.full_name||'');setPhone(p.profile.phone_number||'');setPhoto(null);setClearPhoto(false);try{const rr=await fetch(REQUIREMENTS_API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.access_token}`},body:JSON.stringify({action:'status'})});if(rr.ok)setStatus(await rr.json() as RequirementStatus);}catch{}setMessage('Profile is up to date.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load your profile.');}finally{setBusy(false);}}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const s=await session();if(!s)return;const form=new FormData();form.set('fullName',name.trim());if(phone.trim())form.set('phoneNumber',phone.trim());if(photo)form.set('photo',photo);if(clearPhoto)form.set('clearPhoto','true');const r=await fetch('/api/user/profile',{method:'PUT',headers:{Authorization:`Bearer ${s.access_token}`},body:form});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to update profile.');setEditing(false);await load();setMessage(phone.trim()!==profile?.phone_number?'Profile updated. A changed phone number remains unverified until separately verified.':'Profile updated.');}catch(err){setMessage(err instanceof Error?err.message:'Unable to update profile.');}finally{setBusy(false);}}
 async function signOut(){await supabase.auth.signOut();window.location.href='/login';}
 const completeness=Math.max(0,Math.min(100,status?.profile_completeness??0));const initial=(profile?.full_name||profile?.email||'U').slice(0,1).toUpperCase();const missing=status?.missing_required_field_keys?.length||0;const isProvider=profile?.role==='PROVIDER';
 return <main className="shell accountApp">
  <header className="accountHeader"><div className="accountTitle"><a className="accountBack" href="/">‹</a><div><h1>Profile</h1><p>{isProvider?'Provider account and marketplace settings':'Account, preferences and request readiness'}</p></div></div><button className="accountIconButton" type="button" onClick={()=>void load()} disabled={busy} aria-label="Refresh profile">↻</button></header>
  <section className="profileHeroCard"><div className="profileIdentity">{profile?.photoUrl&&!clearPhoto?<img className="profileAvatar" src={profile.photoUrl} alt="Profile"/>:<div className="profileAvatar">{initial}</div>}<div className="profileIdentityCopy"><h2>{profile?.full_name||'Your FixIt profile'}</h2><p>{profile?.email||'Email not provided'}</p><div className="profileBadges">{profile?<span className="profileBadge">{profile.role}</span>:null}{profile?.phone_number?<span className={profile.is_phone_verified?'profileBadge verified':'profileBadge warning'}>{profile.is_phone_verified?'✓ Phone Verified':'Phone Unverified'}</span>:null}{isProvider?<span className={profile?.provider_approved?'profileBadge verified':'profileBadge warning'}>{profile?.provider_approved?'✓ Verified Provider':'Approval Pending'}</span>:null}</div></div></div><button className="secondary profileEditButton" type="button" onClick={()=>setEditing(v=>!v)}>{editing?'Close':'Edit Profile'}</button></section>
  {editing?<section className="profileSection"><div className="profileSectionHeader"><div><h3>Edit profile</h3><p className="sectionLead">Photo and phone are optional after registration. Changing the verified registration phone marks the new number unverified.</p></div></div><form className="authForm" onSubmit={save}><label>Full name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Phone number<input type="tel" inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+9607XXXXXX"/></label><label>Profile photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{setPhoto(e.target.files?.[0]||null);setClearPhoto(false);}}/></label>{profile?.profile_photo_url?<button className="secondary" type="button" onClick={()=>{setPhoto(null);setClearPhoto(true);}}>Remove Current Photo</button>:null}<button className="primary" disabled={busy}>{busy?'Saving…':'Save Profile'}</button></form></section>:null}
  {profile?.role!=='ADMIN'&&status?.completion_required?<section className="profileAlert"><span className="profileAlertIcon">!</span><div><strong>Complete your required profile fields</strong><p>{missing} required field{missing===1?' is':'s are'} still missing.</p></div><a href="#profile-fields" className="primary">Complete Now</a></section>:null}
  {profile?.role!=='ADMIN'?<section className="profileSection"><div className="completionBarWrap"><div className="completionTop"><div><h3>Profile completion</h3><p className="sectionLead">Required and optional account readiness.</p></div><strong>{completeness}%</strong></div><div className="completionTrack"><div className="completionFill" style={{width:`${completeness}%`}}/></div><div className="profileMetricGrid"><div><span>Required</span><strong>{status?.counts?`${status.counts.required_completed}/${status.counts.required}`:'—'}</strong></div><div><span>Missing</span><strong>{missing}</strong></div><div><span>Marketplace</span><strong>{status?.can_request===false?'Action required':'Ready'}</strong></div></div></div></section>:null}
  <section className="profileSection"><div className="profileSectionHeader"><div><h3>Account details</h3><p className="sectionLead">Your core FixIt identity and verification status.</p></div></div><div className="profileDetailList"><div className="profileDetailRow"><span>Name</span><strong>{profile?.full_name||'Not provided'}</strong></div><div className="profileDetailRow"><span>Email</span><strong>{profile?.email||'Not provided'}</strong></div><div className="profileDetailRow"><span>Phone</span><strong>{profile?.phone_number||'Not provided'}</strong></div><div className="profileDetailRow"><span>Phone verification</span><strong className={profile?.is_phone_verified?'positiveText':'warningText'}>{profile?.phone_number?(profile.is_phone_verified?'Verified':'Not verified'):'Not applicable'}</strong></div><div className="profileDetailRow"><span>Account type</span><strong>{profile?.role||'Loading…'}</strong></div>{profile?.created_at?<div className="profileDetailRow"><span>Member since</span><strong>{new Date(profile.created_at).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</strong></div>:null}</div></section>
  {profile?.role!=='ADMIN'?<div id="profile-fields"><ProfileRequirementsCard/></div>:null}
  <section className="profileSection"><div className="profileSectionHeader"><div><h3>Quick access</h3></div></div><div className="profileQuickGrid">{isProvider?<><a className="profileQuickCard" href="/provider/onboarding"><span className="profileQuickIcon">⚙</span><span><strong>Provider Setup</strong><small>Services, areas and availability</small></span></a><a className="profileQuickCard" href="/provider"><span className="profileQuickIcon">▣</span><span><strong>Provider Dashboard</strong><small>Requests and active work</small></span></a><a className="profileQuickCard" href="/provider/completion-photos"><span className="profileQuickIcon">▧</span><span><strong>Completion Photos</strong><small>Before and after work photos</small></span></a><a className="profileQuickCard" href="/messages"><span className="profileQuickIcon">✉</span><span><strong>Messages</strong><small>Customer conversations</small></span></a></>:<><a className="profileQuickCard" href="/requests"><span className="profileQuickIcon">▣</span><span><strong>My Requests</strong><small>Active and completed requests</small></span></a><a className="profileQuickCard" href="/messages"><span className="profileQuickIcon">✉</span><span><strong>Messages</strong><small>Provider conversations</small></span></a></>}</div></section>
  <button className="profileSignOut" type="button" onClick={signOut}>Sign Out</button><p className="muted accountStatusText" role="status">{busy?'Working…':message}</p>
 </main>;
}
