'use client';

import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '../../lib/supabaseClient';
import ProfileRequirementsCard from '../ProfileRequirementsCard';

const REQUIREMENTS_API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/profile-requirements';
type Address={line1:string;line2:string;city:string;stateRegion:string;postalCode:string;country:string};
type ServiceAddress={id?:string;label:string;address_line1:string;address_line2?:string|null;city?:string|null;state_region?:string|null;postal_code?:string|null;country?:string|null;access_instructions?:string|null;service_atoll_id?:string|null;service_island_id?:string|null;service_location_unit_id?:string|null;is_default:boolean};
type Profile={user_id:string;role:'CUSTOMER'|'PROVIDER'|'ADMIN';full_name?:string|null;email?:string|null;provider_approved?:boolean;phone_number?:string|null;is_phone_verified:boolean;profile_photo_url?:string|null;photoUrl?:string|null;primaryAddress?:Partial<Address>;providerAddress?:Partial<Address>;serviceAddresses?:ServiceAddress[];created_at?:string};
type RequirementStatus={profile_completeness:number;missing_required_field_keys:string[];can_request:boolean;completion_required:boolean;counts?:{required:number;required_completed:number;optional:number;optional_completed:number}};
const emptyAddress=():Address=>({line1:'',line2:'',city:'',stateRegion:'',postalCode:'',country:''});
function normalizedAddress(v?:Partial<Address>|null):Address{return{line1:v?.line1||'',line2:v?.line2||'',city:v?.city||'',stateRegion:v?.stateRegion||'',postalCode:v?.postalCode||'',country:v?.country||''};}
function addressText(a?:Partial<Address>|null){return[a?.line1,a?.line2,a?.city,a?.stateRegion,a?.postalCode,a?.country].filter(Boolean).join(', ')||'Not provided';}

export default function ProfilePage(){
 const[profile,setProfile]=useState<Profile|null>(null);const[status,setStatus]=useState<RequirementStatus|null>(null);const[message,setMessage]=useState('Loading profile…');const[busy,setBusy]=useState(false);const[editing,setEditing]=useState(false);const[name,setName]=useState('');const[phone,setPhone]=useState('');const[photo,setPhoto]=useState<File|null>(null);const[clearPhoto,setClearPhoto]=useState(false);const[primary,setPrimary]=useState<Address>(emptyAddress());const[providerAddress,setProviderAddress]=useState<Address>(emptyAddress());const[serviceAddresses,setServiceAddresses]=useState<ServiceAddress[]>([]);
 useEffect(()=>{void load();},[]);
 async function session(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return null;}return data.session;}
 async function load(){setBusy(true);try{const s=await session();if(!s)return;const r=await fetch('/api/user/profile',{headers:{Authorization:`Bearer ${s.access_token}`}});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to load your profile.');const next=p.profile as Profile;setProfile(next);setName(next.full_name||'');setPhone(next.phone_number||'');setPrimary(normalizedAddress(next.primaryAddress));setProviderAddress(normalizedAddress(next.providerAddress));setServiceAddresses((next.serviceAddresses||[]).map(a=>({...a,is_default:Boolean(a.is_default)})));setPhoto(null);setClearPhoto(false);try{const rr=await fetch(REQUIREMENTS_API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.access_token}`},body:JSON.stringify({action:'status'})});if(rr.ok)setStatus(await rr.json() as RequirementStatus);}catch{}setMessage('Profile is up to date.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load your profile.');}finally{setBusy(false);}}
 function setPrimaryField<K extends keyof Address>(key:K,value:Address[K]){setPrimary(v=>({...v,[key]:value}));}
 function setProviderField<K extends keyof Address>(key:K,value:Address[K]){setProviderAddress(v=>({...v,[key]:value}));}
 function updateService(index:number,patch:Partial<ServiceAddress>){setServiceAddresses(list=>list.map((a,i)=>i===index?{...a,...patch}:a));}
 function setDefaultService(index:number){setServiceAddresses(list=>list.map((a,i)=>({...a,is_default:i===index})));}
 function addServiceAddress(){setServiceAddresses(list=>list.length>=10?list:[...list,{label:'',address_line1:'',address_line2:'',city:'',state_region:'',postal_code:'',country:'',access_instructions:'',is_default:false}]);}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const s=await session();if(!s)return;const form=new FormData();form.set('fullName',name.trim());if(phone.trim())form.set('phoneNumber',phone.trim());if(photo)form.set('photo',photo);if(clearPhoto)form.set('clearPhoto','true');form.set('primaryAddress',JSON.stringify(primary));if(profile?.role==='PROVIDER')form.set('providerAddress',JSON.stringify(providerAddress));const saved=serviceAddresses.filter(a=>a.id||a.label.trim()||a.address_line1.trim()).map(a=>({id:a.id,label:a.label,line1:a.address_line1,line2:a.address_line2||'',city:a.city||'',stateRegion:a.state_region||'',postalCode:a.postal_code||'',country:a.country||'',accessInstructions:a.access_instructions||'',serviceAtollId:a.service_atoll_id||null,serviceIslandId:a.service_island_id||null,serviceLocationUnitId:a.service_location_unit_id||null,isDefault:a.is_default}));form.set('serviceAddresses',JSON.stringify(saved));const r=await fetch('/api/user/profile',{method:'PUT',headers:{Authorization:`Bearer ${s.access_token}`},body:form});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to update profile.');setEditing(false);const phoneChanged=phone.trim()!==profile?.phone_number;await load();setMessage(phoneChanged?'Profile updated. The changed phone number is unverified until separately verified.':'Profile and addresses updated.');}catch(err){setMessage(err instanceof Error?err.message:'Unable to update profile.');}finally{setBusy(false);}}
 async function signOut(){await supabase.auth.signOut();window.location.href='/login';}
 const completeness=Math.max(0,Math.min(100,status?.profile_completeness??0));const initial=(profile?.full_name||profile?.email||'U').slice(0,1).toUpperCase();const missing=status?.missing_required_field_keys?.length||0;const isProvider=profile?.role==='PROVIDER';const isAdmin=profile?.role==='ADMIN';const defaultAddress=profile?.serviceAddresses?.find(a=>a.is_default);
 return <main className="shell accountApp">
  <header className="accountHeader"><div className="accountTitle"><a className="accountBack" href={isAdmin?'/admin':'/'}>‹</a><div><h1>Profile</h1><p>{isProvider?'Provider identity, addresses and marketplace settings':isAdmin?'Administrative oversight and account settings':'Account, addresses and request readiness'}</p></div></div><button className="accountIconButton" type="button" onClick={()=>void load()} disabled={busy} aria-label="Refresh profile">↻</button></header>
  <section className="profileHeroCard"><div className="profileIdentity">{profile?.photoUrl&&!clearPhoto?<img className="profileAvatar" src={profile.photoUrl} alt="Profile"/>:<div className="profileAvatar">{initial}</div>}<div className="profileIdentityCopy"><h2>{profile?.full_name||'Your FixIt profile'}</h2><p>{profile?.email||'Email not provided'}</p><div className="profileBadges">{profile?<span className="profileBadge">{profile.role}</span>:null}{profile?.phone_number?<span className={profile.is_phone_verified?'profileBadge verified':'profileBadge warning'}>{profile.is_phone_verified?'✓ Phone Verified':'Phone Unverified'}</span>:null}{isProvider?<span className={profile?.provider_approved?'profileBadge verified':'profileBadge warning'}>{profile?.provider_approved?'✓ Verified Provider':'Approval Pending'}</span>:null}</div></div></div><button className="secondary profileEditButton" type="button" onClick={()=>setEditing(v=>!v)}>{editing?'Close':'Edit Profile'}</button></section>

  {editing?<section className="profileSection"><div className="profileSectionHeader"><div><h3>Edit profile & addresses</h3><p className="sectionLead">Only WhatsApp OTP is mandatory at registration. Photo and address information remain optional and can be updated later.</p></div></div><form className="authForm" onSubmit={save}>
   <label>Full name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Phone number<input type="tel" inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+9607XXXXXX"/></label><label>Profile photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{setPhoto(e.target.files?.[0]||null);setClearPhoto(false);}}/></label>{profile?.profile_photo_url?<button className="secondary" type="button" onClick={()=>{setPhoto(null);setClearPhoto(true);}}>Remove Current Photo</button>:null}
   <fieldset className="panel" style={{padding:14}}><legend><strong>Primary address</strong></legend><label>Address line 1<input value={primary.line1} onChange={e=>setPrimaryField('line1',e.target.value)} maxLength={255}/></label><label>Address line 2<input value={primary.line2} onChange={e=>setPrimaryField('line2',e.target.value)} maxLength={255}/></label><div className="scheduleGrid"><label>City / Island<input value={primary.city} onChange={e=>setPrimaryField('city',e.target.value)} maxLength={120}/></label><label>State / Atoll / Region<input value={primary.stateRegion} onChange={e=>setPrimaryField('stateRegion',e.target.value)} maxLength={120}/></label><label>Postal code<input value={primary.postalCode} onChange={e=>setPrimaryField('postalCode',e.target.value)} maxLength={40}/></label><label>Country<input value={primary.country} onChange={e=>setPrimaryField('country',e.target.value)} maxLength={120}/></label></div></fieldset>
   {isProvider?<fieldset className="panel" style={{padding:14}}><legend><strong>Provider business / physical address</strong></legend><label>Address line 1<input value={providerAddress.line1} onChange={e=>setProviderField('line1',e.target.value)} maxLength={255}/></label><label>Address line 2<input value={providerAddress.line2} onChange={e=>setProviderField('line2',e.target.value)} maxLength={255}/></label><div className="scheduleGrid"><label>City / Island<input value={providerAddress.city} onChange={e=>setProviderField('city',e.target.value)} maxLength={120}/></label><label>State / Atoll / Region<input value={providerAddress.stateRegion} onChange={e=>setProviderField('stateRegion',e.target.value)} maxLength={120}/></label><label>Postal code<input value={providerAddress.postalCode} onChange={e=>setProviderField('postalCode',e.target.value)} maxLength={40}/></label><label>Country<input value={providerAddress.country} onChange={e=>setProviderField('country',e.target.value)} maxLength={120}/></label></div></fieldset>:null}
   <fieldset className="panel" style={{padding:14}}><legend><strong>Saved service addresses</strong></legend><p className="muted">Save up to 10 job locations. Mark one as default for future quick dispatching.</p>{serviceAddresses.map((a,i)=><div key={a.id||`new-${i}`} className="profileSection" style={{padding:12,margin:'10px 0'}}><div className="profileSectionHeader"><strong>Address {i+1}</strong><div className="actions"><button className="secondary" type="button" onClick={()=>setDefaultService(i)}>{a.is_default?'Default':'Make Default'}</button><button className="secondary" type="button" onClick={()=>setServiceAddresses(list=>list.filter((_,n)=>n!==i))}>Remove</button></div></div><label>Label<input value={a.label} onChange={e=>updateService(i,{label:e.target.value})} placeholder="Home, Office, Shop" maxLength={80}/></label><label>Address line 1<input value={a.address_line1} onChange={e=>updateService(i,{address_line1:e.target.value})} maxLength={255}/></label><label>Address line 2<input value={a.address_line2||''} onChange={e=>updateService(i,{address_line2:e.target.value})} maxLength={255}/></label><div className="scheduleGrid"><label>City / Island<input value={a.city||''} onChange={e=>updateService(i,{city:e.target.value})}/></label><label>State / Atoll / Region<input value={a.state_region||''} onChange={e=>updateService(i,{state_region:e.target.value})}/></label><label>Postal code<input value={a.postal_code||''} onChange={e=>updateService(i,{postal_code:e.target.value})}/></label><label>Country<input value={a.country||''} onChange={e=>updateService(i,{country:e.target.value})}/></label></div><label>Access / dispatch instructions<textarea rows={2} value={a.access_instructions||''} onChange={e=>updateService(i,{access_instructions:e.target.value})} maxLength={1000}/></label></div>)}<button className="secondary" type="button" onClick={addServiceAddress} disabled={serviceAddresses.length>=10}>+ Add Service Address</button></fieldset>
   <button className="primary" disabled={busy}>{busy?'Saving…':'Save Profile & Addresses'}</button>
  </form></section>:null}

  {profile?.role!=='ADMIN'&&status?.completion_required?<section className="profileAlert"><span className="profileAlertIcon">!</span><div><strong>Complete your required profile fields</strong><p>{missing} required field{missing===1?' is':'s are'} still missing.</p></div><a href="#profile-fields" className="primary">Complete Now</a></section>:null}
  {profile?.role!=='ADMIN'?<section className="profileSection"><div className="completionBarWrap"><div className="completionTop"><div><h3>Profile completion</h3><p className="sectionLead">Required and optional account readiness.</p></div><strong>{completeness}%</strong></div><div className="completionTrack"><div className="completionFill" style={{width:`${completeness}%`}}/></div><div className="profileMetricGrid"><div><span>Required</span><strong>{status?.counts?`${status.counts.required_completed}/${status.counts.required}`:'—'}</strong></div><div><span>Missing</span><strong>{missing}</strong></div><div><span>Marketplace</span><strong>{status?.can_request===false?'Action required':'Ready'}</strong></div></div></div></section>:null}

  <section className="profileSection"><div className="profileSectionHeader"><div><h3>Account details</h3><p className="sectionLead">Your core FixIt identity and verification status.</p></div></div><div className="profileDetailList"><div className="profileDetailRow"><span>Name</span><strong>{profile?.full_name||'Not provided'}</strong></div><div className="profileDetailRow"><span>Email</span><strong>{profile?.email||'Not provided'}</strong></div><div className="profileDetailRow"><span>Phone</span><strong>{profile?.phone_number||'Not provided'}</strong></div><div className="profileDetailRow"><span>Phone verification</span><strong className={profile?.is_phone_verified?'positiveText':'warningText'}>{profile?.phone_number?(profile.is_phone_verified?'Verified':'Not verified'):'Not applicable'}</strong></div><div className="profileDetailRow"><span>Primary address</span><strong>{addressText(profile?.primaryAddress)}</strong></div>{isProvider?<div className="profileDetailRow"><span>Provider address</span><strong>{addressText(profile?.providerAddress)}</strong></div>:null}<div className="profileDetailRow"><span>Default service address</span><strong>{defaultAddress?[defaultAddress.label,defaultAddress.address_line1,defaultAddress.city].filter(Boolean).join(' · '):'Not set'}</strong></div><div className="profileDetailRow"><span>Saved service addresses</span><strong>{profile?.serviceAddresses?.length||0}</strong></div><div className="profileDetailRow"><span>Account type</span><strong>{profile?.role||'Loading…'}</strong></div>{profile?.created_at?<div className="profileDetailRow"><span>Member since</span><strong>{new Date(profile.created_at).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</strong></div>:null}</div></section>
  {profile?.role!=='ADMIN'?<div id="profile-fields"><ProfileRequirementsCard/></div>:null}
  <button className="profileSignOut" type="button" onClick={signOut}>Sign Out</button><p className="muted accountStatusText" role="status">{busy?'Working…':message}</p>
 </main>;
}