'use client';

import { useEffect, useMemo, useState } from 'react';
import AppModeSwitch from '../../AppModeSwitch';
import { supabase } from '../../../lib/supabaseClient';
import { useProviderMode } from '../useProviderMode';

const MARKET_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-marketplace';
const INSIGHTS_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-insights';
const OFFERS_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-offers';

type Job={ticket_number:string;service_name:string;service_location_text:string;preferred_date:string;status:string;created_at:string;customer?:{name?:string|null}|null;inspection?:{scheduled_start?:string|null;status?:string|null}|null};
type Review={id:string;overall_rating?:number|null;quality_rating?:number|null;time_rating?:number|null;cost_rating?:number|null;review_text?:string|null;created_at:string;ticketNumber?:string|null;serviceName?:string|null};
type Insights={stats:{earnings:number;completionRate:number;avgResponseMinutes:number|null;newOfferCount:number;totalJobs:number;completedJobs:number};summary:{review_count:number;average_rating:number|null};reviews:Review[]};
type Offer={id:string;rank_score:number;offered_at:string;response_deadline_at:string;request:{ticket_number:string;service_name:string;service_location_text:string;preferred_date:string;problem_description:string;urgency?:string|null;dispatch_tier?:string|null}|null};

function deadlineLabel(value:string){const d=new Date(value);if(Number.isNaN(d.getTime()))return 'Response deadline pending';const mins=Math.max(0,Math.ceil((d.getTime()-Date.now())/60000));return mins>60?`${Math.floor(mins/60)}h ${mins%60}m left`:`${mins}m left`;}

export default function ProviderTodayPage(){
 const mode=useProviderMode(true);const[jobs,setJobs]=useState<Job[]>([]);const[offers,setOffers]=useState<Offer[]>([]);const[insights,setInsights]=useState<Insights|null>(null);const[busy,setBusy]=useState(true);const[message,setMessage]=useState('Loading today…');
 useEffect(()=>{if(mode.ready)void load();},[mode.ready]);
 async function session(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return null;}return data.session;}
 async function load(){setBusy(true);try{const s=await session();if(!s)return;const headers={'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`};const[mr,ir,or]=await Promise.all([fetch(MARKET_URL,{method:'POST',headers,body:JSON.stringify({action:'dashboard'})}),fetch(INSIGHTS_URL,{method:'POST',headers,body:'{}'}),fetch(OFFERS_URL,{method:'POST',headers,body:JSON.stringify({action:'list'})})]);const mp=await mr.json();const ip=await ir.json();const op=await or.json();if(!mr.ok)throw new Error(mp?.error||'Unable to load provider dashboard');if(!or.ok)throw new Error(op?.error||'Unable to load customer requests');setJobs(mp.requests||[]);setOffers(op.offers||[]);if(ir.ok)setInsights(ip);setMessage('Provider dashboard is up to date.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load provider dashboard.');}finally{setBusy(false);}}
 async function respond(offerId:string,action:'accept'|'decline'){setBusy(true);try{const s=await session();if(!s)return;const r=await fetch(OFFERS_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`},body:JSON.stringify({action,offerId})});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to respond to customer request');setMessage(action==='accept'?'Customer request accepted. The customer and full job details are now available.':'Request declined. FixIt will offer it to the next matched provider.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to respond to customer request.');setBusy(false);}}
 const active=useMemo(()=>jobs.filter(j=>['ACCEPTED','INSPECTION_SCHEDULED','IN_PROGRESS'].includes(j.status)),[jobs]);const upcoming=useMemo(()=>jobs.filter(j=>Boolean(j.inspection?.scheduled_start)&&j.status!=='COMPLETED').sort((a,b)=>new Date(a.inspection?.scheduled_start||0).getTime()-new Date(b.inspection?.scheduled_start||0).getTime()),[jobs]);const followUps=useMemo(()=>jobs.filter(j=>j.status==='ACCEPTED'&&!j.inspection?.scheduled_start),[jobs]);
 if(mode.loading)return <main className="providerModePage"><div className="providerModeShell"><div className="providerModeCard">Checking provider setup…</div></div></main>;
 const stats=insights?.stats;const reviews=insights?.reviews||[];
 return <main className="providerModePage"><div className="providerModeShell">
  <header className="providerModeTop"><div><span className="modeBadge provider"><span className="modeDot provider"/>Provider</span><h1>Today</h1><p>Welcome back, {mode.name}. Customer requests matched to you appear here first.</p></div><AppModeSwitch mode="provider" compact/></header>

  <section className="providerModeCard providerRequestsCard"><div className="providerSectionHead"><div><h2>Customer Requests</h2><p>Only requests currently matched to you are shown. Customer private details unlock after you accept.</p></div><a className="secondary" href="/provider/jobs">View all</a></div>{offers.length?<div className="providerOfferGrid">{offers.map(o=><article className="providerOfferCard" key={o.id}><div className="providerOfferTop"><span className="modeBadge provider">{o.request?.urgency||o.request?.dispatch_tier||'STANDARD'}</span><strong>{o.request?.service_name||'Service request'}</strong></div><p><b>Location:</b> {o.request?.service_location_text||'Service location'}</p><p><b>Preferred date:</b> {o.request?.preferred_date?new Date(o.request.preferred_date+'T00:00:00').toLocaleDateString():'Not specified'}</p><p className="providerOfferProblem"><b>Customer request:</b> {o.request?.problem_description||'No problem description supplied.'}</p><div className="providerOfferReasons"><span>Matched service</span><span>Matched area</span><span>Score {Number(o.rank_score||0).toFixed(0)}</span></div><div className="providerOfferDeadline"><strong>{deadlineLabel(o.response_deadline_at)}</strong> · respond by {new Date(o.response_deadline_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div><div className="providerSetupActions"><button className="secondary" disabled={busy} onClick={()=>void respond(o.id,'decline')}>Decline</button><button className="primary" disabled={busy} onClick={()=>void respond(o.id,'accept')}>Accept Request</button></div></article>)}</div>:<div className="providerEmptyState"><h3>No customer requests for you right now</h3><p>When FixIt matches a customer's service, location and availability to you, the request will appear here with a response deadline.</p><a className="secondary" href="/provider/listings">Check services & availability</a></div>}</section>

  <section className="providerModeStats"><div className="providerStat"><span>Customer requests</span><strong>{offers.length}</strong></div><div className="providerStat"><span>Active jobs</span><strong>{active.length}</strong></div><div className="providerStat"><span>Earnings</span><strong>MVR {Number(stats?.earnings||0).toFixed(0)}</strong></div><div className="providerStat"><span>Response time</span><strong>{stats?.avgResponseMinutes==null?'—':`${stats.avgResponseMinutes}m`}</strong></div></section>

  <section className="providerModeCard"><div className="providerSectionHead"><div><h2>Accepted Customer Jobs</h2><p>After you accept a customer request, their job and customer details appear here.</p></div><a className="secondary" href="/provider/jobs">All customer work</a></div>{active.length?<div className="providerList">{active.slice(0,6).map(j=><a className="providerListItem providerListLink" href={`/provider/jobs?ticket=${encodeURIComponent(j.ticket_number)}`} key={j.ticket_number}><div><h3>{j.service_name}</h3><p>{j.customer?.name||'Customer'} · {j.service_location_text} · {j.ticket_number}</p></div><span className="modeBadge provider">{j.status.replaceAll('_',' ')}</span></a>)}</div>:<div className="providerEmptyState"><h3>No accepted customer jobs</h3><p>Accepted customer requests will move here automatically.</p></div>}</section>

  <section className="providerModeCard"><div className="providerSectionHead"><div><h2>Upcoming bookings</h2><p>Your next scheduled customer visits.</p></div><a className="secondary" href="/provider/calendar">Calendar</a></div>{upcoming.length?<div className="providerList">{upcoming.slice(0,5).map(j=><a className="providerListItem providerListLink" href={`/provider/jobs?ticket=${encodeURIComponent(j.ticket_number)}`} key={j.ticket_number}><div><h3>{j.service_name}</h3><p>{new Date(j.inspection?.scheduled_start||'').toLocaleString()} · {j.service_location_text}</p></div><strong>›</strong></a>)}</div>:<div className="providerEmptyState"><h3>No upcoming bookings</h3><p>Your scheduled customer work will appear here automatically.</p></div>}</section>

  <section className="providerModeCard"><div className="providerSectionHead"><div><h2>Follow-ups</h2><p>Accepted customer work that still needs scheduling or a next action.</p></div></div>{followUps.length?<div className="providerList">{followUps.slice(0,5).map(j=><div className="providerListItem" key={j.ticket_number}><div><h3>{j.service_name}</h3><p>{j.ticket_number} · schedule the next step</p></div><a className="primary" href={`/provider/jobs?ticket=${encodeURIComponent(j.ticket_number)}`}>Open</a></div>)}</div>:<div className="providerEmptyState"><h3>You’re caught up</h3><p>No provider follow-ups need attention right now.</p></div>}</section>

  <section className="providerModeCard"><div className="providerSectionHead"><div><h2>Recent reviews</h2><p>{insights?.summary?.average_rating?`★ ${Number(insights.summary.average_rating).toFixed(1)} · ${insights.summary.review_count} review${insights.summary.review_count===1?'':'s'}`:'Customer ratings appear here after completed jobs.'}</p></div><a className="secondary" href="/provider/menu">Provider menu</a></div>{reviews.length?<div className="providerReviewGrid">{reviews.map(r=><article key={r.id}><div className="providerStars">{'★'.repeat(Math.max(0,Math.round(Number(r.overall_rating||0))))}{'☆'.repeat(Math.max(0,5-Math.round(Number(r.overall_rating||0))))}</div><strong>{r.serviceName||'Service'}</strong><p>{r.review_text||`Quality ${r.quality_rating||'—'} · Time ${r.time_rating||'—'} · Cost ${r.cost_rating||'—'}`}</p><small>{new Date(r.created_at).toLocaleDateString()}</small></article>)}</div>:<div className="providerEmptyState"><h3>No reviews yet</h3><p>Reviews appear automatically after a customer rates a completed job.</p></div>}</section>
  <p className="muted" role="status">{busy?'Refreshing…':message}</p>
 </div></main>;
}
