'use client';

import { useEffect, useMemo, useState } from 'react';
import AppModeSwitch from '../../AppModeSwitch';
import { supabase } from '../../../lib/supabaseClient';
import { useProviderMode } from '../useProviderMode';

const MARKET_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-marketplace';
type Job={ticket_number:string;service_name:string;service_location_text:string;preferred_date:string;status:string;created_at:string;customer?:{name?:string|null}|null;inspection?:{scheduled_start?:string|null;status?:string|null}|null;completion?:{final_amount?:number|string|null;currency?:string|null}|null};

export default function ProviderTodayPage(){
 const mode=useProviderMode(true);const[jobs,setJobs]=useState<Job[]>([]);const[busy,setBusy]=useState(true);const[message,setMessage]=useState('Loading today…');
 useEffect(()=>{if(mode.ready)void load();},[mode.ready]);
 async function load(){setBusy(true);try{const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return;}const r=await fetch(MARKET_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${data.session.access_token}`},body:JSON.stringify({action:'dashboard'})});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to load provider dashboard');setJobs(p.requests||[]);setMessage('Provider dashboard is up to date.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load provider dashboard.');}finally{setBusy(false);}}
 const active=useMemo(()=>jobs.filter(j=>['ACCEPTED','INSPECTION_SCHEDULED','IN_PROGRESS'].includes(j.status)),[jobs]);const upcoming=useMemo(()=>jobs.filter(j=>Boolean(j.inspection?.scheduled_start)&&j.status!=='COMPLETED').sort((a,b)=>new Date(a.inspection?.scheduled_start||0).getTime()-new Date(b.inspection?.scheduled_start||0).getTime()),[jobs]);const completed=useMemo(()=>jobs.filter(j=>j.status==='COMPLETED'),[jobs]);const earnings=completed.reduce((sum,j)=>sum+Number(j.completion?.final_amount||0),0);const completionRate=jobs.length?Math.round((completed.length/jobs.length)*100):100;const followUps=jobs.filter(j=>j.status==='ACCEPTED'&&!j.inspection?.scheduled_start);
 if(mode.loading)return <main className="providerModePage"><div className="providerModeShell"><div className="providerModeCard">Checking provider setup…</div></div></main>;
 return <main className="providerModePage"><div className="providerModeShell">
  <header className="providerModeTop"><div><span className="modeBadge provider"><span className="modeDot provider"/>Provider</span><h1>Today</h1><p>Welcome back, {mode.name}. Here’s what needs your attention.</p></div><AppModeSwitch mode="provider" compact/></header>
  <section className="providerModeStats"><div className="providerStat"><span>Active jobs</span><strong>{active.length}</strong></div><div className="providerStat"><span>Upcoming</span><strong>{upcoming.length}</strong></div><div className="providerStat"><span>Earnings preview</span><strong>MVR {earnings.toFixed(0)}</strong></div><div className="providerStat"><span>Completion rate</span><strong>{completionRate}%</strong></div></section>
  <section className="providerModeCard"><div className="providerSectionHead"><div><h2>Active reservations</h2><p>Ongoing jobs and customer details.</p></div><a className="secondary" href="/provider">Job operations</a></div>{active.length?<div className="providerList">{active.slice(0,6).map(j=><div className="providerListItem" key={j.ticket_number}><div><h3>{j.service_name}</h3><p>{j.customer?.name||'Customer'} · {j.service_location_text} · {j.ticket_number}</p></div><span className="modeBadge provider">{j.status.replaceAll('_',' ')}</span></div>)}</div>:<div className="providerEmptyState"><h3>No active jobs</h3><p>New accepted jobs will appear here.</p><a className="primary" href="/provider">Check job offers</a></div>}</section>
  <section className="providerModeCard"><div className="providerSectionHead"><div><h2>Upcoming bookings</h2><p>Your next scheduled visits.</p></div><a className="secondary" href="/provider/calendar">Calendar</a></div>{upcoming.length?<div className="providerList">{upcoming.slice(0,5).map(j=><div className="providerListItem" key={j.ticket_number}><div><h3>{j.service_name}</h3><p>{new Date(j.inspection?.scheduled_start||'').toLocaleString()} · {j.service_location_text}</p></div><strong>›</strong></div>)}</div>:<div className="providerEmptyState"><h3>No upcoming bookings</h3><p>Your scheduled work will appear here automatically.</p></div>}</section>
  <section className="providerModeCard"><div className="providerSectionHead"><div><h2>Follow-ups</h2><p>Accepted work that still needs scheduling or a next action.</p></div></div>{followUps.length?<div className="providerList">{followUps.slice(0,5).map(j=><div className="providerListItem" key={j.ticket_number}><div><h3>{j.service_name}</h3><p>{j.ticket_number} · schedule the next step</p></div><a className="primary" href="/provider">Open</a></div>)}</div>:<div className="providerEmptyState"><h3>You’re caught up</h3><p>No provider follow-ups need attention right now.</p></div>}</section>
  <section className="providerModeCard"><div className="providerSectionHead"><div><h2>Reviews</h2><p>Customer star ratings appear after completed jobs.</p></div><a className="secondary" href="/provider/menu">Provider menu</a></div><div className="providerEmptyState"><h3>Recent reviews</h3><p>Quality, Time and Cost ratings are already stored by FixIt; a dedicated provider review feed can be added here without changing the rating model.</p></div></section>
  <p className="muted" role="status">{busy?'Refreshing…':message}</p>
 </div></main>;
}
