'use client';

import { useEffect, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import AdminNav from '../AdminNav';

const API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/admin-marketplace';
type Summary={totalRequests:number;last30Days:number;completionRate:number;unassignedNew:number;approvedProviders:number;activeProviders:number;coveredIslands:number;totalIslands:number};
type ServiceRow={code:string;name:string;total:number;completed:number};
type PlaceRow={id:string;name:string;code?:string;total:number};
type StatusCounts={NEW:number;ACCEPTED:number;PROCESSING:number;COMPLETED:number};

export default function AdminReportsPage(){
 const[summary,setSummary]=useState<Summary|null>(null);const[statusCounts,setStatusCounts]=useState<StatusCounts>({NEW:0,ACCEPTED:0,PROCESSING:0,COMPLETED:0});const[byService,setByService]=useState<ServiceRow[]>([]);const[byAtoll,setByAtoll]=useState<PlaceRow[]>([]);const[byIsland,setByIsland]=useState<PlaceRow[]>([]);const[message,setMessage]=useState('Loading reports…');const[busy,setBusy]=useState(false);
 useEffect(()=>{void load();},[]);
 async function token(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return '';}return data.session.access_token;}
 async function load(){setBusy(true);try{const t=await token();if(!t)return;const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify({action:'reports'})});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to load reports');setSummary(p.summary);setStatusCounts(p.statusCounts||{});setByService(p.byService||[]);setByAtoll(p.byAtoll||[]);setByIsland(p.byIsland||[]);setMessage('Reporting dashboard is up to date.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load reports.');}finally{setBusy(false);}}
 const coverage=summary?.totalIslands?Math.round((summary.coveredIslands/summary.totalIslands)*1000)/10:0;
 return <main className="shell"><header className="topbar"><div><a className="brand" href="/admin">FixIt</a><p className="tagline">Admin • Reporting</p></div><button className="secondary" onClick={()=>void load()} disabled={busy}>{busy?'Loading…':'Refresh'}</button></header><AdminNav />
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">OPERATIONS REPORT</p><h2>Marketplace performance</h2></div><span className="pill">Live data</span></div><p className="formMessage" role="status">{message}</p>{summary?<div className="adminStats"><div className="statCard"><span>Total requests</span><strong>{summary.totalRequests}</strong></div><div className="statCard"><span>Last 30 days</span><strong>{summary.last30Days}</strong></div><div className="statCard"><span>Completion rate</span><strong>{summary.completionRate}%</strong></div><div className="statCard"><span>Unassigned new</span><strong>{summary.unassignedNew}</strong></div><div className="statCard"><span>Active providers</span><strong>{summary.activeProviders}</strong></div></div>:null}</section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">REQUEST PIPELINE</p><h2>Current lifecycle</h2></div></div><div className="adminStats"><div className="statCard"><span>New</span><strong>{statusCounts.NEW||0}</strong></div><div className="statCard"><span>Accepted</span><strong>{statusCounts.ACCEPTED||0}</strong></div><div className="statCard"><span>Processing</span><strong>{statusCounts.PROCESSING||0}</strong></div><div className="statCard"><span>Completed</span><strong>{statusCounts.COMPLETED||0}</strong></div></div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">PROVIDER COVERAGE</p><h2>Service footprint</h2></div><span className="pill">{coverage}% island coverage</span></div>{summary?<div className="adminStats"><div className="statCard"><span>Approved providers</span><strong>{summary.approvedProviders}</strong></div><div className="statCard"><span>Active providers</span><strong>{summary.activeProviders}</strong></div><div className="statCard"><span>Covered islands</span><strong>{summary.coveredIslands}</strong></div><div className="statCard"><span>Total locations</span><strong>{summary.totalIslands}</strong></div></div>:null}</section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">SERVICE DEMAND</p><h2>Requests by service</h2></div></div><div className="userTableWrap"><table className="userTable"><thead><tr><th>Service</th><th>Requests</th><th>Completed</th><th>Completion</th></tr></thead><tbody>{byService.map(s=><tr key={s.code}><td><strong>{s.name}</strong><small>{s.code}</small></td><td>{s.total}</td><td>{s.completed}</td><td>{s.total?Math.round(s.completed*1000/s.total)/10:0}%</td></tr>)}</tbody></table></div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">GEOGRAPHIC DEMAND</p><h2>Requests by atoll</h2></div></div><div className="userTableWrap"><table className="userTable"><thead><tr><th>Atoll</th><th>Requests</th></tr></thead><tbody>{byAtoll.map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{a.code||''}</small></td><td>{a.total}</td></tr>)}</tbody></table></div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">TOP ISLANDS / CITIES</p><h2>Highest request volumes</h2></div></div><div className="userTableWrap"><table className="userTable"><thead><tr><th>Island / City</th><th>Requests</th></tr></thead><tbody>{byIsland.map(i=><tr key={i.id}><td><strong>{i.name}</strong></td><td>{i.total}</td></tr>)}</tbody></table></div></section>
 </main>;
}
