'use client';

import { useEffect, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import AdminNav from '../AdminNav';

const API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/admin-marketplace';
const PROVIDER_REPORT_API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/admin-provider-reports';
type Summary={totalRequests:number;last30Days:number;completionRate:number;unassignedNew:number;approvedProviders:number;activeProviders:number;coveredIslands:number;totalIslands:number};
type ServiceRow={code:string;name:string;total:number;completed:number};
type PlaceRow={id:string;name:string;code?:string;total:number};
type StatusCounts={NEW:number;ACCEPTED:number;PROCESSING:number;COMPLETED:number};
type RequestListRow={id:string;ticket_number:string;service_name:string;service_location_text:string;preferred_date:string;status:string;assigned_provider_user_id?:string|null;created_at:string;customer?:{full_name?:string|null;email?:string|null}|null};
type NoProviderRow={id:string;ticket:string;service:string;location:string;preferredDate:string;createdAt:string;customer:string;reason:string};
type ProviderTimeRow={providerUserId:string;providerName:string;reviewCount:number;overallRating:number|null;qualityRating:number|null;timeRating:number|null;costRating:number|null;providerRank:number|null};
type ProviderTimeSummary={ratedProviders:number;averageTimeRating:number;excellentTimeProviders:number;needsAttention:number};

export default function AdminReportsPage(){
 const[summary,setSummary]=useState<Summary|null>(null);const[statusCounts,setStatusCounts]=useState<StatusCounts>({NEW:0,ACCEPTED:0,PROCESSING:0,COMPLETED:0});const[byService,setByService]=useState<ServiceRow[]>([]);const[byAtoll,setByAtoll]=useState<PlaceRow[]>([]);const[byIsland,setByIsland]=useState<PlaceRow[]>([]);const[noProvider,setNoProvider]=useState<NoProviderRow[]>([]);const[providerTime,setProviderTime]=useState<ProviderTimeRow[]>([]);const[providerTimeSummary,setProviderTimeSummary]=useState<ProviderTimeSummary>({ratedProviders:0,averageTimeRating:0,excellentTimeProviders:0,needsAttention:0});const[message,setMessage]=useState('Loading reports…');const[busy,setBusy]=useState(false);
 useEffect(()=>{void load();},[]);
 async function token(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return '';}return data.session.access_token;}
 async function call(url:string,t:string,body:Record<string,unknown>){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to load reports');return p;}
 async function load(){setBusy(true);try{const t=await token();if(!t)return;const[p,list,providerReport]=await Promise.all([call(API,t,{action:'reports'}),call(API,t,{action:'request_list'}),call(PROVIDER_REPORT_API,t,{action:'timeliness'})]);setSummary(p.summary);setStatusCounts(p.statusCounts||{});setByService(p.byService||[]);setByAtoll(p.byAtoll||[]);setByIsland(p.byIsland||[]);setProviderTime(providerReport.providers||[]);setProviderTimeSummary(providerReport.summary||{ratedProviders:0,averageTimeRating:0,excellentTimeProviders:0,needsAttention:0});
   const unassigned=((list.requests||[]) as RequestListRow[]).filter(r=>r.status==='NEW'&&!r.assigned_provider_user_id);
   const checks=await Promise.allSettled(unassigned.map(async r=>{const detail=await call(API,t,{action:'request_detail',ticketNumber:r.ticket_number});return{row:r,eligible:Array.isArray(detail.eligibleProviders)?detail.eligibleProviders.length:0};}));
   const exceptions:NoProviderRow[]=[];for(const check of checks){if(check.status!=='fulfilled'||check.value.eligible>0)continue;const r=check.value.row;exceptions.push({id:r.id,ticket:r.ticket_number,service:r.service_name,location:r.service_location_text,preferredDate:r.preferred_date,createdAt:r.created_at,customer:r.customer?.full_name||r.customer?.email||'Customer',reason:'No approved and available provider currently matches both the service and exact service area.'});}setNoProvider(exceptions.sort((a,b)=>new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime()));setMessage('Reporting dashboard is up to date.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load reports.');}finally{setBusy(false);}}
 const coverage=summary?.totalIslands?Math.round((summary.coveredIslands/summary.totalIslands)*1000)/10:0;
 return <main className="shell"><header className="topbar"><div><a className="brand" href="/admin">FixIt</a><p className="tagline">Admin • Reporting</p></div><button className="secondary" onClick={()=>void load()} disabled={busy}>{busy?'Loading…':'Refresh'}</button></header><AdminNav />
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">OPERATIONS REPORT</p><h2>Marketplace performance</h2></div><span className="pill">Live data</span></div><p className="formMessage" role="status">{message}</p>{summary?<div className="adminStats"><div className="statCard"><span>Total requests</span><strong>{summary.totalRequests}</strong></div><div className="statCard"><span>Last 30 days</span><strong>{summary.last30Days}</strong></div><div className="statCard"><span>Completion rate</span><strong>{summary.completionRate}%</strong></div><div className="statCard"><span>Unassigned new</span><strong>{summary.unassignedNew}</strong></div><div className="statCard"><span>No provider available</span><strong>{noProvider.length}</strong></div><div className="statCard"><span>Active providers</span><strong>{summary.activeProviders}</strong></div></div>:null}</section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">PROVIDER PERFORMANCE</p><h2>Provider Timeliness</h2><p className="muted">Customer Time ratings from verified completed jobs, ranked highest to lowest.</p></div><span className="pill">★ {providerTimeSummary.averageTimeRating.toFixed(1)} average</span></div><div className="adminStats"><div className="statCard"><span>Rated providers</span><strong>{providerTimeSummary.ratedProviders}</strong></div><div className="statCard"><span>Average Time rating</span><strong>{providerTimeSummary.averageTimeRating.toFixed(1)}</strong></div><div className="statCard"><span>Excellent ≥ 4.5</span><strong>{providerTimeSummary.excellentTimeProviders}</strong></div><div className="statCard"><span>Needs attention &lt; 3.5</span><strong>{providerTimeSummary.needsAttention}</strong></div></div>{providerTime.length?<div className="userTableWrap"><table className="userTable"><thead><tr><th>Provider</th><th>Time</th><th>Quality</th><th>Cost</th><th>Overall</th><th>Reviews</th><th>Performance</th></tr></thead><tbody>{providerTime.map(p=><tr key={p.providerUserId}><td><strong>{p.providerName}</strong>{p.providerRank?<small>Overall rank #{p.providerRank}</small>:null}</td><td><strong>★ {p.timeRating?.toFixed(1)??'—'}</strong></td><td>{p.qualityRating?.toFixed(1)??'—'}</td><td>{p.costRating?.toFixed(1)??'—'}</td><td>{p.overallRating?.toFixed(1)??'—'}</td><td>{p.reviewCount}</td><td>{p.timeRating!==null&&p.timeRating>=4.5?'Excellent':p.timeRating!==null&&p.timeRating>=3.5?'Good':'Needs attention'}</td></tr>)}</tbody></table></div>:<div className="emptyQueue">No provider Time ratings have been submitted yet.</div>}</section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">ACTION REQUIRED</p><h2>No Provider Available</h2><p className="muted">Open requests where the current matching rules return zero eligible providers.</p></div><span className="pill">{noProvider.length} request{noProvider.length===1?'':'s'}</span></div>{noProvider.length?<div className="userTableWrap"><table className="userTable"><thead><tr><th>Request</th><th>Service</th><th>Location</th><th>Preferred date</th><th>Customer</th><th>Reason</th><th>Action</th></tr></thead><tbody>{noProvider.map(r=><tr key={r.id}><td><strong>{r.ticket}</strong><small>Created {new Date(r.createdAt).toLocaleString()}</small></td><td>{r.service}</td><td>{r.location}</td><td>{r.preferredDate}</td><td>{r.customer}</td><td>{r.reason}</td><td><a className="primary" href="/admin/requests">Open Requests</a></td></tr>)}</tbody></table></div>:<div className="emptyQueue">No open requests currently have zero eligible providers.</div>}</section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">REQUEST PIPELINE</p><h2>Current lifecycle</h2></div></div><div className="adminStats"><div className="statCard"><span>New</span><strong>{statusCounts.NEW||0}</strong></div><div className="statCard"><span>Accepted</span><strong>{statusCounts.ACCEPTED||0}</strong></div><div className="statCard"><span>Processing</span><strong>{statusCounts.PROCESSING||0}</strong></div><div className="statCard"><span>Completed</span><strong>{statusCounts.COMPLETED||0}</strong></div></div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">PROVIDER COVERAGE</p><h2>Service footprint</h2></div><span className="pill">{coverage}% island coverage</span></div>{summary?<div className="adminStats"><div className="statCard"><span>Approved providers</span><strong>{summary.approvedProviders}</strong></div><div className="statCard"><span>Active providers</span><strong>{summary.activeProviders}</strong></div><div className="statCard"><span>Covered islands</span><strong>{summary.coveredIslands}</strong></div><div className="statCard"><span>Total locations</span><strong>{summary.totalIslands}</strong></div></div>:null}</section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">SERVICE DEMAND</p><h2>Requests by service</h2></div></div><div className="userTableWrap"><table className="userTable"><thead><tr><th>Service</th><th>Requests</th><th>Completed</th><th>Completion</th></tr></thead><tbody>{byService.map(s=><tr key={s.code}><td><strong>{s.name}</strong><small>{s.code}</small></td><td>{s.total}</td><td>{s.completed}</td><td>{s.total?Math.round(s.completed*1000/s.total)/10:0}%</td></tr>)}</tbody></table></div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">GEOGRAPHIC DEMAND</p><h2>Requests by atoll</h2></div></div><div className="userTableWrap"><table className="userTable"><thead><tr><th>Atoll</th><th>Requests</th></tr></thead><tbody>{byAtoll.map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{a.code||''}</small></td><td>{a.total}</td></tr>)}</tbody></table></div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">TOP ISLANDS / CITIES</p><h2>Highest request volumes</h2></div></div><div className="userTableWrap"><table className="userTable"><thead><tr><th>Island / City</th><th>Requests</th></tr></thead><tbody>{byIsland.map(i=><tr key={i.id}><td><strong>{i.name}</strong></td><td>{i.total}</td></tr>)}</tbody></table></div></section>
 </main>;
}