'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import { useAutoLocation } from '../../../lib/useAutoLocation';
import './onboarding.css';

const ONBOARDING_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-onboarding';
const LOCATION_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/location-catalogue';
type Category={id:string;code:string;name:string};
type Profile={provider_type:'INDIVIDUAL'|'BUSINESS';public_name:string;business_name?:string|null;description?:string|null;experience_years:number;service_area_text:string;availability_status:'AVAILABLE_NOW'|'AVAILABLE_TODAY'|'BY_APPOINTMENT'|'UNAVAILABLE';onboarding_status:'DRAFT'|'SUBMITTED'|'APPROVED'|'REJECTED'|'SUSPENDED'};
type Hour={dayOfWeek:number;isWorking:boolean;startTime:string;endTime:string};
type Atoll={id:string;code:string;display_name:string;sort_order:number};
type Island={id:string;atoll_id:string;display_name:string;sort_order:number};
type Unit={id:string;island_id:string;display_name:string;unit_type:string;sort_order:number};
type ServiceArea={islandId:string;locationUnitId:string|null;atollId?:string|null;islandName:string;locationUnitName?:string|null};
const dayNames=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const defaultHours:Hour[]=dayNames.map((_,i)=>({dayOfWeek:i+1,isWorking:i<6,startTime:'08:00',endTime:'17:00'}));

export default function ProviderOnboardingPage(){
 const[providerType,setProviderType]=useState<'INDIVIDUAL'|'BUSINESS'>('INDIVIDUAL');const[publicName,setPublicName]=useState('');const[businessName,setBusinessName]=useState('');const[description,setDescription]=useState('');const[experienceYears,setExperienceYears]=useState(0);const[availabilityStatus,setAvailabilityStatus]=useState<'AVAILABLE_NOW'|'AVAILABLE_TODAY'|'BY_APPOINTMENT'|'UNAVAILABLE'>('BY_APPOINTMENT');const[categories,setCategories]=useState<Category[]>([]);const[selected,setSelected]=useState<string[]>([]);const[hours,setHours]=useState<Hour[]>(defaultHours);const[status,setStatus]=useState<Profile['onboarding_status']>('DRAFT');const[message,setMessage]=useState('Loading provider profile…');const[busy,setBusy]=useState(false);
 const[atolls,setAtolls]=useState<Atoll[]>([]);const[islands,setIslands]=useState<Island[]>([]);const[units,setUnits]=useState<Unit[]>([]);const[serviceAreas,setServiceAreas]=useState<ServiceArea[]>([]);const[areaAtollId,setAreaAtollId]=useState('');const[areaIslandId,setAreaIslandId]=useState('');const[areaUnitId,setAreaUnitId]=useState('');const[loaded,setLoaded]=useState(false);const[autoTried,setAutoTried]=useState(false);
 const{resolving,resolved,error:locationError,resolveCurrentLocation}=useAutoLocation();
 const selectedCount=useMemo(()=>selected.length,[selected]);const islandOptions=useMemo(()=>islands.filter(i=>i.atoll_id===areaAtollId),[islands,areaAtollId]);const unitOptions=useMemo(()=>units.filter(u=>u.island_id===areaIslandId),[units,areaIslandId]);
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(!loaded||autoTried||serviceAreas.length)return;setAutoTried(true);void resolveCurrentLocation().then(hit=>{if(!hit)return;const area={islandId:hit.island.id,locationUnitId:hit.locationUnit?.id||null,atollId:hit.atoll.id,islandName:hit.island.display_name,locationUnitName:hit.locationUnit?.display_name||null};setServiceAreas([area]);setAreaAtollId(hit.atoll.id);setAreaIslandId(hit.island.id);setAreaUnitId(hit.locationUnit?.id||'');setMessage(`Current service area detected automatically: ${area.islandName}${area.locationUnitName?` — ${area.locationUnitName}`:''}.`);});},[loaded,autoTried,serviceAreas.length,resolveCurrentLocation]);
 async function token(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return '';}return data.session.access_token;}
 async function call(body:Record<string,unknown>){const t=await token();if(!t)throw new Error('Sign in required');const response=await fetch(ONBOARDING_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload?.error||'Provider onboarding request failed');return payload;}
 async function load(){setBusy(true);try{const t=await token();const [payload,locResponse]=await Promise.all([call({action:'get'}),fetch(LOCATION_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:'{}'})]);const loc=await locResponse.json();if(!locResponse.ok)throw new Error(loc?.error||'Unable to load locations');if(payload.authProfile?.role!=='PROVIDER'){setMessage('This account is not a Provider account. An Admin can change your role to Provider.');return;}setAtolls(loc.atolls||[]);setIslands(loc.islands||[]);setUnits(loc.locationUnits||[]);setServiceAreas((payload.serviceAreas||[]).map((a:any)=>({islandId:a.islandId,locationUnitId:a.locationUnitId||null,atollId:a.atollId||null,islandName:a.islandName||'Selected location',locationUnitName:a.locationUnitName||null})));setCategories(payload.categories||[]);setSelected(payload.selectedCategoryIds||[]);if(payload.profile){const p=payload.profile as Profile;setProviderType(p.provider_type);setPublicName(p.public_name||'');setBusinessName(p.business_name||'');setDescription(p.description||'');setExperienceYears(Number(p.experience_years||0));setAvailabilityStatus(p.availability_status||'BY_APPOINTMENT');setStatus(p.onboarding_status||'DRAFT');}if(Array.isArray(payload.hours)&&payload.hours.length){setHours(dayNames.map((_,i)=>{const h=payload.hours.find((x:any)=>Number(x.day_of_week)===i+1);return h?{dayOfWeek:i+1,isWorking:Boolean(h.is_working),startTime:(h.start_time||'08:00').slice(0,5),endTime:(h.end_time||'17:00').slice(0,5)}:defaultHours[i];}));}setMessage(payload.authProfile?.provider_approved?'Provider account approved. Keep your service areas current.':'Complete your profile and submit it for Admin approval.');setLoaded(true);}catch(error){setMessage(error instanceof Error?error.message:'Unable to load provider profile.');}finally{setBusy(false);}}
 function toggleCategory(id:string){setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);}
 function updateHour(day:number,patch:Partial<Hour>){setHours(current=>current.map(h=>h.dayOfWeek===day?{...h,...patch}:h));}
 function addArea(){if(!areaIslandId)return setMessage('Select an island or city before adding a service area.');const island=islands.find(i=>i.id===areaIslandId);const unit=areaUnitId?units.find(u=>u.id===areaUnitId):null;if(!island)return;const key=`${areaIslandId}:${areaUnitId}`;if(serviceAreas.some(a=>`${a.islandId}:${a.locationUnitId||''}`===key))return setMessage('That service area is already added.');setServiceAreas(current=>[...current,{islandId:areaIslandId,locationUnitId:areaUnitId||null,atollId:island.atoll_id,islandName:island.display_name,locationUnitName:unit?.display_name||null}]);setAreaUnitId('');setMessage(`${island.display_name}${unit?` — ${unit.display_name}`:''} added.`);}
 async function detectAndAddArea(){const hit=await resolveCurrentLocation();if(!hit)return;const key=`${hit.island.id}:${hit.locationUnit?.id||''}`;if(serviceAreas.some(a=>`${a.islandId}:${a.locationUnitId||''}`===key))return setMessage('Your current location is already in your service areas.');setServiceAreas(current=>[...current,{islandId:hit.island.id,locationUnitId:hit.locationUnit?.id||null,atollId:hit.atoll.id,islandName:hit.island.display_name,locationUnitName:hit.locationUnit?.display_name||null}]);setMessage(`Current location added: ${hit.island.display_name}${hit.locationUnit?` — ${hit.locationUnit.display_name}`:''}.`);}
 function removeArea(index:number){setServiceAreas(current=>current.filter((_,i)=>i!==index));}
 async function save(submit:boolean){if(publicName.trim().length<2)return setMessage('Enter your public provider name.');if(submit&&!selected.length)return setMessage('Select at least one service category before submitting.');if(submit&&!serviceAreas.length)return setMessage('Add at least one service area before submitting.');setBusy(true);try{const payload=await call({action:submit?'submit':'save',providerType,publicName:publicName.trim(),businessName:businessName.trim(),description:description.trim(),experienceYears,availabilityStatus,categoryIds:selected,hours,serviceAreas:serviceAreas.map(a=>({islandId:a.islandId,locationUnitId:a.locationUnitId}))});setStatus(payload.onboardingStatus||status);setMessage(submit?'Provider profile submitted for Admin approval.':'Draft saved.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to save provider profile.');}finally{setBusy(false);}}
 async function signOut(){await supabase.auth.signOut();window.location.href='/login';}
 return <main className="shell">
  <header className="topbar"><div><a className="brand" href="/">FixIt</a><p className="tagline">Provider Onboarding</p></div><div className="actions"><a className="secondary" href="/provider">Job Operations</a><button className="secondary" onClick={signOut}>Sign Out</button></div></header>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">PROVIDER PROFILE</p><h2>Set up your service business</h2></div><span className="pill">{status}</span></div>{message?<p className="formMessage" role="status">{message}</p>:null}{locationError&&!resolved?<p className="localNotice">{locationError}</p>:null}<p className="localNotice">If no service area exists yet, FixIt tries to seed your first one automatically from your current GPS location.</p></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">ABOUT YOU</p><h2>Provider details</h2></div></div><div className="formGrid onboardingForm"><label>Provider type<select value={providerType} onChange={e=>setProviderType(e.target.value as 'INDIVIDUAL'|'BUSINESS')}><option value="INDIVIDUAL">Individual</option><option value="BUSINESS">Business</option></select></label><label>Public provider name<input value={publicName} onChange={e=>setPublicName(e.target.value)} placeholder="Name customers will see"/></label>{providerType==='BUSINESS'?<label>Business name<input value={businessName} onChange={e=>setBusinessName(e.target.value)} placeholder="Registered/trading name"/></label>:null}<label>Years of experience<input type="number" min="0" max="80" value={experienceYears} onChange={e=>setExperienceYears(Number(e.target.value||0))}/></label><label>Current availability<select value={availabilityStatus} onChange={e=>setAvailabilityStatus(e.target.value as typeof availabilityStatus)}><option value="AVAILABLE_NOW">Available now</option><option value="AVAILABLE_TODAY">Available today</option><option value="BY_APPOINTMENT">By appointment</option><option value="UNAVAILABLE">Unavailable</option></select></label><label className="full">About your services<textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Tell customers about your experience and the work you do"/></label></div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">SERVICE AREAS</p><h2>Where do you work?</h2></div><span className="pill">{serviceAreas.length} area(s)</span></div><div className="actions"><button className="secondary" type="button" onClick={()=>void detectAndAddArea()} disabled={resolving}>{resolving?'Detecting…':'Add Current Location'}</button></div><div className="formGrid"><label>Atoll<select value={areaAtollId} onChange={e=>{setAreaAtollId(e.target.value);setAreaIslandId('');setAreaUnitId('');}}><option value="">Select atoll</option>{atolls.map(a=><option key={a.id} value={a.id}>{a.code} — {a.display_name}</option>)}</select></label><label>Island / City<select value={areaIslandId} disabled={!areaAtollId} onChange={e=>{setAreaIslandId(e.target.value);setAreaUnitId('');}}><option value="">Select island or city</option>{islandOptions.map(i=><option key={i.id} value={i.id}>{i.display_name}</option>)}</select></label>{unitOptions.length?<label>Ward / Area<select value={areaUnitId} onChange={e=>setAreaUnitId(e.target.value)}><option value="">Whole island / city</option>{unitOptions.map(u=><option key={u.id} value={u.id}>{u.display_name}</option>)}</select></label>:null}<div className="actions"><button type="button" className="primary" onClick={addArea}>Add Selected Area</button></div></div><div className="jobList">{serviceAreas.map((a,index)=><div className="jobCard" key={`${a.islandId}:${a.locationUnitId||''}`}><strong>{a.islandName}</strong>{a.locationUnitName?<p className="jobDescription">{a.locationUnitName}</p>:<p className="jobDescription">Whole island / city</p>}<button type="button" className="secondary" onClick={()=>removeArea(index)}>Remove</button></div>)}{!serviceAreas.length?<div className="emptyQueue">Detecting your first service area or add one manually.</div>:null}</div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">SERVICES</p><h2>What work do you provide?</h2></div><span className="pill">{selectedCount} selected</span></div><div className="categoryGrid">{categories.map(c=><button type="button" key={c.id} className={selected.includes(c.id)?'categoryChoice selected':'categoryChoice'} onClick={()=>toggleCategory(c.id)}>{c.name}</button>)}{!categories.length?<div className="emptyQueue">No service categories available.</div>:null}</div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">AVAILABILITY</p><h2>Weekly working hours</h2></div><span className="pill">Maldives time</span></div><div className="hoursList">{hours.map((h,i)=><div className="hoursRow" key={h.dayOfWeek}><label className="workingToggle"><input type="checkbox" checked={h.isWorking} onChange={e=>updateHour(h.dayOfWeek,{isWorking:e.target.checked})}/><span>{dayNames[i]}</span></label>{h.isWorking?<><input type="time" value={h.startTime} onChange={e=>updateHour(h.dayOfWeek,{startTime:e.target.value})}/><span className="muted">to</span><input type="time" value={h.endTime} onChange={e=>updateHour(h.dayOfWeek,{endTime:e.target.value})}/></>:<span className="muted">Not working</span>}</div>)}</div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">SUBMISSION</p><h2>Save or send for approval</h2></div></div><div className="actions"><button className="secondary" disabled={busy} onClick={()=>save(false)}>{busy?'Saving…':'Save Draft'}</button><button className="primary" disabled={busy} onClick={()=>save(true)}>{busy?'Submitting…':'Submit for Approval'}</button></div><p className="localNotice">Approved providers receive only jobs matching their selected service category and canonical service area.</p></section>
  <footer className="footer"><span>FixIt Maldives</span><span>Dynamic Provider Location</span></footer>
 </main>;
}
