'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import AdminNav from '../AdminNav';
import styles from './users.module.css';

const ADMIN_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/admin-operations';
const ADMIN_USERS_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/admin-users';
const PAGE_SIZE=10;

type SavedAddress={label?:string|null;address_line1?:string|null;city?:string|null;state_region?:string|null;country?:string|null};
type UserRow={user_id:string;email?:string|null;full_name?:string|null;role:'CUSTOMER'|'PROVIDER'|'ADMIN';provider_approved:boolean;phone_number?:string|null;is_phone_verified:boolean;profile_photo_url?:string|null;photoUrl?:string|null;address_line1?:string|null;address_line2?:string|null;city?:string|null;state_region?:string|null;postal_code?:string|null;country?:string|null;defaultServiceAddress?:SavedAddress|null;created_at:string;updated_at:string;last_sign_in_at?:string|null;last_seen_at?:string|null;email_confirmed_at?:string|null;account_status?:string|null;status?:string|null;business_name?:string|null;service_category?:string|null;subscription_plan?:string|null;request_count?:number|null;open_request_count?:number|null;completed_request_count?:number|null;average_rating?:number|null;provider_is_suspended?:boolean|null;suspension_reason?:string|null};
type PermissionRow={id:string;code:string;name:string;description?:string|null;resource:string;action:string;role_default:boolean;override:boolean|null;effective_enabled:boolean;updated_at?:string|null};
type RoleFilter='ALL'|'CUSTOMER'|'PROVIDER'|'ADMIN';

export default function AdminUsersPage(){
 const[users,setUsers]=useState<UserRow[]>([]);const[currentUserId,setCurrentUserId]=useState('');const[busyUser,setBusyUser]=useState('');const[message,setMessage]=useState('Loading user accounts…');const[query,setQuery]=useState('');const[roleFilter,setRoleFilter]=useState<RoleFilter>('ALL');const[page,setPage]=useState(1);const[selectedUserId,setSelectedUserId]=useState<string|null>(null);const[loading,setLoading]=useState(false);const[lastUpdated,setLastUpdated]=useState<Date|null>(null);const[permissions,setPermissions]=useState<PermissionRow[]>([]);const[permissionsLoading,setPermissionsLoading]=useState(false);const[busyPermission,setBusyPermission]=useState('');
 useEffect(()=>{void load();},[]);
 useEffect(()=>{setPage(1);setSelectedUserId(null);setPermissions([]);},[query,roleFilter]);
 async function jwt(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return '';}setCurrentUserId(data.session.user.id);return data.session.access_token;}
 async function call(url:string,body:Record<string,unknown>={}){const t=await jwt();if(!t)return null;const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload?.error||'Admin request failed');return payload;}
 async function load(){setLoading(true);try{const payload=await call(ADMIN_USERS_URL);if(!payload)return;setUsers((payload.users||[]).filter((u:UserRow)=>String(u.account_status||'ACTIVE').toUpperCase()!=='DEACTIVATED'));setLastUpdated(new Date());setMessage('User accounts are up to date.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to load users.');}finally{setLoading(false);}}
 async function loadPermissions(userId:string){setPermissionsLoading(true);try{const payload=await call(ADMIN_USERS_URL,{action:'get_permissions',targetUserId:userId});setPermissions(payload?.permissions||[]);}catch(error){setPermissions([]);setMessage(error instanceof Error?error.message:'Unable to load user permissions.');}finally{setPermissionsLoading(false);}}
 async function openUser(row:UserRow){if(selectedUserId===row.user_id){setSelectedUserId(null);setPermissions([]);return;}setSelectedUserId(row.user_id);setPermissions([]);await loadPermissions(row.user_id);}
 async function setPermission(row:UserRow,permission:PermissionRow,enabled:boolean){if(permission.effective_enabled===enabled)return;setBusyPermission(permission.id);try{await call(ADMIN_USERS_URL,{action:'set_permission',targetUserId:row.user_id,permissionId:permission.id,enabled});setPermissions(list=>list.map(p=>p.id===permission.id?{...p,override:enabled,effective_enabled:enabled,updated_at:new Date().toISOString()}:p));setMessage(`${permission.name} ${enabled?'enabled':'disabled'} for ${row.full_name||row.email||'user'}.`);}catch(error){setMessage(error instanceof Error?error.message:'Unable to update permission.');}finally{setBusyPermission('');}}
 async function changeRole(row:UserRow,role:'CUSTOMER'|'PROVIDER'){setBusyUser(row.user_id);try{await call(ADMIN_URL,{action:'set_user_role',targetUserId:row.user_id,role,providerApproved:role==='PROVIDER'?row.provider_approved:false});await load();if(selectedUserId===row.user_id)await loadPermissions(row.user_id);setMessage(`${row.full_name||row.email||'User'} changed to ${role}.`);}catch(error){setMessage(error instanceof Error?error.message:'Unable to change role.');}finally{setBusyUser('');}}
 async function setSuspended(row:UserRow,suspended:boolean){const name=row.full_name||row.email||'User';const reason=suspended?window.prompt(`Reason for suspending ${name} (optional):`,'')||'':null;if(suspended&&!window.confirm(`Suspend ${name}? ${row.role==='PROVIDER'?'They will stop receiving new service requests.':'They will not be able to make new service requests.'}`))return;setBusyUser(row.user_id);try{await call(ADMIN_URL,{action:'set_account_suspension',targetUserId:row.user_id,suspended,reason});await load();setMessage(suspended?`${name} suspended.`:`${name} reactivated.`);}catch(error){setMessage(error instanceof Error?error.message:'Unable to update account status.');}finally{setBusyUser('');}}
 async function deleteUser(row:UserRow){const name=row.full_name||row.email||'this user';if(row.role==='ADMIN'||row.user_id===currentUserId)return;const confirmed=window.confirm(`Delete ${name}? The account will be disabled and removed from active users, while historical records are retained.`);if(!confirmed)return;setBusyUser(row.user_id);try{const{error}=await supabase.rpc('admin_deactivate_user',{p_target_user_id:row.user_id});if(error)throw error;setSelectedUserId(null);setPermissions([]);setUsers(list=>list.filter(u=>u.user_id!==row.user_id));setMessage(`${name} was deleted from active users. Historical records were retained.`);}catch(error){setMessage(error instanceof Error?error.message:'Unable to delete user account.');}finally{setBusyUser('');}}
 function avatar(u:UserRow){const src=u.photoUrl||(/^https?:\/\//i.test(u.profile_photo_url||'')?u.profile_photo_url:null);const initial=(u.full_name||u.email||'U').slice(0,1).toUpperCase();return src?<img src={src} alt={`${u.full_name||'User'} profile`} style={{width:64,height:64,borderRadius:'50%',objectFit:'cover',flex:'0 0 auto',border:'1px solid var(--border)'}}/>:<span style={{width:64,height:64,borderRadius:'50%',display:'inline-grid',placeItems:'center',background:'var(--surface-alt)',fontWeight:800,fontSize:22,flex:'0 0 auto'}}>{initial}</span>;}
 function coreAddress(u:UserRow){return[u.address_line1,u.address_line2,u.city,u.state_region,u.postal_code,u.country].filter(Boolean).join(', ');}
 function defaultAddress(u:UserRow){const a=u.defaultServiceAddress;return a?[a.label,a.address_line1,a.city,a.state_region,a.country].filter(Boolean).join(' · '):'';}
 function date(value?:string|null){if(!value)return 'Not available';const d=new Date(value);return Number.isNaN(d.getTime())?'Not available':d.toLocaleString();}
 function accountState(u:UserRow){const status=String(u.account_status||u.status||'ACTIVE').toUpperCase();if(status==='SUSPENDED'||u.provider_is_suspended===true)return'SUSPENDED';if(u.role==='ADMIN')return'ADMIN';if(u.role==='PROVIDER'&&!u.provider_approved)return'PENDING';return'ACTIVE';}
 function privilegeLevel(u:UserRow){const state=accountState(u);if(state==='SUSPENDED')return'Access suspended';if(u.role==='ADMIN')return'Full administrative access';if(u.role==='PROVIDER')return u.provider_approved?'Provider access':'Provider access pending approval';return'Standard user access';}
 function userRights(u:UserRow){if(u.role==='ADMIN')return'Manage users providers requests settings reports activity';if(u.role==='PROVIDER')return'Receive service requests manage assigned work update job status manage provider locations customer requests';return'Create service requests view manage own requests service locations rate completed services';}
 const visible=useMemo(()=>users.filter(u=>{const text=`${u.full_name||''} ${u.email||''} ${u.phone_number||''} ${u.role} ${u.user_id} ${u.account_status||''} ${privilegeLevel(u)} ${userRights(u)}`.toLowerCase();return(roleFilter==='ALL'||u.role===roleFilter)&&(!query.trim()||text.includes(query.trim().toLowerCase()));}).sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()||new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime()),[users,query,roleFilter]);
 const totalPages=Math.max(1,Math.ceil(visible.length/PAGE_SIZE));const pagedVisible=visible.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
 useEffect(()=>{if(page>totalPages)setPage(totalPages);},[page,totalPages]);
 const selected=users.find(u=>u.user_id===selectedUserId)||null;
 function permissionPanel(u:UserRow){const protectedAdmin=u.role==='ADMIN';return <div className="permissionPanel"><div className="permissionHeader"><div><p className="eyebrow">USER RIGHTS & PRIVILEGES</p><h3>Enable or disable permissions</h3><p className="muted">Role defaults are shown below. Changes are saved as user-specific overrides.</p></div><span className={`permissionSummary ${protectedAdmin?'protected':''}`}>{protectedAdmin?'Protected Admin':`${permissions.filter(p=>p.effective_enabled).length} enabled`}</span></div>{permissionsLoading?<div className="permissionEmpty">Loading permissions…</div>:permissions.length?<div className="permissionList">{permissions.map(p=><div className={`permissionRow ${p.effective_enabled?'enabled':'disabled'}`} key={p.id}><div className="permissionInfo"><div className="permissionTitle"><strong>{p.name}</strong><span className={`permissionState ${p.effective_enabled?'enabled':'disabled'}`}>{p.effective_enabled?'Enabled':'Disabled'}</span></div><p>{p.description||p.code}</p><small>{p.code}{p.override!==null?' · Custom override':' · Role default'}</small></div><div className="permissionControls" aria-label={`${p.name} permission`}><button className={p.effective_enabled?'active enable':''} disabled={protectedAdmin||busyPermission===p.id} onClick={()=>void setPermission(u,p,true)}>Enable</button><button className={!p.effective_enabled?'active disable':''} disabled={protectedAdmin||busyPermission===p.id} onClick={()=>void setPermission(u,p,false)}>Disable</button></div></div>)}</div>:<div className="permissionEmpty">No editable permissions are configured for this role.</div>}{protectedAdmin?<p className="permissionNote">Admin permissions are protected here to prevent accidental administrative lockout.</p>:null}</div>}
 function detailPanel(u:UserRow){const state=accountState(u);return <div className="inlineUserDetail"><div className="panelHeader"><div><p className="eyebrow">USER ACCOUNT DETAIL</p><h2>{u.full_name||'Unnamed user'}</h2></div><button className="secondary" onClick={()=>{setSelectedUserId(null);setPermissions([]);}}>Close</button></div><div className="detailGrid"><div className="detailFact"><b>User ID</b><span>{u.user_id}</span></div><div className="detailFact"><b>Account status</b><span>{state}</span></div><div className="detailFact"><b>Role</b><span>{u.role}</span></div><div className="detailFact"><b>Privilege level</b><span>{privilegeLevel(u)}</span></div><div className="detailFact"><b>Email</b><span>{u.email||'Not available'}</span></div><div className="detailFact"><b>Phone</b><span>{u.phone_number||'Not available'}</span></div><div className="detailFact"><b>Email verification</b><span>{u.email_confirmed_at?'Verified':'Not available'}</span></div><div className="detailFact"><b>Phone verification</b><span>{u.phone_number?(u.is_phone_verified?'Verified':'Unverified'):'Not available'}</span></div><div className="detailFact"><b>Joined</b><span>{date(u.created_at)}</span></div><div className="detailFact"><b>Last active</b><span>{date(u.last_seen_at||u.last_sign_in_at)}</span></div><div className="detailFact"><b>Account address</b><span>{coreAddress(u)||'Not available'}</span></div><div className="detailFact"><b>Default service address</b><span>{defaultAddress(u)||'Not available'}</span></div>{u.business_name?<div className="detailFact"><b>Business name</b><span>{u.business_name}</span></div>:null}{u.suspension_reason?<div className="detailFact"><b>Suspension reason</b><span>{u.suspension_reason}</span></div>:null}</div>{permissionPanel(u)}<div className="userRowActions" style={{marginTop:16}}>{u.role==='PROVIDER'?<a className="secondary compactButton" href={`/admin/providers/${u.user_id}`}>Open Provider Record</a>:null}{u.role!=='ADMIN'&&u.role!=='CUSTOMER'?<button className="secondary compactButton" disabled={busyUser===u.user_id} onClick={()=>void changeRole(u,'CUSTOMER')}>Change to Customer</button>:null}{u.role!=='ADMIN'&&u.role!=='PROVIDER'?<button className="primary compactButton" disabled={busyUser===u.user_id} onClick={()=>void changeRole(u,'PROVIDER')}>Grant Provider Access</button>:null}{u.role!=='ADMIN'?(state==='SUSPENDED'?<button className="primary compactButton" disabled={busyUser===u.user_id} onClick={()=>void setSuspended(u,false)}>Reactivate</button>:<button className="secondary compactButton" disabled={busyUser===u.user_id} onClick={()=>void setSuspended(u,true)}>Suspend</button>):<span className="muted">Protected admin account</span>}{u.role!=='ADMIN'&&u.user_id!==currentUserId?<button className="danger compactButton" disabled={busyUser===u.user_id} onClick={()=>void deleteUser(u)}>{busyUser===u.user_id?'Deleting…':'Delete Account'}</button>:null}</div></div>}
 return <main className={`${styles.page} shell`}><header className="topbar usersTopbar"><div><p className="eyebrow">ADMIN WORKSPACE</p><h1 className="pageTitle">User Management</h1><p className="tagline">Search, review and manage users, roles, rights and privileges.</p></div><button className="primary refreshAction" onClick={()=>void load()} disabled={loading}><span aria-hidden="true">↻</span>{loading?'Refreshing…':'Refresh'}</button></header><AdminNav/>
  <section className="usersToolbarPanel"><div className="usersStatusBar" role="status"><span className="statusCheck">✓</span><span><b>{message}</b>{lastUpdated?<small>Last updated {lastUpdated.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small>:null}</span></div><div className="usersSearchRow"><label>Search<span className="usersSearchBox"><span aria-hidden="true">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, email, phone, role, right, privilege, status or user ID"/></span></label></div><div className="usersFilterRow">{(['ALL','CUSTOMER','PROVIDER','ADMIN'] as const).map(x=><button key={x} className={`userFilter userFilter-${x.toLowerCase()} ${roleFilter===x?'active':''}`} onClick={()=>setRoleFilter(x)}><span className="userFilterDot"/>{x==='ALL'?'All Users':x[0]+x.slice(1).toLowerCase()}</button>)}</div></section>
  <section className="panel usersListPanel"><div className="panelHeader"><div><p className="eyebrow">LATEST ACCOUNTS</p><h2>{roleFilter==='ALL'?'All Users':roleFilter[0]+roleFilter.slice(1).toLowerCase()}</h2><p className="muted">Showing {visible.length} user{visible.length===1?'':'s'}. Newest accounts appear first.</p></div></div><div className="jobList">{pagedVisible.map(u=>{const state=accountState(u);const tone=state.toLowerCase();return <div key={u.user_id}><article className={`jobCard userCard userCard-${tone}`}><div className="jobTop"><div style={{display:'flex',gap:13,alignItems:'center'}}>{avatar(u)}<div><strong style={{fontSize:20}}>{u.full_name||'Unnamed user'}</strong><span className="muted" style={{display:'block',overflowWrap:'anywhere'}}>{u.email||'No email address'}</span></div></div><span className={`userStatus userStatus-${tone}`}>{state==='PENDING'?'Pending approval':state[0]+state.slice(1).toLowerCase()}</span></div><div className="userMeta"><span><b>Role</b>{u.role}</span><span><b>Privileges</b>{privilegeLevel(u)}</span><span><b>Phone</b>{u.phone_number||'Not available'}</span><span><b>Joined</b>{date(u.created_at)}</span><span><b>Last active</b>{date(u.last_seen_at||u.last_sign_in_at)}</span></div><div className="userRowActions"><button className="primary openUserButton" onClick={()=>void openUser(u)}>{selectedUserId===u.user_id?'Close Details':'Open User'}</button></div></article>{selectedUserId===u.user_id&&selected?detailPanel(selected):null}</div>})}{!visible.length?<div className="emptyQueue">No users match this view.</div>:null}</div>{visible.length>PAGE_SIZE?<div className="paginationBar"><button className="secondary" disabled={page===1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><span className="muted">Page {page} of {totalPages} · {visible.length} users</span><button className="secondary" disabled={page===totalPages} onClick={()=>setPage(p=>Math.min(totalPages,p+1))}>Next</button></div>:null}</section>
 </main>;
}