'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import AdminNav from '../AdminNav';

const ADMIN_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/admin-operations';
const ADMIN_USERS_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/admin-users';
type SavedAddress={label?:string|null;address_line1?:string|null;city?:string|null;state_region?:string|null;country?:string|null};
type UserRow={user_id:string;email?:string|null;full_name?:string|null;role:'CUSTOMER'|'PROVIDER'|'ADMIN';provider_approved:boolean;phone_number?:string|null;is_phone_verified:boolean;profile_photo_url?:string|null;photoUrl?:string|null;address_line1?:string|null;address_line2?:string|null;city?:string|null;state_region?:string|null;postal_code?:string|null;country?:string|null;defaultServiceAddress?:SavedAddress|null;created_at:string;updated_at:string};
type RoleFilter='ALL'|'CUSTOMER'|'PROVIDER'|'ADMIN';

export default function AdminUsersPage(){
 const[users,setUsers]=useState<UserRow[]>([]);const[currentUserId,setCurrentUserId]=useState('');const[busyUser,setBusyUser]=useState('');const[message,setMessage]=useState('Loading users…');const[query,setQuery]=useState('');const[roleFilter,setRoleFilter]=useState<RoleFilter>('ALL');
 useEffect(()=>{void load();},[]);
 async function jwt(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return '';}setCurrentUserId(data.session.user.id);return data.session.access_token;}
 async function call(url:string,body:Record<string,unknown>={}){const t=await jwt();if(!t)return null;const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload?.error||'Admin request failed');return payload;}
 async function load(){try{const payload=await call(ADMIN_USERS_URL);if(!payload)return;setUsers(payload.users||[]);setMessage('User accounts loaded.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to load users.');}}
 async function changeRole(row:UserRow,role:'CUSTOMER'|'PROVIDER'){setBusyUser(row.user_id);try{await call(ADMIN_URL,{action:'set_user_role',targetUserId:row.user_id,role,providerApproved:role==='PROVIDER'?row.provider_approved:false});await load();setMessage(`${row.full_name||row.email||'User'} changed to ${role}. ${role==='PROVIDER'?'Provider approval and operational setup remain under Providers.':''}`.trim());}catch(error){setMessage(error instanceof Error?error.message:'Unable to change role.');}finally{setBusyUser('');}}
 function avatar(u:UserRow){const initial=(u.full_name||u.email||'U').slice(0,1).toUpperCase();return u.photoUrl?<img src={u.photoUrl} alt="" style={{width:42,height:42,borderRadius:'50%',objectFit:'cover'}}/>:<span style={{width:42,height:42,borderRadius:'50%',display:'inline-grid',placeItems:'center',background:'var(--surface-alt)',fontWeight:800}}>{initial}</span>;}
 function coreAddress(u:UserRow){return[u.address_line1,u.address_line2,u.city,u.state_region,u.postal_code,u.country].filter(Boolean).join(', ')||'—';}
 function defaultAddress(u:UserRow){const a=u.defaultServiceAddress;return a?[a.label,a.address_line1,a.city,a.state_region,a.country].filter(Boolean).join(' · '):'—';}
 const visible=useMemo(()=>users.filter(u=>{const text=`${u.full_name||''} ${u.email||''} ${u.phone_number||''} ${u.role}`.toLowerCase();return(roleFilter==='ALL'||u.role===roleFilter)&&(!query.trim()||text.includes(query.trim().toLowerCase()));}),[users,query,roleFilter]);
 const counts=useMemo(()=>({customers:users.filter(u=>u.role==='CUSTOMER').length,providers:users.filter(u=>u.role==='PROVIDER').length,admins:users.filter(u=>u.role==='ADMIN').length}),[users]);
 return <main className="shell"><header className="topbar"><div><a className="brand" href="/admin">FixIt</a><p className="tagline">Admin • Users</p></div><button className="secondary" onClick={()=>void load()}>Refresh</button></header><AdminNav/>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">IDENTITY & ACCESS</p><h2>User Accounts</h2><p className="muted">Manage account identity and base access here. Provider approval, services, locations, subscription, documents and availability are managed only under Providers.</p></div><span className="pill">{users.length} users</span></div>
   <div className="adminStats"><div className="statCard"><span>Customers</span><strong>{counts.customers}</strong></div><div className="statCard"><span>Providers</span><strong>{counts.providers}</strong></div><div className="statCard"><span>Admins</span><strong>{counts.admins}</strong></div></div>
   <p className="formMessage" role="status">{message}</p>
   <div className="formGrid"><label className="full">Search users<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, email, phone or role"/></label></div>
   <div className="filterRow">{(['ALL','CUSTOMER','PROVIDER','ADMIN'] as const).map(x=><button key={x} className={roleFilter===x?'filterChip active':'filterChip'} onClick={()=>setRoleFilter(x)}>{x==='ALL'?'All':x[0]+x.slice(1).toLowerCase()}</button>)}</div>
  </section>
  <section className="panel"><div className="userTableWrap"><table className="userTable"><thead><tr><th>User</th><th>Phone</th><th>Verification</th><th>Account Address</th><th>Default Service Address</th><th>Access Role</th><th>Actions</th></tr></thead><tbody>{visible.map(u=><tr key={u.user_id}><td><div style={{display:'flex',gap:10,alignItems:'center'}}>{avatar(u)}<div><strong>{u.full_name||'Unnamed user'}</strong><small>{u.email||'No email'}</small>{u.user_id===currentUserId?<span className="selfTag">You</span>:null}</div></div></td><td>{u.phone_number||'—'}</td><td>{u.phone_number?<span className={u.is_phone_verified?'profileBadge verified':'profileBadge warning'}>{u.is_phone_verified?'Verified':'Unverified'}</span>:'—'}</td><td><small>{coreAddress(u)}</small></td><td><small>{defaultAddress(u)}</small></td><td><span className="pill">{u.role}</span></td><td><div className="tableActions">{u.role==='PROVIDER'?<a className="secondary compactButton" href={`/admin/providers/${u.user_id}`}>Open Provider Record</a>:null}{u.role!=='ADMIN'&&u.role!=='CUSTOMER'?<button className="secondary compactButton" disabled={busyUser===u.user_id} onClick={()=>changeRole(u,'CUSTOMER')}>Change to Customer</button>:null}{u.role!=='ADMIN'&&u.role!=='PROVIDER'?<button className="primary compactButton" disabled={busyUser===u.user_id} onClick={()=>changeRole(u,'PROVIDER')}>Grant Provider Access</button>:null}{u.role==='ADMIN'?<span className="muted">Protected admin</span>:null}</div></td></tr>)}</tbody></table></div>{!visible.length?<div className="emptyQueue">No users match this view.</div>:null}</section>
 </main>;
}
