'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import AdminNav from '../../AdminNav';

const API='/api/legacy-edge?service=admin-request-oversight';

type History={from_status?:string|null;to_status:string;actor_type?:string|null;note?:string|null;created_at:string};
type DispatchOffer={id:string;provider_user_id:string;sequence_no:number;rank_score?:number|null;status:string;offered_at?:string|null;response_deadline_at?:string|null;responded_at?:string|null;provider?:{full_name?:string|null;email?:string|null}|null};
type ProviderResponse={provider_user_id:string;status:string;provider_message?:string|null;responded_at?:string|null;selected_at?:string|null;provider_confirmed_at?:string|null;provider?:{full_name?:string|null;email?:string|null}|null};
type Person={user_id:string;full_name?:string|null;email?:string|null;phone_number?:string|null};
type RequestRow={id:string;ticket_number:string;service_name:string;service_location_text:string;problem_description:string;status:string;dispatch_state?:string|null;dispatch_tier?:string|null;dispatch_attempt?:number|null;assigned_provider_label?:string|null;assigned_provider_user_id?:string|null;customer_auth_user_id?:string|null;created_by_admin_user_id?:string|null;created_at:string;updated_at:string;accepted_at?:string|null;processing_at?:string|null;completed_at?:string|null;customer?:Person|null;createdByAdmin?:Person|null};

type Detail={request:RequestRow;customer?:Person|null;createdByAdmin?:Person|null;history:History[];dispatchOffers:DispatchOffer[];providerResponses:ProviderResponse[];job?:{status?:string|null;provider_user_id?:string|null;provider_label?:string|null;accepted_at?:string|null;processing_at?:string|null;completed_at?:string|null}|null};

function when(v?:string|null){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString(undefined,{day:'2-digit',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'});}
async function post(body:Record<string,unknown>){const r=await fetch(API,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const p=await r.json().catch(()=>({}));if(r.status===401){window.location.replace(`/login?next=${encodeURIComponent(window.location.pathname)}`);throw new Error('Authentication required.');}if(!r.ok)throw new Error(p?.error||'Admin operation failed');return p;}

export default function AdminRequestDetailPage(){
 const params=useParams<{ticket:string}>();const router=useRouter();const ticket=decodeURIComponent(String(params.ticket||'')).toUpperCase();
 const[data,setData]=useState<Detail|null>(null);const[busy,setBusy]=useState(true);const[message,setMessage]=useState('Loading request…');
 useEffect(()=>{if(ticket)void load();},[ticket]);
 async function load(){setBusy(true);try{const p=await post({action:'request_detail',ticketNumber:ticket});setData(p as Detail);setMessage('');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load request.');}finally{setBusy(false);}}
 async function transition(){if(!data)return;const current=String(data.request.status||'').toUpperCase();const target=current==='ACCEPTED'?'PROCESSING':current==='PROCESSING'||current==='IN_PROGRESS'?'COMPLETED':'';if(!target)return;if(!window.confirm(`Move ${ticket} to ${target}?`))return;setBusy(true);try{await post({action:'transition_request',ticketNumber:ticket,targetStatus:target});await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to update request.');setBusy(false);}}
 if(!data)return <main className="shell"><AdminNav/><section className="panel"><p role="status">{busy?'Loading request…':message}</p><button className="secondary" onClick={()=>router.push('/admin/requests')}>Back to requests</button></section></main>;
 const r=data.request;const canTransition=['ACCEPTED','PROCESSING','IN_PROGRESS'].includes(String(r.status).toUpperCase());
 return <main className="shell adminRequestDetailPage"><header className="topbar"><div><p className="eyebrow">ADMIN · REQUEST OVERSIGHT</p><h1>{r.ticket_number}</h1><p className="tagline">{r.service_name} · {r.service_location_text}</p></div><button className="secondary" onClick={()=>router.push('/admin/requests')}>← Requests</button></header><AdminNav/>
  {message?<p className="statusNotice" role="status">{message}</p>:null}
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">CURRENT STATE</p><h2>{r.status}</h2><p className="muted">Dispatch: {r.dispatch_state||'—'} · Tier: {r.dispatch_tier||'—'} · Attempt: {r.dispatch_attempt||1}</p></div>{canTransition?<button className="primary" disabled={busy} onClick={()=>void transition()}>{String(r.status).toUpperCase()==='ACCEPTED'?'Start Processing':'Mark Completed'}</button>:null}</div><div className="trackingGrid"><div className="requestSummary"><p><b>Customer:</b> {data.customer?.full_name||data.customer?.email||'Unlinked'}</p><p><b>Customer ID:</b> {r.customer_auth_user_id||'—'}</p><p><b>Provider:</b> {r.assigned_provider_label||'Unassigned'}</p><p><b>Provider ID:</b> {r.assigned_provider_user_id||'—'}</p><p><b>Created by Admin:</b> {data.createdByAdmin?.full_name||data.createdByAdmin?.email||'—'}</p><p><b>Request ID:</b> {r.id}</p></div><div className="requestSummary"><p><b>Created:</b> {when(r.created_at)}</p><p><b>Accepted:</b> {when(r.accepted_at)}</p><p><b>Processing:</b> {when(r.processing_at)}</p><p><b>Completed:</b> {when(r.completed_at)}</p><p><b>Updated:</b> {when(r.updated_at)}</p></div></div><p className="jobDescription">{r.problem_description}</p></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">STATUS HISTORY</p><h2>Lifecycle timeline</h2></div></div><div className="jobList">{data.history.map((h,i)=><article className="jobCard" key={`${h.created_at}-${i}`}><strong>{h.from_status||'START'} → {h.to_status}</strong><p className="jobDescription">{h.note||'Status changed'}</p><span className="muted">{h.actor_type||'SYSTEM'} · {when(h.created_at)}</span></article>)}</div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">DISPATCH HISTORY</p><h2>Provider offers</h2></div><span className="pill">{data.dispatchOffers.length}</span></div><div className="jobList">{data.dispatchOffers.map(o=><article className="jobCard" key={o.id}><div className="jobTop"><strong>Offer #{o.sequence_no} · {o.provider?.full_name||o.provider?.email||o.provider_user_id}</strong><span className="pill">{o.status}</span></div><p className="muted">Score {o.rank_score??'—'} · Offered {when(o.offered_at)} · Deadline {when(o.response_deadline_at)} · Responded {when(o.responded_at)}</p></article>)}{!data.dispatchOffers.length?<div className="emptyQueue">No ranked dispatch offers recorded.</div>:null}</div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">PROVIDER RESPONSES</p><h2>Provider activity</h2></div><span className="pill">{data.providerResponses.length}</span></div><div className="jobList">{data.providerResponses.map((p,i)=><article className="jobCard" key={`${p.provider_user_id}-${i}`}><div className="jobTop"><strong>{p.provider?.full_name||p.provider?.email||p.provider_user_id}</strong><span className="pill">{p.status}</span></div>{p.provider_message?<p className="jobDescription">{p.provider_message}</p>:null}<p className="muted">Responded {when(p.responded_at)} · Selected {when(p.selected_at)} · Confirmed {when(p.provider_confirmed_at)}</p></article>)}{!data.providerResponses.length?<div className="emptyQueue">No provider responses recorded.</div>:null}</div></section>
 </main>;
}
