'use client';

import { useEffect, useMemo, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import AdminNav from '../../AdminNav';

const API='/api/legacy-edge?service=admin-request-oversight';

type Person={user_id:string;full_name?:string|null;email?:string|null};
type HistoryRow={from_status?:string|null;to_status:string;actor_type?:string|null;note?:string|null;created_at:string};
type MessageRow={id:string;sender_role:string;sender_label?:string|null;message_text:string;created_at:string};
type Job={id:string;status:string;provider_user_id?:string|null;provider_label?:string|null;accepted_at?:string|null;processing_at?:string|null;completed_at?:string|null;created_at:string;updated_at:string};
type RequestRow={id:string;ticket_number:string;service_name:string;service_category_code?:string|null;service_location_text:string;problem_description?:string|null;status:string;source?:string|null;dispatch_state?:string|null;dispatch_tier?:string|null;dispatch_attempt?:number|null;assigned_provider_label?:string|null;assigned_provider_user_id?:string|null;customer_auth_user_id?:string|null;created_by_admin_user_id?:string|null;accepted_at?:string|null;processing_at?:string|null;completed_at?:string|null;created_at:string;updated_at:string;attentionReasons?:string[]};

function when(value?:string|null){if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleString(undefined,{day:'2-digit',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'});}
function pretty(value?:string|null){return String(value||'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());}
function canonical(value?:string|null){const s=String(value||'').toUpperCase();if(s==='COMPLETED')return'COMPLETED';if(s==='PROCESSING'||s==='IN_PROGRESS'||s==='INSPECTION_SCHEDULED')return'PROCESSING';if(s==='ACCEPTED')return'ACCEPTED';return s||'NEW';}
async function post(body:Record<string,unknown>){const r=await fetch(API,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const p=await r.json().catch(()=>({}));if(r.status===401){const next=`${window.location.pathname}${window.location.search}`;window.location.replace(`/login?next=${encodeURIComponent(next)}`);throw new Error('Authentication required.');}if(!r.ok)throw new Error(p?.error||'Admin request failed');return p;}

export default function AdminRequestDetailPage(){
 const params=useParams<{ticket:string}>();const router=useRouter();const ticket=decodeURIComponent(String(params?.ticket||'')).toUpperCase();
 const[request,setRequest]=useState<RequestRow|null>(null);const[customer,setCustomer]=useState<Person|null>(null);const[job,setJob]=useState<Job|null>(null);const[history,setHistory]=useState<HistoryRow[]>([]);const[messages,setMessages]=useState<MessageRow[]>([]);const[busy,setBusy]=useState(true);const[message,setMessage]=useState('Loading request…');
 useEffect(()=>{if(ticket)void load();},[ticket]);
 async function load(){setBusy(true);try{const p=await post({action:'request_detail',ticketNumber:ticket});setRequest(p.request||null);setCustomer(p.customer||null);setJob(p.job||null);setHistory(p.history||[]);setMessages(p.messages||[]);setMessage('');}catch(e){if(!(e instanceof Error&&e.message==='Authentication required.'))setMessage(e instanceof Error?e.message:'Unable to load request.');}finally{setBusy(false);}}
 async function transition(target:'PROCESSING'|'COMPLETED'){if(!request||!window.confirm(`Move ${request.ticket_number} to ${target}?`))return;setBusy(true);try{await post({action:'transition_request',ticketNumber:request.ticket_number,targetStatus:target});setMessage(`Request moved to ${target}.`);await load();}catch(e){if(!(e instanceof Error&&e.message==='Authentication required.'))setMessage(e instanceof Error?e.message:'Unable to update request.');}finally{setBusy(false);}}
 const stage=canonical(request?.status);const stages=['ACCEPTED','PROCESSING','COMPLETED'];const stageIndex=Math.max(0,stages.indexOf(stage));const next=stage==='ACCEPTED'?'PROCESSING':stage==='PROCESSING'?'COMPLETED':null;
 const dispatch=useMemo(()=>[{label:'State',value:pretty(request?.dispatch_state)||'—'},{label:'Tier',value:pretty(request?.dispatch_tier)||'—'},{label:'Attempt',value:String(request?.dispatch_attempt??'—')},{label:'Source',value:request?.source||'—'}],[request]);
 if(busy&&!request)return <main className="shell"><AdminNav/><section className="panel"><p>{message}</p></section></main>;
 if(!request)return <main className="shell"><AdminNav/><section className="panel"><h1>Request unavailable</h1><p>{message}</p><button className="primary" onClick={()=>router.push('/admin/requests')}>Back to Requests</button></section></main>;
 return <main className="shell adminRequestDetailPage">
  <header className="topbar"><div><button className="secondary" onClick={()=>router.push('/admin/requests')}>← Requests</button><p className="eyebrow">ADMIN · SERVICE REQUEST</p><h1>{request.ticket_number}</h1><p className="tagline">{request.service_name} · {request.service_location_text}</p></div><span className="pill">{pretty(stage)}</span></header>
  <AdminNav/>
  {message?<p className="formMessage" role="status">{message}</p>:null}
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">LIFECYCLE</p><h2>Request progress</h2></div>{next?<button className="primary" disabled={busy} onClick={()=>void transition(next)}>{busy?'Updating…':next==='PROCESSING'?'Start Processing':'Mark Completed'}</button>:<span className="pill">No action required</span>}</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:10}}>{stages.map((s,i)=><div key={s} className="jobCard"><strong>{i<stageIndex?'✓ ':i===stageIndex?'● ':''}{pretty(s)}</strong><p className="muted">{i<stageIndex?'Completed':i===stageIndex?'Current status':'Pending'}</p></div>)}</div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">ASSIGNMENT</p><h2>Customer & provider</h2></div></div><div className="trackingGrid"><div className="jobCard"><strong>Customer</strong><p>{customer?.full_name||customer?.email||'Customer profile unavailable'}</p><span className="muted">User ID: {request.customer_auth_user_id||'Unlinked'}</span></div><div className="jobCard"><strong>Assigned provider</strong><p>{request.assigned_provider_label||job?.provider_label||'Unassigned'}</p><span className="muted">Provider ID: {request.assigned_provider_user_id||job?.provider_user_id||'Unassigned'}</span></div></div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">REQUEST</p><h2>Service details</h2></div></div><div className="requestSummary"><p><b>Service:</b> {request.service_name}</p><p><b>Category:</b> {request.service_category_code||'—'}</p><p><b>Location:</b> {request.service_location_text}</p><p><b>Created:</b> {when(request.created_at)}</p><p><b>Updated:</b> {when(request.updated_at)}</p><p><b>Accepted:</b> {when(request.accepted_at||job?.accepted_at)}</p><p><b>Processing:</b> {when(request.processing_at||job?.processing_at)}</p><p><b>Completed:</b> {when(request.completed_at||job?.completed_at)}</p><p className="jobDescription">{request.problem_description||'No problem description supplied.'}</p></div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">DISPATCH</p><h2>Routing state</h2></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10}}>{dispatch.map(item=><div className="jobCard" key={item.label}><span className="muted">{item.label}</span><strong>{item.value}</strong></div>)}</div>{request.attentionReasons?.length?<div className="attentionNotice"><b>Needs attention</b><span>{request.attentionReasons.join(' · ')}</span></div>:null}</section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">AUDIT TRAIL</p><h2>Status history</h2></div></div><div className="jobList">{history.map((h,i)=><article className="jobCard" key={`${h.created_at}-${i}`}><strong>{pretty(h.from_status||'START')} → {pretty(h.to_status)}</strong><p>{h.note||'Status updated'}</p><span className="muted">{pretty(h.actor_type||'SYSTEM')} · {when(h.created_at)}</span></article>)}{!history.length?<div className="emptyQueue">No status history found.</div>:null}</div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">COMMUNICATION</p><h2>Messages</h2></div></div><div className="jobList">{messages.map(m=><article className="jobCard" key={m.id}><strong>{m.sender_label||pretty(m.sender_role)}</strong><p>{m.message_text}</p><span className="muted">{when(m.created_at)}</span></article>)}{!messages.length?<div className="emptyQueue">No messages yet.</div>:null}</div></section>
 </main>;
}
