'use client';

import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '../../lib/supabaseClient';

export default function ResetPasswordPage(){
 const[ready,setReady]=useState(false);const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('Opening secure reset session…');
 useEffect(()=>{let mounted=true;supabase.auth.getSession().then(({data})=>{if(!mounted)return;if(data.session){setReady(true);setMessage('Choose a new password.');}});const{data:sub}=supabase.auth.onAuthStateChange((event,session)=>{if(!mounted)return;if(event==='PASSWORD_RECOVERY'||session){setReady(true);setMessage('Choose a new password.');}});const timer=setTimeout(()=>{if(mounted&&!ready)setMessage('Open this page from the password reset link in your email.');},2500);return()=>{mounted=false;clearTimeout(timer);sub.subscription.unsubscribe();};},[ready]);
 async function submit(e:FormEvent){e.preventDefault();if(password.length<8){setMessage('Password must be at least 8 characters.');return;}if(password!==confirm){setMessage('Passwords do not match.');return;}setBusy(true);try{const{data}=await supabase.auth.getSession();if(!data.session)throw new Error('The reset session is missing or expired. Request a new reset link.');const r=await fetch('/api/auth/reset-password',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({password})});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to reset password.');setMessage('Password updated. You can now sign in.');await supabase.auth.signOut();setTimeout(()=>{window.location.href='/login';},1200);}catch(err){setMessage(err instanceof Error?err.message:'Unable to reset password.');}finally{setBusy(false);}}
 return <main className="shell authShell"><header className="topbar"><div><a className="brand" href="/">FixIt</a><p className="tagline">Secure password reset</p></div></header><section className="panel authCard"><div className="panelHeader"><div><p className="eyebrow">ACCOUNT RECOVERY</p><h2>Set a new password</h2></div></div><form className="authForm" onSubmit={submit}><label>New password<input type="password" autoComplete="new-password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} disabled={!ready} required/></label><label>Confirm password<input type="password" autoComplete="new-password" minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)} disabled={!ready} required/></label><button className="primary" disabled={!ready||busy}>{busy?'Updating…':'Update Password'}</button></form><p className="formMessage" role="status">{message}</p></section></main>;
}
