'use client';

import { useEffect, useMemo, useState } from 'react';
import AdminNav from '../AdminNav';
import { supabase } from '../../../lib/supabaseClient';
import './locations.css';

const API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/admin-locations';
type Atoll={id:string;code:string;official_name:string;display_name:string;administrative_prefix?:string|null;is_active:boolean;is_serviceable:boolean;sort_order:number;usage:{islands:number;requests:number}};
type Island={id:string;atoll_id:string;canonical_name:string;display_name:string;reference_code?:string|null;administrative_code_range?:string|null;location_kind:'ISLAND'|'CITY';is_active:boolean;is_serviceable:boolean;sort_order:number;usage:{requests:number;providers:number;units:number}};
type Unit={id:string;atoll_id:string;island_id:string;parent_id?:string|null;unit_type:string;canonical_name:string;display_name:string;reference_code?:string|null;is_active:boolean;is_serviceable:boolean;sort_order:number;usage:{requests:number;providers:number;children:number}};
type Level='ATOLLS'|'ISLANDS'|'UNITS';
type EditType='atoll'|'island'|'unit';
type SearchHit={kind:EditType;id:string;label:string;detail:string;atollId?:string;islandId?:string;parentId?:string|null};

type ApiResult={ok:boolean;status:number;payload:any};

export default function AdminLocationsPage(){
 const[atolls,setAtolls]=useState<Atoll[]>([]);const[islands,setIslands]=useState<Island[]>([]);const[units,setUnits]=useState<Unit[]>([]);const[message,setMessage]=useState('Loading location catalogue…');const[busy,setBusy]=useState(false);
 const[level,setLevel]=useState<Level>('ATOLLS');const[selectedAtollId,setSelectedAtollId]=useState('');const[selectedIslandId,setSelectedIslandId]=useState('');const[selectedUnitId,setSelectedUnitId]=useState('');const[query,setQuery]=useState('');
 const[editType,setEditType]=useState<EditType|null>(null);const[editId,setEditId]=useState('');const[name,setName]=useState('');const[code,setCode]=useState('');const[prefix,setPrefix]=useState('');const[reference,setReference]=useState('');const[range,setRange]=useState('');const[kind,setKind]=useState('ISLAND');const[unitType,setUnitType]=useState('WARD');const[sortOrder,setSortOrder]=useState(0);const[parentAtoll,setParentAtoll]=useState('');const[parentIsland,setParentIsland]=useState('');const[parentUnit,setParentUnit]=useState('');
 useEffect(()=>{void load();},[]);
 async function token(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return '';}return data.session.access_token;}
 async function request(body:Record<string,unknown>):Promise<ApiResult>{const t=await token();if(!t)return{ok:false,status:401,payload:{error:'Sign in required'}};const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify(body)});const payload=await r.json().catch(()=>({error:'Invalid server response'}));return{ok:r.ok,status:r.status,payload};}
 async function call(body:Record<string,unknown>){const r=await request(body);if(!r.ok)throw new Error(r.payload?.error||'Location operation failed');return r.payload;}
 async function load(){setBusy(true);try{const p=await call({action:'list'});setAtolls(p.atolls||[]);setIslands(p.islands||[]);setUnits(p.units||[]);setMessage('Location catalogue ready.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load locations.');}finally{setBusy(false);}}
 const selectedAtoll=useMemo(()=>atolls.find(a=>a.id===selectedAtollId)||null,[atolls,selectedAtollId]);
 const selectedIsland=useMemo(()=>islands.find(i=>i.id===selectedIslandId)||null,[islands,selectedIslandId]);
 const selectedUnit=useMemo(()=>units.find(u=>u.id===selectedUnitId)||null,[units,selectedUnitId]);
 const visibleIslands=useMemo(()=>islands.filter(i=>i.atoll_id===selectedAtollId).sort((a,b)=>a.sort_order-b.sort_order),[islands,selectedAtollId]);
 const visibleUnits=useMemo(()=>units.filter(u=>u.island_id===selectedIslandId&&(!selectedUnitId?u.parent_id==null:u.parent_id===selectedUnitId)).sort((a,b)=>a.sort_order-b.sort_order),[units,selectedIslandId,selectedUnitId]);
 const islandChoices=useMemo(()=>islands.filter(i=>!parentAtoll||i.atoll_id===parentAtoll),[islands,parentAtoll]);
 const parentUnitChoices=useMemo(()=>units.filter(u=>u.island_id===parentIsland&&u.id!==editId),[units,parentIsland,editId]);
 const activeCount=useMemo(()=>[...atolls,...islands,...units].filter((x:any)=>x.is_active&&x.is_serviceable).length,[atolls,islands,units]);
 const searchHits=useMemo<SearchHit[]>(()=>{const q=query.trim().toLowerCase();if(q.length<2)return[];const aa=atolls.filter(x=>`${x.code} ${x.display_name}`.toLowerCase().includes(q)).slice(0,6).map(x=>({kind:'atoll' as const,id:x.id,label:`${x.code} · ${x.display_name}`,detail:'Atoll'}));const ii=islands.filter(x=>`${x.display_name} ${x.reference_code||''} ${x.administrative_code_range||''}`.toLowerCase().includes(q)).slice(0,8).map(x=>({kind:'island' as const,id:x.id,label:x.display_name,detail:`${atolls.find(a=>a.id===x.atoll_id)?.display_name||'Atoll'} · ${x.location_kind}`,atollId:x.atoll_id}));const uu=units.filter(x=>`${x.display_name} ${x.reference_code||''}`.toLowerCase().includes(q)).slice(0,8).map(x=>({kind:'unit' as const,id:x.id,label:x.display_name,detail:`${islands.find(i=>i.id===x.island_id)?.display_name||'Location'} · ${x.unit_type}`,atollId:x.atoll_id,islandId:x.island_id,parentId:x.parent_id}));return[...aa,...ii,...uu].slice(0,16);},[query,atolls,islands,units]);
 function resetForm(){setEditType(null);setEditId('');setName('');setCode('');setPrefix('');setReference('');setRange('');setKind('ISLAND');setUnitType('WARD');setSortOrder(0);setParentAtoll('');setParentIsland('');setParentUnit('');}
 function startAtoll(a?:Atoll){setEditType('atoll');setEditId(a?.id||'');setName(a?.display_name||'');setCode(a?.code||'');setPrefix(a?.administrative_prefix||'');setSortOrder(a?.sort_order||0);}
 function startIsland(i?:Island){setEditType('island');setEditId(i?.id||'');setName(i?.display_name||'');setReference(i?.reference_code||'');setRange(i?.administrative_code_range||'');setKind(i?.location_kind||'ISLAND');setSortOrder(i?.sort_order||0);setParentAtoll(i?.atoll_id||selectedAtollId);}
 function startUnit(u?:Unit){setEditType('unit');setEditId(u?.id||'');setName(u?.display_name||'');setReference(u?.reference_code||'');setUnitType(u?.unit_type||'WARD');setSortOrder(u?.sort_order||0);setParentAtoll(u?.atoll_id||selectedAtollId);setParentIsland(u?.island_id||selectedIslandId);setParentUnit(u?.parent_id??selectedUnitId);}
 async function save(){if(!editType)return;if(!name.trim())return setMessage('Display name is required.');setBusy(true);try{if(editId){await call({action:'update',type:editType,id:editId,displayName:name.trim(),canonicalName:name.trim(),code:editType==='atoll'?code:undefined,officialName:editType==='atoll'?name.trim():undefined,administrativePrefix:editType==='atoll'?prefix:undefined,referenceCode:editType!=='atoll'?reference:undefined,administrativeCodeRange:editType==='island'?range:undefined,locationKind:editType==='island'?kind:undefined,unitType:editType==='unit'?unitType:undefined,parentId:editType==='unit'?parentUnit||null:undefined,sortOrder});}else if(editType==='atoll'){await call({action:'create_atoll',code,displayName:name.trim(),officialName:name.trim(),administrativePrefix:prefix,sortOrder});}else if(editType==='island'){await call({action:'create_island',atollId:parentAtoll,displayName:name.trim(),canonicalName:name.trim(),referenceCode:reference,administrativeCodeRange:range,locationKind:kind,sortOrder});}else{await call({action:'create_unit',atollId:parentAtoll,islandId:parentIsland,parentId:parentUnit||null,displayName:name.trim(),canonicalName:name.trim(),referenceCode:reference,unitType,sortOrder});}setMessage(editId?'Location updated successfully.':'New location added.');resetForm();await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to save location.');}finally{setBusy(false);}}
 async function patch(type:EditType,id:string,values:Record<string,unknown>){setBusy(true);try{await call({action:'update',type,id,...values});setMessage('Location status updated.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to update location.');}finally{setBusy(false);}}
 async function remove(type:EditType,id:string,label:string){if(!window.confirm(`Permanently delete “${label}” and any unused child locations beneath it?`))return;setBusy(true);try{const r=await request({action:'delete',type,id});if(r.ok){const n=Number(r.payload?.deleted?.branchSize||1);setMessage(`${label} deleted permanently${n>1?` with ${n-1} child record(s)`:''}.`);if(type==='atoll'){setSelectedAtollId('');setSelectedIslandId('');setSelectedUnitId('');setLevel('ATOLLS');}else if(type==='island'){setSelectedIslandId('');setSelectedUnitId('');setLevel('ISLANDS');}else if(selectedUnitId===id){setSelectedUnitId('');}await load();return;}if(r.status===409&&r.payload?.canDisable){const usage=r.payload?.usage||{};const details=[usage.requests?`${usage.requests} request(s)`:null,usage.providers?`${usage.providers} provider reference(s)`:null].filter(Boolean).join(' and ');const disable=window.confirm(`${r.payload.error}${details?`\n\nThis location is linked to ${details}.`:''}\n\nDisable it instead?`);if(disable){await call({action:'update',type,id,isActive:false,isServiceable:false});setMessage(`${label} disabled because it has operational history.`);await load();}else setMessage('Delete cancelled.');return;}setMessage(r.payload?.error||'Unable to delete location.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to delete location.');}finally{setBusy(false);}}
 function openAtoll(id:string){setSelectedAtollId(id);setSelectedIslandId('');setSelectedUnitId('');setLevel('ISLANDS');setQuery('');resetForm();}
 function openIsland(id:string){setSelectedIslandId(id);setSelectedUnitId('');setLevel('UNITS');setQuery('');resetForm();}
 function openUnit(id:string){if(units.some(u=>u.parent_id===id)){setSelectedUnitId(id);setQuery('');resetForm();}else setMessage('This is the lowest location level. Open Manage to edit it.');}
 function jump(hit:SearchHit){if(hit.kind==='atoll')return openAtoll(hit.id);if(hit.kind==='island'){setSelectedAtollId(hit.atollId||'');return openIsland(hit.id);}setSelectedAtollId(hit.atollId||'');setSelectedIslandId(hit.islandId||'');setSelectedUnitId(hit.parentId||'');setLevel('UNITS');setQuery('');setMessage(`Showing ${hit.label}.`);}
 function back(){resetForm();if(level==='UNITS'&&selectedUnitId){const current=units.find(u=>u.id===selectedUnitId);setSelectedUnitId(current?.parent_id||'');return;}if(level==='UNITS'){setLevel('ISLANDS');setSelectedIslandId('');return;}if(level==='ISLANDS'){setLevel('ATOLLS');setSelectedAtollId('');}}
 function statusClass(active:boolean,serviceable:boolean){return active&&serviceable?'active':!active?'disabled':'service';}
 function statusLabel(active:boolean,serviceable:boolean){return active&&serviceable?'ACTIVE':!active?'DISABLED':'NOT SERVICEABLE';}
 function card(type:EditType,item:Atoll|Island|Unit){const isAtoll=type==='atoll',isIsland=type==='island';const childCount=isAtoll?(item as Atoll).usage.islands:isIsland?(item as Island).usage.units:(item as Unit).usage.children;const requestCount=item.usage.requests;const providerCount=isAtoll?0:(item as Island|Unit).usage.providers;const badge=isAtoll?(item as Atoll).code:isIsland?((item as Island).location_kind==='CITY'?'CITY':'ISL'):((item as Unit).reference_code||'AREA').slice(0,6);const subtitle=isAtoll?`Prefix ${(item as Atoll).administrative_prefix||'—'}`:isIsland?((item as Island).reference_code||(item as Island).administrative_code_range||'No reference code'):`${(item as Unit).unit_type.replaceAll('_',' ')} · ${(item as Unit).reference_code||'No code'}`;const canOpen=isAtoll||isIsland||childCount>0;return <article className="locationCard" key={`${type}:${item.id}`}><div className="locationCardTop"><div className="locationIdentity"><div className="locationBadge">{badge}</div><div className="locationName"><strong>{item.display_name}</strong><small>{subtitle}</small></div></div><span className={`statusChip ${statusClass(item.is_active,item.is_serviceable)}`}>{statusLabel(item.is_active,item.is_serviceable)}</span></div><div className="locationMetrics">{childCount>0?<span className="metricPill">{childCount} child{childCount===1?'':'ren'}</span>:null}{requestCount>0?<span className="metricPill">{requestCount} request{requestCount===1?'':'s'}</span>:null}{providerCount>0?<span className="metricPill">{providerCount} provider ref{providerCount===1?'':'s'}</span>:null}{childCount===0&&requestCount===0&&providerCount===0?<span className="metricPill">Unused</span>:null}</div><div className="locationCardActions">{canOpen?<button className="openButton" onClick={()=>isAtoll?openAtoll(item.id):isIsland?openIsland(item.id):openUnit(item.id)}>Open branch →</button>:<button className="openButton" onClick={()=>type==='unit'&&startUnit(item as Unit)}>Manage location</button>}<details className="moreActions"><summary aria-label="Location actions">•••</summary><div className="moreMenu"><button onClick={()=>isAtoll?startAtoll(item as Atoll):isIsland?startIsland(item as Island):startUnit(item as Unit)}>Edit details</button><button disabled={busy} onClick={()=>void patch(type,item.id,{isActive:!item.is_active})}>{item.is_active?'Disable':'Enable'}</button><button disabled={busy} onClick={()=>void patch(type,item.id,{isServiceable:!item.is_serviceable})}>{item.is_serviceable?'Mark not serviceable':'Mark serviceable'}</button><button className="dangerItem" disabled={busy} onClick={()=>void remove(type,item.id,item.display_name)}>Delete permanently</button></div></details></div></article>}
 const currentItems=level==='ATOLLS'?atolls.slice().sort((a,b)=>a.sort_order-b.sort_order):level==='ISLANDS'?visibleIslands:visibleUnits;
 return <main className="shell locationPage">
  <header className="topbar"><div><a className="brand" href="/">FixIt</a><p className="tagline">Admin · Locations</p></div><div className="actions"><a className="secondary" href="/admin">Admin Home</a></div></header><AdminNav/>
  <section className="locationHero"><div className="locationHeroTop"><div><p className="eyebrow">LOCATION DIRECTORY</p><h1>Manage service locations</h1><p>Browse one branch at a time, update availability, or add new service areas.</p></div><button className="locButton" onClick={()=>void load()} disabled={busy}>{busy?'Refreshing…':'↻ Refresh'}</button></div><div className="locationStats"><div className="locationStat"><strong>{atolls.length}</strong><span>Atolls</span></div><div className="locationStat"><strong>{islands.length}</strong><span>Islands & cities</span></div><div className="locationStat"><strong>{units.length}</strong><span>Wards & areas</span></div><div className="locationStat"><strong>{activeCount}</strong><span>Active records</span></div></div><div className="locationSearchWrap"><span className="locationSearchIcon">⌕</span><input className="locationSearch" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find an atoll, city, ward or code…"/>{query?<button className="locationClear" onClick={()=>setQuery('')} aria-label="Clear search">×</button>:null}{searchHits.length?<div className="searchResults">{searchHits.map(h=><button className="searchHit" key={`${h.kind}:${h.id}`} onClick={()=>jump(h)}><span><strong>{h.label}</strong><small>{h.detail}</small></span><span>→</span></button>)}</div>:null}</div>{message?<div className="locationMessage" role="status">{message}</div>:null}</section>
  <div className="branchBar"><div className="breadcrumbs"><button className={`crumb ${level==='ATOLLS'?'current':''}`} onClick={()=>{setLevel('ATOLLS');setSelectedAtollId('');setSelectedIslandId('');setSelectedUnitId('');}}>Maldives</button>{selectedAtoll?<><span>›</span><button className={`crumb ${level==='ISLANDS'?'current':''}`} onClick={()=>{setLevel('ISLANDS');setSelectedIslandId('');setSelectedUnitId('');}}>{selectedAtoll.code} · {selectedAtoll.display_name}</button></>:null}{selectedIsland?<><span>›</span><button className={`crumb ${level==='UNITS'&&!selectedUnitId?'current':''}`} onClick={()=>{setLevel('UNITS');setSelectedUnitId('');}}>{selectedIsland.display_name}</button></>:null}{selectedUnit?<><span>›</span><span className="crumb current">{selectedUnit.display_name}</span></>:null}</div><div className="branchTools">{level!=='ATOLLS'?<button className="locButton" onClick={back}>← Back</button>:null}<button className="locButton primary" onClick={()=>level==='ATOLLS'?startAtoll():level==='ISLANDS'?startIsland():startUnit()}>+ Add</button></div></div>
  <section className="locationSection"><div className="locationSectionHeader"><div><small>{level==='ATOLLS'?'ATOLLS':level==='ISLANDS'?'ISLANDS & CITIES':'WARDS & AREAS'}</small><h2>{level==='ATOLLS'?'Choose an atoll':level==='ISLANDS'?selectedAtoll?.display_name:selectedUnitId?selectedUnit?.display_name:selectedIsland?.display_name}</h2></div><small>{currentItems.length} item{currentItems.length===1?'':'s'}</small></div>{currentItems.length?<div className="locationGrid">{level==='ATOLLS'?(currentItems as Atoll[]).map(a=>card('atoll',a)):level==='ISLANDS'?(currentItems as Island[]).map(i=>card('island',i)):(currentItems as Unit[]).map(u=>card('unit',u))}</div>:<div className="emptyBranch"><strong>No child locations here</strong><span>Add a new location to this branch.</span></div>}</section>
  {editType?<div className="editorBackdrop" onMouseDown={e=>{if(e.currentTarget===e.target)resetForm();}}><section className="editorSheet"><div className="editorHandle"/><div className="editorHeader"><div><small>{editId?'EDIT LOCATION':'NEW LOCATION'}</small><h2>{editId?'Update details':`Add ${editType==='atoll'?'atoll':editType==='island'?'island / city':'ward / area'}`}</h2><p>{editType==='atoll'?'Top-level Maldives administrative area':editType==='island'?`Under ${atolls.find(a=>a.id===parentAtoll)?.display_name||'selected atoll'}`:`Under ${islands.find(i=>i.id===parentIsland)?.display_name||'selected island / city'}`}</p></div><button className="editorClose" onClick={resetForm}>×</button></div><div className="editorGrid">
   {editType==='atoll'?<label>Atoll code<input value={code} onChange={e=>setCode(e.target.value)} placeholder="HA"/></label>:<label>Atoll<select value={parentAtoll} disabled={Boolean(editId)} onChange={e=>{setParentAtoll(e.target.value);setParentIsland('');setParentUnit('');}}><option value="">Select atoll</option>{atolls.map(a=><option key={a.id} value={a.id}>{a.code} — {a.display_name}</option>)}</select></label>}
   {editType==='unit'?<label>Island / City<select value={parentIsland} disabled={Boolean(editId)} onChange={e=>{setParentIsland(e.target.value);setParentUnit('');}}><option value="">Select location</option>{islandChoices.map(i=><option key={i.id} value={i.id}>{i.display_name}</option>)}</select></label>:null}
   <label className={editType==='atoll'?'editorFull':''}>Display name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Location name"/></label>
   {editType==='atoll'?<label>Administrative prefix<input value={prefix} onChange={e=>setPrefix(e.target.value)} placeholder="A"/></label>:null}
   {editType==='island'?<><label>Location type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="ISLAND">Island</option><option value="CITY">City</option></select></label><label>Reference code<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="R-M"/></label><label className="editorFull">Administrative code range<input value={range} onChange={e=>setRange(e.target.value)} placeholder="R-M, R1 to R8"/></label></>:null}
   {editType==='unit'?<><label>Area type<select value={unitType} onChange={e=>setUnitType(e.target.value)}><option value="WARD">Ward</option><option value="DISTRICT">District</option><option value="PHASE">Phase</option><option value="ISLAND_AREA">Island area</option><option value="ELECTORAL_AREA">Electoral area</option><option value="AREA">Area</option></select></label><label>Reference code<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="R1"/></label><label className="editorFull">Parent area <span className="muted">(optional)</span><select value={parentUnit} onChange={e=>setParentUnit(e.target.value)}><option value="">No parent</option>{parentUnitChoices.map(u=><option key={u.id} value={u.id}>{u.display_name}</option>)}</select></label></>:null}
   <label>Sort order<input type="number" min="0" value={sortOrder} onChange={e=>setSortOrder(Number(e.target.value||0))}/></label></div><div className="branchHint">Delete is now permanent for unused branches. Locations with customer/provider history are protected and can be disabled instead.</div><div className="editorActions"><button className="locButton" onClick={resetForm}>Cancel</button><button className="locButton primary" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save location'}</button></div></section></div>:null}
  <footer className="footer"><span>FixIt Maldives</span><span>Location Directory</span></footer>
 </main>;
}
