'use client';

import { useEffect, useMemo, useState } from 'react';
import AdminNav from '../AdminNav';
import { supabase } from '../../../lib/supabaseClient';

const API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/admin-locations';
type Atoll={id:string;code:string;official_name:string;display_name:string;administrative_prefix?:string|null;is_active:boolean;is_serviceable:boolean;sort_order:number;usage:{islands:number;requests:number}};
type Island={id:string;atoll_id:string;canonical_name:string;display_name:string;reference_code?:string|null;administrative_code_range?:string|null;location_kind:'ISLAND'|'CITY';is_active:boolean;is_serviceable:boolean;sort_order:number;usage:{requests:number;providers:number;units:number}};
type Unit={id:string;atoll_id:string;island_id:string;parent_id?:string|null;unit_type:string;canonical_name:string;display_name:string;reference_code?:string|null;is_active:boolean;is_serviceable:boolean;sort_order:number;usage:{requests:number;providers:number;children:number}};
type Tab='ATOLLS'|'ISLANDS'|'UNITS';

export default function AdminLocationsPage(){
 const[tab,setTab]=useState<Tab>('ATOLLS');const[atolls,setAtolls]=useState<Atoll[]>([]);const[islands,setIslands]=useState<Island[]>([]);const[units,setUnits]=useState<Unit[]>([]);const[message,setMessage]=useState('Loading locations…');const[busy,setBusy]=useState(false);const[query,setQuery]=useState('');
 const[editType,setEditType]=useState<'atoll'|'island'|'unit'|null>(null);const[editId,setEditId]=useState('');const[name,setName]=useState('');const[code,setCode]=useState('');const[prefix,setPrefix]=useState('');const[reference,setReference]=useState('');const[range,setRange]=useState('');const[kind,setKind]=useState('ISLAND');const[unitType,setUnitType]=useState('WARD');const[sortOrder,setSortOrder]=useState(0);const[parentAtoll,setParentAtoll]=useState('');const[parentIsland,setParentIsland]=useState('');const[parentUnit,setParentUnit]=useState('');
 useEffect(()=>{void load();},[]);
 async function token(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return '';}return data.session.access_token;}
 async function call(body:Record<string,unknown>){const t=await token();if(!t)throw new Error('Sign in required');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Location operation failed');return p;}
 async function load(){setBusy(true);try{const p=await call({action:'list'});setAtolls(p.atolls||[]);setIslands(p.islands||[]);setUnits(p.units||[]);setMessage('Location catalogue loaded.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load locations.');}finally{setBusy(false);}}
 function resetForm(){setEditType(null);setEditId('');setName('');setCode('');setPrefix('');setReference('');setRange('');setKind('ISLAND');setUnitType('WARD');setSortOrder(0);setParentAtoll('');setParentIsland('');setParentUnit('');}
 function startAtoll(a?:Atoll){setEditType('atoll');setEditId(a?.id||'');setName(a?.display_name||'');setCode(a?.code||'');setPrefix(a?.administrative_prefix||'');setSortOrder(a?.sort_order||0);}
 function startIsland(i?:Island){setEditType('island');setEditId(i?.id||'');setName(i?.display_name||'');setReference(i?.reference_code||'');setRange(i?.administrative_code_range||'');setKind(i?.location_kind||'ISLAND');setSortOrder(i?.sort_order||0);setParentAtoll(i?.atoll_id||'');}
 function startUnit(u?:Unit){setEditType('unit');setEditId(u?.id||'');setName(u?.display_name||'');setReference(u?.reference_code||'');setUnitType(u?.unit_type||'WARD');setSortOrder(u?.sort_order||0);setParentAtoll(u?.atoll_id||'');setParentIsland(u?.island_id||'');setParentUnit(u?.parent_id||'');}
 async function save(){if(!editType)return;if(!name.trim())return setMessage('Display name is required.');setBusy(true);try{if(editId){await call({action:'update',type:editType,id:editId,displayName:name.trim(),canonicalName:name.trim(),code:editType==='atoll'?code:undefined,officialName:editType==='atoll'?name.trim():undefined,administrativePrefix:editType==='atoll'?prefix:undefined,referenceCode:editType!=='atoll'?reference:undefined,administrativeCodeRange:editType==='island'?range:undefined,locationKind:editType==='island'?kind:undefined,unitType:editType==='unit'?unitType:undefined,parentId:editType==='unit'?parentUnit||null:undefined,sortOrder});}else if(editType==='atoll'){await call({action:'create_atoll',code,displayName:name.trim(),officialName:name.trim(),administrativePrefix:prefix,sortOrder});}else if(editType==='island'){await call({action:'create_island',atollId:parentAtoll,displayName:name.trim(),canonicalName:name.trim(),referenceCode:reference,administrativeCodeRange:range,locationKind:kind,sortOrder});}else{await call({action:'create_unit',atollId:parentAtoll,islandId:parentIsland,parentId:parentUnit||null,displayName:name.trim(),canonicalName:name.trim(),referenceCode:reference,unitType,sortOrder});}setMessage(editId?'Location updated.':'Location added.');resetForm();await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to save location.');}finally{setBusy(false);}}
 async function patch(type:'atoll'|'island'|'unit',id:string,values:Record<string,unknown>){setBusy(true);try{await call({action:'update',type,id,...values});await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to update location.');}finally{setBusy(false);}}
 async function remove(type:'atoll'|'island'|'unit',id:string,label:string){if(!window.confirm(`Delete ${label}? Used locations cannot be deleted and should be disabled instead.`))return;setBusy(true);try{await call({action:'delete',type,id});setMessage(`${label} deleted.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to delete location.');}finally{setBusy(false);}}
 const filteredAtolls=useMemo(()=>atolls.filter(a=>`${a.code} ${a.display_name}`.toLowerCase().includes(query.toLowerCase())),[atolls,query]);
 const filteredIslands=useMemo(()=>islands.filter(i=>i.display_name.toLowerCase().includes(query.toLowerCase())),[islands,query]);
 const filteredUnits=useMemo(()=>units.filter(u=>u.display_name.toLowerCase().includes(query.toLowerCase())),[units,query]);
 const islandChoices=useMemo(()=>islands.filter(i=>!parentAtoll||i.atoll_id===parentAtoll),[islands,parentAtoll]);
 const parentUnitChoices=useMemo(()=>units.filter(u=>u.island_id===parentIsland&&u.id!==editId),[units,parentIsland,editId]);
 const atollName=(id:string)=>atolls.find(a=>a.id===id)?.display_name||'Unknown atoll';const islandName=(id:string)=>islands.find(i=>i.id===id)?.display_name||'Unknown island';
 return <main className="shell">
  <header className="topbar"><div><a className="brand" href="/">FixIt</a><p className="tagline">Admin Location Management</p></div><div className="actions"><a className="secondary" href="/admin">Admin Home</a></div></header>
  <AdminNav/>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">LOCATION CONTROLS</p><h2>Maldives service locations</h2></div><span className="pill">{atolls.length} atolls · {islands.length} islands/cities · {units.length} areas</span></div><p className="localNotice">Disable locations already in use instead of deleting them. Disabled or non-serviceable locations are removed from new customer/provider selection.</p>{message?<p className="formMessage" role="status">{message}</p>:null}<div className="actions"><button className={tab==='ATOLLS'?'primary':'secondary'} onClick={()=>setTab('ATOLLS')}>Atolls</button><button className={tab==='ISLANDS'?'primary':'secondary'} onClick={()=>setTab('ISLANDS')}>Islands & Cities</button><button className={tab==='UNITS'?'primary':'secondary'} onClick={()=>setTab('UNITS')}>Wards & Areas</button><button className="secondary" onClick={()=>void load()} disabled={busy}>Refresh</button></div><div className="formGrid"><label className="full">Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search location name or atoll code"/></label></div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">ADD / EDIT</p><h2>{editType?`${editId?'Edit':'Add'} ${editType}`:'Choose Add or Edit'}</h2></div><div className="actions"><button className="secondary" onClick={()=>startAtoll()}>Add Atoll</button><button className="secondary" onClick={()=>startIsland()}>Add Island/City</button><button className="secondary" onClick={()=>startUnit()}>Add Ward/Area</button></div></div>{editType?<div className="formGrid">
   {editType!=='atoll'?<label>Atoll<select value={parentAtoll} disabled={Boolean(editId)} onChange={e=>{setParentAtoll(e.target.value);setParentIsland('');setParentUnit('');}}><option value="">Select atoll</option>{atolls.map(a=><option key={a.id} value={a.id}>{a.code} — {a.display_name}</option>)}</select></label>:<label>Atoll code<input value={code} onChange={e=>setCode(e.target.value)} placeholder="e.g. HA"/></label>}
   {editType==='unit'?<label>Island / City<select value={parentIsland} disabled={Boolean(editId)} onChange={e=>{setParentIsland(e.target.value);setParentUnit('');}}><option value="">Select island/city</option>{islandChoices.map(i=><option key={i.id} value={i.id}>{i.display_name}</option>)}</select></label>:null}
   <label>Display name<input value={name} onChange={e=>setName(e.target.value)}/></label>
   {editType==='atoll'?<label>Administrative prefix<input value={prefix} onChange={e=>setPrefix(e.target.value)} placeholder="A / H,T / etc."/></label>:null}
   {editType==='island'?<><label>Type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="ISLAND">Island</option><option value="CITY">City</option></select></label><label>Reference code<input value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="full">Administrative code range<input value={range} onChange={e=>setRange(e.target.value)}/></label></>:null}
   {editType==='unit'?<><label>Area type<select value={unitType} onChange={e=>setUnitType(e.target.value)}><option value="WARD">Ward</option><option value="DISTRICT">District</option><option value="PHASE">Phase</option><option value="ISLAND_AREA">Island Area</option><option value="ELECTORAL_AREA">Electoral Area</option><option value="AREA">Area</option></select></label><label>Reference code<input value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Parent area <span className="muted">(optional)</span><select value={parentUnit} onChange={e=>setParentUnit(e.target.value)}><option value="">No parent</option>{parentUnitChoices.map(u=><option key={u.id} value={u.id}>{u.display_name}</option>)}</select></label></>:null}
   <label>Sort order<input type="number" min="0" value={sortOrder} onChange={e=>setSortOrder(Number(e.target.value||0))}/></label><div className="actions"><button className="primary" onClick={()=>void save()} disabled={busy}>{busy?'Saving…':'Save'}</button><button className="secondary" onClick={resetForm}>Cancel</button></div>
  </div>:<p className="muted">Use the buttons above to add a location, or Edit from the list below.</p>}</section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">CATALOGUE</p><h2>{tab==='ATOLLS'?'Atolls':tab==='ISLANDS'?'Islands & Cities':'Wards, Districts & Areas'}</h2></div></div><div className="jobList">
   {tab==='ATOLLS'?filteredAtolls.map(a=><div className="jobCard" key={a.id}><div className="panelHeader"><div><strong>{a.code} · {a.display_name}</strong><p className="jobDescription">Prefix: {a.administrative_prefix||'—'} · {a.usage.islands} islands/cities · {a.usage.requests} requests</p></div><span className="pill">{a.is_active&&a.is_serviceable?'ACTIVE':'DISABLED'}</span></div><div className="actions"><button className="secondary" onClick={()=>startAtoll(a)}>Edit</button><button className="secondary" onClick={()=>void patch('atoll',a.id,{isActive:!a.is_active})}>{a.is_active?'Disable':'Enable'}</button><button className="secondary" onClick={()=>void patch('atoll',a.id,{isServiceable:!a.is_serviceable})}>{a.is_serviceable?'Not Serviceable':'Serviceable'}</button><button className="secondary" onClick={()=>void remove('atoll',a.id,a.display_name)}>Delete</button></div></div>):null}
   {tab==='ISLANDS'?filteredIslands.map(i=><div className="jobCard" key={i.id}><div className="panelHeader"><div><strong>{i.display_name} <span className="muted">({i.location_kind})</span></strong><p className="jobDescription">{atollName(i.atoll_id)} · {i.reference_code||i.administrative_code_range||'No code'} · {i.usage.providers} provider areas · {i.usage.requests} requests · {i.usage.units} sub-areas</p></div><span className="pill">{i.is_active&&i.is_serviceable?'ACTIVE':'DISABLED'}</span></div><div className="actions"><button className="secondary" onClick={()=>startIsland(i)}>Edit</button><button className="secondary" onClick={()=>void patch('island',i.id,{isActive:!i.is_active})}>{i.is_active?'Disable':'Enable'}</button><button className="secondary" onClick={()=>void patch('island',i.id,{isServiceable:!i.is_serviceable})}>{i.is_serviceable?'Not Serviceable':'Serviceable'}</button><button className="secondary" onClick={()=>void remove('island',i.id,i.display_name)}>Delete</button></div></div>):null}
   {tab==='UNITS'?filteredUnits.map(u=><div className="jobCard" key={u.id}><div className="panelHeader"><div><strong>{u.display_name} <span className="muted">({u.unit_type})</span></strong><p className="jobDescription">{atollName(u.atoll_id)} · {islandName(u.island_id)} · {u.reference_code||'No code'} · {u.usage.providers} provider areas · {u.usage.requests} requests</p></div><span className="pill">{u.is_active&&u.is_serviceable?'ACTIVE':'DISABLED'}</span></div><div className="actions"><button className="secondary" onClick={()=>startUnit(u)}>Edit</button><button className="secondary" onClick={()=>void patch('unit',u.id,{isActive:!u.is_active})}>{u.is_active?'Disable':'Enable'}</button><button className="secondary" onClick={()=>void patch('unit',u.id,{isServiceable:!u.is_serviceable})}>{u.is_serviceable?'Not Serviceable':'Serviceable'}</button><button className="secondary" onClick={()=>void remove('unit',u.id,u.display_name)}>Delete</button></div></div>):null}
  </div></section>
  <footer className="footer"><span>FixIt Maldives</span><span>Admin Location Controls</span></footer>
 </main>;
}
