'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { supabase } from '../../../../lib/supabaseClient';
import AppModeSwitch from '../../../AppModeSwitch';
import { useProviderMode } from '../../useProviderMode';

const MARKET_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-marketplace';
type Job={ticket_number:string;service_name:string;service_location_text:string;preferred_date?:string|null;problem_description?:string|null;status:string;customer?:{name?:string|null;phone?:string|null}|null;inspection?:{scheduled_start?:string|null;duration_minutes?:number|null;status?:string|null}|null};
export default function ProviderJobDetailPage(){
 const mode=useProviderMode(true);const params=useParams<{ticket:string}>();const ticket=decodeURIComponent(String(params?.ticket||''));const[job,setJob]=useState<Job|null>(null);const[busy,setBusy]=useState(true);const[message,setMessage]=useState('Loading customer job…');
 useEffect(()=>{if(mode.ready)void load();},[mode.ready,ticket]);
 async function load(){setBusy(true);try{const{data}=await supabase.auth.getSession();if(!data.session)throw new Error('Sign in required');const r=await fetch(MARKET_URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({action:'dashboard'})});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to load job');const found=(p.requests||[]).find((x:Job)=>x.ticket_number===ticket&&['ACCEPTED','INSPECTION_SCHEDULED','IN_PROGRESS','COMPLETED'].includes(x.status));if(!found)throw new Error('This customer job is not assigned to you.');setJob(found);setMessage('');}catch(e){setJob(null);setMessage(e instanceof Error?e.message:'Unable to load customer job.');}finally{setBusy(false);}}
 if(mode.loading||busy)return <main className="providerModePage"><div className="providerModeShell"><div className="providerModeCard">Loading customer job…</div></div></main>;
 return <main className="providerModePage"><div className="providerModeShell"><header className="providerModeTop"><div><span className="modeBadge provider"><span className="modeDot provider"/>Provider</span><h1>{job?.service_name||'Customer Job'}</h1><p>{ticket}</p></div><AppModeSwitch mode="provider" compact/></header>{job?<><section className="providerModeCard"><div className="providerSectionHead"><div><h2>Customer & job</h2><p>Customer details are visible because this request has been accepted.</p></div><span className="modeBadge provider">{job.status.replaceAll('_',' ')}</span></div><div className="providerJobDetailGrid"><div><small>Customer</small><strong>{job.customer?.name||'Customer'}</strong></div><div><small>Location</small><strong>{job.service_location_text}</strong></div><div><small>Preferred date</small><strong>{job.preferred_date?new Date(job.preferred_date+'T00:00:00').toLocaleDateString():'Not specified'}</strong></div><div><small>Scheduled visit</small><strong>{job.inspection?.scheduled_start?new Date(job.inspection.scheduled_start).toLocaleString():'Not scheduled'}</strong></div></div>{job.problem_description?<div className="providerJobProblem"><small>Customer request</small><p>{job.problem_description}</p></div>:null}<div className="providerSetupActions"><a className="secondary" href="/provider/jobs">Back to requests</a><a className="secondary" href="/provider/calendar">Calendar</a><a className="primary" href={`/provider/messages?ticket=${encodeURIComponent(ticket)}`}>Message Customer</a></div></section><section className="providerModeCard"><div className="providerSectionHead"><div><h2>Next action</h2><p>{job.status==='ACCEPTED'&&!job.inspection?.scheduled_start?'Contact the customer and agree on the next visit or inspection time.':job.status==='COMPLETED'?'This job is completed. Customer review and earnings updates appear in Provider Today.':'Continue the accepted job workflow and keep the customer updated through Messages.'}</p></div></div></section></>:<section className="providerModeCard"><div className="providerEmptyState"><h3>Job unavailable</h3><p>{message}</p><a className="primary" href="/provider/jobs">Customer Requests</a></div></section>}</div></main>;
}
