'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { supabase } from '../../../../lib/supabaseClient';
import AppModeSwitch from '../../../AppModeSwitch';
import { useProviderMode } from '../../useProviderMode';

const MARKET_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-marketplace';
const CONFIRM_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-confirmations';
const FLOW_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-job-flow';
type Job={ticket_number:string;service_name:string;service_location_text:string;preferred_date?:string|null;problem_description?:string|null;status:string;customer?:{name?:string|null;phone?:string|null}|null;inspection?:{scheduled_start?:string|null}|null;completion?:{status?:string|null}|null};
const providerStages=['ACCEPTED','CONFIRMED','IN PROGRESS','COMPLETED','CUSTOMER CONFIRMED'];
function label(job:Job,confirmed:boolean){if(job.status==='COMPLETED'&&job.completion?.status==='CONFIRMED')return'CUSTOMER CONFIRMED';if(job.status==='COMPLETED')return'COMPLETED';if(job.status==='IN_PROGRESS'||job.status==='INSPECTION_SCHEDULED')return'IN PROGRESS';if(job.status==='ACCEPTED'&&confirmed)return'CONFIRMED';return'ACCEPTED';}
export default function ProviderJobDetailPage(){
 const mode=useProviderMode(true);const params=useParams<{ticket:string}>();const ticket=decodeURIComponent(String(params?.ticket||''));const[job,setJob]=useState<Job|null>(null);const[confirmed,setConfirmed]=useState(false);const[schedule,setSchedule]=useState('');const[busy,setBusy]=useState(true);const[message,setMessage]=useState('Loading customer job…');
 useEffect(()=>{if(mode.ready)void load();},[mode.ready,ticket]);
 async function session(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return null;}return data.session;}
 async function load(){setBusy(true);try{const s=await session();if(!s)return;const headers={'Content-Type':'application/json',Authorization:`Bearer ${s.access_token}`};const[mr,cr]=await Promise.all([fetch(MARKET_URL,{method:'POST',headers,body:JSON.stringify({action:'dashboard'})}),fetch(CONFIRM_URL,{method:'POST',headers,body:'{}'})]);const mp=await mr.json();const cp=await cr.json();if(!mr.ok)throw new Error(mp?.error||'Unable to load job');const found=(mp.requests||[]).find((x:Job)=>x.ticket_number===ticket&&['ACCEPTED','INSPECTION_SCHEDULED','IN_PROGRESS','COMPLETED'].includes(x.status));if(!found)throw new Error('This customer job is not assigned to you.');setJob(found);setConfirmed(Boolean((cp.confirmedTickets||[]).includes(ticket)));setMessage('');}catch(e){setJob(null);setMessage(e instanceof Error?e.message:'Unable to load customer job.');}finally{setBusy(false);}}
 async function act(action:'schedule'|'start'|'complete'){setBusy(true);try{const s=await session();if(!s)return;const r=await fetch(FLOW_URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.access_token}`},body:JSON.stringify({action,ticketNumber:ticket,scheduledStart:schedule||undefined})});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to update job');setMessage(action==='schedule'?'Visit time saved. Job is now In Progress.':action==='start'?'Work started.': 'Job completed. Waiting for customer confirmation.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to update job.');}finally{setBusy(false);}}
 if(mode.loading||busy&&!job)return <main className="providerModePage"><div className="providerModeShell"><div className="providerModeCard">Loading customer job…</div></div></main>;
 const stage=job?label(job,confirmed):'';const stageIndex=Math.max(0,providerStages.indexOf(stage));const contactUnlocked=stage!=='ACCEPTED';const isScheduledInternal=job?.status==='INSPECTION_SCHEDULED';const isWorkingInternal=job?.status==='IN_PROGRESS';
 return <main className="providerModePage"><div className="providerModeShell"><header className="providerModeTop"><div><span className="modeBadge provider"><span className="modeDot provider"/>Provider</span><h1>{job?.service_name||'Customer Job'}</h1><p>{ticket}</p></div><AppModeSwitch mode="provider" compact/></header>{job?<><section className="providerModeCard"><div className="providerSectionHead"><div><h2>Job progress</h2><p>Accepted → Confirmed → In Progress → Completed → Customer Confirmed</p></div><span className="modeBadge provider">{stage}</span></div><div className="providerJobDetailGrid">{providerStages.map((item,index)=><div key={item}><small>{index<stageIndex?'✓ Done':index===stageIndex?'Current':'Next'}</small><strong>{item}</strong></div>)}</div></section>
 <section className="providerModeCard"><div className="providerSectionHead"><div><h2>Customer & job</h2><p>{contactUnlocked?'Customer contact is available because the customer confirmed the provider.':'Customer contact unlocks after confirmation.'}</p></div></div><div className="providerJobDetailGrid"><div><small>Customer</small><strong>{job.customer?.name||'Customer'}</strong></div><div><small>Phone</small><strong>{contactUnlocked?(job.customer?.phone||'Not provided'):'Hidden until confirmed'}</strong></div><div><small>Location</small><strong>{job.service_location_text}</strong></div><div><small>Preferred date</small><strong>{job.preferred_date?new Date(job.preferred_date+'T00:00:00').toLocaleDateString():'Not specified'}</strong></div>{job.inspection?.scheduled_start?<div><small>Visit time</small><strong>{new Date(job.inspection.scheduled_start).toLocaleString()}</strong></div>:null}</div>{job.problem_description?<div className="providerJobProblem"><small>Customer request</small><p>{job.problem_description}</p></div>:null}<div className="providerSetupActions"><a className="secondary" href="/provider/jobs">Back</a>{contactUnlocked?<a className="secondary" href={`/provider/messages?ticket=${encodeURIComponent(ticket)}`}>Message Customer</a>:null}</div></section>
 <section className="providerModeCard"><div className="providerSectionHead"><div><h2>Next action</h2><p>{stage==='ACCEPTED'?'Waiting for the customer to confirm you.':stage==='CONFIRMED'?'Choose a visit time to begin this job.':stage==='IN PROGRESS'&&isScheduledInternal?'The visit is arranged. Start the work when ready.':stage==='IN PROGRESS'&&isWorkingInternal?'Work is active. Mark it complete when finished.':stage==='COMPLETED'?'Waiting for the customer to confirm completion.':'Job closed. No further provider action is required.'}</p></div></div>{stage==='CONFIRMED'?<div className="providerSetupActions"><input type="datetime-local" value={schedule} onChange={e=>setSchedule(e.target.value)}/><button className="primary" disabled={busy||!schedule} onClick={()=>void act('schedule')}>Start / Schedule Work</button></div>:null}{stage==='IN PROGRESS'&&isScheduledInternal?<button className="primary" disabled={busy} onClick={()=>void act('start')}>Start Work</button>:null}{stage==='IN PROGRESS'&&isWorkingInternal?<button className="primary" disabled={busy} onClick={()=>void act('complete')}>Mark Complete</button>:null}{stage==='COMPLETED'?<span className="modeBadge customer">Waiting for Customer</span>:null}{stage==='CUSTOMER CONFIRMED'?<span className="modeBadge customer">Closed</span>:null}</section><p className="muted" role="status">{message}</p></>:<section className="providerModeCard"><div className="providerEmptyState"><h3>Job unavailable</h3><p>{message}</p><a className="primary" href="/provider/jobs">Customer Requests</a></div></section>}</div></main>;
}
