'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../lib/supabaseClient';
import './provider-dashboard.css';

const PROVIDER_JOBS_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-jobs';
const MESSAGE_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/request-messages';
type JobStatus='NEW'|'ACCEPTED'|'PROCESSING'|'COMPLETED';
type Job={ticket_number:string;service_name:string;service_location_text:string;preferred_date:string;problem_description:string;status:JobStatus;assigned_provider_label?:string|null;created_at:string;updated_at:string};
type ChatMessage={id:string;sender_role:string;sender_label?:string|null;message_text:string;created_at:string};
type Profile={role:string;provider_approved:boolean;full_name?:string|null};
type MatchInfo={serviceArea?:string;serviceAreaCount?:number;categoryCodes?:string[];availability?:string;normalizedLifecycle?:boolean;exactLocationMatching?:boolean};
const statusLabels:Record<JobStatus,string>={NEW:'New Jobs',ACCEPTED:'Accepted',PROCESSING:'Processing',COMPLETED:'Completed'};

export default function ProviderPage(){
 const[profile,setProfile]=useState<Profile|null>(null);const[providerLabel,setProviderLabel]=useState('');const[jobs,setJobs]=useState<Job[]>([]);const[matchInfo,setMatchInfo]=useState<MatchInfo>({});const[message,setMessage]=useState('Checking provider account…');const[loading,setLoading]=useState(false);const[busyTicket,setBusyTicket]=useState('');const[filter,setFilter]=useState<'ALL'|JobStatus>('ALL');const[selectedTicket,setSelectedTicket]=useState('');const[chat,setChat]=useState<ChatMessage[]>([]);const[chatText,setChatText]=useState('');const[chatBusy,setChatBusy]=useState(false);
 useEffect(()=>{(async()=>{const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return;}const{data:p}=await supabase.from('auth_profiles').select('role,provider_approved,full_name').eq('user_id',data.session.user.id).maybeSingle();setProfile(p as Profile|null);if(p?.role!=='PROVIDER')setMessage('This account is not a Provider account.');else if(!p.provider_approved)setMessage('Complete your provider profile and submit it for Admin approval before accepting jobs.');else{setMessage('Provider account ready.');setTimeout(()=>loadJobs(),0);}})();},[]);
 const visibleJobs=useMemo(()=>filter==='ALL'?jobs:jobs.filter(j=>j.status===filter),[jobs,filter]);
 const counts=useMemo(()=>({NEW:jobs.filter(j=>j.status==='NEW').length,ACCEPTED:jobs.filter(j=>j.status==='ACCEPTED').length,PROCESSING:jobs.filter(j=>j.status==='PROCESSING').length,COMPLETED:jobs.filter(j=>j.status==='COMPLETED').length}),[jobs]);
 const activeJobs=counts.ACCEPTED+counts.PROCESSING;
 async function jwt(){const{data}=await supabase.auth.getSession();return data.session?.access_token||'';}
 async function callProvider(body:Record<string,unknown>){const t=await jwt();const response=await fetch(PROVIDER_JOBS_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload?.error||'Provider request failed');return payload;}
 async function loadJobs(){if(!profile?.provider_approved&&profile)return;setLoading(true);try{const payload=await callProvider({action:'list'});setProviderLabel(payload.provider?.label||profile?.full_name||'Provider');setMatchInfo({serviceArea:payload.provider?.serviceArea,serviceAreaCount:Number(payload.provider?.serviceAreaCount||0),categoryCodes:payload.provider?.categoryCodes||[],availability:payload.provider?.availability,normalizedLifecycle:Boolean(payload.provider?.normalizedLifecycle),exactLocationMatching:Boolean(payload.provider?.exactLocationMatching)});setJobs(payload.requests||[]);setMessage(`${payload.requests?.length||0} matched request(s) loaded.`);}catch(error){setJobs([]);setMessage(error instanceof Error?error.message:'Unable to load jobs.');}finally{setLoading(false);}}
 async function transition(job:Job){const next=job.status==='NEW'?'ACCEPTED':job.status==='ACCEPTED'?'PROCESSING':job.status==='PROCESSING'?'COMPLETED':null;if(!next)return;setBusyTicket(job.ticket_number);try{await callProvider({action:'transition',ticketNumber:job.ticket_number,targetStatus:next});await loadJobs();setMessage(`${job.ticket_number} moved to ${statusLabels[next]}.`);}catch(error){setMessage(error instanceof Error?error.message:'Unable to update job.');}finally{setBusyTicket('');}}
 async function loadMessages(ticket:string,send=false){if(send&&!chatText.trim())return;setSelectedTicket(ticket);setChatBusy(true);try{const t=await jwt();const response=await fetch(MESSAGE_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify({action:send?'send':'list',ticketNumber:ticket,message:chatText.trim()})});const payload=await response.json();if(!response.ok)throw new Error(payload?.error||'Unable to process messages');setChat(payload.messages||[]);if(send)setChatText('');}catch(error){setMessage(error instanceof Error?error.message:'Unable to process messages.');}finally{setChatBusy(false);}}
 async function signOut(){await supabase.auth.signOut();window.location.href='/login';}
 function nextAction(job:Job){if(job.status==='NEW')return'Accept Job';if(job.status==='ACCEPTED')return'Start Processing';if(job.status==='PROCESSING')return'Mark Completed';return'';}
 function statusClass(status:JobStatus){if(status==='COMPLETED')return'providerStatusChip completed';if(status==='PROCESSING')return'providerStatusChip processing';if(status==='ACCEPTED')return'providerStatusChip accepted';return'providerStatusChip';}
 return <main className="shell providerDashboard">
  <header className="topbar"><div><a className="brand" href="/">FixIt</a><p className="tagline">Provider Dashboard</p></div><div className="actions"><a className="secondary" href="/provider/onboarding">Profile</a><a className="secondary" href="/">Customer Home</a><button className="secondary" onClick={signOut}>Sign Out</button></div></header>

  <section className="providerHero">
   <div className="providerHeroCard"><p className="eyebrow">PROVIDER OPERATIONS</p><h1>{providerLabel||profile?.full_name||'Your work dashboard'}</h1><p>See matched jobs, move accepted work through the lifecycle, and keep customer communication in one place.</p><div className="providerQuickActions"><button className="primary" onClick={()=>{setFilter('NEW');document.getElementById('provider-jobs')?.scrollIntoView({behavior:'smooth'});}}>View New Jobs</button><a className="secondary" href="/provider/onboarding">Manage Availability & Areas</a><button className="secondary" onClick={()=>void loadJobs()} disabled={!profile?.provider_approved||loading}>{loading?'Refreshing…':'Refresh Dashboard'}</button></div>{message?<p className="formMessage" role="status">{message}</p>:null}</div>
   <aside className="providerSideCard"><div className="providerSideRow"><span>Availability</span><strong>{matchInfo.availability||'Not set'}</strong></div><div className="providerSideRow"><span>Service areas</span><strong>{matchInfo.serviceAreaCount||0}</strong></div><div className="providerSideRow"><span>Service groups</span><strong>{matchInfo.categoryCodes?.length||0}</strong></div><div className="providerSideRow"><span>Matching</span><strong>{matchInfo.exactLocationMatching?'Exact location IDs':'Profile setup needed'}</strong></div><div className="providerSideRow"><span>Active jobs</span><strong>{activeJobs}</strong></div></aside>
  </section>

  <section className="providerPipeline"><div className="panelHeader"><div><p className="eyebrow">JOB PIPELINE</p><h2>Work at a glance</h2></div><button className={filter==='ALL'?'primary':'secondary'} onClick={()=>setFilter('ALL')}>All {jobs.length}</button></div><div className="providerPipelineGrid">{(['NEW','ACCEPTED','PROCESSING','COMPLETED'] as JobStatus[]).map(status=><button type="button" key={status} className={filter===status?'pipelineCard active':'pipelineCard'} onClick={()=>setFilter(status)}><span>{statusLabels[status]}</span><strong>{counts[status]}</strong></button>)}</div></section>

  <section className="providerJobsPanel" id="provider-jobs"><div className="providerJobsHeader"><div><p className="eyebrow">{filter==='ALL'?'ALL MATCHED JOBS':statusLabels[filter]}</p><h2>{filter==='NEW'?'Requests waiting for you':filter==='ACCEPTED'?'Accepted work':filter==='PROCESSING'?'Jobs in progress':filter==='COMPLETED'?'Completed work':'Your matched service requests'}</h2><p className="localNotice">Eligibility is checked server-side against your active services, availability and canonical service areas.</p></div><div className="providerToolbar"><a className="secondary" href="/provider/onboarding">Coverage Settings</a><button className="secondary" onClick={()=>void loadJobs()} disabled={loading}>{loading?'Loading…':'Refresh'}</button></div></div>
   <div className="providerJobList">{visibleJobs.map(job=><article className="providerJobCard" key={job.ticket_number}><div className="providerJobTop"><div className="providerJobTitle"><strong>{job.service_name}</strong><small>{job.ticket_number}</small></div><span className={statusClass(job.status)}>{statusLabels[job.status]}</span></div><div className="providerJobMeta"><div className="providerMetaItem"><span>Location</span><strong>{job.service_location_text}</strong></div><div className="providerMetaItem"><span>Preferred Date</span><strong>{job.preferred_date}</strong></div><div className="providerMetaItem"><span>Assignment</span><strong>{job.assigned_provider_label||'Available to accept'}</strong></div></div><p className="providerProblem">{job.problem_description}</p><div className="providerJobActions">{job.status!=='COMPLETED'?<button className="primary" type="button" disabled={busyTicket===job.ticket_number} onClick={()=>void transition(job)}>{busyTicket===job.ticket_number?'Updating…':nextAction(job)}</button>:<span className="completedLabel">Completed</span>}<button className="secondary" type="button" disabled={job.status==='NEW'} onClick={()=>void loadMessages(job.ticket_number,false)}>{job.status==='NEW'?'Messages after acceptance':'Open Messages'}</button></div></article>)}{!visibleJobs.length?<div className="providerEmpty"><strong>No jobs in this stage</strong><span>{filter==='NEW'?'New matched requests will appear here automatically.':'Choose another stage or refresh the dashboard.'}</span></div>:null}</div>
  </section>

  {selectedTicket?<section className="providerMessages"><div className="providerJobsHeader"><div><p className="eyebrow">CUSTOMER COMMUNICATION</p><h2>{selectedTicket}</h2></div><div className="providerToolbar"><button className="secondary" onClick={()=>void loadMessages(selectedTicket,false)} disabled={chatBusy}>Refresh</button><button className="secondary" onClick={()=>{setSelectedTicket('');setChat([]);}}>Close</button></div></div><div className="providerMessageList">{chat.map(m=><div className="providerMessage" key={m.id}><strong>{m.sender_label||m.sender_role}</strong><p>{m.message_text}</p><small>{new Date(m.created_at).toLocaleString()}</small></div>)}{!chat.length?<div className="providerEmpty"><strong>No messages yet</strong><span>Start the conversation with the customer below.</span></div>:null}</div><div className="providerAccessRow"><input placeholder="Message the customer" value={chatText} onChange={e=>setChatText(e.target.value)}/><button className="primary" type="button" disabled={chatBusy||!chatText.trim()} onClick={()=>void loadMessages(selectedTicket,true)}>Send Message</button></div></section>:null}

  <footer className="footer"><span>FixIt Maldives</span><span>{matchInfo.normalizedLifecycle?'Normalized job lifecycle':'Provider operations'}</span></footer>
 </main>;
}
