'use client';

import { useEffect, useMemo, useState } from 'react';

const PROVIDER_JOBS_URL = 'https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-jobs';
const MESSAGE_URL = 'https://yzlhlilxiszefneshatm.supabase.co/functions/v1/request-messages';

type Job = { ticket_number:string; service_name:string; service_location_text:string; preferred_date:string; problem_description:string; status:'NEW'|'ACCEPTED'|'PROCESSING'|'COMPLETED'; assigned_provider_label?:string|null; created_at:string; updated_at:string };
type ChatMessage = { id:string; sender_role:string; sender_label?:string|null; message_text:string; created_at:string };
const labels:Record<Job['status'],string>={NEW:'New',ACCEPTED:'Accepted',PROCESSING:'Processing',COMPLETED:'Completed'};

export default function ProviderPage(){
 const[accessToken,setAccessToken]=useState(''); const[providerLabel,setProviderLabel]=useState(''); const[jobs,setJobs]=useState<Job[]>([]); const[message,setMessage]=useState(''); const[loading,setLoading]=useState(false); const[busyTicket,setBusyTicket]=useState(''); const[filter,setFilter]=useState<'ALL'|Job['status']>('ALL'); const[selectedTicket,setSelectedTicket]=useState(''); const[chat,setChat]=useState<ChatMessage[]>([]); const[chatText,setChatText]=useState(''); const[chatBusy,setChatBusy]=useState(false);
 useEffect(()=>{const saved=window.localStorage.getItem('fixit:provider-access-token');if(saved)setAccessToken(saved);},[]);
 const visibleJobs=useMemo(()=>filter==='ALL'?jobs:jobs.filter(j=>j.status===filter),[jobs,filter]);
 async function callProvider(body:Record<string,unknown>){const response=await fetch(PROVIDER_JOBS_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accessToken,...body})});const payload=await response.json();if(!response.ok)throw new Error(payload?.error||'Provider request failed');return payload;}
 async function loadJobs(){if(!accessToken.trim())return setMessage('Enter the provider access code.');setLoading(true);setMessage('');try{const payload=await callProvider({action:'list'});window.localStorage.setItem('fixit:provider-access-token',accessToken.trim());setProviderLabel(payload.provider?.label||'Provider');setJobs(payload.requests||[]);setMessage(`${payload.requests?.length||0} request(s) loaded.`);}catch(error){setJobs([]);setProviderLabel('');setMessage(error instanceof Error?error.message:'Unable to load jobs.');}finally{setLoading(false);}}
 async function transition(job:Job){const next=job.status==='NEW'?'ACCEPTED':job.status==='ACCEPTED'?'PROCESSING':job.status==='PROCESSING'?'COMPLETED':null;if(!next)return;setBusyTicket(job.ticket_number);setMessage('');try{await callProvider({action:'transition',ticketNumber:job.ticket_number,targetStatus:next});await loadJobs();setMessage(`${job.ticket_number} moved to ${labels[next]}.`);}catch(error){setMessage(error instanceof Error?error.message:'Unable to update job.');}finally{setBusyTicket('');}}
 async function loadMessages(ticket:string,send=false){if(!accessToken.trim())return setMessage('Provider access required.');if(send&&!chatText.trim())return;setSelectedTicket(ticket);setChatBusy(true);try{const response=await fetch(MESSAGE_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'provider',action:send?'send':'list',ticketNumber:ticket,accessToken:accessToken.trim(),message:chatText.trim()})});const payload=await response.json();if(!response.ok)throw new Error(payload?.error||'Unable to process messages');setChat(payload.messages||[]);if(send)setChatText('');}catch(error){setMessage(error instanceof Error?error.message:'Unable to process messages.');}finally{setChatBusy(false);}}
 function clearAccess(){window.localStorage.removeItem('fixit:provider-access-token');setAccessToken('');setJobs([]);setProviderLabel('');setSelectedTicket('');setChat([]);setMessage('Provider access cleared.');}
 return <main className="shell">
  <header className="topbar"><div><a className="brand" href="/">FixIt</a><p className="tagline">Provider Operations</p></div><div className="actions"><a className="secondary" href="/admin">Admin</a><a className="secondary" href="/">Customer</a></div></header>
  <section className="panel providerLogin"><div className="panelHeader"><div><p className="eyebrow">PROVIDER</p><h2>Job Operations</h2></div>{providerLabel?<span className="pill">{providerLabel}</span>:<span className="pill">Secure MVP</span>}</div><div className="providerAccessRow"><input type="password" placeholder="Provider access code" value={accessToken} onChange={e=>setAccessToken(e.target.value)}/><button className="primary" type="button" onClick={loadJobs} disabled={loading}>{loading?'Loading…':'Open Job Queue'}</button>{providerLabel?<button className="secondary" type="button" onClick={clearAccess}>Sign Out</button>:null}</div>{message?<p className="formMessage" role="status">{message}</p>:null}<p className="localNotice">Temporary secure provider access for MVP testing. Full phone/OTP authentication will replace it.</p></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">LIVE QUEUE</p><h2>Service Requests</h2></div><button className="secondary" type="button" onClick={loadJobs} disabled={!accessToken||loading}>Refresh</button></div><div className="filterRow">{(['ALL','NEW','ACCEPTED','PROCESSING','COMPLETED'] as const).map(item=><button key={item} className={filter===item?'filterChip active':'filterChip'} onClick={()=>setFilter(item)} type="button">{item==='ALL'?'All':labels[item]}</button>)}</div><div className="jobList">{visibleJobs.map(job=>{const nextLabel=job.status==='NEW'?'Accept Job':job.status==='ACCEPTED'?'Start Processing':job.status==='PROCESSING'?'Mark Completed':null;return <article className="jobCard" key={job.ticket_number}><div className="jobTop"><div><strong className="ticket">{job.ticket_number}</strong><span className="muted">{job.service_name}</span></div><span className="pill">{labels[job.status]}</span></div><div className="jobMeta"><span><b>Location:</b> {job.service_location_text}</span><span><b>Preferred:</b> {job.preferred_date}</span>{job.assigned_provider_label?<span><b>Assigned:</b> {job.assigned_provider_label}</span>:null}</div><p className="jobDescription">{job.problem_description}</p><div className="actions">{nextLabel?<button className="primary" type="button" disabled={busyTicket===job.ticket_number} onClick={()=>transition(job)}>{busyTicket===job.ticket_number?'Updating…':nextLabel}</button>:<span className="completedLabel">Job completed</span>}<button className="secondary" type="button" onClick={()=>loadMessages(job.ticket_number,false)}>Messages</button></div></article>;})}{!visibleJobs.length?<div className="emptyQueue">No requests to show in this filter.</div>:null}</div></section>
  {selectedTicket?<section className="panel"><div className="panelHeader"><div><p className="eyebrow">COMMUNICATION</p><h2>{selectedTicket} Messages</h2></div><button className="secondary" onClick={()=>loadMessages(selectedTicket,false)} disabled={chatBusy}>Refresh</button></div><div className="jobList">{chat.map(m=><div className="jobCard" key={m.id}><strong>{m.sender_label||m.sender_role}</strong><p className="jobDescription">{m.message_text}</p><span className="muted">{new Date(m.created_at).toLocaleString()}</span></div>)}{!chat.length?<div className="emptyQueue">No messages yet.</div>:null}</div><div className="providerAccessRow"><input placeholder="Message the customer" value={chatText} onChange={e=>setChatText(e.target.value)}/><button className="primary" type="button" disabled={chatBusy||!chatText.trim()} onClick={()=>loadMessages(selectedTicket,true)}>Send Message</button></div></section>:null}
  <footer className="footer"><span>FixIt Maldives</span><span>Provider Operations MVP</span></footer>
 </main>;
}
