'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../lib/supabaseClient';
import './provider-dashboard.css';
import './provider-marketplace.css';

const MARKET_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-marketplace';
const MESSAGE_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/request-messages';
type Stage='NEW'|'ACCEPTED'|'SCHEDULED'|'IN_PROGRESS'|'COMPLETED'|'NOT_SELECTED';
type ProviderResponse={status:string;provider_message?:string|null;responded_at?:string|null;selected_at?:string|null;provider_confirmed_at?:string|null};
type Inspection={id:string;preferred_slots:string[];scheduled_start?:string|null;duration_minutes?:number|null;status:string;provider_note?:string|null};
type Estimate={id:string;findings:string;recommended_work:string;estimated_minutes?:number|null;labour_amount:number|string;material_amount:number|string;total_amount:number|string;currency:string;status:string;customer_note?:string|null};
type Completion={id:string;work_performed:string[];labour_amount:number|string;material_amount:number|string;final_amount:number|string;currency:string;payment_note:string;status:string};
type Media={id:string;url?:string|null;media_type:string};
type Customer={name:string;phone?:string|null;email?:string|null};
type Job={id:string;ticket_number:string;service_name:string;service_category_code?:string|null;service_subcategory_code?:string|null;service_location_text:string;preferred_date:string;problem_description:string;urgency?:string|null;customer_notes?:string|null;status:string;assigned_provider_label?:string|null;assigned_provider_user_id?:string|null;created_at:string;accepted_at?:string|null;processing_at?:string|null;completed_at?:string|null;providerResponse?:ProviderResponse|null;inspection?:Inspection|null;estimate?:Estimate|null;completion?:Completion|null;media?:Media[];customer?:Customer|null};
type ChatMessage={id:string;sender_role:string;sender_label?:string|null;message_text:string;created_at:string};
type Profile={role:string;provider_approved:boolean;full_name?:string|null};
type ProviderInfo={label:string;availability?:string;serviceArea?:string};
const tabs:{key:Exclude<Stage,'NOT_SELECTED'>;label:string}[]=[{key:'NEW',label:'New'},{key:'ACCEPTED',label:'Accepted'},{key:'SCHEDULED',label:'Scheduled'},{key:'IN_PROGRESS',label:'In Progress'},{key:'COMPLETED',label:'Completed'}];
function pretty(v:string){return v.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());}
function ago(value:string){const seconds=Math.max(1,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return`${seconds}s ago`;const min=Math.floor(seconds/60);if(min<60)return`${min}m ago`;const hours=Math.floor(min/60);if(hours<24)return`${hours}h ago`;return`${Math.floor(hours/24)}d ago`;}
function when(value?:string|null){if(!value)return'Not set';const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString();}
function money(v:number|string|undefined,currency='MVR'){return`${currency} ${Number(v||0).toFixed(2)}`;}
function stageFor(job:Job):Stage|null{const response=job.providerResponse?.status;if(response==='NOT_SELECTED')return'NOT_SELECTED';if(response==='DECLINED'||response==='WITHDRAWN')return null;if(job.status==='COMPLETED')return'COMPLETED';if(job.status==='PROCESSING')return'IN_PROGRESS';const inspection=job.inspection?.status;if(inspection&&['ON_WAY','ARRIVED','INSPECTING','ESTIMATE_SENT'].includes(inspection))return'IN_PROGRESS';if(inspection&&['PROPOSED','SCHEDULED'].includes(inspection))return'SCHEDULED';if(job.status==='ACCEPTED'||response==='INTERESTED'||response==='SELECTED')return'ACCEPTED';return'NEW';}

export default function ProviderPage(){
 const[profile,setProfile]=useState<Profile|null>(null);const[provider,setProvider]=useState<ProviderInfo>({label:''});const[jobs,setJobs]=useState<Job[]>([]);const[message,setMessage]=useState('Checking provider account…');const[loading,setLoading]=useState(false);const[filter,setFilter]=useState<Exclude<Stage,'NOT_SELECTED'>>('NEW');const[selected,setSelected]=useState<Job|null>(null);const[responseText,setResponseText]=useState('');const[scheduleStart,setScheduleStart]=useState('');const[duration,setDuration]=useState(60);const[scheduleNote,setScheduleNote]=useState('');const[selectedSlot,setSelectedSlot]=useState('');
 const[findings,setFindings]=useState('');const[recommendedWork,setRecommendedWork]=useState('');const[estimatedMinutes,setEstimatedMinutes]=useState(60);const[labour,setLabour]=useState('');const[material,setMaterial]=useState('');const[workItems,setWorkItems]=useState(['']);const[finalLabour,setFinalLabour]=useState('');const[finalMaterial,setFinalMaterial]=useState('');
 const[chat,setChat]=useState<ChatMessage[]>([]);const[chatText,setChatText]=useState('');const[chatBusy,setChatBusy]=useState(false);
 useEffect(()=>{(async()=>{const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return;}const{data:p}=await supabase.from('auth_profiles').select('role,provider_approved,full_name').eq('user_id',data.session.user.id).maybeSingle();setProfile(p as Profile|null);if(p?.role!=='PROVIDER')setMessage('This account is not a Provider account.');else if(!p.provider_approved)setMessage('Complete your provider profile and submit it for Admin approval before accepting jobs.');else{setMessage('Provider marketplace ready.');setTimeout(()=>void loadDashboard(),0);}})();},[]);
 async function jwt(){const{data}=await supabase.auth.getSession();return data.session?.access_token||'';}
 async function callMarket(body:Record<string,unknown>){const t=await jwt();const response=await fetch(MARKET_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload?.error||'Provider request failed');return payload;}
 async function loadDashboard(){setLoading(true);try{const payload=await callMarket({action:'dashboard'});setProvider(payload.provider||{label:profile?.full_name||'Provider'});setJobs(payload.requests||[]);setMessage(`${payload.requests?.length||0} marketplace request(s) loaded.`);if(selected){const latest=(payload.requests||[]).find((j:Job)=>j.ticket_number===selected.ticket_number);if(latest)setSelected(latest);}}catch(e){setJobs([]);setMessage(e instanceof Error?e.message:'Unable to load provider marketplace.');}finally{setLoading(false);}}
 async function refreshSelected(ticket:string){try{const payload=await callMarket({action:'detail',ticketNumber:ticket});setSelected(payload.request||null);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load request detail.');}}
 async function action(name:string,payload:Record<string,unknown>={}){if(!selected)return;setLoading(true);try{await callMarket({action:name,ticketNumber:selected.ticket_number,...payload});setMessage('Request updated successfully.');await loadDashboard();await refreshSelected(selected.ticket_number);}catch(e){setMessage(e instanceof Error?e.message:'Unable to update request.');}finally{setLoading(false);}}
 async function quickInterest(job:Job){setSelected(job);setLoading(true);try{await callMarket({action:'express_interest',ticketNumber:job.ticket_number,message:'Available to help with this request.'});setMessage(`${job.ticket_number}: response sent to customer.`);await loadDashboard();await refreshSelected(job.ticket_number);setFilter('ACCEPTED');}catch(e){setMessage(e instanceof Error?e.message:'Unable to respond to request.');}finally{setLoading(false);}}
 async function decline(job:Job){setLoading(true);try{await callMarket({action:'decline_request',ticketNumber:job.ticket_number});setMessage(`${job.ticket_number} declined.`);if(selected?.ticket_number===job.ticket_number)setSelected(null);await loadDashboard();}catch(e){setMessage(e instanceof Error?e.message:'Unable to decline request.');}finally{setLoading(false);}}
 async function sendInterest(){if(!selected)return;await action('express_interest',{message:responseText.trim()||'Available to help with this request.'});setResponseText('');setFilter('ACCEPTED');}
 async function scheduleInspection(){if(!selected)return;const chosen=selectedSlot||scheduleStart;if(!chosen){setMessage('Choose a customer preferred time or propose another time.');return;}await action('schedule_inspection',{scheduledStart:chosen,durationMinutes:duration,note:scheduleNote.trim()||null});setSelectedSlot('');setScheduleStart('');setScheduleNote('');setFilter('SCHEDULED');}
 async function inspectionStep(targetStatus:string){await action('inspection_step',{targetStatus});setFilter('IN_PROGRESS');}
 async function sendEstimate(){if(findings.trim().length<5||recommendedWork.trim().length<5){setMessage('Add inspection findings and recommended work.');return;}await action('send_estimate',{findings:findings.trim(),recommendedWork:recommendedWork.trim(),estimatedMinutes,labourAmount:Number(labour||0),materialAmount:Number(material||0)});setFilter('IN_PROGRESS');}
 async function submitCompletion(){const items=workItems.map(x=>x.trim()).filter(Boolean);if(!items.length){setMessage('Add at least one work-performed item.');return;}await action('submit_completion',{workPerformed:items,labourAmount:Number(finalLabour||0),materialAmount:Number(finalMaterial||0),paymentNote:'Payment is handled outside iFixIt.'});setFilter('COMPLETED');}
 async function loadMessages(ticket:string,send=false){if(send&&!chatText.trim())return;setChatBusy(true);try{const t=await jwt();const response=await fetch(MESSAGE_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify({action:send?'send':'list',ticketNumber:ticket,message:chatText.trim()})});const payload=await response.json();if(!response.ok)throw new Error(payload?.error||'Unable to process messages');setChat(payload.messages||[]);if(send)setChatText('');}catch(e){setMessage(e instanceof Error?e.message:'Unable to process messages.');}finally{setChatBusy(false);}}
 async function signOut(){await supabase.auth.signOut();window.location.href='/login';}
 const counts=useMemo(()=>Object.fromEntries(tabs.map(t=>[t.key,jobs.filter(j=>stageFor(j)===t.key).length])) as Record<Exclude<Stage,'NOT_SELECTED'>,number>,[jobs]);const notSelected=useMemo(()=>jobs.filter(j=>stageFor(j)==='NOT_SELECTED'),[jobs]);const visible=useMemo(()=>jobs.filter(j=>stageFor(j)===filter),[jobs,filter]);
 function open(job:Job){setSelected(job);setResponseText(job.providerResponse?.provider_message||'');setFindings(job.estimate?.findings||'');setRecommendedWork(job.estimate?.recommended_work||'');setEstimatedMinutes(job.estimate?.estimated_minutes||60);setLabour(String(job.estimate?.labour_amount??''));setMaterial(String(job.estimate?.material_amount??''));if(job.completion){setWorkItems(job.completion.work_performed?.length?job.completion.work_performed:['']);setFinalLabour(String(job.completion.labour_amount??''));setFinalMaterial(String(job.completion.material_amount??''));}else{setWorkItems(['']);setFinalLabour('');setFinalMaterial('');}void loadMessages(job.ticket_number,false);}
 const selectedStage=selected?stageFor(selected):null;const inspection=selected?.inspection||null;const estimate=selected?.estimate||null;const completion=selected?.completion||null;
 const inspectionSequence=['SCHEDULED','ON_WAY','ARRIVED','INSPECTING','ESTIMATE_SENT'];const inspectionIndex=inspection?inspectionSequence.indexOf(inspection.status):-1;

 return <main className="shell providerDashboard">
  <header className="topbar"><div><a className="brand" href="/">FixIt</a><p className="tagline">Provider Marketplace</p></div><div className="actions"><a className="secondary" href="/provider/onboarding">Profile</a><button className="secondary" onClick={()=>void loadDashboard()} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button><button className="secondary" onClick={signOut}>Sign Out</button></div></header>
  <section className="providerHero"><div className="providerHeroCard"><p className="eyebrow">PROVIDER OPERATIONS</p><h1>{provider.label||profile?.full_name||'Your work dashboard'}</h1><p>Respond to matched requests, wait for customer selection, schedule inspections, send estimates and complete approved work.</p><div className="providerQuickActions"><button className="primary" onClick={()=>{setFilter('NEW');document.getElementById('provider-jobs')?.scrollIntoView({behavior:'smooth'});}}>Browse New Requests</button><a className="secondary" href="/provider/onboarding">Update Availability</a></div>{message?<p className="formMessage" role="status">{message}</p>:null}</div><aside className="providerSideCard"><div className="providerSideRow"><span>Availability</span><strong>{provider.availability||'Not set'}</strong></div><div className="providerSideRow"><span>Service area</span><strong>{provider.serviceArea||'Not set'}</strong></div><div className="providerSideRow"><span>New requests</span><strong>{counts.NEW||0}</strong></div><div className="providerSideRow"><span>Active work</span><strong>{(counts.ACCEPTED||0)+(counts.SCHEDULED||0)+(counts.IN_PROGRESS||0)}</strong></div><div className="providerSideRow"><span>Not selected</span><strong>{notSelected.length}</strong></div></aside></section>

  <section className="providerJobsPanel" id="provider-jobs"><div className="providerJobsHeader"><div><p className="eyebrow">REQUESTS</p><h2>Marketplace pipeline</h2></div><a className="secondary" href="/provider/onboarding">Availability & Areas</a></div><div className="providerTabs">{tabs.map(tab=><button key={tab.key} className={filter===tab.key?'providerTab active':'providerTab'} onClick={()=>setFilter(tab.key)}>{tab.label} {counts[tab.key]||0}</button>)}</div>
   <div className="providerJobList">{visible.map(job=><article className="providerJobCard" key={job.ticket_number}><div className="providerJobTop"><div className="providerJobTitle"><strong>{job.service_subcategory_code||job.service_name}</strong><small>{job.ticket_number} · {ago(job.created_at)}</small></div><span className="providerStatusChip">{pretty(stageFor(job)||'NEW')}</span></div><div className="providerJobMeta"><div className="providerMetaItem"><span>Location</span><strong>{job.service_location_text}</strong></div><div className="providerMetaItem"><span>Customer</span><strong>{job.customer?.name||'Customer'}</strong></div><div className="providerMetaItem"><span>Preferred</span><strong>{job.preferred_date}</strong></div></div><p className="providerProblem">{job.problem_description}</p>{job.media?.length?<div className="requestPhotoRow">{job.media.filter(m=>m.url).map(m=><img className="requestPhoto" key={m.id} src={m.url||''} alt="Request attachment"/>)}</div>:null}<div className="providerJobActions">{stageFor(job)==='NEW'?<><button className="danger" type="button" disabled={loading} onClick={()=>void decline(job)}>Decline</button><button className="secondary" type="button" onClick={()=>{open(job);setResponseText('I can help. I have a question about: ');}}>Ask Question</button><button className="primary" type="button" disabled={loading} onClick={()=>void quickInterest(job)}>Accept</button></>:<button className="primary" type="button" onClick={()=>open(job)}>Open Request</button>}</div></article>)}{!visible.length?<div className="providerEmpty"><strong>No requests in this stage</strong><span>{filter==='NEW'?'New eligible requests will appear automatically.':'Choose another tab or refresh the dashboard.'}</span></div>:null}</div>
   {notSelected.length?<div style={{marginTop:16}}><button className="secondary" onClick={()=>open(notSelected[0])}>View {notSelected.length} Not Selected request{notSelected.length===1?'':'s'}</button></div>:null}
  </section>

  {selected?<section className="providerDetailDrawer"><div className="providerDetailTop"><div><p className="eyebrow">{selectedStage==='NOT_SELECTED'?'NOT SELECTED':selected.ticket_number}</p><h2>{selected.service_name}</h2><p className="muted">{selected.service_location_text} · {selected.customer?.name||'Customer'}</p></div><div className="actions"><span className="pill">{pretty(selectedStage||selected.status)}</span><button className="secondary" onClick={()=>{setSelected(null);setChat([]);}}>Close</button></div></div>

   {selectedStage==='NEW'?<div className="providerJourneyGrid"><div className="providerJourneyCard"><h3>New request</h3><p>{selected.problem_description}</p>{selected.customer_notes?<p className="providerMessage">Customer note: {selected.customer_notes}</p>:null}<div className="customerBlock"><div className="customerDatum"><span>Customer</span><strong>{selected.customer?.name||'Customer'}</strong></div><div className="customerDatum"><span>Phone</span><strong>{selected.customer?.phone||'Available after selection'}</strong></div></div></div><div className="responseComposer"><strong>Respond to customer</strong><textarea rows={5} value={responseText} onChange={e=>setResponseText(e.target.value)} placeholder="Introduce yourself or ask a question. This message appears on the customer's provider-selection screen."/><button className="primary" disabled={loading} onClick={()=>void sendInterest()}>Accept & Send Response</button><button className="danger" disabled={loading} onClick={()=>void decline(selected)}>Decline Request</button></div></div>:null}

   {selectedStage==='ACCEPTED'&&selected.status==='NEW'&&selected.providerResponse?.status==='INTERESTED'?<div className="providerJourneyGrid"><div className="providerJourneyCard"><h3>Response sent</h3><div className="statusNotice">The customer is comparing interested providers. No assignment has been made yet.</div><p className="providerMessage">{selected.providerResponse.provider_message||'Available to help with this request.'}</p><div className="notSelectedTimeline"><div className="notSelectedStep">✓ Request matched to your services</div><div className="notSelectedStep">✓ You responded to the customer</div><div className="notSelectedStep">○ Customer selects one provider</div></div></div><div className="providerJourneyCard"><h3>While you wait</h3><p className="muted">Keep your availability accurate. Customer messaging opens only after you are selected.</p><div className="actions"><a className="secondary" href="/provider/onboarding">Update Availability</a><button className="danger" onClick={()=>void action('withdraw_interest')}>Withdraw Response</button></div></div></div>:null}

   {selected.status==='ACCEPTED'&&selected.providerResponse?.status==='SELECTED'?<><div className="selectionBanner"><div><strong>🎉 Selected by Customer</strong><span>{selected.customer?.name||'The customer'} chose you for {selected.service_name}.</span></div>{!selected.providerResponse.provider_confirmed_at?<button className="primary" onClick={()=>void action('confirm_selection')} disabled={loading}>Confirm Selection</button>:<span className="verifiedBadge">✓ Confirmed</span>}</div><div className="providerJourneyGrid" style={{marginTop:14}}><div className="providerJourneyCard"><h3>Service details</h3><p>{selected.problem_description}</p>{selected.customer_notes?<p className="providerMessage">Customer message: {selected.customer_notes}</p>:null}<div className="customerBlock"><div className="customerDatum"><span>Customer</span><strong>{selected.customer?.name||'Customer'}</strong></div><div className="customerDatum"><span>Phone</span><strong>{selected.customer?.phone||'Not provided'}</strong></div></div></div><div className="providerJourneyCard"><h3>Next steps</h3><div className="inspectionChecklist">{['Confirm Selection','Schedule Inspection','Visit & Diagnose','Send Estimate'].map((s,i)=><div className={i===0&&selected.providerResponse?.provider_confirmed_at?'inspectionCheck done':'inspectionCheck'} key={s}><span className="checkDot">{i+1}</span><strong>{s}</strong></div>)}</div></div></div></>:null}

   {selected.status==='ACCEPTED'&&(!inspection||inspection.status==='PROPOSED')?<div className="providerJourneyCard" style={{marginTop:14}}><h3>Schedule Inspection</h3><p className="muted">Choose one of the customer's preferred times or propose another time.</p>{inspection?.preferred_slots?.length?<div className="slotList">{inspection.preferred_slots.map((slot,i)=><button className={selectedSlot===slot?'slotButton selected':'slotButton'} key={`${slot}:${i}`} onClick={()=>{setSelectedSlot(slot);setScheduleStart('');}}><span>Customer option {i+1}</span><strong>{when(slot)}</strong></button>)}</div>:<div className="statusNotice">The customer has not sent preferred times yet. You can propose a time below.</div>}<div className="scheduleGrid" style={{marginTop:12}}><label className="formField">Propose another time<input type="datetime-local" value={scheduleStart} onChange={e=>{setScheduleStart(e.target.value);setSelectedSlot('');}}/></label><label className="formField">Duration (minutes)<input type="number" min={15} max={720} value={duration} onChange={e=>setDuration(Number(e.target.value)||60)}/></label></div><label className="formField" style={{marginTop:10}}>Note<textarea rows={3} value={scheduleNote} onChange={e=>setScheduleNote(e.target.value)} placeholder="Optional scheduling note"/></label><div className="actions" style={{marginTop:10}}><button className="secondary" onClick={()=>void loadMessages(selected.ticket_number,false)}>Message Customer</button><button className="primary" disabled={loading||(!selectedSlot&&!scheduleStart)} onClick={()=>void scheduleInspection()}>Schedule Inspection</button></div></div>:null}

   {inspection&&inspection.status!=='PROPOSED'?<div className="providerJourneyGrid" style={{marginTop:14}}><div className="providerJourneyCard"><h3>Inspection Journey</h3><div className="scheduleSummary"><div className="scheduleMetric"><span>Schedule</span><strong>{when(inspection.scheduled_start)}</strong></div><div className="scheduleMetric"><span>Duration</span><strong>{inspection.duration_minutes||60} min</strong></div><div className="scheduleMetric"><span>Status</span><strong>{pretty(inspection.status)}</strong></div></div><div className="inspectionChecklist" style={{marginTop:12}}>{inspectionSequence.map((step,index)=><div key={step} className={index<inspectionIndex?'inspectionCheck done':index===inspectionIndex?'inspectionCheck current':'inspectionCheck'}><span className="checkDot">{index+1}</span><div><strong>{pretty(step)}</strong></div></div>)}</div><div className="providerActionGrid" style={{marginTop:12}}><a className="secondary" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(selected.service_location_text)}`}>View Address</a><a className="secondary" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(selected.service_location_text)}`}>Start Navigation</a>{selected.customer?.phone?<a className="secondary" href={`tel:${selected.customer.phone}`}>Call Customer</a>:<button className="secondary" disabled>Call Customer</button>}<button className="secondary" onClick={()=>void loadMessages(selected.ticket_number,false)}>Message</button></div>{inspection.status==='SCHEDULED'?<button className="primary" style={{marginTop:10}} onClick={()=>void inspectionStep('ON_WAY')}>I'm On the Way</button>:inspection.status==='ON_WAY'?<button className="primary" style={{marginTop:10}} onClick={()=>void inspectionStep('ARRIVED')}>Arrived</button>:inspection.status==='ARRIVED'?<button className="primary" style={{marginTop:10}} onClick={()=>void inspectionStep('INSPECTING')}>Start Inspection</button>:null}</div>
     <div className="providerJourneyCard"><h3>{inspection.status==='INSPECTING'?'Send Estimate':inspection.status==='ESTIMATE_SENT'?'Estimate Sent':'Inspection Actions'}</h3>{inspection.status==='INSPECTING'?<div className="estimateForm"><label className="formField">Inspection findings<textarea rows={4} value={findings} onChange={e=>setFindings(e.target.value)} /></label><label className="formField">Recommended work<textarea rows={4} value={recommendedWork} onChange={e=>setRecommendedWork(e.target.value)} /></label><div className="estimateMoneyGrid"><label className="formField">Estimated minutes<input type="number" min={1} value={estimatedMinutes} onChange={e=>setEstimatedMinutes(Number(e.target.value)||60)}/></label><label className="formField">Labour MVR<input type="number" min={0} step="0.01" value={labour} onChange={e=>setLabour(e.target.value)}/></label><label className="formField">Material MVR<input type="number" min={0} step="0.01" value={material} onChange={e=>setMaterial(e.target.value)}/></label></div><button className="primary" onClick={()=>void sendEstimate()} disabled={loading}>Send Estimate</button></div>:inspection.status==='ESTIMATE_SENT'?<><div className="statusNotice">Estimate sent. Wait for the customer to approve or decline before starting repair work.</div>{estimate?<div style={{marginTop:10}}><p><b>Total:</b> {money(estimate.total_amount,estimate.currency)}</p><p><b>Status:</b> {pretty(estimate.status)}</p>{estimate.customer_note?<p className="providerMessage">Customer note: {estimate.customer_note}</p>:null}</div>:null}</>:<p className="muted">Continue the inspection checklist on the left.</p>}</div></div>:null}

   {selected.status==='PROCESSING'?<div className="providerJourneyGrid" style={{marginTop:14}}><div className="providerJourneyCard"><h3>Approved Work In Progress</h3><div className="statusSuccess">The customer approved the estimate. Complete the approved work, then submit the final summary.</div>{estimate?<div style={{marginTop:10}}><p><b>Approved work:</b> {estimate.recommended_work}</p><p><b>Estimate:</b> {money(estimate.total_amount,estimate.currency)}</p></div>:null}</div><div className="providerJourneyCard"><h3>Submit Completion</h3><div className="completionForm"><div className="workItems">{workItems.map((item,index)=><div className="workItemRow" key={index}><input value={item} onChange={e=>setWorkItems(items=>items.map((v,i)=>i===index?e.target.value:v))} placeholder={`Work performed ${index+1}`}/>{workItems.length>1?<button className="secondary" onClick={()=>setWorkItems(items=>items.filter((_,i)=>i!==index))}>×</button>:null}</div>)}</div><button className="secondary" onClick={()=>setWorkItems(items=>[...items,''])}>+ Add Work Item</button><div className="estimateMoneyGrid"><label className="formField">Final labour MVR<input type="number" min={0} step="0.01" value={finalLabour} onChange={e=>setFinalLabour(e.target.value)}/></label><label className="formField">Final material MVR<input type="number" min={0} step="0.01" value={finalMaterial} onChange={e=>setFinalMaterial(e.target.value)}/></label><div className="customerDatum"><span>Final total</span><strong>{money(Number(finalLabour||0)+Number(finalMaterial||0))}</strong></div></div><p className="mutedMini">iFixIt records the cost summary but does not process payment.</p><button className="primary" disabled={loading} onClick={()=>void submitCompletion()}>Mark Work Completed</button></div></div></div>:null}

   {selectedStage==='COMPLETED'?<div className="providerJourneyGrid" style={{marginTop:14}}><div className="providerJourneyCard"><h3>Completed Job</h3><div className="statusSuccess">The core request lifecycle is complete.</div>{completion?<><p><b>Work performed</b></p><ul>{completion.work_performed.map((item,i)=><li key={`${item}:${i}`}>{item}</li>)}</ul><p><b>Final amount:</b> {money(completion.final_amount,completion.currency)}</p><p className="muted">{completion.payment_note}</p><p><b>Customer confirmation:</b> {pretty(completion.status)}</p></>:<p className="muted">This older completed job does not have a marketplace completion summary.</p>}</div><div className="providerJourneyCard"><h3>Next</h3><p className="muted">Completed jobs remain available for your history. Customer ratings will contribute to your marketplace reputation when submitted.</p><button className="secondary" onClick={()=>{setSelected(null);setFilter('NEW');}}>Browse New Requests</button></div></div>:null}

   {selectedStage==='NOT_SELECTED'?<div className="notSelectedCard"><p className="eyebrow">NOT SELECTED</p><h2>The customer selected another provider</h2><p className="muted">Your response remains part of the request history, but you are not assigned to this job.</p><div className="notSelectedTimeline"><div className="notSelectedStep">✓ Request matched to your profile</div><div className="notSelectedStep">✓ You responded</div><div className="notSelectedStep">✓ Customer completed provider selection</div><div className="notSelectedStep">○ Continue browsing other requests</div></div><div className="actions" style={{justifyContent:'center'}}><a className="secondary" href="/provider/onboarding">Update Availability</a><button className="primary" onClick={()=>{setSelected(null);setFilter('NEW');}}>Browse Requests</button></div></div>:null}

   {selected.status!=='NEW'&&selectedStage!=='NOT_SELECTED'?<div style={{marginTop:16}}><div className="providerJobsHeader"><div><p className="eyebrow">CUSTOMER COMMUNICATION</p><h3>Request Messages</h3></div><button className="secondary" onClick={()=>void loadMessages(selected.ticket_number,false)} disabled={chatBusy}>Refresh</button></div><div className="providerMessageList">{chat.map(m=><div className="providerMessage" key={m.id}><strong>{m.sender_label||m.sender_role}</strong><p>{m.message_text}</p><small>{when(m.created_at)}</small></div>)}{!chat.length?<div className="providerEmpty"><strong>No messages yet</strong><span>Start the conversation below.</span></div>:null}</div><div className="providerAccessRow"><input placeholder="Message the customer" value={chatText} onChange={e=>setChatText(e.target.value)}/><button className="primary" type="button" disabled={chatBusy||!chatText.trim()} onClick={()=>void loadMessages(selected.ticket_number,true)}>Send Message</button></div></div>:null}
  </section>:null}

  <footer className="footer"><span>FixIt Maldives</span><span>Provider marketplace workflow</span></footer>
 </main>;
}
