'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import AppModeSwitch from '../../AppModeSwitch';
import { useProviderMode } from '../useProviderMode';

const MARKET_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-marketplace';
const MESSAGE_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/request-messages';
type Job={ticket_number:string;service_name:string;service_location_text:string;status:string;customer?:{name?:string|null}|null};type Msg={id:string;sender_role:string;sender_label?:string|null;message_text:string;created_at:string};type Conv={job:Job;messages:Msg[];unread:number};
export default function ProviderMessagesPage(){
 const mode=useProviderMode(true);const[convs,setConvs]=useState<Conv[]>([]);const[selected,setSelected]=useState('');const[text,setText]=useState('');const[busy,setBusy]=useState(true);const[message,setMessage]=useState('Loading provider messages…');
 useEffect(()=>{if(mode.ready)void load();},[mode.ready]);
 async function session(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return null;}return data.session;}
 async function callMessages(ticket:string,action='list',messageText=''){const s=await session();if(!s)throw new Error('Sign in required');const r=await fetch(MESSAGE_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`},body:JSON.stringify({action,ticketNumber:ticket,message:messageText,mode:'PROVIDER'})});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to load messages');return p;}
 async function load(){setBusy(true);try{const s=await session();if(!s)return;const r=await fetch(MARKET_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`},body:JSON.stringify({action:'dashboard'})});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to load provider jobs');const assigned:Job[]=(p.requests||[]).filter((j:any)=>Boolean(j.customer)&&['ACCEPTED','INSPECTION_SCHEDULED','IN_PROGRESS','COMPLETED'].includes(j.status));const next:Conv[]=[];for(const job of assigned){try{const mp=await callMessages(job.ticket_number);next.push({job,messages:mp.messages||[],unread:Number(mp.unreadCount||0)});}catch{next.push({job,messages:[],unread:0});}}next.sort((a,b)=>{const am=a.messages.at(-1)?.created_at||'',bm=b.messages.at(-1)?.created_at||'';return new Date(bm||0).getTime()-new Date(am||0).getTime();});setConvs(next);if(!selected&&next.length)setSelected(next[0].job.ticket_number);setMessage(next.length?'Provider conversations are up to date.':'No customer conversations yet.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load messages.');}finally{setBusy(false);}}
 const current=useMemo(()=>convs.find(c=>c.job.ticket_number===selected)||null,[convs,selected]);
 async function choose(ticket:string){setSelected(ticket);try{await callMessages(ticket,'mark_read');setConvs(v=>v.map(c=>c.job.ticket_number===ticket?{...c,unread:0}:c));}catch{}}
 async function send(e:FormEvent){e.preventDefault();const value=text.trim();if(!value||!selected)return;setBusy(true);try{const p=await callMessages(selected,'send',value);setText('');setConvs(v=>v.map(c=>c.job.ticket_number===selected?{...c,messages:p.messages||[],unread:0}:c));setMessage('Message sent.');}catch(err){setMessage(err instanceof Error?err.message:'Unable to send message.');}finally{setBusy(false);}}
 if(mode.loading)return <main className="providerModePage"><div className="providerModeShell"><div className="providerModeCard">Checking provider access…</div></div></main>;
 const unread=convs.reduce((n,c)=>n+c.unread,0);
 return <main className="providerModePage"><div className="providerModeShell"><header className="providerModeTop"><div><span className="modeBadge provider"><span className="modeDot provider"/>Provider</span><h1>Messages</h1><p>Customer conversations for jobs assigned to you.</p></div><AppModeSwitch mode="provider" compact/></header>
 <section className="providerMessagesLayout"><aside className="providerInbox"><div className="providerSectionHead"><div><h2>Inbox</h2><p>{unread?`${unread} unread`:'All caught up'}</p></div></div>{convs.length?<div className="providerConversationList">{convs.map(c=>{const last=c.messages.at(-1);return <button key={c.job.ticket_number} className={selected===c.job.ticket_number?'active':''} onClick={()=>void choose(c.job.ticket_number)}><span className="providerConversationAvatar">{(c.job.customer?.name||'C')[0].toUpperCase()}</span><span><strong>{c.job.customer?.name||'Customer'}</strong><small>{c.job.service_name} · {last?.message_text||'Open conversation'}</small></span>{c.unread?<b>{c.unread>9?'9+':c.unread}</b>:null}</button>})}</div>:<div className="providerEmptyState"><h3>No conversations</h3><p>Messages become available after a job is assigned to you.</p></div>}</aside>
 <section className="providerChat">{current?<><header><div><strong>{current.job.customer?.name||'Customer'}</strong><small>{current.job.service_name} · {current.job.ticket_number}</small></div><span className="modeBadge provider">{current.job.status.replaceAll('_',' ')}</span></header><div className="providerChatMessages">{current.messages.length?current.messages.map(m=><div key={m.id} className={`providerBubble ${m.sender_role==='PROVIDER'?'mine':''}`}><span>{m.message_text}</span><small>{new Date(m.created_at).toLocaleString()}</small></div>):<div className="providerEmptyState"><h3>Start the conversation</h3><p>Send the customer a message about their assigned service request.</p></div>}</div><form className="providerChatComposer" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} maxLength={2000} placeholder="Message customer…"/><button className="primary" disabled={busy||!text.trim()}>Send</button></form></>:<div className="providerEmptyState"><h3>Select a conversation</h3><p>Choose a customer from your provider inbox.</p></div>}</section></section><p className="muted" role="status">{busy?'Refreshing…':message}</p></div></main>;
}
