'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import AppModeSwitch from '../../AppModeSwitch';
import { useProviderMode } from '../useProviderMode';

const MARKET_URL='/api/legacy-edge?service=provider-marketplace';
const MESSAGE_URL='/api/legacy-edge?service=request-messages';
type Job={ticket_number:string;service_name:string;service_location_text:string;status:string;customer?:{name?:string|null}|null};
type Msg={id:string;sender_role:string;sender_mode?:string|null;sender_label?:string|null;message_text:string;created_at:string;delivered_at?:string|null;read_at?:string|null};
type Conv={job:Job;messages:Msg[];unread:number};

function receipt(m:Msg){if(m.read_at)return'Read';if(m.delivered_at)return'Delivered';return'Sent';}
async function post(url:string,body:Record<string,unknown>){const r=await fetch(url,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const p=await r.json().catch(()=>({}));if(r.status===401){const next=`${window.location.pathname}${window.location.search}`;window.location.replace(`/login?next=${encodeURIComponent(next)}`);throw new Error('Authentication required.');}if(!r.ok)throw new Error(p?.error||'Request failed');return p;}

export default function ProviderMessagesPage(){
 const mode=useProviderMode(true);const[convs,setConvs]=useState<Conv[]>([]);const[selected,setSelected]=useState('');const[text,setText]=useState('');const[busy,setBusy]=useState(true);const[message,setMessage]=useState('Loading provider messages…');
 useEffect(()=>{if(!mode.ready)return;void load(false);},[mode.ready]);
 useEffect(()=>{if(!mode.ready)return;const channel=supabase.channel(`provider-messages-${mode.name}`).on('postgres_changes',{event:'*',schema:'public',table:'request_messages'},()=>{if(selected)void callMessages(selected,'mark_read').then(()=>load(true)).catch(()=>load(true));else void load(true);}).subscribe();return()=>{void supabase.removeChannel(channel);};},[mode.ready,selected]);
 async function callMessages(ticket:string,action='list',messageText=''){return post(MESSAGE_URL,{action,ticketNumber:ticket,message:messageText,mode:'PROVIDER'});}
 async function load(silent=false){if(!silent)setBusy(true);try{const p=await post(MARKET_URL,{action:'dashboard'});const assigned:Job[]=(p.requests||[]).filter((j:any)=>Boolean(j.customer)&&['ACCEPTED','INSPECTION_SCHEDULED','IN_PROGRESS','PROCESSING','COMPLETED'].includes(String(j.status).toUpperCase()));const next:Conv[]=[];for(const job of assigned){try{const mp=await callMessages(job.ticket_number);next.push({job,messages:mp.messages||[],unread:Number(mp.unreadCount||0)});}catch{next.push({job,messages:[],unread:0});}}next.sort((a,b)=>{const am=a.messages.at(-1)?.created_at||'',bm=b.messages.at(-1)?.created_at||'';return new Date(bm||0).getTime()-new Date(am||0).getTime();});setConvs(next);const requested=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('ticket')||'':'';setSelected(current=>requested&&next.some(c=>c.job.ticket_number===requested)?requested:current&&next.some(c=>c.job.ticket_number===current)?current:next[0]?.job.ticket_number||'');if(!silent)setMessage(next.length?'Provider conversations are connected live.':'No customer conversations yet.');}catch(e){if(!silent&&!(e instanceof Error&&e.message==='Authentication required.'))setMessage(e instanceof Error?e.message:'Unable to load messages.');}finally{if(!silent)setBusy(false);}}
 const current=useMemo(()=>convs.find(c=>c.job.ticket_number===selected)||null,[convs,selected]);
 async function choose(ticket:string){setSelected(ticket);try{const p=await callMessages(ticket,'mark_read');setConvs(v=>v.map(c=>c.job.ticket_number===ticket?{...c,messages:p.messages||c.messages,unread:0}:c));}catch{}}
 async function send(e:FormEvent){e.preventDefault();const value=text.trim();if(!value||!selected)return;setBusy(true);try{const p=await callMessages(selected,'send',value);setText('');setConvs(v=>v.map(c=>c.job.ticket_number===selected?{...c,messages:p.messages||[],unread:0}:c));setMessage('Message sent.');}catch(err){if(!(err instanceof Error&&err.message==='Authentication required.'))setMessage(err instanceof Error?err.message:'Unable to send message.');}finally{setBusy(false);}}
 if(mode.loading)return <main className="providerModePage"><div className="providerModeShell"><div className="providerModeCard">Checking provider access…</div></div></main>;
 const unread=convs.reduce((n,c)=>n+c.unread,0);
 return <main className="providerModePage"><div className="providerModeShell"><header className="providerModeTop"><div><span className="modeBadge provider"><span className="modeDot provider"/>Provider</span><h1>Messages</h1><p>Live customer conversations for jobs assigned to you.</p></div><AppModeSwitch mode="provider" compact/></header>
 <section className="providerMessagesLayout"><aside className="providerInbox"><div className="providerSectionHead"><div><h2>Inbox</h2><p>{unread?`${unread} unread`:'All caught up'}</p></div><span className="modeBadge customer">Live</span></div>{convs.length?<div className="providerConversationList">{convs.map(c=>{const last=c.messages.at(-1);return <button key={c.job.ticket_number} className={selected===c.job.ticket_number?'active':''} onClick={()=>void choose(c.job.ticket_number)}><span className="providerConversationAvatar">{(c.job.customer?.name||'C')[0].toUpperCase()}</span><span><strong>{c.job.customer?.name||'Customer'}</strong><small>{c.job.service_name} · {last?.message_text||'Open conversation'}</small></span>{c.unread?<b>{c.unread>9?'9+':c.unread}</b>:null}</button>})}</div>:<div className="providerEmptyState"><h3>No conversations</h3><p>Messages become available only after you accept a customer request.</p></div>}</aside>
 <section className="providerChat">{current?<><header><div><strong>{current.job.customer?.name||'Customer'}</strong><small>{current.job.service_name} · {current.job.ticket_number}</small></div><span className="modeBadge provider">{current.job.status.replaceAll('_',' ')}</span></header><div className="providerChatMessages">{current.messages.length?current.messages.map(m=>{const mine=(m.sender_mode||m.sender_role)==='PROVIDER';return <div key={m.id} className={`providerBubble ${mine?'mine':''}`}><span>{m.message_text}</span><small>{new Date(m.created_at).toLocaleString()}{mine?` · ${receipt(m)}`:''}</small></div>}):<div className="providerEmptyState"><h3>Start the conversation</h3><p>Send the customer a message about their assigned service request.</p></div>}</div><form className="providerChatComposer" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} maxLength={2000} placeholder="Message customer…"/><button className="primary" disabled={busy||!text.trim()}>Send</button></form></>:<div className="providerEmptyState"><h3>Select a conversation</h3><p>Choose a customer from your provider inbox.</p></div>}</section></section><p className="muted" role="status">{busy?'Refreshing…':message}</p></div></main>;
}
