'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import AppModeSwitch from '../../AppModeSwitch';
import { useProviderMode } from '../useProviderMode';

const OFFERS_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-offers';
const MARKET_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-marketplace';
type Offer={id:string;rank_score:number;rank_breakdown:any;offered_at:string;response_deadline_at:string;request:{ticket_number:string;service_name:string;service_location_text:string;preferred_date:string;problem_description:string;urgency:string}|null};
type Job={ticket_number:string;service_name:string;service_location_text:string;status:string;customer?:{name?:string|null}|null;inspection?:{scheduled_start?:string|null}|null};
export default function ProviderJobsPage(){
 const mode=useProviderMode(true);const[offers,setOffers]=useState<Offer[]>([]);const[jobs,setJobs]=useState<Job[]>([]);const[busy,setBusy]=useState(true);const[message,setMessage]=useState('Loading jobs…');
 useEffect(()=>{if(mode.ready)void load();},[mode.ready]);
 async function auth(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return null;}return data.session;}
 async function load(){setBusy(true);try{const s=await auth();if(!s)return;const headers={'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`};const[or,mr]=await Promise.all([fetch(OFFERS_URL,{method:'POST',headers,body:JSON.stringify({action:'list'})}),fetch(MARKET_URL,{method:'POST',headers,body:JSON.stringify({action:'dashboard'})})]);const op=await or.json(),mp=await mr.json();if(!or.ok)throw new Error(op?.error||'Unable to load job offers');if(!mr.ok)throw new Error(mp?.error||'Unable to load jobs');setOffers(op.offers||[]);setJobs((mp.requests||[]).filter((j:Job)=>['ACCEPTED','INSPECTION_SCHEDULED','IN_PROGRESS','COMPLETED'].includes(j.status)));setMessage('Jobs are up to date.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load provider jobs.');}finally{setBusy(false);}}
 async function respond(offerId:string,action:'accept'|'decline'){setBusy(true);try{const s=await auth();if(!s)return;const r=await fetch(OFFERS_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`},body:JSON.stringify({action,offerId})});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to respond to offer');try{sessionStorage.setItem('fixit:mode-toast',action==='accept'?'Job accepted. It is now in your active work.':'Offer declined. FixIt will offer it to the next matched provider.');}catch{}await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to respond to job offer.');setBusy(false);}}
 const active=useMemo(()=>jobs.filter(j=>j.status!=='COMPLETED'),[jobs]);const completed=useMemo(()=>jobs.filter(j=>j.status==='COMPLETED'),[jobs]);
 if(mode.loading)return <main className="providerModePage"><div className="providerModeShell"><div className="providerModeCard">Checking provider access…</div></div></main>;
 return <main className="providerModePage"><div className="providerModeShell"><header className="providerModeTop"><div><span className="modeBadge provider"><span className="modeDot provider"/>Provider</span><h1>Jobs</h1><p>Ranked offers and your active service work.</p></div><AppModeSwitch mode="provider" compact/></header>
 <section className="providerModeCard"><div className="providerSectionHead"><div><h2>New job offers</h2><p>Offers are sent one provider at a time and expire automatically.</p></div><span className="modeBadge provider">{offers.length} new</span></div>{offers.length?<div className="providerOfferGrid">{offers.map(o=><article className="providerOfferCard" key={o.id}><div className="providerOfferTop"><span className="modeBadge provider">{o.request?.urgency||'STANDARD'}</span><strong>{o.request?.service_name||'Service request'}</strong></div><p>{o.request?.service_location_text||'Service location'} · {o.request?.ticket_number}</p><p className="providerOfferProblem">{o.request?.problem_description||'Open the request after accepting for full job details.'}</p><div className="providerOfferReasons"><span>Exact service</span><span>Matched location</span><span>Rank score {Number(o.rank_score||0).toFixed(0)}</span></div><div className="providerOfferDeadline">Respond by {new Date(o.response_deadline_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div><div className="providerSetupActions"><button className="secondary" disabled={busy} onClick={()=>void respond(o.id,'decline')}>Decline</button><button className="primary" disabled={busy} onClick={()=>void respond(o.id,'accept')}>Accept Job</button></div></article>)}</div>:<div className="providerEmptyState"><h3>No new offers</h3><p>When FixIt ranks you as the best available provider, the offer will appear here.</p></div>}</section>
 <section className="providerModeCard"><div className="providerSectionHead"><div><h2>Active reservations</h2><p>Accepted jobs currently assigned to you.</p></div></div>{active.length?<div className="providerList">{active.map(j=><div className="providerListItem" key={j.ticket_number}><div><h3>{j.service_name}</h3><p>{j.customer?.name||'Customer'} · {j.service_location_text} · {j.ticket_number}</p>{j.inspection?.scheduled_start?<p>Scheduled {new Date(j.inspection.scheduled_start).toLocaleString()}</p>:null}</div><span className="modeBadge provider">{j.status.replaceAll('_',' ')}</span></div>)}</div>:<div className="providerEmptyState"><h3>No active reservations</h3><p>Accept a matching offer to start a provider job.</p></div>}</section>
 {completed.length?<section className="providerModeCard"><div className="providerSectionHead"><div><h2>Recently completed</h2></div></div><div className="providerList">{completed.slice(0,6).map(j=><div className="providerListItem" key={j.ticket_number}><div><h3>{j.service_name}</h3><p>{j.ticket_number} · {j.service_location_text}</p></div><span className="modeBadge customer">Completed</span></div>)}</div></section>:null}<p className="muted" role="status">{busy?'Refreshing…':message}</p></div></main>;
}
