'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import AppModeSwitch from '../../AppModeSwitch';
import { useProviderMode } from '../useProviderMode';

const OFFERS_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-offers';
const MARKET_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-marketplace';
type Offer={id:string;rank_score:number;rank_breakdown:any;offered_at:string;response_deadline_at:string;request:{ticket_number:string;service_name:string;service_location_text:string;preferred_date:string;problem_description:string;urgency:string}|null};
type Job={ticket_number:string;service_name:string;service_location_text:string;status:string;customer?:{name?:string|null}|null;inspection?:{scheduled_start?:string|null}|null};
function left(value:string){const d=new Date(value);if(Number.isNaN(d.getTime()))return'';const m=Math.max(0,Math.ceil((d.getTime()-Date.now())/60000));return m>60?`${Math.floor(m/60)}h ${m%60}m left`:`${m}m left`;}
export default function ProviderJobsPage(){
 const mode=useProviderMode(true);const[offers,setOffers]=useState<Offer[]>([]);const[jobs,setJobs]=useState<Job[]>([]);const[busy,setBusy]=useState(true);const[message,setMessage]=useState('Loading customer requests…');
 useEffect(()=>{if(mode.ready)void load();},[mode.ready]);
 async function auth(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return null;}return data.session;}
 async function load(){setBusy(true);try{const s=await auth();if(!s)return;const headers={'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`};const[or,mr]=await Promise.all([fetch(OFFERS_URL,{method:'POST',headers,body:JSON.stringify({action:'list'})}),fetch(MARKET_URL,{method:'POST',headers,body:JSON.stringify({action:'dashboard'})})]);const op=await or.json(),mp=await mr.json();if(!or.ok)throw new Error(op?.error||'Unable to load customer requests');if(!mr.ok)throw new Error(mp?.error||'Unable to load accepted customer jobs');setOffers(op.offers||[]);setJobs((mp.requests||[]).filter((j:Job)=>['ACCEPTED','INSPECTION_SCHEDULED','IN_PROGRESS','COMPLETED'].includes(j.status)));setMessage('Customer requests are up to date.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load customer requests.');}finally{setBusy(false);}}
 async function respond(offerId:string,action:'accept'|'decline'){setBusy(true);try{const s=await auth();if(!s)return;const r=await fetch(OFFERS_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`},body:JSON.stringify({action,offerId})});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to respond to customer request');try{sessionStorage.setItem('fixit:mode-toast',action==='accept'?'Customer request accepted. Customer details and messaging are now available.':'Request declined. FixIt will offer it to the next matched provider.');}catch{}await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to respond to customer request.');setBusy(false);}}
 const active=useMemo(()=>jobs.filter(j=>j.status!=='COMPLETED'),[jobs]);const completed=useMemo(()=>jobs.filter(j=>j.status==='COMPLETED'),[jobs]);
 if(mode.loading)return <main className="providerModePage"><div className="providerModeShell"><div className="providerModeCard">Checking provider access…</div></div></main>;
 return <main className="providerModePage"><div className="providerModeShell"><header className="providerModeTop"><div><span className="modeBadge provider"><span className="modeDot provider"/>Provider</span><h1>Customer Requests</h1><p>Requests FixIt has matched to you, followed by customer jobs you have accepted.</p></div><AppModeSwitch mode="provider" compact/></header>
 <section className="providerModeCard"><div className="providerSectionHead"><div><h2>Requests waiting for you</h2><p>These are real customer requests currently offered to you. They expire if you do not respond in time.</p></div><span className="modeBadge provider">{offers.length} waiting</span></div>{offers.length?<div className="providerOfferGrid">{offers.map(o=><article className="providerOfferCard" key={o.id}><div className="providerOfferTop"><span className="modeBadge provider">{o.request?.urgency||'STANDARD'}</span><strong>{o.request?.service_name||'Service request'}</strong></div><p><b>Location:</b> {o.request?.service_location_text||'Service location'}</p><p><b>Preferred date:</b> {o.request?.preferred_date?new Date(o.request.preferred_date+'T00:00:00').toLocaleDateString():'Not specified'}</p><p className="providerOfferProblem"><b>Customer request:</b> {o.request?.problem_description||'No problem description supplied.'}</p><div className="providerOfferReasons"><span>Exact service</span><span>Matched location</span><span>Rank score {Number(o.rank_score||0).toFixed(0)}</span></div><div className="providerOfferDeadline"><strong>{left(o.response_deadline_at)}</strong> · respond by {new Date(o.response_deadline_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div><p className="muted">Customer name/contact details stay private until you accept the request.</p><div className="providerSetupActions"><button className="secondary" disabled={busy} onClick={()=>void respond(o.id,'decline')}>Decline</button><button className="primary" disabled={busy} onClick={()=>void respond(o.id,'accept')}>Accept Request</button></div></article>)}</div>:<div className="providerEmptyState"><h3>No customer requests waiting</h3><p>FixIt will show a request here when your service category, location and availability match the customer.</p><a className="secondary" href="/provider/listings">Review services & availability</a></div>}</section>
 <section className="providerModeCard"><div className="providerSectionHead"><div><h2>Accepted customer jobs</h2><p>After accepting a request, the customer identity and job workflow are available here.</p></div></div>{active.length?<div className="providerList">{active.map(j=><div className="providerListItem" key={j.ticket_number}><div><h3>{j.service_name}</h3><p>{j.customer?.name||'Customer'} · {j.service_location_text} · {j.ticket_number}</p>{j.inspection?.scheduled_start?<p>Scheduled {new Date(j.inspection.scheduled_start).toLocaleString()}</p>:null}</div><span className="modeBadge provider">{j.status.replaceAll('_',' ')}</span></div>)}</div>:<div className="providerEmptyState"><h3>No accepted customer jobs</h3><p>Accept a matching request above to begin working with the customer.</p></div>}</section>
 {completed.length?<section className="providerModeCard"><div className="providerSectionHead"><div><h2>Recently completed customer jobs</h2></div></div><div className="providerList">{completed.slice(0,6).map(j=><div className="providerListItem" key={j.ticket_number}><div><h3>{j.service_name}</h3><p>{j.customer?.name||'Customer'} · {j.ticket_number} · {j.service_location_text}</p></div><span className="modeBadge customer">Completed</span></div>)}</div></section>:null}<p className="muted" role="status">{busy?'Refreshing customer requests…':message}</p></div></main>;
}
