'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import AdminNav from '../AdminNav';

type FieldRow={field_key:string;entity_scope:'CUSTOMER'|'PROVIDER'|'BOTH';display_name:string;section:string;data_type:string;validation_rules:Record<string,unknown>;sensitivity:string;editable_by_user:boolean;can_be_required:boolean;priority:number;total_users:number;completed_users:number;missing_users:number;completion_rate:number;rule:{is_required:boolean;grace_period_days:number;effective_at:string}|null};
type Stats={total:number;average:number;complete:number;partial:number;low:number};
type AuditRow={id:string;field_key:string;old_required:boolean|null;new_required:boolean;old_grace_period_days:number|null;new_grace_period_days:number|null;created_at:string};
type IncompleteRow={auth_user_id:string;role:string;completeness:number;missing_required_field_keys:string[];updated_at:string;profile?:{email?:string|null;full_name?:string|null}|null};

type Tab='FIELDS'|'STATS'|'INCOMPLETE'|'AUDIT';

export default function AdminRequiredFieldsPage(){
 const[fields,setFields]=useState<FieldRow[]>([]);const[stats,setStats]=useState<{customer:Stats;provider:Stats}|null>(null);const[audit,setAudit]=useState<AuditRow[]>([]);const[incomplete,setIncomplete]=useState<IncompleteRow[]>([]);const[tab,setTab]=useState<Tab>('FIELDS');const[scope,setScope]=useState<'ALL'|'CUSTOMER'|'PROVIDER'>('ALL');const[message,setMessage]=useState('Loading profile requirements…');const[busy,setBusy]=useState('');const[grace,setGrace]=useState<Record<string,string>>({});const[selectedField,setSelectedField]=useState('');
 useEffect(()=>{void loadFields();void loadStats();},[]);
 async function call(body:Record<string,unknown>){const{data,error}=await supabase.functions.invoke('admin-profile-requirements',{body});if(error)throw error;if(data?.error)throw new Error(data.error);return data;}
 async function loadFields(){setBusy('load');try{const p=await call({action:'list'});setFields(p.fields||[]);const next:Record<string,string>={};for(const f of p.fields||[])next[f.field_key]=String(f.rule?.grace_period_days||0);setGrace(next);setMessage('Profile requirement configuration is up to date.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load profile requirements.');}finally{setBusy('');}}
 async function loadStats(){try{const p=await call({action:'stats'});setStats({customer:p.customer,provider:p.provider});}catch{/* surfaced when tab opens */}}
 async function loadAudit(){setBusy('audit');try{const p=await call({action:'audit'});setAudit(p.audit||[]);setMessage('Audit history loaded.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load audit history.');}finally{setBusy('');}}
 async function loadIncomplete(role:'CUSTOMER'|'PROVIDER'='CUSTOMER',fieldKey=''){setBusy('incomplete');try{const p=await call({action:'incomplete_users',role,fieldKey});setIncomplete(p.users||[]);setMessage(`${(p.users||[]).length} incomplete ${role.toLowerCase()} profile(s) loaded.`);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load incomplete profiles.');}finally{setBusy('');}}
 async function toggle(field:FieldRow){const next=!Boolean(field.rule?.is_required);if(!window.confirm(`${next?'Require':'Make optional'} “${field.display_name}”? Existing users will not be blocked because request blocking remains controlled separately in App Settings.`))return;setBusy(field.field_key);try{const p=await call({action:'toggle',fieldKey:field.field_key,isRequired:next,gracePeriodDays:Number(grace[field.field_key]||0)});setMessage(`${field.display_name} is now ${next?'required':'optional'}. ${p.prompts_queued||0} in-app prompt(s) queued.`);await Promise.all([loadFields(),loadStats()]);}catch(e){setMessage(e instanceof Error?e.message:'Unable to update field requirement.');}finally{setBusy('');}}
 async function prompt(field:FieldRow){setBusy(`prompt:${field.field_key}`);try{const p=await call({action:'prompt_users',fieldKeys:[field.field_key],role:field.entity_scope});setMessage(`${p.prompts_queued||0} in-app prompt(s) queued for ${field.display_name}.`);}catch(e){setMessage(e instanceof Error?e.message:'Unable to queue prompts.');}finally{setBusy('');}}
 async function recalc(){setBusy('recalc');try{const p=await call({action:'recalc_all'});setMessage(`${p.users_recalculated||0} customer/provider profile(s) recalculated.`);await Promise.all([loadFields(),loadStats()]);}catch(e){setMessage(e instanceof Error?e.message:'Unable to recalculate profiles.');}finally{setBusy('');}}
 const visible=useMemo(()=>fields.filter(f=>scope==='ALL'||f.entity_scope==='BOTH'||f.entity_scope===scope),[fields,scope]);
 const requiredCount=fields.filter(f=>f.rule?.is_required).length;
 return <main className="shell">
  <header className="topbar"><div><a className="brand" href="/admin">FixIt</a><p className="tagline">Admin • Profile Requirements</p></div><div className="actions"><button className="secondary" onClick={()=>void recalc()} disabled={Boolean(busy)}>{busy==='recalc'?'Recalculating…':'Recalculate'}</button><button className="secondary" onClick={()=>void loadFields()} disabled={Boolean(busy)}>Refresh</button></div></header>
  <AdminNav />
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">DYNAMIC REQUIRED FIELDS</p><h2>Profile Requirements</h2><p className="muted">Only approved registry fields can be configured. Admin cannot type arbitrary database columns.</p></div><span className="pill">{requiredCount} required</span></div>
   <div className="adminStats"><div className="statCard"><span>Approved fields</span><strong>{fields.length}</strong></div><div className="statCard"><span>Required now</span><strong>{requiredCount}</strong></div><div className="statCard"><span>Customer average</span><strong>{stats?.customer?.average??'—'}%</strong></div><div className="statCard"><span>Provider average</span><strong>{stats?.provider?.average??'—'}%</strong></div></div>
   <p className="formMessage" role="status">{message}</p>
   <div className="filterRow">{(['FIELDS','STATS','INCOMPLETE','AUDIT'] as const).map(x=><button key={x} className={tab===x?'filterChip active':'filterChip'} onClick={()=>{setTab(x);if(x==='AUDIT')void loadAudit();if(x==='INCOMPLETE')void loadIncomplete('CUSTOMER',selectedField);if(x==='STATS')void loadStats();}}>{x==='FIELDS'?'Fields':x==='STATS'?'Statistics':x==='INCOMPLETE'?'Incomplete Profiles':'Audit Log'}</button>)}</div>
  </section>

  {tab==='FIELDS'?<section className="panel"><div className="panelHeader"><div><p className="eyebrow">CONTROLLED REGISTRY</p><h2>Required Field Rules</h2></div><div className="filterRow">{(['ALL','CUSTOMER','PROVIDER'] as const).map(x=><button key={x} className={scope===x?'filterChip active':'filterChip'} onClick={()=>setScope(x)}>{x==='ALL'?'All':x[0]+x.slice(1).toLowerCase()}</button>)}</div></div>
   <div className="jobList">{visible.map(f=><article className="jobCard" key={f.field_key}><div className="jobTop"><div><strong>{f.display_name}</strong><span className="muted">{f.field_key} • {f.entity_scope} • {f.section}</span></div><span className="pill">{f.rule?.is_required?'Required':'Optional'}</span></div><div className="jobMeta"><span><b>Completion:</b> {f.completion_rate}% ({f.completed_users}/{f.total_users})</span><span><b>Missing:</b> {f.missing_users}</span><span><b>Editable by user:</b> {f.editable_by_user?'Yes':'No'}</span><span><b>Sensitivity:</b> {f.sensitivity}</span></div><div className="providerAccessRow"><label>Grace days<input type="number" min="0" max="365" value={grace[f.field_key]??'0'} onChange={e=>setGrace(g=>({...g,[f.field_key]:e.target.value}))}/></label><button className={f.rule?.is_required?'secondary':'primary'} disabled={busy===f.field_key} onClick={()=>void toggle(f)}>{busy===f.field_key?'Updating…':f.rule?.is_required?'Make Optional':'Make Required'}</button>{f.rule?.is_required?<button className="secondary" disabled={busy===`prompt:${f.field_key}`} onClick={()=>void prompt(f)}>{busy===`prompt:${f.field_key}`?'Queuing…':'Prompt Missing Users'}</button>:null}<button className="secondary" onClick={()=>{setSelectedField(f.field_key);setTab('INCOMPLETE');void loadIncomplete(f.entity_scope==='PROVIDER'?'PROVIDER':'CUSTOMER',f.field_key);}}>View Missing</button></div></article>)}{!visible.length?<div className="emptyQueue">No approved fields in this filter.</div>:null}</div>
  </section>:null}

  {tab==='STATS'?<section className="panel"><div className="panelHeader"><div><p className="eyebrow">PROFILE COMPLETENESS</p><h2>Compliance Overview</h2></div></div><div className="adminStats"><div className="statCard"><span>Customers</span><strong>{stats?.customer.total??0}</strong><small>{stats?.customer.complete??0} complete • {stats?.customer.partial??0} partial • {stats?.customer.low??0} low</small></div><div className="statCard"><span>Customer average</span><strong>{stats?.customer.average??100}%</strong></div><div className="statCard"><span>Providers</span><strong>{stats?.provider.total??0}</strong><small>{stats?.provider.complete??0} complete • {stats?.provider.partial??0} partial • {stats?.provider.low??0} low</small></div><div className="statCard"><span>Provider average</span><strong>{stats?.provider.average??100}%</strong></div></div><p className="localNotice">Completeness is calculated from the approved field registry. If no fields exist for a role, completeness is 100%. If only required or only optional fields exist, that group receives the full score weight.</p></section>:null}

  {tab==='INCOMPLETE'?<section className="panel"><div className="panelHeader"><div><p className="eyebrow">FOLLOW-UP</p><h2>Incomplete Profiles</h2></div><div className="actions"><button className="secondary" onClick={()=>void loadIncomplete('CUSTOMER',selectedField)}>Customers</button><button className="secondary" onClick={()=>void loadIncomplete('PROVIDER',selectedField)}>Providers</button><button className="secondary" onClick={()=>{setSelectedField('');void loadIncomplete('CUSTOMER','');}}>Clear Field Filter</button></div></div>{selectedField?<p className="localNotice">Filtered to missing field: <b>{selectedField}</b></p>:null}<div className="jobList">{incomplete.map(u=><article className="jobCard" key={u.auth_user_id}><div className="jobTop"><div><strong>{u.profile?.full_name||u.profile?.email||u.auth_user_id}</strong><span className="muted">{u.profile?.email||u.role}</span></div><span className="pill">{u.completeness}%</span></div><p className="jobDescription">Missing: {(u.missing_required_field_keys||[]).join(', ')||'None'}</p></article>)}{!incomplete.length?<div className="emptyQueue">No incomplete profiles in this view.</div>:null}</div></section>:null}

  {tab==='AUDIT'?<section className="panel"><div className="panelHeader"><div><p className="eyebrow">COMPLIANCE HISTORY</p><h2>Rule Audit Log</h2></div><button className="secondary" onClick={()=>void loadAudit()} disabled={busy==='audit'}>{busy==='audit'?'Loading…':'Refresh'}</button></div><div className="jobList">{audit.map(a=><article className="jobCard" key={a.id}><div className="jobTop"><strong>{a.field_key}</strong><span className="pill">{a.new_required?'Required':'Optional'}</span></div><p className="jobDescription">{a.old_required?'Required':'Optional'} → {a.new_required?'Required':'Optional'} • Grace {a.old_grace_period_days??0} → {a.new_grace_period_days??0} days</p><span className="muted">{new Date(a.created_at).toLocaleString()}</span></article>)}{!audit.length?<div className="emptyQueue">No requirement changes recorded yet.</div>:null}</div></section>:null}

  <footer className="footer"><span>FixIt Maldives</span><span>Server-gateway profile requirements</span></footer>
 </main>;
}
