'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import AdminNav from '../AdminNav';
import styles from './requests.module.css';

const API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/admin-request-oversight';
const PAGE_SIZE=10;
type Person={user_id:string;full_name?:string|null;email?:string|null};
type RequestStatus='NEW'|'PENDING'|'RESPONDED'|'ACCEPTED'|'PROCESSING'|'IN_PROGRESS'|'COMPLETED'|'CANCELLED';
type RequestRow={id:string;ticket_number:string;service_name:string;service_category_code:string;service_location_text:string;preferred_date?:string|null;problem_description:string;status:RequestStatus;source?:string|null;dispatch_state?:string|null;dispatch_tier?:string|null;dispatch_attempt?:number|null;dispatch_started_at?:string|null;dispatch_initial_deadline_at?:string|null;dispatch_extended_at?:string|null;dispatch_extension_deadline_at?:string|null;dispatch_secured_at?:string|null;dispatch_exhausted_at?:string|null;assigned_provider_label?:string|null;assigned_provider_user_id?:string|null;customer_auth_user_id?:string|null;created_by_admin_user_id?:string|null;accepted_at?:string|null;processing_at?:string|null;completed_at?:string|null;cancelled_at?:string|null;cancellation_reason?:string|null;created_at:string;updated_at:string;customer?:Person|null;createdByAdmin?:Person|null;ownershipState?:'CUSTOMER_OWNED'|'TEST_SYSTEM'|'UNLINKED';attentionReasons?:string[];needsAttention?:boolean;exception?:boolean};
type HistoryRow={from_status?:string|null;to_status:string;actor_type?:string|null;note?:string|null;created_at:string};
type MessageRow={id:string;sender_role:string;sender_label?:string|null;message_text:string;created_at:string};
type Provider={user_id:string;label:string;availability:string};
type JobRow={id?:string;status?:string;provider_user_id?:string;provider_label?:string;accepted_at?:string|null;processing_at?:string|null;completed_at?:string|null;created_at?:string|null;updated_at?:string|null};
type View='ALL'|'NEW'|'PENDING'|'ACCEPTED'|'PROCESSING'|'COMPLETED'|'CANCELLED';

const statusLabel=(s:string)=>String(s||'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const canonicalStatus=(s:string):View=>{const v=String(s||'').toUpperCase();if(v==='COMPLETED')return'COMPLETED';if(v==='PROCESSING'||v==='IN_PROGRESS')return'PROCESSING';if(v==='ACCEPTED')return'ACCEPTED';if(v==='CANCELLED')return'CANCELLED';if(v==='NEW')return'NEW';return'PENDING';};
const viewLabel:Record<View,string>={ALL:'All Requests',NEW:'New',PENDING:'Pending',ACCEPTED:'Accepted',PROCESSING:'Processing',COMPLETED:'Completed',CANCELLED:'Cancelled'};
const statusFilters:[View,string][]=[['ALL','All'],['NEW','New'],['PENDING','Pending'],['ACCEPTED','Accepted'],['PROCESSING','Processing'],['COMPLETED','Completed'],['CANCELLED','Cancelled']];
const requestCardTone=(status:string)=>canonicalStatus(status)==='COMPLETED'?'completed':canonicalStatus(status)==='PROCESSING'?'processing':['NEW','PENDING'].includes(canonicalStatus(status))?'unaccepted':'other';
const when=(v?:string|null)=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString();};

export default function AdminRequestsPage(){
 const[requests,setRequests]=useState<RequestRow[]>([]);const[view,setView]=useState<View>('ALL');const[query,setQuery]=useState('');const[page,setPage]=useState(1);const[message,setMessage]=useState('Loading service requests…');const[loading,setLoading]=useState(false);const[selected,setSelected]=useState<RequestRow|null>(null);const[history,setHistory]=useState<HistoryRow[]>([]);const[messages,setMessages]=useState<MessageRow[]>([]);const[eligible,setEligible]=useState<Provider[]>([]);const[job,setJob]=useState<JobRow|null>(null);const[providerId,setProviderId]=useState('');const[lastUpdated,setLastUpdated]=useState<Date|null>(null);
 const matches=(r:RequestRow)=>!query.trim()||`${r.ticket_number} ${r.service_name} ${r.service_location_text} ${r.customer?.full_name||''} ${r.customer?.email||''} ${r.assigned_provider_label||''} ${r.assigned_provider_user_id||''} ${r.customer_auth_user_id||''} ${(r.attentionReasons||[]).join(' ')}`.toLowerCase().includes(query.trim().toLowerCase());
 const visible=useMemo(()=>requests.filter(r=>matches(r)&&(view==='ALL'||canonicalStatus(r.status)===view)).sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()),[requests,view,query]);
 const totalPages=Math.max(1,Math.ceil(visible.length/PAGE_SIZE));const pagedVisible=useMemo(()=>visible.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE),[visible,page]);
 useEffect(()=>{void load();const id=window.setInterval(()=>void load(false),30000);return()=>window.clearInterval(id);},[]);useEffect(()=>{setPage(1);setSelected(null);},[view,query]);useEffect(()=>{if(page>totalPages)setPage(totalPages);},[page,totalPages]);
 async function token(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return'';}return data.session.access_token;}
 async function call(body:Record<string,unknown>){const t=await token();if(!t)throw new Error('Sign in required');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify(body)});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error||'Admin operation failed');return p;}
 async function load(showLoading=true){if(showLoading)setLoading(true);try{const p=await call({action:'request_list'});setRequests(p.requests||[]);setLastUpdated(new Date());setMessage('Service requests are up to date.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load service requests.');}finally{if(showLoading)setLoading(false);}}
 async function open(row:RequestRow){if(selected?.ticket_number===row.ticket_number){setSelected(null);return;}setLoading(true);try{const p=await call({action:'request_detail',ticketNumber:row.ticket_number});setSelected(p.request);setHistory(p.history||[]);setMessages(p.messages||[]);setEligible(p.eligibleProviders||[]);setJob(p.job||null);setProviderId('');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load service request detail.');}finally{setLoading(false);}}
 async function assign(){if(!selected||!providerId)return;setLoading(true);try{await call({action:'assign_provider',ticketNumber:selected.ticket_number,providerUserId:providerId});setMessage(`${selected.ticket_number} assigned successfully.`);await load();setSelected(null);}catch(e){setMessage(e instanceof Error?e.message:'Unable to assign provider.');}finally{setLoading(false);}}
 async function transition(){if(!selected)return;const current=canonicalStatus(selected.status);const target=current==='ACCEPTED'?'PROCESSING':current==='PROCESSING'?'COMPLETED':'';if(!target)return;if(!window.confirm(`Move ${selected.ticket_number} to ${target}?`))return;setLoading(true);try{await call({action:'transition_request',ticketNumber:selected.ticket_number,targetStatus:target});setMessage(`${selected.ticket_number} moved to ${target}.`);await load();setSelected(null);}catch(e){setMessage(e instanceof Error?e.message:'Unable to transition service request.');}finally{setLoading(false);}}
 function ownership(r:RequestRow){if(r.ownershipState==='CUSTOMER_OWNED')return r.customer?.full_name||r.customer?.email||'Customer';if(r.ownershipState==='TEST_SYSTEM')return'Unlinked / Test / System';return'Unlinked';}
 function detailPanel(){if(!selected)return null;const current=canonicalStatus(selected.status);return <div className="inlineRequestDetail">
  <div className="panelHeader"><div><p className="eyebrow">SERVICE REQUEST DETAIL</p><h2>{selected.ticket_number}</h2><p className="muted">Live operational record · refreshed from Supabase</p></div><button className="secondary" onClick={()=>setSelected(null)}>Close</button></div>
  <div className="trackingGrid"><div className="requestSummary"><p><b>Customer:</b> {ownership(selected)}</p><p><b>Customer ID:</b> {selected.customer_auth_user_id||'Not linked'}</p><p><b>Service:</b> {selected.service_name} ({selected.service_category_code})</p><p><b>Location:</b> {selected.service_location_text}</p><p><b>Status:</b> {statusLabel(selected.status)}</p><p><b>Provider:</b> {selected.assigned_provider_label||'Unassigned'}</p><p><b>Provider ID:</b> {selected.assigned_provider_user_id||'Unassigned'}</p><p><b>Dispatch:</b> {statusLabel(selected.dispatch_state||'Not started')} {selected.dispatch_tier?`· ${statusLabel(selected.dispatch_tier)}`:''}</p>{selected.attentionReasons?.length?<p><b>Attention:</b> {selected.attentionReasons.join(' · ')}</p>:null}<p className="jobDescription">{selected.problem_description}</p></div>
   <div>{(current==='NEW'||current==='PENDING')&&!selected.assigned_provider_user_id?<><label>Eligible provider<select value={providerId} onChange={e=>setProviderId(e.target.value)}><option value="">Select eligible provider</option>{eligible.map(p=><option key={p.user_id} value={p.user_id}>{p.label} — {p.availability}</option>)}</select></label><button className="primary button" disabled={!providerId||loading||current!=='NEW'} onClick={()=>void assign()}>Assign Provider</button>{current==='PENDING'?<p className="localNotice">Automatic provider matching is active. Manual assignment is limited to NEW admin-managed requests.</p>:!eligible.length?<p className="localNotice">No approved eligible provider currently matches the service and location.</p>:null}</>:current==='ACCEPTED'||current==='PROCESSING'?<button className="primary" disabled={loading} onClick={()=>void transition()}>{current==='ACCEPTED'?'Start Processing':'Mark Completed'}</button>:<span className="completedLabel">No lifecycle action required</span>}</div></div>
  <h3>Lifecycle timestamps</h3><div className="jobMeta requestMeta"><span><b>Created</b>{when(selected.created_at)}</span><span><b>Accepted</b>{when(selected.accepted_at||job?.accepted_at)}</span><span><b>Processing</b>{when(selected.processing_at||job?.processing_at)}</span><span><b>Completed</b>{when(selected.completed_at||job?.completed_at)}</span><span><b>Updated</b>{when(selected.updated_at)}</span><span><b>Dispatch started</b>{when(selected.dispatch_started_at)}</span><span><b>Dispatch secured</b>{when(selected.dispatch_secured_at)}</span><span><b>Dispatch exhausted</b>{when(selected.dispatch_exhausted_at)}</span></div>
  {job?<><h3>Service job</h3><div className="jobCard"><strong>{job.provider_label||selected.assigned_provider_label||'Provider'} · {statusLabel(job.status||selected.status)}</strong><p className="jobDescription">Provider ID: {job.provider_user_id||selected.assigned_provider_user_id||'—'}</p><span className="muted">Job record {job.id||'—'} · Updated {when(job.updated_at)}</span></div></>:null}
  <h3>Status history</h3><div className="jobList">{history.map((h,i)=><div className="jobCard" key={`${h.created_at}:${i}`}><strong>{h.from_status||'START'} → {h.to_status}</strong><p className="jobDescription">{h.note||'Status updated'}</p><span className="muted">{h.actor_type||'SYSTEM'} · {when(h.created_at)}</span></div>)}{!history.length?<div className="emptyQueue">No status history recorded.</div>:null}</div>
  <h3>Messages</h3><div className="jobList">{messages.map(m=><div className="jobCard" key={m.id}><strong>{m.sender_label||m.sender_role}</strong><p className="jobDescription">{m.message_text}</p><span className="muted">{when(m.created_at)}</span></div>)}{!messages.length?<div className="emptyQueue">No messages yet.</div>:null}</div>
  {selected.cancellation_reason?<div className="localNotice"><b>Cancellation:</b> {selected.cancellation_reason} · {when(selected.cancelled_at)}</div>:null}
 </div>}
 return <main className={`${styles.page} shell adminRequestsPage`}><header className="topbar adminRequestsTopbar"><div><p className="tagline">Monitor, manage and resolve customer requests.</p></div><button className="primary refreshAction" onClick={()=>void load()} disabled={loading}><span aria-hidden="true">↻</span>{loading?'Refreshing…':'Refresh'}</button></header><AdminNav />
  <section className="requestToolbarPanel"><div className="requestStatusBar" role="status"><span className="statusCheck">✓</span><span><b>{message}</b>{lastUpdated?<small>Last updated {lastUpdated.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small>:null}</span></div><div className="requestSearchRow"><label className="requestSearchLabel">Search<span className="requestSearchBox"><span aria-hidden="true">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ticket, customer, provider, ID, service or location"/></span></label></div><div className="filterRow requestFilterRow" aria-label="Filter by latest status">{statusFilters.map(([key,label])=><button key={key} className={`statusFilter statusFilter-${key.toLowerCase()} ${view===key?'active':''}`} onClick={()=>setView(key)}><span className="statusFilterDot" aria-hidden="true"/>{label}</button>)}</div></section>
  <section className="panel requestsListPanel"><div className="panelHeader"><div><p className="eyebrow">LATEST STATUS</p><h2>{viewLabel[view]}</h2><p className="muted">Showing {visible.length} request{visible.length===1?'':'s'}. Newest requests appear first.</p></div></div><div className="jobList">{pagedVisible.map(r=><div className="requestCardGroup" key={r.ticket_number}><article className={`jobCard requestRowCard requestCardTone-${requestCardTone(r.status)}`}><div className="jobTop"><div><strong className="ticket">{r.ticket_number}</strong><span className="requestServiceName">{r.service_name}</span></div><span className={`requestStatus requestStatus-${canonicalStatus(r.status).toLowerCase()}`}>{statusLabel(r.status)}</span></div><div className="jobMeta requestMeta"><span><b>Customer</b>{ownership(r)}</span><span><b>Location</b>{r.service_location_text}</span><span><b>Provider</b>{r.assigned_provider_label||'Unassigned'}</span><span><b>Dispatch</b>{statusLabel(r.dispatch_state||'Not started')}</span><span><b>Created</b>{when(r.created_at)}</span><span><b>Updated</b>{when(r.updated_at)}</span></div>{r.attentionReasons?.length?<div className="attentionNotice"><b>Needs attention</b><span>{r.attentionReasons.join(' · ')}</span></div>:null}<div className="actions requestRowActions"><button className="primary" onClick={()=>void open(r)}>{selected?.ticket_number===r.ticket_number?'Close Details':'Open Request'}</button></div></article>{selected?.ticket_number===r.ticket_number?detailPanel():null}</div>)}{!visible.length?<div className="emptyQueue">No service requests match this latest status.</div>:null}</div>{visible.length>PAGE_SIZE?<div className="paginationBar"><button className="secondary" disabled={page===1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><span className="muted">Page {page} of {totalPages} · {visible.length} requests</span><button className="secondary" disabled={page===totalPages} onClick={()=>setPage(p=>Math.min(totalPages,p+1))}>Next</button></div>:null}</section></main>;
}
