'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import AdminNav from '../AdminNav';

const API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/admin-marketplace';
type Customer={user_id:string;full_name?:string|null;email?:string|null};
type RequestRow={id:string;ticket_number:string;service_name:string;service_category_code:string;service_location_text:string;preferred_date:string;problem_description:string;status:'NEW'|'ACCEPTED'|'PROCESSING'|'COMPLETED';assigned_provider_label?:string|null;assigned_provider_user_id?:string|null;customer_auth_user_id?:string|null;created_at:string;updated_at:string;customer?:Customer|null};
type HistoryRow={from_status?:string|null;to_status:string;actor_type?:string|null;note?:string|null;created_at:string};
type MessageRow={id:string;sender_role:string;sender_label?:string|null;message_text:string;created_at:string};
type Provider={user_id:string;label:string;availability:string};
const labels:Record<RequestRow['status'],string>={NEW:'New',ACCEPTED:'Accepted',PROCESSING:'Processing',COMPLETED:'Completed'};

export default function AdminRequestsPage(){
 const[requests,setRequests]=useState<RequestRow[]>([]);const[filter,setFilter]=useState<'ALL'|RequestRow['status']>('ALL');const[query,setQuery]=useState('');const[message,setMessage]=useState('Loading requests…');const[loading,setLoading]=useState(false);const[selected,setSelected]=useState<RequestRow|null>(null);const[history,setHistory]=useState<HistoryRow[]>([]);const[messages,setMessages]=useState<MessageRow[]>([]);const[eligible,setEligible]=useState<Provider[]>([]);const[providerId,setProviderId]=useState('');
 const visible=useMemo(()=>requests.filter(r=>(filter==='ALL'||r.status===filter)&&(!query.trim()||`${r.ticket_number} ${r.service_name} ${r.service_location_text} ${r.customer?.full_name||''} ${r.customer?.email||''} ${r.assigned_provider_label||''}`.toLowerCase().includes(query.trim().toLowerCase()))),[filter,requests,query]);
 useEffect(()=>{void load();},[]);
 async function token(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return '';}return data.session.access_token;}
 async function call(body:Record<string,unknown>){const t=await token();if(!t)throw new Error('Sign in required');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Admin operation failed');return p;}
 async function load(){setLoading(true);try{const p=await call({action:'request_list'});setRequests(p.requests||[]);setMessage('Request operations loaded.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load requests.');}finally{setLoading(false);}}
 async function open(row:RequestRow){setLoading(true);try{const p=await call({action:'request_detail',ticketNumber:row.ticket_number});setSelected(p.request);setHistory(p.history||[]);setMessages(p.messages||[]);setEligible(p.eligibleProviders||[]);setProviderId('');setMessage(`${row.ticket_number} loaded.`);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load request detail.');}finally{setLoading(false);}}
 async function assign(){if(!selected||!providerId)return;setLoading(true);try{await call({action:'assign_provider',ticketNumber:selected.ticket_number,providerUserId:providerId});setMessage(`${selected.ticket_number} assigned successfully.`);await load();const refreshed=requests.find(r=>r.ticket_number===selected.ticket_number);if(refreshed)await open(refreshed);else setSelected(null);}catch(e){setMessage(e instanceof Error?e.message:'Unable to assign provider.');}finally{setLoading(false);}}
 async function transition(){if(!selected)return;const target=selected.status==='ACCEPTED'?'PROCESSING':selected.status==='PROCESSING'?'COMPLETED':'';if(!target)return;if(!window.confirm(`Move ${selected.ticket_number} to ${target}?`))return;setLoading(true);try{await call({action:'transition_request',ticketNumber:selected.ticket_number,targetStatus:target});setMessage(`${selected.ticket_number} moved to ${target}.`);await load();setSelected(null);}catch(e){setMessage(e instanceof Error?e.message:'Unable to transition request.');}finally{setLoading(false);}}
 const counts=useMemo(()=>({NEW:requests.filter(r=>r.status==='NEW').length,ACCEPTED:requests.filter(r=>r.status==='ACCEPTED').length,PROCESSING:requests.filter(r=>r.status==='PROCESSING').length,COMPLETED:requests.filter(r=>r.status==='COMPLETED').length}),[requests]);
 return <main className="shell"><header className="topbar"><div><a className="brand" href="/admin">FixIt</a><p className="tagline">Admin • Request Operations</p></div><button className="secondary" onClick={()=>void load()} disabled={loading}>{loading?'Loading…':'Refresh'}</button></header><AdminNav />
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">REQUEST OPERATIONS</p><h2>Lifecycle & assignment control</h2></div><span className="pill">{requests.length} total</span></div><div className="adminStats"><div className="statCard"><span>New</span><strong>{counts.NEW}</strong></div><div className="statCard"><span>Accepted</span><strong>{counts.ACCEPTED}</strong></div><div className="statCard"><span>Processing</span><strong>{counts.PROCESSING}</strong></div><div className="statCard"><span>Completed</span><strong>{counts.COMPLETED}</strong></div></div><p className="formMessage" role="status">{message}</p><div className="formGrid"><label className="full">Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ticket, customer, provider, service or location"/></label></div><div className="filterRow">{(['ALL','NEW','ACCEPTED','PROCESSING','COMPLETED'] as const).map(item=><button key={item} className={filter===item?'filterChip active':'filterChip'} onClick={()=>setFilter(item)}>{item==='ALL'?'All':labels[item]}</button>)}</div></section>
  <section className="panel"><div className="jobList">{visible.map(r=><article className="jobCard" key={r.ticket_number}><div className="jobTop"><div><strong className="ticket">{r.ticket_number}</strong><span className="muted">{r.service_name}</span></div><span className="pill">{labels[r.status]}</span></div><div className="jobMeta"><span><b>Location:</b> {r.service_location_text}</span><span><b>Preferred:</b> {r.preferred_date}</span><span><b>Customer:</b> {r.customer?.full_name||r.customer?.email||'Customer'}</span><span><b>Provider:</b> {r.assigned_provider_label||'Unassigned'}</span></div><p className="jobDescription">{r.problem_description}</p><div className="actions"><button className="primary" onClick={()=>void open(r)}>Open Operations</button></div></article>)}{!visible.length?<div className="emptyQueue">No requests match this view.</div>:null}</div></section>
  {selected?<section className="panel"><div className="panelHeader"><div><p className="eyebrow">REQUEST CONTROL</p><h2>{selected.ticket_number}</h2></div><button className="secondary" onClick={()=>setSelected(null)}>Close</button></div><div className="trackingGrid"><div className="requestSummary"><p><b>Service:</b> {selected.service_name}</p><p><b>Location:</b> {selected.service_location_text}</p><p><b>Status:</b> {selected.status}</p><p><b>Provider:</b> {selected.assigned_provider_label||'Unassigned'}</p><p className="jobDescription">{selected.problem_description}</p></div><div>{selected.status==='NEW'&&!selected.assigned_provider_user_id?<><label>Eligible provider<select value={providerId} onChange={e=>setProviderId(e.target.value)}><option value="">Select eligible provider</option>{eligible.map(p=><option key={p.user_id} value={p.user_id}>{p.label} — {p.availability}</option>)}</select></label><button className="primary button" disabled={!providerId||loading} onClick={()=>void assign()}>Assign Provider</button>{!eligible.length?<p className="localNotice">No approved provider currently matches both service and exact service area.</p>:null}</>:selected.status==='ACCEPTED'||selected.status==='PROCESSING'?<button className="primary" disabled={loading} onClick={()=>void transition()}>{selected.status==='ACCEPTED'?'Start Processing':'Mark Completed'}</button>:<span className="completedLabel">Lifecycle complete</span>}</div></div><h3>Status history</h3><div className="jobList">{history.map((h,i)=><div className="jobCard" key={`${h.created_at}:${i}`}><strong>{h.from_status||'START'} → {h.to_status}</strong><p className="jobDescription">{h.note||'Status updated'}</p><span className="muted">{h.actor_type||'SYSTEM'} · {new Date(h.created_at).toLocaleString()}</span></div>)}</div><h3>Messages</h3><div className="jobList">{messages.map(m=><div className="jobCard" key={m.id}><strong>{m.sender_label||m.sender_role}</strong><p className="jobDescription">{m.message_text}</p><span className="muted">{new Date(m.created_at).toLocaleString()}</span></div>)}{!messages.length?<div className="emptyQueue">No messages yet.</div>:null}</div></section>:null}
 </main>;
}
