'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import AdminNav from '../AdminNav';
import styles from './requests.module.css';

const API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/admin-request-oversight';
const PAGE_SIZE=10;
type Person={user_id:string;full_name?:string|null;email?:string|null};
type RequestStatus='NEW'|'PENDING'|'ACCEPTED'|'PROCESSING'|'COMPLETED'|'CANCELLED';
type RequestRow={id:string;ticket_number:string;service_name:string;service_category_code:string;service_location_text:string;preferred_date:string;problem_description:string;status:RequestStatus;source?:string|null;dispatch_state?:string|null;assigned_provider_label?:string|null;assigned_provider_user_id?:string|null;customer_auth_user_id?:string|null;created_by_admin_user_id?:string|null;created_at:string;updated_at:string;customer?:Person|null;createdByAdmin?:Person|null;ownershipState?:'CUSTOMER_OWNED'|'TEST_SYSTEM'|'UNLINKED';attentionReasons?:string[];needsAttention?:boolean;exception?:boolean};
type HistoryRow={from_status?:string|null;to_status:string;actor_type?:string|null;note?:string|null;created_at:string};
type MessageRow={id:string;sender_role:string;sender_label?:string|null;message_text:string;created_at:string};
type Provider={user_id:string;label:string;availability:string};
type View='ALL'|RequestStatus;
const statusLabel=(s:string)=>s.charAt(0)+s.slice(1).toLowerCase();
const viewLabel:Record<View,string>={ALL:'All Requests',NEW:'New',PENDING:'Pending',ACCEPTED:'Accepted',PROCESSING:'Processing',COMPLETED:'Completed',CANCELLED:'Cancelled'};
const requestCardTone=(status:RequestStatus)=>status==='COMPLETED'?'completed':status==='PROCESSING'?'processing':status==='NEW'||status==='PENDING'?'unaccepted':'other';
const statusFilters:[View,string][]=[['ALL','All'],['NEW','New'],['PENDING','Pending'],['ACCEPTED','Accepted'],['PROCESSING','Processing'],['COMPLETED','Completed'],['CANCELLED','Cancelled']];

export default function AdminRequestsPage(){
 const[requests,setRequests]=useState<RequestRow[]>([]);const[view,setView]=useState<View>('ALL');const[query,setQuery]=useState('');const[page,setPage]=useState(1);const[message,setMessage]=useState('Loading service requests…');const[loading,setLoading]=useState(false);const[selected,setSelected]=useState<RequestRow|null>(null);const[history,setHistory]=useState<HistoryRow[]>([]);const[messages,setMessages]=useState<MessageRow[]>([]);const[eligible,setEligible]=useState<Provider[]>([]);const[providerId,setProviderId]=useState('');const[lastUpdated,setLastUpdated]=useState<Date|null>(null);
 const matches=(r:RequestRow)=>!query.trim()||`${r.ticket_number} ${r.service_name} ${r.service_location_text} ${r.customer?.full_name||''} ${r.customer?.email||''} ${r.assigned_provider_label||''} ${(r.attentionReasons||[]).join(' ')}`.toLowerCase().includes(query.trim().toLowerCase());
 const visible=useMemo(()=>requests.filter(r=>matches(r)&&(view==='ALL'||r.status===view)).sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()||new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime()),[view,requests,query]);
 const totalPages=Math.max(1,Math.ceil(visible.length/PAGE_SIZE));
 const pagedVisible=useMemo(()=>visible.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE),[visible,page]);
 useEffect(()=>{void load();},[]);
 useEffect(()=>{setPage(1);setSelected(null);},[view,query]);
 useEffect(()=>{if(page>totalPages)setPage(totalPages);},[page,totalPages]);
 async function token(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return '';}return data.session.access_token;}
 async function call(body:Record<string,unknown>){const t=await token();if(!t)throw new Error('Sign in required');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Admin operation failed');return p;}
 async function load(){setLoading(true);try{const p=await call({action:'request_list'});setRequests(p.requests||[]);setLastUpdated(new Date());setMessage('Service requests are up to date.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load service requests.');}finally{setLoading(false);}}
 async function open(row:RequestRow){if(selected?.ticket_number===row.ticket_number){setSelected(null);return;}setLoading(true);try{const p=await call({action:'request_detail',ticketNumber:row.ticket_number});setSelected(p.request);setHistory(p.history||[]);setMessages(p.messages||[]);setEligible(p.eligibleProviders||[]);setProviderId('');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load service request detail.');}finally{setLoading(false);}}
 async function assign(){if(!selected||!providerId)return;setLoading(true);try{await call({action:'assign_provider',ticketNumber:selected.ticket_number,providerUserId:providerId});setMessage(`${selected.ticket_number} assigned successfully.`);await load();setSelected(null);}catch(e){setMessage(e instanceof Error?e.message:'Unable to assign provider.');}finally{setLoading(false);}}
 async function transition(){if(!selected)return;const target=selected.status==='ACCEPTED'?'PROCESSING':selected.status==='PROCESSING'?'COMPLETED':'';if(!target)return;if(!window.confirm(`Move ${selected.ticket_number} to ${target}?`))return;setLoading(true);try{await call({action:'transition_request',ticketNumber:selected.ticket_number,targetStatus:target});setMessage(`${selected.ticket_number} moved to ${target}.`);await load();setSelected(null);}catch(e){setMessage(e instanceof Error?e.message:'Unable to transition service request.');}finally{setLoading(false);}}
 function ownership(r:RequestRow){if(r.ownershipState==='CUSTOMER_OWNED')return r.customer?.full_name||r.customer?.email||'Customer';if(r.ownershipState==='TEST_SYSTEM')return 'Unlinked / Test / System';return 'Unlinked';}
 function detailPanel(){if(!selected)return null;return <div className="inlineRequestDetail"><div className="panelHeader"><div><p className="eyebrow">SERVICE REQUEST DETAIL</p><h2>{selected.ticket_number}</h2></div><button className="secondary" onClick={()=>setSelected(null)}>Close</button></div><div className="trackingGrid"><div className="requestSummary"><p><b>Customer:</b> {ownership(selected)}</p><p><b>Service:</b> {selected.service_name}</p><p><b>Location:</b> {selected.service_location_text}</p><p><b>Status:</b> {statusLabel(selected.status)}</p><p><b>Provider:</b> {selected.assigned_provider_label||'Unassigned'}</p>{selected.attentionReasons?.length?<p><b>Attention:</b> {selected.attentionReasons.join(' · ')}</p>:null}<p className="jobDescription">{selected.problem_description}</p></div><div>{(selected.status==='NEW'||selected.status==='PENDING')&&!selected.assigned_provider_user_id?<><label>Eligible provider<select value={providerId} onChange={e=>setProviderId(e.target.value)}><option value="">Select eligible provider</option>{eligible.map(p=><option key={p.user_id} value={p.user_id}>{p.label} — {p.availability}</option>)}</select></label><button className="primary button" disabled={!providerId||loading||selected.status!=='NEW'} onClick={()=>void assign()}>Assign Provider</button>{selected.status==='PENDING'?<p className="localNotice">This legacy pending request must be normalized to NEW before assignment.</p>:!eligible.length?<p className="localNotice">No approved and eligible provider currently matches both the service and service location.</p>:null}</>:selected.status==='ACCEPTED'||selected.status==='PROCESSING'?<button className="primary" disabled={loading} onClick={()=>void transition()}>{selected.status==='ACCEPTED'?'Start Processing':'Mark Completed'}</button>:<span className="completedLabel">No lifecycle action required</span>}</div></div><h3>Status history</h3><div className="jobList">{history.map((h,i)=><div className="jobCard" key={`${h.created_at}:${i}`}><strong>{h.from_status||'START'} → {h.to_status}</strong><p className="jobDescription">{h.note||'Status updated'}</p><span className="muted">{h.actor_type||'SYSTEM'} · {new Date(h.created_at).toLocaleString()}</span></div>)}</div><h3>Messages</h3><div className="jobList">{messages.map(m=><div className="jobCard" key={m.id}><strong>{m.sender_label||m.sender_role}</strong><p className="jobDescription">{m.message_text}</p><span className="muted">{new Date(m.created_at).toLocaleString()}</span></div>)}{!messages.length?<div className="emptyQueue">No messages yet.</div>:null}</div></div>}
 return <main className={`${styles.page} shell adminRequestsPage`}>
  <header className="topbar adminRequestsTopbar"><div><p className="eyebrow">ADMIN WORKSPACE</p><h1 className="pageTitle">Service Requests</h1><p className="tagline">Monitor, manage and resolve customer requests.</p></div><button className="primary refreshAction" onClick={()=>void load()} disabled={loading}><span aria-hidden="true">↻</span>{loading?'Refreshing…':'Refresh'}</button></header>
  <AdminNav />

  <section className="requestToolbarPanel">
   <div className="requestStatusBar" role="status"><span className="statusCheck">✓</span><span><b>{message}</b>{lastUpdated?<small>Last updated {lastUpdated.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small>:null}</span></div>
   <div className="requestSearchRow"><label className="requestSearchLabel">Search<span className="requestSearchBox"><span aria-hidden="true">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ticket, customer, provider, service or location"/></span></label></div>
   <div className="filterRow requestFilterRow" aria-label="Filter by latest status">{statusFilters.map(([key,label])=><button key={key} className={`statusFilter statusFilter-${key.toLowerCase()} ${view===key?'active':''}`} onClick={()=>setView(key)}><span className="statusFilterDot" aria-hidden="true"/>{label}</button>)}</div>
  </section>

  <section className="panel requestsListPanel"><div className="panelHeader"><div><p className="eyebrow">LATEST STATUS</p><h2>{viewLabel[view]}</h2><p className="muted">Showing {visible.length} request{visible.length===1?'':'s'} by current/latest status. Newest requests appear first.</p></div></div><div className="jobList">{pagedVisible.map(r=><div className="requestCardGroup" key={r.ticket_number}><article className={`jobCard requestRowCard requestCardTone-${requestCardTone(r.status)}`}><div className="jobTop"><div><strong className="ticket">{r.ticket_number}</strong><span className="requestServiceName">{r.service_name}</span></div><span className={`requestStatus requestStatus-${r.status.toLowerCase()}`}>{statusLabel(r.status)}</span></div><div className="jobMeta requestMeta"><span><b>Customer</b>{ownership(r)}</span><span><b>Location</b>{r.service_location_text}</span><span><b>Provider</b>{r.assigned_provider_label||'Unassigned'}</span><span><b>Created</b>{new Date(r.created_at).toLocaleString()}</span><span><b>Updated</b>{new Date(r.updated_at).toLocaleString()}</span></div>{r.attentionReasons?.length?<div className="attentionNotice"><b>Needs attention</b><span>{r.attentionReasons.join(' · ')}</span></div>:null}<div className="actions requestRowActions"><button className="primary" onClick={()=>void open(r)}>{selected?.ticket_number===r.ticket_number?'Close Details':'Open Request'}</button></div></article>{selected?.ticket_number===r.ticket_number?detailPanel():null}</div>)}{!visible.length?<div className="emptyQueue">No service requests match this latest status.</div>:null}</div>{visible.length>PAGE_SIZE?<div className="paginationBar"><button className="secondary" disabled={page===1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><span className="muted">Page {page} of {totalPages} · {visible.length} requests</span><button className="secondary" disabled={page===totalPages} onClick={()=>setPage(p=>Math.min(totalPages,p+1))}>Next</button></div>:null}</section>
 </main>;
}
