'use client';

import { useEffect, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import AppModeSwitch from '../../AppModeSwitch';
import { useProviderMode } from '../useProviderMode';

const ONBOARDING_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/provider-onboarding';
const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
type Hour={dayOfWeek:number;isWorking:boolean;startTime:string;endTime:string};
export default function ProviderAvailabilityPage(){
 const mode=useProviderMode(true);const[hours,setHours]=useState<Hour[]>([]);const[availability,setAvailability]=useState('BY_APPOINTMENT');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
 useEffect(()=>{if(!mode.ready)return;setAvailability(mode.profile?.availability_status||'BY_APPOINTMENT');setHours(days.map((_,i)=>{const h=mode.hours.find((x:any)=>Number(x.day_of_week)===i+1);return{dayOfWeek:i+1,isWorking:Boolean(h?.is_working),startTime:String(h?.start_time||'08:00').slice(0,5),endTime:String(h?.end_time||'17:00').slice(0,5)}}));},[mode.ready,mode.hours,mode.profile]);
 function patch(day:number,p:Partial<Hour>){setHours(v=>v.map(h=>h.dayOfWeek===day?{...h,...p}:h));}
 async function save(){setBusy(true);try{const{data}=await supabase.auth.getSession();if(!data.session)throw new Error('Sign in required');const p=mode.profile||{};const r=await fetch(ONBOARDING_URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({action:'save',providerType:p.provider_type||'INDIVIDUAL',publicName:p.public_name||mode.name,businessName:p.business_name||'',description:p.description||'',experienceYears:Number(p.experience_years||0),availabilityStatus:availability,categoryIds:mode.selectedCategoryIds,hours,serviceAreas:mode.serviceAreas.map((a:any)=>({islandId:a.islandId,locationUnitId:a.locationUnitId||null}))})});const out=await r.json();if(!r.ok)throw new Error(out?.error||'Unable to save availability');setMessage('Availability updated.');await mode.reload();}catch(e){setMessage(e instanceof Error?e.message:'Unable to save availability.');}finally{setBusy(false);}}
 if(mode.loading)return <main className="providerModePage"><div className="providerModeShell"><div className="providerModeCard">Loading availability…</div></div></main>;
 return <main className="providerModePage"><div className="providerModeShell"><header className="providerModeTop"><div><span className="modeBadge provider"><span className="modeDot provider"/>Provider</span><h1>Availability</h1><p>Control when FixIt can match and schedule customer work with you.</p></div><AppModeSwitch mode="provider" compact/></header><section className="providerModeCard"><div className="providerSectionHead"><div><h2>Availability status</h2><p>This affects whether you can receive new matched requests.</p></div></div><select value={availability} onChange={e=>setAvailability(e.target.value)}><option value="AVAILABLE_NOW">Available now</option><option value="AVAILABLE_TODAY">Available today</option><option value="BY_APPOINTMENT">By appointment</option><option value="UNAVAILABLE">Unavailable</option></select></section><section className="providerModeCard"><div className="providerSectionHead"><div><h2>Weekly hours</h2><p>Times use Maldives time.</p></div></div><div className="providerAvailabilityEditor">{hours.map((h,i)=><div className="providerAvailabilityRow" key={h.dayOfWeek}><label><input type="checkbox" checked={h.isWorking} onChange={e=>patch(h.dayOfWeek,{isWorking:e.target.checked})}/><strong>{days[i]}</strong></label><input type="time" disabled={!h.isWorking} value={h.startTime} onChange={e=>patch(h.dayOfWeek,{startTime:e.target.value})}/><span>to</span><input type="time" disabled={!h.isWorking} value={h.endTime} onChange={e=>patch(h.dayOfWeek,{endTime:e.target.value})}/></div>)}</div><div className="providerSetupActions"><a className="secondary" href="/provider/calendar">Back to Calendar</a><button className="primary" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save availability'}</button></div>{message?<p className="muted" role="status">{message}</p>:null}</section></div></main>;
}
