'use client';

import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import { supabase } from '../../../lib/supabaseClient';
import './marketplace.css';

const DETAIL_API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/customer-requests';
const MARKET_API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/customer-marketplace';
const MESSAGE_URL='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/request-messages';
const workflow=['NEW','ACCEPTED','PROCESSING','COMPLETED'] as const;

type RequestRow={id:string;ticket_number:string;service_name:string;service_category_code?:string|null;service_subcategory_code?:string|null;service_location_text:string;preferred_date:string;problem_description:string;urgency?:string|null;customer_notes?:string|null;status:string;assigned_provider_label?:string|null;assigned_provider_user_id?:string|null;accepted_at?:string|null;processing_at?:string|null;completed_at?:string|null;created_at:string;updated_at:string};
type HistoryRow={from_status?:string|null;to_status:string;actor_type?:string|null;note?:string|null;created_at:string};
type MessageRow={id:string;sender_role:string;sender_label?:string|null;message_text:string;created_at:string};
type ProviderCard={userId:string;name:string;businessName?:string|null;description?:string|null;profilePhotoUrl?:string|null;experienceYears:number;specialty:string[];rating:number|null;reviewCount:number;completedJobs:number;verified:boolean;availability:string;message?:string|null;responseStatus?:string|null};
type Inspection={id:string;preferred_slots:string[];scheduled_start?:string|null;duration_minutes?:number|null;status:string;provider_note?:string|null};
type Estimate={id:string;findings:string;recommended_work:string;estimated_minutes?:number|null;labour_amount:number|string;material_amount:number|string;total_amount:number|string;currency:string;status:string;customer_note?:string|null;sent_at:string;decided_at?:string|null};
type Completion={id:string;work_performed:string[];labour_amount:number|string;material_amount:number|string;final_amount:number|string;currency:string;payment_note:string;status:string;submitted_at:string;confirmed_at?:string|null;issue_note?:string|null};
type Review={satisfied?:boolean|null;rating?:number|null;review_text?:string|null;created_at?:string};
type Journey={request:RequestRow;providerOptions:ProviderCard[];selectedProvider:ProviderCard|null;inspection:Inspection|null;estimate:Estimate|null;completion:Completion|null;review:Review|null;paymentProcessing:boolean};

function money(value:number|string|undefined,currency='MVR'){const n=Number(value||0);return `${currency} ${Number.isFinite(n)?n.toFixed(2):'0.00'}`;}
function when(value?:string|null){if(!value)return 'Not set';const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString();}
function shortStatus(value:string){return value.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());}

export default function RequestDetailPage(){
 const params=useParams<{ticket:string}>();const ticket=decodeURIComponent(String(params.ticket||'')).toUpperCase();
 const[request,setRequest]=useState<RequestRow|null>(null);const[history,setHistory]=useState<HistoryRow[]>([]);const[messages,setMessages]=useState<MessageRow[]>([]);const[journey,setJourney]=useState<Journey|null>(null);const[message,setMessage]=useState('Loading request…');const[busy,setBusy]=useState(false);const[text,setText]=useState('');
 const[expandedProvider,setExpandedProvider]=useState<string|null>(null);const[showSchedule,setShowSchedule]=useState(false);const[slots,setSlots]=useState(['','','']);const[estimateNote,setEstimateNote]=useState('');const[satisfied,setSatisfied]=useState<boolean|null>(null);const[rating,setRating]=useState(0);const[reviewText,setReviewText]=useState('');const[problemText,setProblemText]=useState('');
 useEffect(()=>{if(ticket)void load();},[ticket]);
 async function token(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return '';}return data.session.access_token;}
 async function load(){setBusy(true);try{const t=await token();if(!t)return;const headers={'Content-Type':'application/json','Authorization':`Bearer ${t}`};const[detailResponse,marketResponse]=await Promise.all([
   fetch(DETAIL_API,{method:'POST',headers,body:JSON.stringify({action:'detail',ticketNumber:ticket})}),
   fetch(MARKET_API,{method:'POST',headers,body:JSON.stringify({action:'journey',ticketNumber:ticket})})
  ]);const detail=await detailResponse.json();const market=await marketResponse.json();if(!detailResponse.ok)throw new Error(detail?.error||'Unable to load request');if(!marketResponse.ok)throw new Error(market?.error||'Unable to load marketplace journey');setRequest(market.request||detail.request);setHistory(detail.history||[]);setMessages(detail.messages||[]);setJourney(market as Journey);setMessage('Request is up to date.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load request.');}finally{setBusy(false);}}
 async function marketAction(action:string,payload:Record<string,unknown>={}){setBusy(true);try{const t=await token();if(!t)return null;const r=await fetch(MARKET_API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify({action,ticketNumber:ticket,...payload})});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to update request');setJourney(p as Journey);setRequest(p.request||request);setMessage('Request updated successfully.');return p;}catch(e){setMessage(e instanceof Error?e.message:'Unable to update request.');return null;}finally{setBusy(false);}}
 async function selectProvider(providerUserId:string){const result=await marketAction('select_provider',{providerUserId});if(result){setExpandedProvider(null);await load();}}
 async function proposeInspection(){const preferredSlots=slots.map(x=>x.trim()).filter(Boolean);if(!preferredSlots.length){setMessage('Choose at least one preferred inspection time.');return;}const result=await marketAction('propose_inspection',{preferredSlots});if(result){setShowSchedule(false);setSlots(['','','']);}}
 async function decideEstimate(decision:'APPROVE'|'DECLINE'){const result=await marketAction('decide_estimate',{decision,note:estimateNote.trim()||null});if(result){setEstimateNote('');await load();}}
 async function confirmCompletion(){if(satisfied===null){setMessage('Please tell us whether you are satisfied.');return;}if(rating<1||rating>5){setMessage('Please select a rating from 1 to 5 stars.');return;}const result=await marketAction('confirm_completion',{satisfied,rating,review:reviewText.trim()});if(result){await load();}}
 async function reportProblem(){if(problemText.trim().length<5){setMessage('Please describe the problem before reporting it.');return;}const result=await marketAction('report_problem',{note:problemText.trim()});if(result){setProblemText('');await load();}}
 async function send(){if(!text.trim())return;setBusy(true);try{const t=await token();const r=await fetch(MESSAGE_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify({action:'send',ticketNumber:ticket,message:text.trim()})});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to send message');setText('');await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to send message.');}finally{setBusy(false);}}
 function goMessages(){document.getElementById('messages')?.scrollIntoView({behavior:'smooth',block:'start'});}
 const activeStep=request?Math.max(0,workflow.indexOf(request.status as typeof workflow[number])):0;
 const selected=journey?.selectedProvider||null;const inspection=journey?.inspection||null;const estimate=journey?.estimate||null;const completion=journey?.completion||null;const review=journey?.review||null;
 const inspectionSteps=useMemo(()=>['SCHEDULED','ON_WAY','ARRIVED','INSPECTING','ESTIMATE_SENT'],[]);
 const inspectionIndex=inspection?inspectionSteps.indexOf(inspection.status):-1;

 return <main className="shell marketplacePage">
  <header className="topbar"><div><a className="brand" href="/">FixIt</a><p className="tagline">Service Marketplace</p></div><div className="actions"><a className="secondary" href="/requests">← My Requests</a><button className="secondary" onClick={()=>void load()} disabled={busy}>{busy?'Refreshing…':'Refresh'}</button></div></header>

  <section className="marketHero"><div className="marketHeroCard"><p className="eyebrow">CUSTOMER REQUEST</p><div className="journeyStatus"><h1>{request?.ticket_number||ticket}</h1>{request?<span className="pill">{shortStatus(request.status)}</span>:null}</div>{request?<><p><b>{request.service_name}</b> · {request.service_location_text}</p><p className="muted">{request.problem_description}</p><div className="stageStrip">{workflow.map((item,index)=><div key={item} className={index<=activeStep?'stagePill active':'stagePill'}>{shortStatus(item)}</div>)}</div></>:null}</div>
   <div className="marketHeroCard"><p className="smallLabel">CURRENT NEXT STEP</p><h2>{request?.status==='NEW'?'Choose a provider':request?.status==='ACCEPTED'&&!inspection?'Schedule inspection':request?.status==='ACCEPTED'&&inspection&&!estimate?'Complete inspection':request?.status==='ACCEPTED'&&estimate?.status==='SENT'?'Review estimate':request?.status==='PROCESSING'?'Provider is completing the work':request?.status==='COMPLETED'&&completion?.status==='SUBMITTED'?'Confirm completion':request?.status==='COMPLETED'?'Request completed':'Request in progress'}</h2><p className="muted">{selected?`Selected provider: ${selected.name}`:'Providers who are interested in your job will appear below.'}</p><p className="formMessage" role="status">{message}</p></div></section>

  {request?.status==='NEW'?<section className="panel marketSection"><div className="marketSectionHeader"><div><p className="eyebrow">PROVIDER SELECTION</p><h2>Choose from interested providers</h2><p className="muted">Compare verified status, experience, completed jobs and customer ratings before selecting.</p></div><span className="pill">{journey?.providerOptions?.length||0} interested</span></div>
   {journey?.providerOptions?.length?<div className="providerGrid">{journey.providerOptions.map(provider=><article className="providerCard" key={provider.userId}><div className="providerTop"><div className="providerIdentity"><div className="providerAvatar">{provider.profilePhotoUrl?<img src={provider.profilePhotoUrl} alt=""/>:provider.name.slice(0,1).toUpperCase()}</div><div><div className="providerName">{provider.name}</div><div className="mutedMini">{provider.businessName||`${provider.experienceYears} years experience`}</div></div></div>{provider.verified?<span className="verifiedBadge">✓ Verified Provider</span>:null}</div><div className="providerStats"><div className="providerStat"><strong>{provider.rating??'New'}</strong><span>{provider.reviewCount} reviews</span></div><div className="providerStat"><strong>{provider.completedJobs}</strong><span>completed jobs</span></div><div className="providerStat"><strong>{shortStatus(provider.availability)}</strong><span>availability</span></div></div>{provider.specialty?.length?<div className="specialtyRow">{provider.specialty.map(s=><span className="specialtyChip" key={s}>{s}</span>)}</div>:null}{provider.message?<div className="providerMessage">“{provider.message}”</div>:null}{expandedProvider===provider.userId&&provider.description?<p className="muted">{provider.description}</p>:null}<div className="actions"><button className="secondary" type="button" onClick={()=>setExpandedProvider(expandedProvider===provider.userId?null:provider.userId)}>View Profile</button><button className="primary" type="button" disabled={busy} onClick={()=>void selectProvider(provider.userId)}>Select Provider</button></div></article>)}</div>:<div className="emptyQueue"><strong>No provider responses yet.</strong><p className="muted">Your request remains open while matching providers review it. Refresh this page to see new responses.</p></div>}</section>:null}

  {request?.status==='ACCEPTED'&&selected?<section className="panel marketSection"><div className="marketSectionHeader"><div><p className="eyebrow">PROVIDER SELECTED</p><h2>{selected.name}</h2><p className="muted">Your provider has been selected. The request stays in Accepted status until the estimate is approved and work starts.</p></div>{selected.verified?<span className="verifiedBadge">✓ Verified Provider</span>:null}</div><div className="providerGrid"><article className="providerCard"><div className="providerIdentity"><div className="providerAvatar">{selected.profilePhotoUrl?<img src={selected.profilePhotoUrl} alt=""/>:selected.name.slice(0,1).toUpperCase()}</div><div><div className="providerName">{selected.name}</div><div className="mutedMini">{selected.rating?`★ ${selected.rating} · ${selected.reviewCount} reviews`:'New provider'} · {selected.completedJobs} jobs</div></div></div>{selected.message?<div className="providerMessage">{selected.message}</div>:null}<div className="actions"><button className="secondary" type="button" onClick={goMessages}>Message Provider</button><button className="primary" type="button" onClick={()=>setShowSchedule(v=>!v)}>{inspection?'Update Preferred Times':'Schedule Inspection'}</button></div></article><div className="timelineCard">{['Schedule Inspection','Visit & Diagnose','Send Estimate','Repair & Complete'].map((step,index)=><div className={(inspection&&index===0)||(estimate&&index<=2)||request.status==='PROCESSING'||request.status==='COMPLETED'?'nextStep done':'nextStep'} key={step}><span className="nextStepIcon">{index+1}</span><div><strong>{step}</strong><small>{index===0?'Choose times that work for you':index===1?'Provider inspects the issue':index===2?'Review findings and cost':'Approved work is completed'}</small></div></div>)}</div></div>
   {showSchedule?<div className="marketSection"><div className="marketNotice">Choose up to three preferred inspection times. Your provider will confirm one or propose another time.</div><div className="scheduleGrid" style={{marginTop:12}}>{slots.map((slot,index)=><label key={index}>Preferred time {index+1}<input type="datetime-local" value={slot} onChange={e=>setSlots(current=>current.map((v,i)=>i===index?e.target.value:v))}/></label>)}</div><div className="actions" style={{marginTop:12}}><button className="primary" type="button" onClick={()=>void proposeInspection()} disabled={busy}>Send Preferred Times</button><button className="secondary" type="button" onClick={()=>setShowSchedule(false)}>Cancel</button></div></div>:null}</section>:null}

  {inspection&&selected?<section className="panel marketSection"><div className="marketSectionHeader"><div><p className="eyebrow">INSPECTION</p><h2>{inspection.status==='PROPOSED'?'Waiting for provider confirmation':'Inspection scheduled'}</h2></div><span className="pill">{shortStatus(inspection.status)}</span></div>{inspection.status==='PROPOSED'?<><div className="marketNotice">Your preferred times were sent to {selected.name}.</div><div className="jobList" style={{marginTop:12}}>{inspection.preferred_slots?.map((slot,i)=><div className="jobCard" key={`${slot}:${i}`}><strong>Option {i+1}</strong><p>{when(slot)}</p></div>)}</div></>:<><div className="scheduleSummary"><div className="scheduleMetric"><span>Date & time</span><strong>{when(inspection.scheduled_start)}</strong></div><div className="scheduleMetric"><span>Duration</span><strong>{inspection.duration_minutes?`${inspection.duration_minutes} minutes`:'To be confirmed'}</strong></div><div className="scheduleMetric"><span>Location</span><strong>{request?.service_location_text}</strong></div></div><div className="timelineCard" style={{marginTop:14}}>{inspectionSteps.map((step,index)=><div key={step} className={index<=inspectionIndex?'nextStep done':'nextStep'}><span className="nextStepIcon">{index+1}</span><div><strong>{shortStatus(step)}</strong><small>{index<inspectionIndex?'Completed':index===inspectionIndex?'Current inspection step':'Pending'}</small></div></div>)}</div><div className="actions" style={{marginTop:12}}><button className="secondary" type="button" onClick={goMessages}>Message Provider</button><button className="secondary" type="button" disabled title="Phone sharing is not enabled for this provider">Call Provider</button><a className="secondary" href="#request-summary">View Request Details</a></div></>}</section>:null}

  {estimate&&selected?<section className="panel marketSection"><div className="marketSectionHeader"><div><p className="eyebrow">INSPECTION FINDINGS</p><h2>Review the provider estimate</h2></div><span className="pill">{shortStatus(estimate.status)}</span></div><div className="estimateGrid"><div className="timelineCard"><div className="findingCard"><h3>Inspection findings</h3><p>{estimate.findings}</p></div><div className="findingCard"><h3>Recommended work</h3><p>{estimate.recommended_work}</p>{estimate.estimated_minutes?<p className="muted"><b>Estimated time:</b> {estimate.estimated_minutes} minutes</p>:null}</div></div><div className="costCard"><h3>Cost breakdown</h3><div className="costRow"><span>Labour</span><strong>{money(estimate.labour_amount,estimate.currency)}</strong></div><div className="costRow"><span>Material</span><strong>{money(estimate.material_amount,estimate.currency)}</strong></div><div className="costRow total"><span>Total</span><span>{money(estimate.total_amount,estimate.currency)}</span></div><p className="mutedMini">This is a work estimate only. iFixIt does not process payment.</p></div></div>{['SENT','REVISED'].includes(estimate.status)?<div className="decisionBox"><textarea rows={3} placeholder="Optional question or note for the provider" value={estimateNote} onChange={e=>setEstimateNote(e.target.value)}/><div className="actions"><button className="primary" type="button" disabled={busy} onClick={()=>void decideEstimate('APPROVE')}>Approve Work</button><button className="secondary" type="button" onClick={goMessages}>Ask Question</button><button className="danger" type="button" disabled={busy} onClick={()=>void decideEstimate('DECLINE')}>Decline</button></div></div>:estimate.status==='APPROVED'?<div className="marketSuccess">Estimate approved. The request is now in Processing and the provider can perform the approved work.</div>:<div className="marketWarning">Estimate declined. Message the provider if you want a revised estimate.</div>}</section>:null}

  {request?.status==='PROCESSING'&&selected?<section className="panel marketSection"><div className="marketSectionHeader"><div><p className="eyebrow">WORK IN PROGRESS</p><h2>{selected.name} is completing the approved work</h2></div><span className="pill">Processing</span></div><div className="marketNotice">The provider will submit a completion summary when the work is finished. You can continue using request messaging during this stage.</div><div className="actions" style={{marginTop:12}}><button className="secondary" type="button" onClick={goMessages}>Message Provider</button></div></section>:null}

  {request?.status==='COMPLETED'?<section className="panel marketSection"><div className="marketSectionHeader"><div><p className="eyebrow">WORK COMPLETED</p><h2>{selected?.name||request.assigned_provider_label||'Provider'} completed the job</h2></div><span className="pill">Completed</span></div>{completion?<><div className="estimateGrid"><div><h3>Work performed</h3><ul className="completionList">{completion.work_performed?.map((item,i)=><li key={`${item}:${i}`}>✓ {item}</li>)}</ul></div><div className="costCard"><h3>Final cost</h3><div className="costRow"><span>Labour</span><strong>{money(completion.labour_amount,completion.currency)}</strong></div><div className="costRow"><span>Material</span><strong>{money(completion.material_amount,completion.currency)}</strong></div><div className="costRow total"><span>Total</span><span>{money(completion.final_amount,completion.currency)}</span></div><p className="mutedMini">{completion.payment_note}</p></div></div>{completion.status==='SUBMITTED'&&!review?<div className="reviewBox marketSection"><h3>Confirm completion</h3><p>Are you satisfied with the completed work?</p><div className="satisfactionRow"><button type="button" className={satisfied===true?'primary satisfactionButton':'secondary satisfactionButton'} onClick={()=>setSatisfied(true)}>Yes</button><button type="button" className={satisfied===false?'danger satisfactionButton':'secondary satisfactionButton'} onClick={()=>setSatisfied(false)}>No</button></div><p><b>Rate your provider</b></p><div className="ratingStars">{[1,2,3,4,5].map(star=><button type="button" key={star} className={rating>=star?'starButton selected':'starButton'} onClick={()=>setRating(star)}>★</button>)}</div><textarea rows={4} placeholder="Share your experience" value={reviewText} onChange={e=>setReviewText(e.target.value)}/><div className="actions"><button className="primary" type="button" disabled={busy} onClick={()=>void confirmCompletion()}>Confirm Completion</button><a className="secondary" href="/#request">Rebook Provider</a></div></div>:null}{review?<div className="marketSuccess marketSection"><strong>Completion confirmed.</strong> {review.rating?`Your rating: ${'★'.repeat(review.rating)}`:''}{review.review_text?<p>{review.review_text}</p>:null}</div>:null}<div className="marketSection"><h3>Report a problem</h3><textarea rows={3} value={problemText} onChange={e=>setProblemText(e.target.value)} placeholder="Describe any issue with the completed work"/><div className="actions" style={{marginTop:10}}><button className="danger" type="button" disabled={busy||!problemText.trim()} onClick={()=>void reportProblem()}>Report a Problem</button></div>{completion.status==='ISSUE_REPORTED'?<div className="marketWarning" style={{marginTop:10}}>A problem has been reported for this completion.</div>:null}</div></>:<div className="marketNotice">The request is marked completed. The provider completion summary is not available for this older job.</div>}</section>:null}

  <section className="panel marketSection" id="request-summary"><div className="marketSectionHeader"><div><p className="eyebrow">REQUEST DETAILS</p><h2>Original service request</h2></div><span className="pill">{request?.urgency||'Standard'}</span></div>{request?<div className="trackingGrid"><div className="requestSummary"><p><b>Service:</b> {request.service_name}</p><p><b>Location:</b> {request.service_location_text}</p><p><b>Preferred date:</b> {request.preferred_date}</p><p><b>Provider:</b> {request.assigned_provider_label||'Not selected yet'}</p><p><b>Created:</b> {when(request.created_at)}</p>{request.customer_notes?<p><b>Notes:</b> {request.customer_notes}</p>:null}<p className="jobDescription">{request.problem_description}</p></div><div className="miniTimeline">{workflow.map((item,index)=><div className={index<=activeStep?'timelineItem done':'timelineItem'} key={item}><span>{index+1}</span><div><strong>{shortStatus(item)}</strong><small>{index<activeStep?'Completed stage':index===activeStep?'Current stage':'Pending'}</small></div></div>)}</div></div>:null}</section>

  <section className="panel marketSection" id="messages"><div className="marketSectionHeader"><div><p className="eyebrow">MESSAGES</p><h2>Customer ↔ Provider</h2></div><span className="pill">{messages.length}</span></div><div className="chatList">{messages.map(m=><div className={m.sender_role==='CUSTOMER'?'chatBubble customer':'chatBubble'} key={m.id}><strong>{m.sender_label||m.sender_role}</strong><p>{m.message_text}</p><time>{when(m.created_at)}</time></div>)}{!messages.length?<div className="emptyQueue">Messaging becomes available after a provider is selected and the request is accepted.</div>:null}</div><div className="providerAccessRow"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message about this request"/><button className="primary" disabled={busy||!text.trim()||request?.status==='NEW'} onClick={()=>void send()}>Send</button></div></section>

  <section className="panel marketSection"><div className="marketSectionHeader"><div><p className="eyebrow">STATUS HISTORY</p><h2>Request timeline</h2></div><span className="pill">{history.length} event(s)</span></div><div className="jobList">{history.map((h,i)=><div className="jobCard" key={`${h.created_at}:${i}`}><strong>{h.from_status||'START'} → {h.to_status}</strong><p className="jobDescription">{h.note||'Status updated'}</p><div className="jobMeta"><span>{h.actor_type||'SYSTEM'}</span><span>{when(h.created_at)}</span></div></div>)}{!history.length?<div className="emptyQueue">No status-history entries yet.</div>:null}</div></section>

  <div className="stickyActions"><div className="actions"><a className="secondary" href="/requests">My Requests</a>{request?.status!=='NEW'?<button className="primary" type="button" onClick={goMessages}>Message Provider</button>:null}<a className="secondary" href="/#request">New Request</a></div></div>
 </main>;
}
