'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { supabase } from '../../../lib/supabaseClient';
import './marketplace.css';
import './completion-media.css';

const DETAIL_API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/customer-requests';
const MARKET_API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/customer-marketplace';
const MESSAGE_API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/request-messages';
const MEDIA_API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/completion-media';
const CANCEL_API='https://yzlhlilxiszefneshatm.supabase.co/functions/v1/customer-cancel-request';

type RequestRow={id:string;ticket_number:string;service_name:string;service_location_text:string;preferred_date:string;problem_description:string;urgency?:string|null;customer_notes?:string|null;status:string;assigned_provider_label?:string|null;created_at:string;updated_at:string;accepted_at?:string|null;processing_at?:string|null;completed_at?:string|null};
type MessageRow={id:string;sender_role:string;sender_label?:string|null;message_text:string;created_at:string};
type Provider={userId:string;name:string;businessName?:string|null;profilePhotoUrl?:string|null;rating:number|null;reviewCount:number;completedJobs:number;verified:boolean;specialty:string[];qualityRating?:number|null;timeRating?:number|null;costRating?:number|null;rankingScore?:number|null;providerRank?:number|null;message?:string|null};
type Inspection={preferred_slots:string[];scheduled_start?:string|null;duration_minutes?:number|null;status:string;provider_note?:string|null};
type Estimate={findings:string;recommended_work:string;estimated_minutes?:number|null;labour_amount:number|string;material_amount:number|string;total_amount:number|string;currency:string;status:string;customer_note?:string|null;sent_at:string};
type Completion={work_performed:string[];labour_amount:number|string;material_amount:number|string;final_amount:number|string;currency:string;payment_note:string;status:string;submitted_at:string;confirmed_at?:string|null;issue_note?:string|null};
type Review={quality_rating?:number|null;time_rating?:number|null;cost_rating?:number|null;overall_rating?:number|string|null;rating?:number|null;review_text?:string|null;created_at?:string|null};
type RatingEligibility={status:'not_available'|'pending'|'submitted'|'expired';deadline:string|null;remainingSeconds:number};
type Journey={request:RequestRow;providerOptions:Provider[];selectedProvider:Provider|null;inspection:Inspection|null;estimate:Estimate|null;completion:Completion|null;review:Review|null;ratingEligibility?:RatingEligibility};
type CompletionMedia={id:string;media_type:'BEFORE'|'AFTER';url?:string|null;created_at:string};
type Tab='overview'|'messages'|'confirm'|'report';

function when(v?:string|null){if(!v)return'Not set';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString(undefined,{day:'2-digit',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'});}
function money(v:number|string|undefined,c='MVR'){return`${c} ${Number(v||0).toFixed(0)}`;}
function pretty(v?:string|null){return String(v||'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());}
function initials(v?:string|null){return(v||'P').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();}
function remaining(deadline:string|null|undefined,clock:number){if(!deadline)return'';const ms=new Date(deadline).getTime()-clock;if(ms<=0)return'Expired';const totalMinutes=Math.ceil(ms/60000);const hours=Math.floor(totalMinutes/60);const minutes=totalMinutes%60;return hours>=24?`${Math.floor(hours/24)}d ${hours%24}h remaining`:`${hours}h ${minutes}m remaining`;}
function StarRow({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <div style={{marginTop:14}}><strong>{label}</strong><div className="bigStars" style={{marginTop:6}}>{[1,2,3,4,5].map(n=><button type="button" aria-label={`${label} ${n} star${n===1?'':'s'}`} key={n} onClick={()=>onChange(n)} className={n<=value?'selected':''}>{n<=value?'★':'☆'}</button>)}</div></div>}

export default function RequestDetailPage(){
 const params=useParams<{ticket:string}>();const ticket=decodeURIComponent(String(params.ticket||'')).toUpperCase();
 const[request,setRequest]=useState<RequestRow|null>(null);const[journey,setJourney]=useState<Journey|null>(null);const[messages,setMessages]=useState<MessageRow[]>([]);const[unread,setUnread]=useState(0);const[media,setMedia]=useState<CompletionMedia[]>([]);const[tab,setTab]=useState<Tab>('overview');const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('Loading request…');const[text,setText]=useState('');const[slots,setSlots]=useState(['','','']);const[estimateNote,setEstimateNote]=useState('');const[qualityRating,setQualityRating]=useState(0);const[timeRating,setTimeRating]=useState(0);const[costRating,setCostRating]=useState(0);const[reviewText,setReviewText]=useState('');const[problemText,setProblemText]=useState('');const[clock,setClock]=useState(Date.now());
 useEffect(()=>{if(ticket)void load();},[ticket]);
 useEffect(()=>{if(tab==='messages')void markRead();},[tab]);
 useEffect(()=>{const id=window.setInterval(()=>setClock(Date.now()),60000);return()=>window.clearInterval(id);},[]);
 async function token(){const{data}=await supabase.auth.getSession();if(!data.session){window.location.href='/login';return'';}return data.session.access_token;}
 async function post(url:string,body:Record<string,unknown>){const t=await token();const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p?.error||'Request failed');return p;}
 async function load(){setBusy(true);try{const t=await token();if(!t)return;const headers={'Content-Type':'application/json','Authorization':`Bearer ${t}`};const[dr,jr,mr,cr]=await Promise.all([fetch(DETAIL_API,{method:'POST',headers,body:JSON.stringify({action:'detail',ticketNumber:ticket})}),fetch(MARKET_API,{method:'POST',headers,body:JSON.stringify({action:'journey',ticketNumber:ticket})}),fetch(MESSAGE_API,{method:'POST',headers,body:JSON.stringify({action:'list',ticketNumber:ticket})}),fetch(MEDIA_API,{method:'POST',headers,body:JSON.stringify({action:'list',ticketNumber:ticket})})]);const[d,j,m,c]=await Promise.all([dr.json(),jr.json(),mr.json(),cr.json()]);if(!dr.ok)throw new Error(d?.error||'Unable to load request');if(!jr.ok)throw new Error(j?.error||'Unable to load journey');setRequest(j.request||d.request);setJourney(j);if(mr.ok){setMessages(m.messages||[]);setUnread(m.unreadCount||0);}if(cr.ok)setMedia(c.media||[]);setNotice('');}catch(e){setNotice(e instanceof Error?e.message:'Unable to load request.');}finally{setBusy(false);}}
 async function market(action:string,payload:Record<string,unknown>={}){setBusy(true);try{const p=await post(MARKET_API,{action,ticketNumber:ticket,...payload});setJourney(p);setRequest(p.request||request);setNotice('Request updated successfully.');await load();return true;}catch(e){setNotice(e instanceof Error?e.message:'Unable to update request.');return false;}finally{setBusy(false);}}
 async function cancelRequest(){if(!window.confirm('Cancel this service request? This will stop the request and notify any selected provider.'))return;setBusy(true);try{await post(CANCEL_API,{ticketNumber:ticket,reason:'Cancelled by customer'});window.location.replace('/requests');}catch(e){setNotice(e instanceof Error?e.message:'Unable to cancel request.');}finally{setBusy(false);}}
 async function selectProvider(providerUserId:string){await market('select_provider',{providerUserId});}
 async function proposeInspection(){const preferredSlots=slots.filter(Boolean);if(!preferredSlots.length){setNotice('Choose at least one preferred inspection time.');return;}if(await market('propose_inspection',{preferredSlots}))setSlots(['','','']);}
 async function decideEstimate(decision:'APPROVE'|'DECLINE'){if(await market('decide_estimate',{decision,note:estimateNote.trim()||null}))setEstimateNote('');}
 async function confirmCompletion(){if(await market('confirm_completion'))window.location.replace('/requests');}
 async function submitRating(){if(qualityRating<1||timeRating<1||costRating<1){setNotice('Choose 1–5 stars for Quality, Time, and Cost.');return;}if(await market('submit_rating',{qualityRating,timeRating,costRating,review:reviewText.trim()})){setReviewText('');setQualityRating(0);setTimeRating(0);setCostRating(0);}}
 async function reportProblem(){if(problemText.trim().length<5){setNotice('Please describe the problem.');return;}if(await market('report_problem',{note:problemText.trim()}))setProblemText('');}
 async function send(){if(!text.trim())return;setBusy(true);try{const p=await post(MESSAGE_API,{action:'send',ticketNumber:ticket,message:text.trim()});setMessages(p.messages||[]);setUnread(0);setText('');}catch(e){setNotice(e instanceof Error?e.message:'Unable to send message.');}finally{setBusy(false);}}
 async function markRead(){try{const p=await post(MESSAGE_API,{action:'mark_read',ticketNumber:ticket});setMessages(p.messages||[]);setUnread(0);}catch{}}
 const selected=journey?.selectedProvider||null,inspection=journey?.inspection||null,estimate=journey?.estimate||null,completion=journey?.completion||null,review=journey?.review||null;const before=media.filter(x=>x.media_type==='BEFORE'&&x.url),after=media.filter(x=>x.media_type==='AFTER'&&x.url);const awaitingConfirm=request?.status==='COMPLETED'&&completion?.status==='SUBMITTED';const closed=completion?.status==='CONFIRMED';const canCancel=['PENDING','RESPONDED','ACCEPTED','INSPECTION_SCHEDULED'].includes(request?.status||'');const ratingDeadline=journey?.ratingEligibility?.deadline||null;const ratingExpired=journey?.ratingEligibility?.status==='expired'||Boolean(ratingDeadline&&new Date(ratingDeadline).getTime()<=clock);const ratingPending=journey?.ratingEligibility?.status==='pending'&&!ratingExpired&&!review;const reviewOverall=review?.overall_rating==null?null:Number(review.overall_rating);
 const progressSteps=['New','Accepted','Processing','Completed'];const progressIndex=['COMPLETED'].includes(request?.status||'')?3:['PROCESSING'].includes(request?.status||'')?2:['ACCEPTED','INSPECTION_SCHEDULED','INSPECTION_COMPLETED','ESTIMATE_SENT','ESTIMATE_APPROVED','SCHEDULED'].includes(request?.status||'')?1:0;
 if(!request)return <main className="ifixPage"><div className="ifixLoading"><div className="ifixLogo"><span>iFix</span><b>.It</b></div><p>{notice}</p></div></main>;
 return <main className="ifixPage"><header className="ifixHeader"><a className="backButton" href="/requests">‹</a><a className="ifixLogo" href="/"><span>iFix</span><b>.It</b></a><div className="headerIcons"><button onClick={()=>setTab('messages')} aria-label="Messages">◌{unread>0?<i>{unread>9?'9+':unread}</i>:null}</button></div></header><div className="requestAppPanel">
  <div className="requestAppHeading"><div><p className="eyebrow">{request.ticket_number}</p><h1>Service Request Details</h1><p>{request.service_name} · {pretty(request.status)}</p></div></div>
  <div className="requestTabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='messages'?'active':''} onClick={()=>setTab('messages')}>Messages {unread?`(${unread})`:''}</button>{completion?<button className={tab==='report'?'active':''} onClick={()=>setTab('report')}>Service Report</button>:null}{canCancel?<button onClick={()=>void cancelRequest()} disabled={busy}>{busy?'Please wait…':'Cancel'}</button>:null}<button onClick={()=>void confirmCompletion()} disabled={busy||!awaitingConfirm||closed} title={closed?'Request is already closed':awaitingConfirm?'Close this completed request':'Close becomes available after work is completed'}>Close</button></div>
  {notice?<p className="statusNotice">{notice}</p>:null}
  {tab==='messages'?<section className="screenCard"><div className="sectionHeading"><div><h2>Messages</h2><p>{selected?`Conversation with ${selected.name}`:'Provider conversation'}</p></div></div><div className="chatList">{messages.map(m=><div key={m.id} className={`chatBubble ${m.sender_role==='CUSTOMER'?'customer':''}`}><strong>{m.sender_label||pretty(m.sender_role)}</strong><p>{m.message_text}</p><time>{when(m.created_at)}</time></div>)}{!messages.length?<div className="emptyState">No messages yet.</div>:null}</div><div className="messageComposer"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message"/><button className="blueButton" onClick={()=>void send()} disabled={busy||!text.trim()}>Send</button></div></section>:null}
  {tab==='report'&&completion?<section className="screenCard serviceReport"><div className="sectionHeading"><div><h2>Service Report</h2><p>{request.ticket_number} · {when(completion.submitted_at)}</p></div><button className="secondary" onClick={()=>window.print()}>Print</button></div><div className="requestInfoGrid"><div><span>Service</span><strong>{request.service_name}</strong></div><div><span>Provider</span><strong>{selected?.name||request.assigned_provider_label||'Provider'}</strong></div><div><span>Location</span><strong>{request.service_location_text}</strong></div><div><span>Status</span><strong>{pretty(completion.status)}</strong></div></div><h3>Work performed</h3><ul>{completion.work_performed.map((w,i)=><li key={i}>{w}</li>)}</ul><div className="estimateMoneyGrid"><div><span>Labour</span><strong>{money(completion.labour_amount,completion.currency)}</strong></div><div><span>Materials</span><strong>{money(completion.material_amount,completion.currency)}</strong></div><div><span>Final job value</span><strong>{money(completion.final_amount,completion.currency)}</strong></div></div><p className="statusNotice">{completion.payment_note||'Payment is handled outside iFixIt.'}</p>{before.length||after.length?<div className="completionMediaGrid"><div><h3>Before</h3><div className="requestPhotoRow">{before.map(m=><img className="requestPhoto" key={m.id} src={m.url||''} alt="Before work"/>)}</div></div><div><h3>After</h3><div className="requestPhotoRow">{after.map(m=><img className="requestPhoto" key={m.id} src={m.url||''} alt="After work"/>)}</div></div></div>:null}</section>:null}
  {tab==='overview'?<>
   <section className="screenCard"><div className="sectionHeading"><div><h2>Request Details</h2><p>Complete information for this service request</p></div><button className="secondary" onClick={()=>void load()} disabled={busy}>{busy?'Refreshing…':'Refresh'}</button></div><div className="requestInfoGrid"><div><span>Request number</span><strong>{request.ticket_number}</strong></div><div><span>Status</span><strong>{pretty(request.status)}</strong></div><div><span>Service</span><strong>{request.service_name}</strong></div><div><span>Service address</span><strong>{request.service_location_text||'Not provided'}</strong></div><div><span>Requested date</span><strong>{when(request.preferred_date)}</strong></div><div><span>Created</span><strong>{when(request.created_at)}</strong></div><div><span>Last updated</span><strong>{when(request.updated_at)}</strong></div><div><span>Provider</span><strong>{selected?.name||request.assigned_provider_label||'Not assigned yet'}</strong></div></div><div className="findingCard"><strong>Issue / description</strong><p>{request.problem_description||'No description provided.'}</p></div>{request.customer_notes?<div className="findingCard"><strong>Customer notes</strong><p>{request.customer_notes}</p></div>:null}{request.urgency?<div className="findingCard"><strong>Urgency</strong><p>{pretty(request.urgency)}</p></div>:null}</section>
   <section className="screenCard"><div className="sectionHeading"><div><h2>Request Progress</h2><p>Follow the service request from start to completion</p></div></div><div className="requestInfoGrid">{progressSteps.map((step,index)=><div key={step}><span>{index<progressIndex?'Completed':index===progressIndex?'Current':'Next'}</span><strong>{index<=progressIndex?'✓ ':''}{step}</strong></div>)}</div><div className="findingCard"><strong>Current stage</strong><p>{pretty(request.status)}</p></div>{request.accepted_at?<div className="findingCard"><strong>Accepted</strong><p>{when(request.accepted_at)}</p></div>:null}{request.processing_at?<div className="findingCard"><strong>Processing started</strong><p>{when(request.processing_at)}</p></div>:null}{request.completed_at?<div className="findingCard"><strong>Completed</strong><p>{when(request.completed_at)}</p></div>:null}</section>
   {selected?<section className="providerSummaryCard"><div className="providerProfileMain"><div className="providerPhoto">{selected.profilePhotoUrl?<img src={selected.profilePhotoUrl} alt=""/>:<span>{initials(selected.name)}</span>}</div><div className="providerDetails"><div className="providerTitleRow"><h2>{selected.name}</h2>{selected.verified?<span className="verifiedMark">◆</span>:null}</div><strong className="providerSpecialty">{selected.specialty?.[0]||selected.businessName||'Service Provider'}</strong>{selected.reviewCount>0&&selected.rating!==null?<div className="ratingLine"><span className="star">★</span><b>{selected.rating.toFixed(1)}</b><span>({selected.reviewCount} reviews)</span></div>:<div className="completedJobsLine">No ratings yet · New provider</div>}<div className="completedJobsLine">Completed Jobs: {selected.completedJobs}</div></div></div></section>:null}
   {!selected&&journey?.providerOptions?.length?<section className="screenCard"><div className="sectionHeading"><div><h2>Choose a Provider</h2><p>{journey.providerOptions.length} provider response(s)</p></div></div><div className="providerGrid">{journey.providerOptions.map(p=><article className="providerCard" key={p.userId}><div className="providerIdentity"><div className="providerAvatar">{initials(p.name)}</div><div><strong className="providerName">{p.name}</strong><p>{p.specialty?.[0]||'Service Provider'}</p>{p.reviewCount>0&&p.rating!==null?<p>★ {p.rating.toFixed(1)} · {p.reviewCount} review{p.reviewCount===1?'':'s'}</p>:<p>No ratings yet</p>}</div></div>{p.message?<p className="providerMessage">{p.message}</p>:null}<button className="blueButton" onClick={()=>void selectProvider(p.userId)} disabled={busy}>Select Provider</button></article>)}</div></section>:null}
   {selected&&request.status==='ACCEPTED'&&!inspection?<section className="screenCard"><h2>Schedule Inspection</h2><p className="muted">Choose up to three preferred times for the provider.</p><div className="scheduleGrid">{slots.map((s,i)=><input key={i} type="datetime-local" value={s} onChange={e=>setSlots(v=>v.map((x,n)=>n===i?e.target.value:x))}/>)}</div><button className="blueButton" onClick={()=>void proposeInspection()} disabled={busy}>Send Preferred Times</button></section>:null}
   {inspection?<section className="screenCard"><div className="sectionHeading"><div><h2>Inspection</h2><p>{pretty(inspection.status)}</p></div></div><div className="requestInfoGrid"><div><span>Scheduled</span><strong>{when(inspection.scheduled_start)}</strong></div><div><span>Duration</span><strong>{inspection.duration_minutes?`${inspection.duration_minutes} min`:'Not set'}</strong></div></div>{inspection.provider_note?<p className="providerMessage">{inspection.provider_note}</p>:null}</section>:null}
   {estimate?<section className="screenCard"><div className="sectionHeading"><div><h2>Estimate</h2><p>{pretty(estimate.status)}</p></div><strong>{money(estimate.total_amount,estimate.currency)}</strong></div><div className="findingCard"><strong>Findings</strong><p>{estimate.findings}</p></div><div className="findingCard"><strong>Recommended work</strong><p>{estimate.recommended_work}</p></div>{['SENT','REVISED'].includes(estimate.status)?<><textarea value={estimateNote} onChange={e=>setEstimateNote(e.target.value)} placeholder="Optional note"/><div className="actions"><button className="danger" onClick={()=>void decideEstimate('DECLINE')} disabled={busy}>Decline</button><button className="blueButton" onClick={()=>void decideEstimate('APPROVE')} disabled={busy}>Approve Estimate</button></div></>:null}</section>:null}
   {completion?<section className="screenCard"><div className="sectionHeading"><div><h2>Work Completed</h2><p>{pretty(completion.status)}</p></div><strong>{money(completion.final_amount,completion.currency)}</strong></div><ul>{completion.work_performed.map((x,i)=><li key={i}>{x}</li>)}</ul>{before.length||after.length?<div className="completionMediaGrid"><div><h3>Before</h3><div className="requestPhotoRow">{before.map(m=><img className="requestPhoto" key={m.id} src={m.url||''} alt="Before work"/>)}</div></div><div><h3>After</h3><div className="requestPhotoRow">{after.map(m=><img className="requestPhoto" key={m.id} src={m.url||''} alt="After work"/>)}</div></div></div>:<p className="muted">No completion photos uploaded yet.</p>}<div className="actions"><button className="secondary" onClick={()=>setTab('report')}>View Service Report</button>{awaitingConfirm?<button className="blueButton" onClick={()=>setTab('confirm')}>Confirm Completion</button>:null}</div></section>:null}
   {ratingPending?<section className="screenCard"><div className="sectionHeading"><div><h2>Rate your service</h2><p>Rate {selected?.name||request.assigned_provider_label||'your provider'} within 48 hours of completion.</p></div><strong>{remaining(ratingDeadline,clock)}</strong></div><StarRow label="Quality" value={qualityRating} onChange={setQualityRating}/><StarRow label="Time" value={timeRating} onChange={setTimeRating}/><StarRow label="Cost" value={costRating} onChange={setCostRating}/><textarea maxLength={2000} value={reviewText} onChange={e=>setReviewText(e.target.value)} placeholder="Optional review comment"/><button className="blueButton" onClick={()=>void submitRating()} disabled={busy||qualityRating<1||timeRating<1||costRating<1}>Submit Rating</button></section>:null}
   {ratingExpired&&!review?<section className="screenCard"><div className="sectionHeading"><div><h2>Rating period has expired</h2><p>This service was not rated within 48 hours of completion. No score was recorded for the provider.</p></div></div></section>:null}
   {review?<section className="screenCard"><div className="sectionHeading"><div><h2>Rating submitted</h2><p>Verified completed-service review</p></div><strong>★ {reviewOverall?.toFixed(1)??Number(review.rating||0).toFixed(1)}</strong></div><div className="requestInfoGrid"><div><span>Quality</span><strong>{review.quality_rating??review.rating}/5</strong></div><div><span>Time</span><strong>{review.time_rating??review.rating}/5</strong></div><div><span>Cost</span><strong>{review.cost_rating??review.rating}/5</strong></div></div>{review.review_text?<p className="providerMessage">{review.review_text}</p>:null}</section>:null}
   {completion&&completion.status!=='CONFIRMED'?<section className="screenCard"><h3>Problem with completed work?</h3><textarea value={problemText} onChange={e=>setProblemText(e.target.value)} placeholder="Describe the issue"/><button className="danger" onClick={()=>void reportProblem()} disabled={busy}>Report Problem</button></section>:null}
  </>:null}
  {tab==='confirm'&&completion?<section className="screenCard"><div className="sectionHeading"><div><h2>Confirm Completion</h2><p>Confirm that the provider has finished the work. Your separate 48-hour rating window is already available and will not be extended by this confirmation.</p></div></div><div className="actions"><button className="secondary" onClick={()=>setTab('overview')} disabled={busy}>Back</button><button className="blueButton" onClick={()=>void confirmCompletion()} disabled={busy}>Confirm & Close Request</button></div></section>:null}
 </div></main>;
}
